### ISSUE TITLE
Clarify MPI_ERRORS_ARE_FATAL scope of abort

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#1]
# Original
## Problem

Section 8.3 is imprecise about the set of processes over which `MPI_ERRORS_ARE_FATAL` is applied. Since the error handle is associated with a communication object, then it is implied that the error handle is only applied to the group of processes associated with that communication object. Therefore it should be clarified that the processes in that group are aborted.

Similarly, `MPI_ABORT` (p. 294, Section 8.7) takes as an argument a communicator that defines the scope of the abort. The defining test specifies the operation is:

> ... to abort all tasks in the group of comm

Since `MPI_ERRORS_ARE_FATAL` is specified as an "abort" operation, it should fall under these same restrictions when applied to a communication object.
## Proposed Solution

Clarify the text in the MPI standard per the pdf document attached to this ticket. Search for `ticket1` and `ticket3`.

Note that text changes are in the following chapters:
- Chapter 2: MPI Terms and Conventions
- Chapter 3: Point-to-Point Communication 
- Chapter 8: MPI Environmental Management
## Implementation

Finished in Open MPI branch.
# Updated

After discussion in Chicago (06/2015), the forum decided that it would rather have `MPI_ERRORS_ARE_FATAL` maintain its current expected behavior which is to abort all connected processes. This allows applications that expect that behavior (to avoid things like being overcharged for their allocation) to maintain their current behavior. The new solution is to better clarify error handlers in general, including `MPI_ERRORS_ARE_FATAL` here and to open another new ticket (issue #3) which specifies a new error handler which captures the original goals of this ticket (abort a subset of the applications when the new error handler is called).

This text now includes text which:
- Clarifies how error should be handled when errors are not attached to a communicator (or the communicator is gone).
- Specifies how error handlers should be inherited for communicators, windows, and files;
- Specifies the `MPI_ERRORS_ARE_FATAL` causes all connected processes to abort;
- Specifies which error codes should be provided to `MPI_ABORT` when error handlers call it;
- Specifies the default error handler for `MPI_COMM_SELF`;
- Removes old rationale;
- Tell this implementation to correctly detect that processes have aborted;
- Make the default error handler for windows attached to `MPI_WIN_NULL`.
# PDF

[issues-1-3.pdf](https://github.com/mpi-forum/mpi-issues/files/1282445/issues-1-3.pdf)

**Comment by jsquyres** [comment]
Here's the PDF: 
[tickets-1-3.pdf](https://github.com/mpi-forum/mpi-issues/files/2574/tickets-1-3.pdf)

**Comment by wesbland** [comment]
There were multiple comments and edits during the meeting. Many things were minor wordsmithing, but a major objection was raised from Rolf. He is concerned that this could break backward compatibility in the following case:

* An application is catching its own errors via `MPI_ERRORS_RETURN` on `MPI_COMM_WORLD`, but does not change `MPI_ERRORS_ARE_FATAL` on `MPI_COMM_SELF`.
* For this application, errors which are not attached to a communicator (such as `MPI_ALLOC_MEM` when you run out of memory) would now be fatal because the app never changed `MPI_COMM_SELF`'s error handler where before, the error would not be fatal because the error would have been raised on `MPI_COMM_WORLD`.

There were a couple of options for trying to mitigate this and allow both backward compatibility and the new behavior.

* Add a new API to change the default communicator where the error handler is raised.
* The default error handler comes from `MPI_COMM_NULL` which, by default, points to the error handler for `MPI_COMM_WORLD`.
* Create a new error handler with a name like `MPI_ERRORS_USE_MPI_COMM_WORLD` (hopefully shorter) which just calls the error handler for `MPI_COMM_WORLD` and passes `MPI_COMM_WORLD` as the communicator which raised the error.

The WG decided that we still prefer the original proposal and that the backward compatibility issue is not worth adding all of the new semantics and complicating things. We expect that the group of users who would be impacted by this issue is sufficiently small and the fix is sufficiently trivial (call `MPI_COMM_SET_ERRHANDLER(MPI_COMM_SELF, MPI_ERRORS_RETURN);`) that the extra work is not justified.

**Comment by wesbland** [comment]
Here is the latest version of the PDF: [issues-1-3.pdf](https://github.com/mpi-forum/mpi-issues/files/127191/issues-1-3.pdf)

The pull request can be found at mpi-forum/mpi-standard#1 and has the full colorized diff.

**Comment by wesbland** [comment]
The edits that were made since the last reading can be found here:

https://github.com/mpiwg-ft/mpi-standard/commit/5a11f28e669d0fe7393afe5afd0dd021912c46d4

The intention is to go over those early for a no "no" vote.

**Comment by wesbland** [comment]
Updated marked-up PDF: [issue-1-markup.pdf](https://github.com/mpi-forum/mpi-issues/files/276697/issue-1-markup.pdf)

Pull Request: https://github.com/mpi-forum/mpi-standard/pull/1

**Comment by wesbland** [comment]
PDF to be read at June 2016 meeting: [errhandler.pdf](https://github.com/mpi-forum/mpi-issues/files/303337/errhandler.pdf)

**Comment by wesbland** [comment]
There was lots of discussion at the Bellevue, WA, June 2016 meeting around this issue along with #3. These slides were presented:

[2016-06-08-issues-1-3-reading.pptx](https://github.com/mpi-forum/mpi-issues/files/312033/2016-06-08-issues-1-3-reading.pptx)

One major change was proposed (mostly by Pavan, but with feedback from all) which is reflected in the straw vote at the end of the slides:

* Rather than have communicators inherit error handlers when they are created, we should be consistent with other things like info keys and attributes and have them only be propagated explicitly. This will also avoid a backward compatibility issue where libraries might expect the application to abort on an error and suddenly a user error handler is being called from library code.

This was straw voted against the current proposal and the vote was a 9 to 9 tie. After the vote, I had a discussion with Dan who pointed out that unlike info keys and attributes, if an error handler defaults to fatal, there are times where your application is "unprotected" and therefore vulnerable to being killed. This is a valid point and makes me lean in favor of keeping the proposal as is. The backward compatibility issue is still a tough one and may require people writing new error handlers to check that they are in the right part of the code (via some external mechanism).

**Comment by wesbland** [comment]
PDFs for Dec '16 meeting:

[PDF with markup](https://github.com/mpi-forum/mpi-issues/files/604635/errhandler_cleanup-with-markup.pdf)
[Clean PDF](https://github.com/mpi-forum/mpi-issues/files/604636/errhandler_cleanup.pdf)

**Comment by abouteiller** [comment]
MPI_ERRORS_ABORT: whose group is similar to that of the window or file

**Comment by wesbland** [comment]
There were many small pieces of feedback at the Dec 2016 meeting which will require some changes. These will be larger than we can take care of with a "no no" vote so we will need to fix and re-read this issue.

**Comment by wesbland** [comment]
[Marked up PDF for reading](https://github.com/mpi-forum/mpi-issues/files/1300379/issues-1-3-markedup.pdf)

**Comment by wesbland** [comment]
[Marked up PDF](https://github.com/mpi-forum/mpi-issues/files/1511327/issues-1-3-markedup.pdf)
 for reading at Dec 2017 meeting.

**Comment by wesbland** [comment]
Notes from the December 2017 reading:

The reading was generally successful. There were a few minor changes that people asked for and were made. [These](https://github.com/mpi-forum/procedures/pull/2/files/062d23521ac312f5e902452f710187edc55c7712..HEAD) will need to be voted on at a no-no vote at the February meeting .

The sentence about MPI being undefined after an error was removed from this proposal given that the catastrophic error proposal is going to tackle that problem in a different way.

**Comment by schulzm** [comment]
Passed second vote at June 2018 meeting in Austin
