### ISSUE TITLE
Big MPI---point-to-point functionality (MPI_Count + miscellaneous)

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#100]
# Problem

For 64-bit clean functionality, convenience, and symmetry, the Big MPI principles being applied in Ticket #80 to collective operations should be applied to MPI point-to-point functionality.

# Proposal

MPI needs to be 64-bit clean throughout.  

# Changes to the Text

MPI_Count will replace int for counts;  support counts > 2^31 

Other checks of any non-64-bit-clean features in point-to-point after review.

This ticket does not address the MPI_Rank issue; that is a separate, cross-cutting ticket.

# Impact on Implementations

No current API is impacted.  New _X APIs for all point-to-point operations affected will be needed.

MPI implementations will have to be 64-bit clean inside since count*extent > 2^31 is already problematic for some implementations.  New APIs will have to be added and the internals of MPI will have to be 64-bit capable for buffers and related issues.

# Impact on Users

Users who opt in with the new API will be able to send and receive larger messages [MPI_Count]

# References

See also Ticket #80, #97, #98, #99 

PR https://github.com/mpi-forum/mpi-standard/pull/60

**Comment by tonyskjellum** [comment]
Here is the initial text for the pull request:

[mpi32-report-ticket100-pt2pt-20sep18-1641.pdf](https://github.com/mpi-forum/mpi-issues/files/2401776/mpi32-report-ticket100-pt2pt-20sep18-1641.pdf)

**Comment by wesbland** [comment]
@tonyskjellum / @puribangalore - Is this issue replaced by #137? Can we close this?

**Comment by puribangalore** [comment]
Yes.
