### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#103]
# Problem

Initialisation of MPI is too restrictive. MPI can only be initialised once. Multiple application components (libraries, etc) must coordinate at runtime to arrange for initialisation to happen before any of them can use MPI. No component can finalise MPI without finalising MPI for all components. The race between querying MPI_INITIALIZED and calling MPI_INIT[_THREAD] cannot be resolved cleanly without a priori knowledge or runtime coordination not provided by MPI functionality.

Considering a change to the way MPI is initialised opens up other problems for inclusion in the scope of this change: the built-in communicator MPI_COMM_WORLD is problematic, for a number of reasons, including fault-tolerance (fairly well accepted) and scalability (contentious, debatable). Dynamic use of resources (dynamic applications, fault-tolerance, etc) is considered to be too hard using existing MPI functionality. The progress rule currently applies to the whole of MPI but a finer granularity would be very useful in some circumstances.

# Proposal

Sessions introduces a new way to initialise and use MPI.

# Changes to the Text

This proposal adds new API calls for initialisation of MPI via sessions, called the Peer-to-peer Process Model and adjusts the existing text to accommodate. The traditional initialisation method for MPI (i.e. MPI_INIT[_THREAD]) is named the World Process Model, to complement the new Peer-to-peer Model and the existing Dynamic Process Model (spawn, connect/accept, join).

# Impact on Implementations

This proposal will have fairly broad implications for implementations - it is likely that not all consequential code changes have been worked out yet.

# Impact on Users

New initialisation API available. Backwards compatible, in that the old API still works as previously specified. Incremental adoption is possible and encouraged, in that any combination of the three process models can be used concurrently in each process/application.

# References

Daniel Holmes, Kathryn Mohror, Ryan E. Grant, Anthony Skjellum, Martin Schulz, Wesley Bland, and Jeffrey M. Squyres. 2016. MPI Sessions: Leveraging Runtime Infrastructure to Increase Scalability of Applications at Exascale. In Proceedings of the 23rd European MPI Users' Group Meeting (EuroMPI 2016). ACM, New York, NY, USA, 121-129. DOI: https://doi.org/10.1145/2966884.2966915

https://github.com/hpc/mpi_sessions_code_sandbox

https://pmix.org/pmix-standard/pmix-groups/

Pull request (full development history) -- https://github.com/mpi-forum/mpi-standard/pull/55 (closed, see PR https://github.com/mpi-forum/mpi-standard/pull/160 instead)

Pull request (simple history plus change-bars) -- https://github.com/mpi-forum/mpi-standard/pull/160

**Comment by dholmes-epcc-ed-ac-uk** [comment]
This is the draft standard PDF with the changes from this issue (no change-bars or colours):
[mpi-report-ticket103.pdf](https://github.com/mpi-forum/mpi-issues/files/2404242/mpi-report-ticket103.pdf)

This is an attempt to produce a PDF-diff using latexdiff (disclaimer: nowhere near perfect result!):
[mpi-report-ticket103-diff.pdf](https://github.com/mpi-forum/mpi-issues/files/2404245/mpi-report-ticket103-diff.pdf)

**Comment by brandongc** [comment]
I am getting 404 error from https://github.com/hpc/mpi_sessions_code_sandbox, is this meant to be open?

**Comment by wesbland** [comment]
It’s probably a private repo that we haven’t been granted access to (that’s how repositories with the MPI Standard text are supposed to work). I imagine @hppritcha can help us out here.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@hppritcha has now made the git repo public. Apologies for this oversight.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
This is the latest version of the Standard containing the most recent text for the core Sessions proposal:
[mpi-report-ticket103.pdf](https://github.com/mpi-forum/mpi-issues/files/2558092/mpi-report-ticket103.pdf)

This is the document I will be using for the MPI Forum Virtual meeting today.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Most recent version - probably the version to be read at the Dec meeting:
[mpi-report-ticket103-Dec.pdf](https://github.com/mpi-forum/mpi-issues/files/2596285/mpi-report-ticket103-Dec.pdf)

**Comment by hjelmn** [comment]
Hmm, something I found. Do we want sessions to have names? All MPI objects have names and sessions probably should be no different. Unlike windows there is no easy way to give a session a default name so it might be worth adding ```MPI_Session_get_name``` and ```MPI_Session_set_name```.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Observation:
Groups/requests/error-handlers don't have names, communicators/windows/files do.

Suggested rule:
Things with only local meaning don't have names, things with global meaning do.

Extrapolation to this new situation:
Sessions don't have names, process sets do.

(I'm not actually against adding names to sessions. But we should have a good reason.)

**Comment by hjelmn** [comment]
@dholmes-epcc-ed-ac-uk Makes sense. The reason I asked is because all objects that have error handlers have names. That might be a reason to have them?

This came up because I am ~ 90% of the way through the prototype and just finished implementing ```MPI_Session_create_errhandler``` and noticed the missing name.

**Comment by hjelmn** [comment]
And, while we are discussing this. There is no pset object so should groups now get a name (since they were possibly created from a pset)?

**Comment by bosilca** [comment]
One piece missing: datatypes have names and they are local.

Do sessions have an accessor to retrieve the name/URI they have been
created from ?

George.


  George.

**Comment by hjelmn** [comment]
@bosilca No they do not. They only way the name would be useful is if the user sets it.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
> all objects that have error handlers have names

@hjelmn the converse is not true - why not? Because unclaimed errors are currently raised on MPI_COMM_SELF. This suggests that anything that can be named (for "debugging" purposes) should have an error-handler. If a group manipulation function runs out of resources while manipulating a group created from a PSET obtained from a session, we would have to invoke the session's error-handler at the moment. This almost immediately becomes a topic for the FT WG to arbitrate.

**Comment by bosilca** [comment]
@dholmes-epcc-ed-ac-uk it looks as if all constructs that are neither performance or memory critical have names. Thus, naming requests, which are supposed to be nimble, might be an overhead that we don't want to afford.

Talking about the MPI datatype introspection mechanism, it is a mess to use and to maintain, and while there are reasons to be able to explore how a datatype has been constructed, they are restricted to few, extremely valuable cases (such as I/O). I do not see a similar need for an introspection mechanism for sessions (and it's not because we can that we should add one).

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@bosilca adding a pointer to a string into the request struct would break ABI (bad enough on its own) but would it slow down other operations that use that struct?

I agree that I do not see the need/use-case for additional introspection for groups. Your comment "not because we can that we should" is my reason for gently pushing back against names for sessions.

**Comment by jsquyres** [comment]
@dholmes-epcc-ed-ac-uk Adding a string to a request handle doesn't necessarily break ABI.  But adding that extra data to maintain on a request *could* have performance implications -- at the very least, it's another data member to initialize.  It may also cause a string allocation/copy.  Indeed, if requests always have to have a valid name (i.e,. they can't be empty), then an implementation has to put *some* name there, and that will take time, which is undesirable in the performance-critical code paths in which requests are typically used.

That being said, I like having string names available where possible.  It would be nice to be able to printf, for example, that this session handle is for the ABC library and that session handle is for the XYZ library.  It's not a killer feature, but it would be handy to have (vs. having to make a human realize that session handle 0x392bd3f0 is for library ABC and session handle 0x392bd3fe0 is for library XYZ).

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@jsquyres no other name in MPI is required (disclaimer: I have only checked MPI_Comm names). For example, for MPI_COMM_SET_NAME (MPI-3.1, p282, li 4-5):
> There is no requirement that the same (or any) name be assigned to a communicator
in every process where it exists.

So far, names do not propagate on duplication or copy by MPI. For example, for MPI_COMM_SET_NAME (MPI-3.1, p281, li 24-5):
> The names attached to opaque objects do not propagate when the object is duplicated or copied by MPI routines.

String allocation *does* happen, but only when setting explicitly the name. For example, for MPI_COMM_SET_NAME (MPI-3.1, p281, li 46-47):
> The character string which is passed to MPI_COMM_SET_NAME will be saved inside the MPI library (so it can be freed by the caller immediately after the call, or allocated on the stack)

There is a question about handle-aliasing:
```
MPI_Comm real_thing;
MPI_Comm_dup(MCW, &real_thing);
MPI_Comm_set_name("my comm", &real_thing);
MPI_Comm alias_thing = real_thing;
MPI_Comm_get_name(&myString, alias_thing);
printf(myString);
```
The ```alias_thing``` is not a "duplicate or copy by MPI", what happens? If the name is an internal pointer in the struct MPI_Comm, that pointer will get copied so the above would print "my comm", without the existence of a string dup. Other implementations are possible; YMMV.

Tentative assertion: MPI_Request names would be no worse than existing MPI_Comm names?

**Comment by hjelmn** [comment]
Another point that needs to be addressed (if it isn't already):

Since clearly ```MPI_Session_create_errhandler``` must be allowed before ```MPI_Init``` or ```MPI_Session_Init``` should we allow the other errhandler routines be called. The infrastructure already has to be available for the session error handlers so there is no technical reason to limit it to just session error handlers.

I don't care either way. Just making sure we work through everything with this error handler stuff.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@hjelmn I'm not sure of the relative merits of the options for other types of error handlers.

Creation of error handlers is one thing, but they cannot be used until an object of the appropriate type exists, i.e. until after MPI is initialised by one of the available mechanisms. That suggests that allowing creation of error handler types other than built-in (proposed for use by MPI_INIT) or for sessions before initialisation serves no purpose.

OTOH, if it is really free, in all conceivable implementations, then great.

**Comment by hjelmn** [comment]
@dholmes-epcc-ed-ac-uk It might also make writing the text easier. We can say that all errhandler and info functions are allowed before init and after finalize. It's worth allowing if it makes it easier to update/maintain the standard.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Most recent version - the version that was (partially) read at the Dec meeting and will be (further) read at the 9th Jan virtual meeting, today:
[mpi-report-ticket103-Dec.pdf](https://github.com/mpi-forum/mpi-issues/files/2596533/mpi-report-ticket103-Dec.pdf)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Most recent version - for reading at the face-to-face meeting in Chattanooga, TN in Mar 2019.
[mpi-report-ticket103-2019-FEB-18.pdf](https://github.com/mpi-forum/mpi-issues/files/2876679/mpi-report-ticket103-2019-FEB-18.pdf)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Most recent version - for reading at the face-to-face meeting in Chicago, IL in May 2019.
[mpi-report-ticket103-2019-MAY-13.pdf](https://github.com/mpi-forum/mpi-issues/files/3173525/mpi-report-ticket103-2019-MAY-13.pdf)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Most recent version - for reading at the face-to-face meeting in Chicago, IL in May 2019.
Same as MAY-13 version but with added change-bars.
[mpi-report-ticket103-2019-MAY-27-cb.pdf](https://github.com/mpi-forum/mpi-issues/files/3225519/mpi-report-ticket103-2019-MAY-27-cb.pdf)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Most recent version - for reading (if necessary) at the face-to-face meeting in Zurich in Sept 2019.
[mpi-report-ticket103-2019-AUG-21.pdf](https://github.com/mpi-forum/mpi-issues/files/3526944/mpi-report-ticket103-2019-AUG-21.pdf)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Most recent version - reading at the face-to-face meeting in Albuquerque in Dec 2019.
[mpi-report-ticket103-2019-NOV-25.pdf](https://github.com/mpi-forum/mpi-issues/files/3887544/mpi-report-ticket103-2019-NOV-25.pdf)

A "git diff" file showing changes since the last face-to-face meeting.
[mpi-report-ticket103-2019-NOV-25.diff.txt](https://github.com/mpi-forum/mpi-issues/files/3887549/mpi-report-ticket103-2019-NOV-25.diff.txt)

A "git diff --numstat" file summarising the changes in the "git diff" file.
[mpi-report-ticket103-2019-NOV-25.numstat.txt](https://github.com/mpi-forum/mpi-issues/files/3887553/mpi-report-ticket103-2019-NOV-25.numstat.txt)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
The most recent PDFs (for consideration at the Portland face-to-face in 2 weeks) are attached to this comment.

The clean doc PDF (no change-bars) is here:
[mpi-report-ticket103-2020-FEB-03-clean.pdf](https://github.com/mpi-forum/mpi-issues/files/4149596/mpi-report-ticket103-2020-FEB-03-clean.pdf)

The marked-up PDF (with change-bars) is here:
[mpi-report-ticket103-2020-FEB-03-changebars.pdf](https://github.com/mpi-forum/mpi-issues/files/4149600/mpi-report-ticket103-2020-FEB-03-changebars.pdf)

Note that I created a new PR #160 with simplified history and the change-bars:
https://github.com/mpi-forum/mpi-standard/pull/160

The original PR #55 with full development history and reviews is still available:
https://github.com/mpi-forum/mpi-standard/pull/55

**Comment by wesbland** [comment]
The no-no vote for this proposal at the February 2020 meeting passed:

Yes - 20
No - 0
Abstain - 1

**Comment by wesbland** [comment]
This proposal passed a first vote at the February 2020 meeting:

Yes - 21
No - 0
Abstain - 3

**Comment by dholmes-epcc-ed-ac-uk** [comment]
The most recent clean PDF for this proposal (now fully Pythonised!) is here:
[mpi-report-ticket103-2020-APR-17-clean.pdf](https://github.com/mpi-forum/mpi-issues/files/4494244/mpi-report-ticket103-2020-APR-17-clean.pdf)

The most recent changebars PDF for this proposal (pre-Pythonisation) is here:
[mpi-report-ticket103-2020-APR-17-changebars.pdf](https://github.com/mpi-forum/mpi-issues/files/4494250/mpi-report-ticket103-2020-APR-17-changebars.pdf)

These are intended to be the final PDF versions that will be used for the 2nd (and final) vote for this proposal in the next voting meeting. The changebars version shows *all* changes made by this entire proposal, not just those made since the Portland meeting in Feb 2020.

The changes since the Portland meeting in Feb 2020 (without Pythonisation) can be viewed via Github:
https://github.com/mpi-forum/mpi-standard/pull/55/files/26ccb5fa1940fd8c5dec943d79dd8a955e342281..53ec5c199b6c91fa5e0b032a73ba21c6a61ae348

The changes since the Portland meeting in Feb 2020 (including Pythonisation) can be viewed via Github:
https://github.com/mpi-forum/mpi-standard/pull/160/files/97c83668832c5ea573983d911bc240c30dafbbe5..426b7ede33a36531974b914c67bf018bc768a143

**Comment by wesbland** [comment]
This passed a second vote on 2020-06-30.

https://www.mpi-forum.org/meetings/2020/06/votes
