### ISSUE TITLE
Big MPI--Apply Big MPI -- Large Count / Large Displacement Ideas to the Topologies Chapter

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#105]
# Problem

See Motivation with Ticket #80. 

# Proposal

See Proposal with Ticket #80.  [As may be modified by discussion in Barcelona.]

# Changes to the Text

Add _x function APIs where applicable.

# Impact on Implementations

TBD.

# Impact on Users

New APIs that support MPI_Count / MPI_Aint (where applicable) are done in analogy to Chapter 5.

# References

Ticket #80.

PR https://github.com/mpi-forum/mpi-standard/pull/56

**Comment by tonyskjellum** [comment]
Here is the zeroth version of this chapter (see topologies chapter only).

[mpi32-report-ticket105-19sep18.pdf](https://github.com/mpi-forum/mpi-issues/files/2397843/mpi32-report-ticket105-19sep18.pdf)

**Comment by RolfRabenseifner** [comment]
Dear Tony,

Review:

- MPI_Neighbor_allgather : all _x are missing

- int MPI_Neighbor_allgatherv_x(const void* sendbuf, MPI_Count sendcount,
  MPI_Datatype sendtype, void* recvbuf,
  const_MPI_Count recvcounts[],

  const_MPI_Count --> const MPI_Count

- MPI_NEIGHBOR_ALLGATHERV_X(SENDBUF, SENDCOUNT, SENDTYPE, RECVBUF,
  RECVCOUNTS, DISPLS, RECVTYPE, COMM, IERROR)
  <type> SENDBUF(*), RECVBUF(*)
  INTEGER SENDCOUNT, SENDTYPE, RECVCOUNTS(*), DISPLS(*), RECVTYPE, COMM, IERROR

  You forgot to make them MPI_Count

- MPI_NEIGHBOR_ALLTOALL_X(SENDBUF, SENDCOUNT, SENDTYPE, RECVBUF, RECVCOUNT, ...

  You forgot to make them MPI_Count

- MPI_NEIGHBOR_ALLTOALLV_X(SENDBUF, SENDCOUNTS, SDISPLS, SENDTYPE, RECVBUF,
RECVCOUNTS, RDISPLS,
 
  You forgot to make them MPI_Count

- MPI_Neighbor_alltoallw_x

  C: completetly missing

  F_90: correct

  Old Fortran: You forgot to make them MPI_Count
  and you still have old Name without _x

Best regards
Rolf


  

----- Original Message -----
> From: "github notifications" <notifications@github.com>
> To: "mpi-forum" <mpi-issues@noreply.github.com>
> Cc: "Subscribed" <subscribed@noreply.github.com>
> Sent: Wednesday, September 19, 2018 6:12:30 PM
> Subject: Re: [mpi-forum/mpi-issues] Big MPI--Apply Big MPI -- Large Count / Large Displacement Ideas to the Topologies
> Chapter (#105)

> Here is the zeroth version of this chapter (see topologies chapter only).
> 
> [mpi32-report-ticket105-19sep18.pdf](https://github.com/mpi-forum/mpi-issues/files/2397843/mpi32-report-ticket105-19sep18.pdf)
> 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mpi-forum/mpi-issues/issues/105#issuecomment-422863500

-- 
Dr. Rolf Rabenseifner . . . . . . . . . .. email rabenseifner@hlrs.de .
High Performance Computing Center (HLRS) . phone ++49(0)711/685-65530 .
University of Stuttgart . . . . . . . . .. fax ++49(0)711 / 685-65832 .
Head of Dpmt Parallel Computing . . . www.hlrs.de/people/rabenseifner .
Nobelstr. 19, D-70550 Stuttgart, Germany . . . . (Office: Room 1.307) .

**Comment by tonyskjellum** [comment]
@RolfRabenseifner -- making updates now; that was the rough draft admittedly.  Thank you for checking.
Will post update shortly on this comment.

**Comment by tonyskjellum** [comment]
Latest update:

[mpi32-report-ticket105-19sep18-2333.pdf](https://github.com/mpi-forum/mpi-issues/files/2398843/mpi32-report-ticket105-19sep18-2333.pdf)

**Comment by tonyskjellum** [comment]
Latest update (improves change log):

[mpi32-report-ticket105-20sep18-1044.pdf](https://github.com/mpi-forum/mpi-issues/files/2400484/mpi32-report-ticket105-20sep18-1044.pdf)

**Comment by tonyskjellum** [comment]
An update is forthcoming that adds _X APIs for the persistent API approved with Ticket #25 at the Barcelona meeting.

**Comment by wesbland** [comment]
@tonyskjellum / @puribangalore - Is this issue replaced by #137? Can we close this?

**Comment by puribangalore** [comment]
Yes, we can close this issue.
