### ISSUE TITLE
MPI_Alltoallw is inconsistent in its definition because it has byte displacements. 

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#106]
# Problem

MPI_Alltoallw is inconsistent in its definition because it has byte displacements.

# Proposal

MPI_Alltoallw is inconsistent in its definition because it has byte displacements, yet they are defined as int, not MPI_Aint.

So, we need a ticket as an "Advice to Users" in the Collective Chapter.  Notice that a solution from Big MPI Ticket #80 will address this in an _x API.  But, we also want to document the limitation of the existing API, which remains in use.

# Changes to the Text

An advice to users will be added beneath the MPI_Alltoallw definition.

# Impact on Implementations

None.

# Impact on Users

It is just a warning.  It may induce users to use MPI_Neighbor_alltoallw or to use MPI_Alltoallw_x (if adopted).

# References

See Ticket #80 and https://github.com/mpi-forum/mpi-standard/pull/34 .

**Comment by jeffhammond** [comment]
I don’t see why this is necessary. The standard is not a user guard and
this advice seems pretty obvious to the type of people who read the
standard. Hopefully the advice will be present in tutorials and man pages.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by tonyskjellum** [comment]
Reopen?

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@tonyskjellum re-visit for consideration when MPI-4k (pronounced MPI-fork) is in full swing.

**Comment by jsquyres** [comment]
Please don't use the term "fork" -- per https://github.com/mpi-forum/mpi-issues/issues/80#issuecomment-424013091.
