### ISSUE TITLE
Big MPI---Apply Big MPI---Datatype chapter needs work to complete its support

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#108]
# Problem

Ticket #80 specifies the Big MPI approach for 64-bit clean MPI.  The datatype chapter has to have some changes.

# Proposal

_X version of functions involving counts and displacements are needed.

# Changes to the Text

Appropriate _X APIs will be added.

# Impact on Implementations

TBD.

# Impact on Users

Enables users to use Ticket #80 and its relatives fully in MPI-4.

# References

Ticket #80, #98, #105

**Comment by wesbland** [comment]
@tonyskjellum / @puribangalore - Is this issue replaced by #137? Can we close this?

**Comment by puribangalore** [comment]
Yes.
