### ISSUE TITLE
Info Assertions

### ISSUE THREAD

**Issue by jdinan** [mpi-forum/mpi-issues#11]
## Summary

This ticket relaxes the restriction that info keys cannot change semantics.  It allows info keys to be used to provide application behavior hints, which an implementation can use to restrict the set of functionality or semantics supported, e.g. on a particular communicator, to optimize performance for the given usage model.

The proposal has been split into three parts:
- #52  - Removes info key propagation from MPI_COMM_DUP (ticketErrta)
- #53 - MPI_COMM_DUP_WITH_INFO can be used to explicitly propagate info hints (ticketIDWI)
- #11 - Adds communicator info keys and allows info assertions (ticketInfo)
## Proposed Changes
- [P2P WG comm-info branch](https://github.com/mpiwg-p2p/mpi-standard/tree/comm-info).
## Related Tickets
-  Old Trac ticket -- https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/476
-  Communicator info assertions -- https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/381
## Proposal Drafts
- 03-01-2016 Reading: [PDF Draft](https://github.com/mpi-forum/mpi-issues/files/131883/mpi-report.pdf), [PDF Draft with Notes](https://github.com/mpi-forum/mpi-issues/files/157806/comm-info-reading.pdf)
- 12-09-2015 Reading: [PDF Draft](https://github.com/mpi-forum/mpi-issues/files/41884/mpi-report.pdf), [PDF Draft with Notes](https://github.com/mpi-forum/mpi-issues/files/66909/Info.Reading.Notes.-.12-9-2015.pdf)
- 06-08-2016 Readings: [PDF Draft](https://github.com/mpi-forum/mpi-issues/files/278103/mpi-report.pdf)

**Comment by rsth** [comment]
For the four new asserts on pg 249, can we change "If set to true" to "If set to \infoval{true}" so that true appears in the right font. See, for example, the values for the collective_buffering key on pg 502.

**Comment by jdinan** [comment]
Thanks!  I updated the PDF and PR with the corrected formatting for 'true' info values.

**Comment by jsquyres** [comment]
@jdinan Is this to be read in Bellevue?  If so, can you update the milestone?  Thanks.

**Comment by hritzdorf** [comment]
There is a blank missing in "torestrict" Page 365 Line 20 of PDF draft.

**Comment by RolfRabenseifner** [comment]
In general, when implementing blocking and non-blocking collective communication internally with MPI point-to-point then the overtaking must be switched off for such messages, which may be not a problem if the communicator is duplicated without duplicationg this info about overtaking is allowed.

**Comment by RolfRabenseifner** [comment]
And yes, an advice to implementors would be a good idea.

**Comment by tonyskjellum** [comment]
Sure but the standard just has to say  that the assertion only applies to point to point ; it is ok as advice to implementers to remind them 

Anthony Skjellum, PhD
205-807-4968

**Comment by jdinan** [comment]
The info key text is as follows:
> If set to true, then the implementation may assume that point-to-point communications on the given communicator do not rely on the non-overtaking rule specied in Section 3.5.

If there is an advice needed, perhaps it is advice to implementors to be careful that support for this info key doesn't break their collectives?
