### ISSUE TITLE
Clean up topology chapter

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#110]
# Problem

Issues noted by Bill Gropp before the release of SC'18 Draft--- Example issues in Topologies Chapter.

# Proposal

From Bill: In Topologies - there are many examples, but they aren't  all listed as
"Examples", which means that they are not indexed.  This should be
reconsidered, and appropriate \exindex commands added.

In 7.5.7, 
- [x] Example 7.8 is mixed C and language independent - it needs
to be eithe all C or all language independent.  To make language
independent, it should use mpicodeblock environemnt, and not have a
';' at the end of the call.

In 7.6.1, 
- [x] there is an example that (a) isn't described as an example
(just inline in the text) and 
- [x] <strike>(b) declares "int k,l;" between
executable statements, something not in older versions of the C
standard.
 Check that this is (a) allowed and (b) better exposition.</strike> (c99 is fine as discussed in https://github.com/mpi-forum/mpi-standard/pull/392)

# Changes to the Text

Appropriate corrections to be made.

# Impact on Implementations

None.

# Impact on Users

Readability of standard.

# References

Insert any internal (other issues) or external (websites, papers, etc.) references here.

**Comment by cniethammer** [comment]
The mixed language example 7.8. was fixed with https://github.com/mpi-forum/mpi-standard/pull/303

**Comment by cniethammer** [comment]
Single letter variables using the letters `l`, `I`, `O` should be avoided in general.
The mentioned code in 7.6.1 could use only the single variable k for iterating over the two loops as they are independent.

**Comment by cniethammer** [comment]
I see in total five places in 7.6.1 having the same issues (a) and (b):
`MPI_Neighbor_allgather`, `MPI_Neighbor_allgatherv`, `MPI_Neighbor_alltoall`, `MPI_Neighbor_alltoallv`, `MPI_Neighbor_alltoallw`

**Comment by cniethammer** [comment]
The mentioned code in 7.6.1 (MPI-3.1, pp. 315-316) is part of the definition text and not an example. (Was discussed in https://github.com/mpi-forum/mpi-issues/issues/343#issuecomment-733838274)

**Comment by cniethammer** [comment]
@wgropp: With https://github.com/mpi-forum/mpi-standard/pull/392 all mentioned points are addressed.

**Comment by cniethammer** [comment]
This can be closed:
* first 2 points already addressed
* third point will not be addressed after discussions (details in https://github.com/mpi-forum/mpi-standard/pull/392)
