### ISSUE TITLE
Allow management of MPI_Info objects independed of initialization state of MPI

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#115]
# Problem

With `MPI_Info`, MPI defines standardized access to string-based key/value stores. These can be used to communicate information between the MPI implementation and the user.

In some situations, such as setup of the MPI tool information interface, fault tolerance, or the upcoming sessions, information would need to be set up before MPI initialization, which is currently not allowed. In these scenarios, information would need to be passed by other arguments to the respective calls.

# Proposal

Allow `MPI_Info` objects to be created and managed independent of the initialization stage of MPI.

# Changes to the Text

Info routines will need to be added to the list of functions allowed to be called before MPI initialization.

# Impact on Implementations

- As info objects are just string-based key/value stores, this should be able to be provided without much additional setup of MPI.
- The current proposal requires the calls to be thread-safe, which may have a larger implementation impact.

# Impact on Users

More integrated use of info objects to communicate information between users and implementation.

# References

mpi-forum/mpi-standard/pull/110

**Comment by mahermanns** [comment]
@wesbland @dholmes-epcc-ed-ac-uk Should we add the labels of your groups to this ticket as well, as you voiced interest in this for your topics as well?

**Comment by wesbland** [comment]
I don't think so. We usually only add labels for the group driving the proposal. If course, that doesn't mean that we can't take a look and pitch in opinions. I'll try to look through this today and hopefully @abouteiller can do so as well.

**Comment by wesbland** [comment]
Oh, nevermind. I thought this was a pull request, not an issue saying what needs to happen later. 😄

**Comment by abouteiller** [comment]
Marc-André, the error management working group will design a mechanism for controlling error behavior before MPI init. I'll cross-ref your issue when we have the PR on our side, since this will be the main driver for now.

**Comment by jeffhammond** [comment]
> Marc-André, the error management working group will design a mechanism for
> controlling error behavior before MPI init. I'll cross-ref your issue when
> we have the PR on our side, since this will be the main driver for now.
>

What happens in a hosted implementation?  That seems like the primary
obstacle to reasonable behavior here.


> --
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by hjelmn** [comment]
FYI, this also affects the sessions working group. We need a definition for failures before ```MPI_Session_init```. This includes info and errhandler creation. The only sensible definition is that it is errors returns until you have some MPI object IMHO. Anything else is just going to be too complicated.

**Comment by abouteiller** [comment]
@hjelmn Yes, this is another critical reason why we are reworking the current MPI_init behavior ticket: include something that will play nice before session_init.

**Comment by abouteiller** [comment]
Current text for  issue #102 (pull request https://github.com/mpi-forum/mpi-standard/pull/50) adds capabilities for sane error handling before MPI_INIT. Please verify if that serves your purpose.

**Comment by raffenet** [comment]
I think the impact on implementations is a bit downplayed in the above summary. The string handling is straight-forward, but the PR adds all `MPI_Info_*` routines to the "required to be thread safe" list. For MPICH, object creation requires thread safety. This change will require the thread safety system to be initialized without knowledge of the required thread level, or else some workaround provide the required protection. Why not push this requirement on users to not make concurrent calls to `MPI_Info_*` routines before `MPI_Init`?

**Comment by hjelmn** [comment]
Ken, all routines before MPI_Init or MPI_Session_init must be thread safe. In Open MPI it is trivial to drop the level on init if needed.

**Comment by raffenet** [comment]
All routines before M

**Comment by omor1** [comment]
@hjelmn and in any case info creation shouldn't be in the critical path of any reasonable application.

**Comment by hjelmn** [comment]
@omor1 Exactly.

**Comment by raffenet** [comment]
@hjelmn @omor1 I think everyone understands that there are software engineering solutions to this issue, and that Info creation is not critical path functionality. My point is that requiring thread safety makes this more complicated than just storing some string-based key/value pairs before `MPI_Init`. I think the impact statement above misses this context.

**Comment by jsquyres** [comment]
Also, we discussed yesterday during the tools WG meeting that this has impacts for `MPI_INFO_ENV`, specifically:

* An implementation may need to lazily make `MPI_INFO_ENV` (vs. just unconditionally making it in INIT), because "lazily" may mean "before INIT" and/or "after FINALIZE".
* A high quality implementation may need to install a hook to be fired when the process completes (e.g., `atexit()` or the like) to tear down `MPI_INFO_ENV` and/or any other behind-the-scenes info state so that MPI can be memory-debugger clean at exit.
* The `thread_level` value in `MPI_INFO_ENV` will only be available / relevant while MPI is initialized.
    * We rationalized this because there's also a `wdir` value on `MPI_INFO_ENV` that can also potentially change value during the life of the MPI process.

All of these are very do-able, and none impact performance.  But they do emphasize that it may not be a trivially little thing to divorce the usage of info objects from the initialization state of MPI.

**Comment by wesbland** [comment]
> Also, we discussed yesterday during the tools WG meeting that this has impacts for `MPI_INFO_ENV`, specifically:
> 
> * An implementation may need to lazily make `MPI_INFO_ENV` (vs. just unconditionally making it in INIT), because "lazily" may mean "before INIT" and/or "after FINALIZE".
> * A high quality implementation may need to install a hook to be fired when the process completes (e.g., `atexit()` or the like) to tear down `MPI_INFO_ENV` and/or any other behind-the-scenes info state so that MPI can be memory-debugger clean at exit.
> * The `thread_level` value in `MPI_INFO_ENV` will only be available / relevant while MPI is initialized.
>   
>   * We rationalized this because there's also a `wdir` value on `MPI_INFO_ENV` that can also potentially change value during the life of the MPI process.
> 
> All of these are very do-able, and none impact performance. But they do emphasize that it may not be a trivially little thing to divorce the usage of info objects from the initialization state of MPI.

Does this mean that you're going to give `MPI_INFO_ENV` support after all? If so, that's great, but I don't know how you'll get around the problem of not having run `MPI_INIT` yet for implementations that rely on it.

**Comment by mahermanns** [comment]
@raffenet I updated the impact section to reflect that tread-safety may not be trivial. Is the statement what you need/expect/want?

**Comment by raffenet** [comment]
Yes, thanks.

**Comment by abouteiller** [comment]
> * The `thread_level` value in `MPI_INFO_ENV` will only be available / relevant while MPI is initialized.
>   
>   * We rationalized this because there's also a `wdir` value on `MPI_INFO_ENV` that can also potentially change value during the life of the MPI process.
> 

According to the text in section 8.7 
```
Advice to users. The values passed in MPI_INFO_ENV are the values of the arguments passed to the mechanism that started the MPI execution — not the actual value provided. Thus, the value associated with maxprocs is the number of MPI processes requested; it can be larger than the actual number of processes obtained, if the soft option was used. (End of advice to users.)
```

So similarly for `wdir`, `thread_level` and friends, all these are immutable.

**Comment by mahermanns** [comment]
As the functionality described here is also contained in the [sessions proposal](github.com/mpi-forum/mpi-issues/103) and the corresponding [PR](github.com/mpi-forum/mpi-standard/pull/55), we decided not to pursue the functionality with this separate issue. Access to `MPI_INFO_ENV` or similar information is handled [here](https://github.com/mpi-forum/mpi-issues/issues/143) and the corresponding [PR](https://github.com/mpi-forum/mpi-standard/pull/126).
