### ISSUE TITLE
Clarify what MPI_SUCCESS guarantees, and what is left undefined when MPI_ERR_XXX happens

### ISSUE THREAD

**Issue by abouteiller** [mpi-forum/mpi-issues#119]
# Problem

The definition of `MPI_SUCCESS` is a terse "no error returned".  When we operate under the assumption that some failure (process, resource, transport, otherwise)  may happen, we need to clarify in which cases `MPI_SUCCESS` is possible, and what it guarantees. For example an implementation may mask errors that do not have a direct consequence on the call semantic. 

Conversely, we need to clarify what arguments and buffers are valid or undefined after a call has raised an error.

# Proposal

Define that `MPI_SUCCESS` means that the operational semantic is respected when the call returns `MPI_SUCCESS`.

Define that array of statuses and other error-code containing output parameters are always valid, even after an error is raised. Clarify that the rest is undefined (i.e., synchronizing behavior, buffer content, and other output parameters). 

# Changes to the Text

Section 8.3 (details in PR).

# Impact on Implementations

None, standardizing and clarifying current state of the practice for success case. The proposal remains very flexible about what an implementation may choose to provide.  

# Impact on Users

Backward compatible. Permits better error handling by making reasonable assumptions about error code and status objects explicit. 

# References

mpi-forum/mpi-standard#95

Spawned from mpi-forum/mpi-standard#50

**Comment by abouteiller** [comment]
Some of the original rationale can be found in the discussion of the referenced PR

**Comment by wesbland** [comment]
Here's the text that will be voted on as no-no on 2019-05-31: https://github.com/mpi-forum/mpi-standard/pull/95/files/2c96377434af4b5c88bd09001ead749d4ab389df..d94b3d34946a24820241e74339771ca169388122

**Comment by wesbland** [comment]
This passed the second and final vote in Zurich, Switzerland on 2019-09-07.
