### ISSUE TITLE
MPI_T Errata: Code bug in Example 14.4 in 3.1

### ISSUE THREAD

**Issue by kathrynmohror** [mpi-forum/mpi-issues#12]
The CVAR example in the official 3.1 document Section 14.3 (MPI Tool CVAR) page 577 compiles but doesn¹t do the expected work. One must change the || at line 7 into && to have it perform as advertised.

Replace page 577 line 7:
`if (err!=MPI_SUCCESS || err!=MPI_T_ERR_INVALID_INDEX) return err;`

with 
`if (err!=MPI_SUCCESS && err!=MPI_T_ERR_INVALID_INDEX) return err;`

**Comment by kathrynmohror** [comment]
[Pull request 7](https://github.com/mpi-forum/mpi-standard/pull/7)

**Comment by jsquyres** [comment]
This issue would have been voted on at the 2015 Dec meeting (it had a reading and there was a meeting quorum), but against all odds, the Forum completed all the rest of its work a day before the scheduled vote.  Hence, no one came for the scheduled vote at the appointed time, and the per-vote quorum was not met.

So we're deferring this vote until the Feb 2016 Forum meeting.

**Comment by jsquyres** [comment]
PR was merged.
