### ISSUE TITLE
Errata: Add missing info keys to language bindings

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#123]
# Problem

When previously adding info keys prefixed with `mpi_`, the authors forgot to add these to Appendix A with the language bindings.

Note that this is an errata with the text adopted after MPI 3.1 so there will not be an entry in the errata document. Only the appendix will be changed.

# Proposal

Add the missing info keys to the bindings appendix.

# Changes to the Text

Add these keys

* mpi_assert_allow_overtaking
* mpi_assert_exact_length
* mpi_assert_no_any_source
* mpi_assert_no_any_tag
* mpi_assert_strict_start_ordering
* mpi_optimization_goal
* mpi_reuse_count

# Impact on Implementations

None

# Impact on Users

None

# References

None

**Comment by abouteiller** [comment]
There is also a list of predefined info values right under it you might want to check.

**Comment by wesbland** [comment]
The values for all of the assertions are `true`/`false`, which are already in the list.
