### ISSUE TITLE
Add MPI assertion keys to the Language Bindings chapter

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#124]
# Problem

A previous issue added four info assertions to the standard but failed to add the keys to the Language Bindings chapter.

# Proposal

The four keys are added to the list of info keys in section A.1.5

# Changes to the Text

The four keys are added to the list of info keys in section A.1.5

# Impact on Implementations

None.

# Impact on Users

None.

# References

None.

**Comment by wesbland** [comment]
Duplicates #123
