### ISSUE TITLE
Add nonblocking versions of sendrecv

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#125]
# Problem

The MPI_SENDRECV and MPI_SENDRECV_REPLACE operations are useful to express ring communication (and other patterns). However, there is no nonblocking version or persistent version of these functions.

# Proposal

Add new API definitions for nonblocking and persistent versions of send and receive operations.

# Changes to the Text

1. Move blocking send and receive operations into the blocking subsection.
2. Add nonblocking versions of send and receive operations to nonblocking subsection.
3. Add persistent versions of send and receive operations to persistent subsection.

# Impact on Implementations

A minimal implementation can be achieved by {MPI_ISEND;MPI_IRECV;MPI_WAITALL;} with additional internally buffering for the replace operation.

# Impact on Users

Additional opportunities to introduce nonblocking and persistent semantics into application codes.

# References

PR 104: https://github.com/mpi-forum/mpi-standard/pull/104

**Comment by raffenet** [comment]
> A minimal implementation can be achieved by {MPI_ISEND;MPI_IRECV;MPI_WAITALL;} with additional internally buffering for the replace operation.

Is the suggestion that a minimal implementation would implement these as blocking calls by using `MPI_Waitall` internally?

**Comment by raffenet** [comment]
Can an `MPI_Isendrecv` be cancelled?

**Comment by raffenet** [comment]
> Can an `MPI_Isendrecv` be cancelled?

To be clear, I'm assuming (hoping) the answer is no. IIRC, nonblocking pt2pt operations are allowed to be cancelled, with the caveat that cancelling a send is "deprecated". Explicitly disallowing cancel of nonblocking sendrecv operations might be good to do from the start.

**Comment by brandongc** [comment]
Yes, the suggestion was that a minimal implementation could be done that way.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
> Is the suggestion that a minimal implementation would implement these as blocking calls by using MPI_Waitall internally?

No. MPI_ISENDRECV only includes the MPI_ISEND and MPI_IRECV. The MPI_WAITALL is called separately by the user.

MPI_ISENDRECV is local and nonblocking - including MPI_WAITALL inside it breaks that semantic.

``` C
int MPI_Isendrecv(...) {
    MPI_Isend(...);
    MPI_Irecv(...);
}

int main() {
    MPI_Isendrecv(...);
    MPI_Waitall(...);
}
```

**Comment by dholmes-epcc-ed-ac-uk** [comment]
I am hoping that MPI_ISENDRECV cannot be cancelled.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Corollary question: can MPI_SENDRECV_INIT be implemented using MPI_SEND_INIT and MPI_RECV_INIT?

``` C
int MPI_Sendrecv_init(...) {
    MPI_Send_init(...);
    MPI_Recv_init(...);
}

int main(...) {
    MPI_Sendrecv_init(...);
    MPI_Start(...);
    MPI_Waitall(...);
}
```

This assumes that MPI_SENDRECV_INIT follows point-to-point matching rules, i.e. the match happens each time MPI_START is called.

The alternative is that we could define MPI_SENDRECV_INIT to be more like a collective, i.e. the matching is done once during the initialisation function. For this option, the minimal implementation might involve MPI_ALLTOALLV_INIT with count=1 for only two processes (and count=0 for all others).

**Comment by raffenet** [comment]
> The alternative is that we could define MPI_SENDRECV_INIT to be more like a collective, i.e. the matching is done once during the initialisation function. For this option, the minimal implementation might involve MPI_ALLTOALLV_INIT with count=1 for only two processes (and count=0 for all others).

MPI_SENDRECV is not required to be symmetrical, so I'm not sure how this would be possible without further restrictions.

**Comment by raffenet** [comment]
> > The alternative is that we could define MPI_SENDRECV_INIT to be more like a collective, i.e. the matching is done once during the initialisation function. For this option, the minimal implementation might involve MPI_ALLTOALLV_INIT with count=1 for only two processes (and count=0 for all others).
> 
> MPI_SENDRECV is not required to be symmetrical, so I'm not sure how this would be possible without further restrictions.

For instance, how to deal with `MPI_ANY_SOURCE`?

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@raffenet you are right, the implementation may not be able to use MPI_ALLTOALLV in all situations. The question is about the matching though. Once or many times?

**Comment by raffenet** [comment]
Matching once is an interesting idea to consider, but I think it strays from the intent of the proposal. At minimum there would need to be guidance or restrictions on the use of wildcards in the recv arguments.

**Comment by jeffhammond** [comment]
@raffenet If people want to implement a match-once semantic, they can use RMA with dynamic windows.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@jeffhammond RMA != point-to-point

**Comment by brandongc** [comment]
Since the path forward for the persistent version is unclear I am going to try to remove it from this PR via "no no".

The non-blocking still makes sense on the basis of:

a) MPI_Sendrecv_replace is a different semantic than separate send and receive operations, there is no nonblocking/persistent version of that semantic
b) consistency, orthogonality, least-surprise (e.g. a user may have copied the shift example in the standard which uses sendrecv_replace).

**Comment by hzhou** [comment]
> @raffenet If people want to implement a match-once semantic, they can use RMA with dynamic windows.

Actually I am start seeing the merit of this comment.

**Comment by wesbland** [comment]
This passed the no-no vote and first vote in Albuquerque, New Mexico on 2019-12-12.

**Comment by wesbland** [comment]
This proposal passed a second and final vote at the February 2020 meeting:

Yes - 17
No - 2
Abstain - 5
