### ISSUE TITLE
Erroneous deletion of text

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#126]
# Problem

The approved text fix for deprecating MPI_SIZEOF erroneously deleted a sentence that refers to a different MPI routine

# Proposal

Restore (the slightly modified) text

# Changes to the Text

Insert

> The following function allows a user to obtain a size-specific \MPI/ datatype for any intrinsic Fortran type.

in binding-2.tex immediately before this line

> \begin{funcdef}{MPI\_TYPE\_MATCH\_SIZE(typeclass, size, datatype)}

# Impact on Implementations

No change to implementations

# Impact on Users

No change for users

# References

See discussion in https://github.com/mpi-forum/mpi-standard/pull/17

**Comment by wesbland** [comment]
@wgropp - Will you be at the Zurich meeting to read this or do you need someone to move it along? I don't think anything happened with this at the Chicago meeting.

Alternatively, I'd personally say that this could be a document editor change and wouldn't need to go through a reading either way.

**Comment by wgropp** [comment]
I think this can be done as the editor's choice.  Unfortunately, I won't be at the Zurich MPI Forum meeting, though I will be at the workshop and EuroMPI meeting the following week.

**Comment by wgropp** [comment]
The best thing is to fix it in the change, which hasn't been applied yet.

**Comment by wgropp** [comment]
I've restored this sentence as an editor's change.
