### ISSUE TITLE
Cleanup datatype creation function names

### ISSUE THREAD

**Issue by yfguo** [mpi-forum/mpi-issues#131]
# Problem

In MPI-2, we deprecated a bunch of datatype creation functions and created new versions for those.  For example, we created `MPI_Type_create_hvector` and deprecated `MPI_Type_hvector`.  However, we missed a few functions in doing that.  Specifically, `MPI_Type_contiguous`, `MPI_Type_vector` and `MPI_Type_indexed`. 

# Proposal

Deprecatie `MPI_Type_contiguous`, `MPI_Type_vector` and `MPI_Type_indexed` and create `MPI_Type_create_contiguous`, `MPI_Type_create_vector` and `MPI_Type_create_indexed` to supercede them respectively.

# Changes to the Text

https://github.com/mpi-forum/mpi-standard/pull/109

# Impact on Implementations

Adding the corresponding new function which can be done by duplicating the existing functions and change the function names.

# Impact on Users

The can still use the deprecated functions but encouraged to use the new functions.

# References

Insert any internal (other issues) or external (websites, papers, etc.) references here.

**Comment by zerothi** [comment]
I agree on this!

**Comment by jeffhammond** [comment]
Sounds good to me.  It's annoying to have to remember which types are `MPI_Type_create_<type>` and which are `MPI_Type_<type>`.

**Comment by jeffhammond** [comment]
FYI the private discussion is negative on this:

Bill:
> I don't see the point in this change. The "create" versions of the datatype routines were added to replace int/INTEGER with address-sized integers where that mattered - that is why MPI_Type_hvector became MPI_Type_create_hvector (the stride was in bytes) and MPI_Type_vector was not change (the stride was in extents of the datatype, using the natural integer type. This was not an oversight but a deliberate choice.

George:
> We had this discussion in the past. In MPI-2 we did deprecate some of the datatype creation functions because there was a mismatch between their C and Fortran interfaces (C taking MPI_Aint or the stride where the Fortran API was limited to an int). We deliberately made the decision not to deprecate the other datatype creation function simply to accommodate for a name change.

This does not mean you can't try again, but there will be a headwind.

**Comment by zerothi** [comment]
The main idea would be to streamline the API, and in this case it is confusing that `MPI_Type_create_hvector` *AND* `MPI_Type_vector` are the preferred methods.

@jeffhammond (knowing you are not the target to convince ;))

My 2 cents. :)

**Comment by Wee-Free-Scot** [comment]
PR has been abandoned -- closing issue.
