### ISSUE TITLE
specify normative language references (particularly for ISO C)

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#139]
# Problem

We say "ISO C" many times without defining it or citing a specific ISO document.

On the other hand, we cite specific documents for Fortran 2008, POSIX, Unicode, etc.

# Proposal

Define what ISO means and cite the document that defines it, e.g. ISO/IEC 9899:2011.

# Changes to the Text

TODO

# Impact on Implementations

None in most cases, but Microsoft may have a problem if we refer to a version of C that their compiler doesn't support.  On the other hand, MPI references `int64_t` already, which was introduced in C99, so there is already an implicit requirement of C99 support, which Microsoft's compiler lacks (although they support fixed-width integer types, which are also defined in C++11).

# Impact on Users

Users almost certainly don't care what the standard says about ISO standard languages, as long as their MPI implementation works with their compiler.

# References

https://github.com/mpi-forum/mpi-issues/issues/137#issuecomment-498516821

**Comment by hjelmn** [comment]
@jeffhammond I believe that Microsoft has updated their compiler to support most of C99 (and probably C11). Someone from Microsoft will have to confirm but otherwise I fully support clarifying it as being at least ISO C99.

**Comment by omor1** [comment]
If I recall correctly the fixed-width integer MPI types are optional as well.

How do people feel about introducing support for C integer types (e.g. `size_t`, `ptrdiff_t`)? MPI does support its own version of each (`MPI_Count`, `MPI_Aint`), but doesn’t have built-in types for the C language types.

**Comment by hjelmn** [comment]
@omor1 I think this is covered by another proposal. The idea is to allow the MPI implementation to make datatypes for every language type if it is defined. Can't remember the ticket number. I am hoping at the same time we can deprecate the poorly-named MPI_LONG_INT, and MPI_SHORT_INT at the same time as those names collide with C types and do not represent the C types.

**Comment by hjelmn** [comment]
@omor1 The proposal was along the lines of MPI_LANGUAGE_TYPE. So, MPI_C_INT64_T for example.

**Comment by mhoemmen** [comment]
> How do people feel about introducing support for C integer types (e.g. `size_t`, `ptrdiff_t`)?

It's useful for C or C++ programmers who call MPI functions directly.  It's not so useful for writing C++ bindings.  In practice, we create C++ bindings by template-specializing some traits class and/or function for every built-in type that's actually a type, not a typedef.  `size_t` etc. are aliases (typedefs), not actual types, so you can't template-specialize on them or safely write overloads (e.g., `size_t` could be any unsigned integer type of the right size).

**Comment by hzhou** [comment]
A related side-note: what does standard say about when an optional type, e.g. MPI_LONG_LONG_INT, is not available in an implementation?

**Comment by hjelmn** [comment]
MPI_LONG_LONG_INT .... now there is some great consistency for you :)

**Comment by hzhou** [comment]
> How do people feel about introducing support for C integer types (e.g. `size_t`, `ptrdiff_t`)? MPI does support its own version of each (`MPI_Count`, `MPI_Aint`), but doesn’t have built-in types for the C language types.

It is just adding on top of existing mess, ...so, why not?

Personally I would see just another direction. How about only specifying sized-types, i.e. MPI_INT_8, MPI_UINT_8, ..., MPI_INT_32, MPI_UINT_32, ... . Plus get-functions, e.g. `MPI_Type_basic(TYPE, sizeof(long))`, where `TYPE` is one of the enum constants - INT, UINT, FLOAT, .... The second argument is the type size in bytes, but for FORTRAN, it could be a kind value.

**Comment by hjelmn** [comment]
@hzhou I personally don't think that is the best path forward. As I already mentioned, there is a proposal to allow the MPI implementation to define any type available in the binding language. IMHO that is the best path forward. See PR mpi-forum/mpi-standard#54

**Comment by tonyskjellum** [comment]
Hi when did that happen ? It was not case as of recently ... is there evidence ?  A URL? Generics weren’t there in C when I looked a month or so ago ... 

Anthony Skjellum, PhD
205-807-4968

**Comment by hjelmn** [comment]
@tonyskjellum From Microsoft's website: "C99 Conformance Visual Studio 2015 fully implements the C99 Standard Library, with the exception of any library features that depend on compiler features not yet supported by the Visual C++ compiler". They were the last to add support for it.

**Comment by tonyskjellum** [comment]
Write it up IMHO :-) 

size_t is unsigned ; isn’t both MPI_Count and MPI_Aint signee ? 



Are these guarantees 

Anthony Skjellum, PhD
205-807-4968

**Comment by mhoemmen** [comment]
@hjelmn wrote:
> See PR [mpi-forum/mpi-standard#54](https://github.com/mpi-forum/mpi-standard/pull/54)

The link appears to be broken -- would you happen to have a working link?  Thanks!

**Comment by puribangalore** [comment]
It works fine, you need to login to github.

**Comment by mhoemmen** [comment]
@puribangalore wrote:
> It works fine, you need to login to github.

Does one need access permissions?  I'm typing this comment in my browser window while logged into GitHub.

**Comment by jsquyres** [comment]
@mhoemmen You need to have access to the MPI Forum repo.  If you agree to [these terms](https://github.com/mpi-forum/mpi-issues/wiki/Access-to-the-MPI-Forum-private-repository), we can give you access.

**Comment by mhoemmen** [comment]
@jsquyres I do so agree; thanks!

**Comment by mhoemmen** [comment]
Thanks @jsquyres ! :-D

**Comment by hjelmn** [comment]
Wow, @jsquyres will just let anyone have access :)

**Comment by omor1** [comment]
@hjelmn well the link clearly lays out that anyone can have access as long as they agree to the listed terms ¯\_(ツ)_/¯.

**Comment by mhoemmen** [comment]
@hjelmn wrote:
> Wow, @jsquyres will just let anyone have access :)

You apparently think I'm just anyone ;-P

**Comment by jeffhammond** [comment]
Closing in favor of https://github.com/mpi-forum/mpi-issues/issues/693

**Comment by bkmgit** [comment]
Sorry, missed this.

**Comment by jeffhammond** [comment]
So did I 😄
