### ISSUE TITLE
MPI_SCATTERV missing "significant only at root"

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#14]
Unlike MPI_SCATTER, MPI_SCATTERV is missing 'significant only at root' for sendcounts, displs and sendtype

**Comment by rsth** [comment]
It is mentioned in the text on 162:9-10. "All arguments to the function are significant on process root, while on other processes, only arguments recvbuf, recvcount, recvtype, root, and comm are significant."

**Comment by bosilca** [comment]
While we're talking about the significance of the collective arguments, should we change the prototype of the collective functions to change the recvbuf from OUT to INOUT to cover the case of MPI_IN_PLACE ?

**Comment by jeffhammond** [comment]
@rsth Ok, thanks.  I don't know how I missed that, or the user that reported this to me.
