### ISSUE TITLE
Create MPI_INFO_ENV before MPI_INIT

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#143]
# Problem

As part of a number of proposals (improving error handling - #102, sessions - #103, and tools) it is helpful to have access to an `MPI_INFO_ENV`-like object before `MPI_INIT` is called. The ability to manipulate `MPI_INFO` objects before initialization is being proposed as part of Sessions (#103), but the ability to construct such an object is not part of that proposal.

# Proposal

This proposes a new function called `MPI_INFO_ENV_CREATE_ARGV` which would allow the user to pass in the `argc` and `argv` parameters and receive an `MPI_INFO_ENV`-like object back, which could be used for all of the same functionality as `MPI_INFO_ENV`.

# Changes to the Text

The new function `MPI_INFO_ENV_CREATE_ARV` is added and described.

# Impact on Implementations

Implementations will need to implement the new function, which should hopefully be the same code as is currently used in `MPI_INIT`. It's possible that if the implementation relies on the input parameters to `MPI_INIT` for `argc` and `argv` and doesn't currently have another way of getting those values, the output info object here might not be the same as `MPI_INFO_ENV`.

# Impact on Users

Users not using this function will not be impacted. Users who want to use this function for the purposes mentioned above will be able to access the `MPI_INFO_ENV`-like object before initialization.

# References

The pull request is available at https://github.com/mpi-forum/mpi-standard/pull/126

**Comment by wesbland** [comment]
PDF including no-no changes made on 2019-09-06: [mpi40-report-get_info_env.pdf](https://github.com/mpi-forum/mpi-issues/files/3584613/mpi40-report-get_info_env.pdf)

**Comment by wesbland** [comment]
PDF including no-no changes for 2019-09-07: [mpi40-report-get_info_env.pdf](https://github.com/mpi-forum/mpi-issues/files/3585604/mpi40-report-get_info_env.pdf)

**Comment by ahori** [comment]
I wonder why you did not mention that this routine can be called before calling MPI_INIT.  Isn't this the point of this routine?

**Comment by wesbland** [comment]
That's a good point. I'll fix that before the reading.

**Comment by wesbland** [comment]
This is the [PDF](https://github.com/mpi-forum/mpi-issues/files/3940248/mpi40-report-issue143.pdf) to be read at the December 2019 meeting.

**Comment by wesbland** [comment]
This commit, https://github.com/mpi-forum/mpi-standard/pull/126/commits/67b597098d3880d4fc282badcae0d051be5af72a, will be read as a no-no item at the December 2019 meeting.

**Comment by wesbland** [comment]
This passed the no-no vote in Albuquerque, New Mexico on 2019-12-12.

**Comment by wesbland** [comment]
This proposal passed a first vote at the February 2020 meeting:

Yes - 23
No - 0
Abstain - 1

**Comment by wesbland** [comment]
This passed a second vote on 2020-06-30.

https://www.mpi-forum.org/meetings/2020/06/votes
