### ISSUE TITLE
Proposed Rule Changes to Allow No-No-Votes at Same Meeting

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#145]
This issue refers to the procedure document and allows the use of No-No-Votes for any item officially brought up at a meeting without the 14 days notice. The PR is

https://github.com/mpi-forum/procedures/pull/4

The proposed PDF is here:

[procedures.pdf](https://github.com/mpi-forum/mpi-issues/files/3526357/procedures.pdf)

**Comment by wesbland** [comment]
This passed the vote and went into effect on 2019-09-07

@schulzm - Do you merge this?
