### ISSUE TITLE
Deprecate MPI_Info_get and MPI_Info_get_valuelen

### ISSUE THREAD

**Issue by regrant** [mpi-forum/mpi-issues#147]
# Problem

MPI_Info_get has a security issue in C. This ticket deprecates the MPI_Info_get and related MPI_Info_get_valuelen functions in favor of new replacements in tickets #133 or #146 

# Proposal

The C versions of these functions should be deprecated. Users should be made aware that they should shift to using the replacement decided upon by the forum.

**Note: This ticket will be withdrawn from voting if both #133 and #146 fail to pass in the forum**

# Changes to the Text

Move MPI_Info_get and MPI_Info_get_valuelen to the deprecation section

# Impact on Implementations

Implementations will have to mark these functions as deprecated.

# Impact on Users

Users will receive warnings to update their code to use the new safe string handling functions in C.

# References

Pull Request - https://github.com/mpi-forum/mpi-standard/pull/131

Table update: [terms-2_safe_info.pdf](https://github.com/mpi-forum/mpi-issues/files/3951842/terms-2_safe_info.pdf)
[deprecated.pdf](https://github.com/mpi-forum/mpi-issues/files/3951873/deprecated.pdf)

**Comment by wesbland** [comment]
This passed the no-no and first vote in Albuquerque, New Mexico on 2019-12-12.

**Comment by wesbland** [comment]
This proposal passed a no-no vote at the February 2020 meeting:

Yes - 23
No - 0
Abstain - 1

**Comment by wesbland** [comment]
This proposal passed a second and final vote at the February 2020 meeting:

Yes - 23
No - 1
Abstain - 0
