### ISSUE TITLE
Changes to MPI_T Events if info objects were available before MPI initialization 

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#148]
in the advent of the sessions proposal that will also allow info objects outside the init-finalize scope, I'd like to announce another reading of a PR with small changes that deal with text changes to the MPI_T events PR that deal with handling of info objects for the new MPI_T calls.

The PR: https://github.com/mpi-forum/mpi-standard/pull/274

**Comment by wesbland** [comment]
This passed an errata vote on 2020-09-28.

https://www.mpi-forum.org/meetings/2020/09/votes
