### ISSUE TITLE
Update text and references to backward incompatibilities

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#151]
# Problem

Not all backward incompatibilities are listed in the corresponding chapter.

# Proposal

- List all incompatibilities introduced so far
- Update ChangeLog with a standard warning about a new incompatibility

# Changes to the Text

See PR

# Impact on Implementations

None

# Impact on Users

Readers of the standard will better notice backward incompatible changes.

# References

Deprecated previous PR: mpi-forum/mpi-standard/pull/137

**Comment by wesbland** [comment]
I think this issue was resolved elsewhere. @mahermanns - Can you reopen this and correct me if I'm wrong? I see this in the `mpi-4.x` branch today.
