### ISSUE TITLE
Make error code functions thread-safe

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#152]
# Problem

When adding functions that return error codes to the list of functions callable before initialization, the accompanying functions to query those error codes should have also added to the list of always thread-safe functions.

# Proposal

Add `MPI_ERROR_CLASS` and `MPI_ERROR_STRING` to the list of always thread-safe functions.

# Changes to the Text

Change this text in the external interfaces chapter:

> Regardless of whether or not the MPI implementation is thread compliant, MPI_INITIALIZED,
MPI_FINALIZED, MPI_QUERY_THREAD, MPI_IS_THREAD_MAIN, MPI_GET_VERSION and MPI_GET_LIBRARY_VERSION must always be thread-safe.

to say this:

> Regardless of whether or not the MPI implementation is thread compliant, MPI_INITIALIZED,
MPI_FINALIZED, MPI_ERROR_CLASS, MPI_ERROR_STRING, MPI_QUERY_THREAD, MPI_IS_THREAD_MAIN, MPI_GET_VERSION and MPI_GET_LIBRARY_VERSION must always be thread-safe.

# Impact on Implementations

It's unlikely that these functions will have been implemented in a way that they would not be thread safe (perhaps for user-created error classes), but if so, the implementations will need to adjust.

# Impact on Users

None

# References

https://github.com/mpi-forum/mpi-standard/pull/141

**Comment by wesbland** [comment]
[PDF](https://github.com/mpi-forum/mpi-issues/files/3940379/mpi32-report-issue152.pdf) of the errata item being read.

**Comment by wesbland** [comment]
This passed the errata vote in Albuquerque, New Mexico on 2019-12-12.

**Comment by abouteiller** [comment]
pr https://github.com/mpi-forum/mpi-standard/pull/141 merged to mpi3.x and mpi4.x. We are done here. 

(mention from @jsquyres appears to  be unintentional)
