### ISSUE TITLE
A new split_type value for MPI_Comm_split_type: MPI_COMM_TYPE_HW_SUBDOMAIN (Unguided mode) 

### ISSUE THREAD

**Issue by GuillaumeMercier** [mpi-forum/mpi-issues#156]
This issue is a complement to issue #132 and provides the behaviour for the **unguided** mode 
when no info key is provided when using the proposed new split value `MPI_COMM_TYPE_HW_SUBDOMAIN`.

Originally, this was part of issue #132 but after the meeting in Zürich, it was decided to split (no pun
intended) this into two different issues.

**Comment by GuillaumeMercier** [comment]
PR is here: https://github.com/mpi-forum/mpi-standard/pull/148

**Comment by GuillaumeMercier** [comment]
The current text of the proposal is here:  [mpi40-report-hw-topo-issue-156-2019-11-04.pdf](https://github.com/mpi-forum/mpi-issues/files/3806288/mpi40-report-hw-topo-issue-156-2019-11-04.pdf)

Main changes are on pages **268 to 271**.

**Comment by GuillaumeMercier** [comment]
Current text of the proposal:  [mpi40-report-hw-topo-issue-156-2019-11-20.pdf](https://github.com/mpi-forum/mpi-issues/files/3871660/mpi40-report-hw-topo-issue-156-2019-11-20.pdf)

Main changes located on pages  **268 to 270**.

**Comment by GuillaumeMercier** [comment]
Proposal with the minor fix in the example (wrong variable name): [mpi40-report-hw-topo-issue-156-2019-11-26.pdf](https://github.com/mpi-forum/mpi-issues/files/3894472/mpi40-report-hw-topo-issue-156-2019-11-26.pdf)

**Comment by GuillaumeMercier** [comment]
New version after MPI Forum feedback:  [mpi40-report-hw-topo-issue-156-2019-12-11_v2.pdf](https://github.com/mpi-forum/mpi-issues/files/3952929/mpi40-report-hw-topo-issue-156-2019-12-11_v2.pdf)

Main changes located on pages **267 to 270**

**Comment by wesbland** [comment]
This passed the no-no vote in Albuquerque, New Mexico on 2019-12-12.

**Comment by wesbland** [comment]
This proposal passed a first vote at the February 2020 meeting:

Yes - 20
No - 2
Abstain - 2

**Comment by wesbland** [comment]
This passed a second vote on 2020-06-30.

https://www.mpi-forum.org/meetings/2020/06/votes
