### ISSUE TITLE
Pythonization of LaTeX bindings

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#158]
# Problem

The MPI API bindings are currently hard-coded five times in the LaTeX for the MPI standard:

1. Language independent specification (LIS)
1. C
1. C++ (yes, these are still in the LaTeX ⚠️) 
1. Fortran 90
1. Fortran 08

We propose to convert this 5x-hard-coding into a single specification of each API in Python, and then automatically render each of the 4 desired bindings in LaTeX (i.e., it's no longer necessary to render the C++ bindings).

# Proposal

As stated above, convert all hard-coded LaTeX MPI API bindings to a block of Python in the `.tex` files that are then rendered to LaTeX during `make`.

[We have a wiki setup for Chapter Authors](https://github.com/mpiwg-large-count/large-count-issues/wiki/pythonizing), including:

1. [Rationale / benefits of this scheme](https://github.com/mpiwg-large-count/large-count-issues/wiki/pythonizing-why)
1. [Help for those who do not know Python](https://github.com/mpiwg-large-count/large-count-issues/wiki/pythonizing-dont-know-python)

This scheme was detailed in:

* The 9 Dec 2019 MPI Forum Physical meeting. [See the slides](https://docs.google.com/presentation/d/1QZyh6TbjDMu7mEcNqBFfe9fFOltaCtxgZ2ZODzdtDpI/edit)
* The 13 Nov 2019 MPI Forum Virtual meeting.  [See the slides](https://docs.google.com/presentation/d/1dcyTuX4My-M9lwL9g2zEqAKuFQuL3dulCfN44YngLgM/edit).

Note that while this effort is related to [the Embiggenment](https://github.com/mpi-forum/mpi-issues/issues/137) (a.k.a. "Large Count"), it is a separate effort.  Meaning:

1. This effort will create a more-or-less comparible LaTeX to MPI-3.1
    * [See the slides](https://docs.google.com/presentation/d/1dcyTuX4My-M9lwL9g2zEqAKuFQuL3dulCfN44YngLgM/edit) for a list of differences compared to MPI-3.1
1. Embiggenment depends on this Pythonization.  I.e., Embiggenment will likely tweak the Python rendering engine to _also_ generate new interfaces for "large count" parameters.

# Changes to the Text

This touches nearly every chapter in the MPI specification document.  Here's an example of one change -- for MPI_Send.

From this (note the extremely-long lines -- scroll to the right):

```
\begin{funcdef}{MPI\_SEND(buf, count, datatype, dest, tag, comm)}
\funcarg{\IN}{buf}{initial address of send buffer (choice)}
\funcarg{\IN}{count}{number of elements in send buffer (non-negative integer)}
\funcarg{\IN}{datatype}{datatype of each send buffer element (handle)}
\funcarg{\IN}{dest}{rank of destination (integer)}
\funcarg{\IN}{tag}{message tag (integer)}
\funcarg{\IN}{comm}{communicator (handle)}
\end{funcdef}

\cdeclmainindex{MPI\_Comm}%
\mpibind{MPI\_Send(const~void*~buf, int~count, MPI\_Datatype~datatype, int~dest, int~tag, MPI\_Comm~comm)}

\mpifnewbind{MPI\_Send(buf, count, datatype, dest, tag, comm, ierror) \fargs TYPE(*), DIMENSION(..), INTENT(IN) :: buf \\ INTEGER, INTENT(IN) :: count, dest, tag \\ TYPE(MPI\_Datatype), INTENT(IN) :: datatype \\ TYPE(MPI\_Comm), INTENT(IN) :: comm \\ INTEGER, OPTIONAL, INTENT(OUT) :: ierror}
\mpifbind{MPI\_SEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, IERROR)\fargs <type> BUF(*) \\ INTEGER  COUNT, DATATYPE, DEST, TAG, COMM, IERROR}
\mpicppemptybind{MPI::Comm::Send(const void*~buf, int~count, const MPI::Datatype\&~datatype, int~dest, int~tag) const}{void}
```

To this:

```
\cdeclmainindex{MPI\_Comm}
\begin{mpi-binding}
    function_name('MPI_Send')

    parameter('buf', 'BUFFER', desc='initial address of send buffer', constant=True)
    parameter('count', 'POLYXFER_NUM_ELEM', desc='number of elements in send buffer')
    parameter('datatype', 'DATATYPE', desc='datatype of each send buffer element')
    parameter('dest', 'RANK', desc='rank of destination')
    parameter('tag', 'TAG', desc='message tag')
    parameter('comm', 'COMMUNICATOR')
\end{mpi-binding}
```

# Impact on Implementations

None.

# Impact on Users

None.

# References

* Corresponding PR: https://github.com/mpi-forum/mpi-standard/pull/152
* [Wiki for Chapter Authors](https://github.com/mpiwg-large-count/large-count-issues/wiki/pythonizing) -- describing how this will affect them, examples to show how to Pythonize, etc.
* [Slides from 13 Nov 2019 MPI Forum Virtual meeting](https://docs.google.com/presentation/d/1dcyTuX4My-M9lwL9g2zEqAKuFQuL3dulCfN44YngLgM/edit)
* [MPI Forum issue for The Embiggenment](https://github.com/mpi-forum/mpi-issues/issues/137)
* [Pull Request for the Pythonization effort](https://github.com/mpiwg-large-count/mpi-standard/pull/2) -- on the Large Count WG repo

**Comment by jsquyres** [comment]
Here is a copy of the "cleandoc" PDF as of 2019-11-26.  The Pythonization is not yet complete, and we have not yet verified all the converted bindings.  But it gives a good example of what the Pythonization process is doing.

[mpi-report-pythonization-as-of-2019-11-26.pdf](https://github.com/mpi-forum/mpi-issues/files/3892031/mpi-report-pythonization-as-of-2019-11-26.pdf)

Most notably, the following chapters are not yet complete:

* Chapter 5: collectives
* Chapter 7: process topologies (partially completed)
* Chapter 11: one sided
* Chapter 13: io

**Comment by omor1** [comment]
An interesting note is that this could allow MPI to relatively simply adopt future bindings if necessary by simply adding them as additional backends. Obviously not something to be looked at in this juncture, but some food for thought.

**Comment by jsquyres** [comment]
> An interesting note is that this could allow MPI to relatively simply adopt future bindings if necessary by simply adding them as additional backends. 

That is definitely in the plan for the future.  😄

**Comment by jsquyres** [comment]
Here is a copy of the "cleandoc" PDF from the Pythonization PR as of 2019-12-09. It is all but complete; it needs review by chapter committees.

[mpi-report-pythonized-2019-12-09.pdf](https://github.com/mpi-forum/mpi-issues/files/3941742/mpi-report-pythonized-2019-12-09.pdf)

**Comment by jsquyres** [comment]
Here is a copy of the "cleandoc" PDF from the Pythonization PR as of 2020-02-03 for reading at the Feb 2020 Portland MPI Forum meeting.

https://aws.open-mpi.org/~jsquyres/forum-unofficial/mpi-report-2020-02-03-f876294-pythonized-NOT-embiggened.pdf

**Comment by jjhursey** [comment]
A ticket0 suggestion. Can we change `F` to `Fortran` and `F08` to `Fortran 2008` in the header to the Fortran bindings?

Rationale:
 * There is an `F` programming language [link](https://en.wikipedia.org/wiki/F_(programming_language)) which is related to Fortan, but distinct from it (from what I can tell).
 * We should be as precise as practical about the programming language to which the binding applies.

**Comment by jsquyres** [comment]
Done -- new (trivial) commit is now on this PR.  I will present at the 2020-02 Portland Forum meeting.

New PDF: https://aws.open-mpi.org/~jsquyres/forum-unofficial/mpi-report-2020-02-19-bd48215-pythonized-NOT-emibggened.pdf

**Comment by wesbland** [comment]
This proposal passed the first and only vote at the February 2020 meeting:

Yes - 24
No - 0
Abstain - 0

**Comment by martinruefenacht** [comment]
Newest PDF: 
[mpi40-report.pdf](https://github.com/mpi-forum/mpi-issues/files/4453259/mpi40-report.pdf)

This fixes:
- None return in F08 generator for VARARG kinds
- Escaping spaces for uniform spacing behaviour
- Line breaking within LIS parameter names
- Autogenerates "For this routine, an interface within the mpi_f08 module was never defined." for bindings which require this proxy rendering of F08 bindings.

Not yet fixed, because they are Latex changes (Bill):
- Indentation of line breaking F08 descriptors to ensure typing clarity
- "Fortran 2008 Binding" for proxy rendered (above)
    - Need to modify "mpifnewnonebind" latex macro
