### ISSUE TITLE
ERRATA: Clarify behavior for invalid MPI_T binding arguments

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#160]
# Problem

The Section 14.3.2 discussing binding of MPI_T variables currently does not state expected behavior when an invalid object handle is passed as binding argument.

# Proposal

Explicitly state that passing invalid handles as binding arguments is erroneous.

# Changes to the Text

Add explicit clarification that invalid handles are erroneous. Also add Advice to Users reminding the user that `MPI_COMM_WORLD` and `MPI_COMM_SELF` are invalid outside the INIT/FINALIZE scope.

# Impact on Implementations

Behavior and potential implementation clarified.

# Impact on Users

Expected arguments and potential behavior of implementation clarified.

# References

PR: mpi-forum/mpi-standard/pull/161

**Comment by wesbland** [comment]
@mahermanns I think this might have been accidentally closed when mpi-forum/mpi-standard#269 was merged last week. This is still in progress, right? Should it be reopened?

**Comment by mahermanns** [comment]
@wesbland Yes, this issue needs further discussion, which we pushed to 4.1.

**Comment by mahermanns** [comment]
Tools WG Dec 2, 2021: Propose text to allow any predefined handle to be passed as a binding argument at any time in the program execution.

**Comment by mahermanns** [comment]
Tools WG Discussion 2022-11-03: With the difficulties showing up on the current PR regarding link-time vs. compile-time constants, the working group decided to propose to only allow binding to valid handles while MPI is in an initialized state. This would actually be more consistent with the handling of non-predefined handles, and might make implementation for MPI libraries and tools simpler.

**Comment by wesbland** [comment]
This passed an [errata vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 29
	<td> 0
	<td> 4
</table>
