### ISSUE TITLE
Consistent use: Throughout - Data Representations Formatting

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#161]
## Problem

What is the formatting for the data-representations, such as "external32" and "native"?  Does it include the double quotes?  What is the font?  Are these all indexed (they could be \const values)? Not all uses include the double quotes.

### Suggested Fix

Use \const{"external32"}

**Comment by wesbland** [comment]
5 votes for editor change
2 votes for chapter committee

Given that this touches the entire document, I think the document editor should own this change and consult with the relevant committees if necessary.

**Comment by wgropp** [comment]
I believe this has been handled; these names are now expressed using `\mpistring`
