### ISSUE TITLE
Consistent use: Throughout - Replace \const with More Specific Macros

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#165]
## Problem

Throughout, \const is often used where \error, \errormain, and related macros should be used (to properly index the terms).

### Suggested Fix

Edit to update

**Comment by wesbland** [comment]
I'm still erring on the side of having the document editor make such consistency decisions that impact every chapter and then have the relevant committees make the changes (if necessary).

Votes
Editor Change - 4
Chapter Committee - 3

**Comment by wgropp** [comment]
The document is improved but still needs more work
