### ISSUE TITLE
Editing: Section 16.1.3, Table 16.2 - p. 634 - Fix Caption

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#166]
## Problem

The replacements here are not datatypes. This caption is incorrect.

### Suggested Fix

Change the caption to "Removed MPI-1 datatypes. The indicated routine may be used for changing the lower and upper bound respectively."

**Comment by wesbland** [comment]
Votes
- Editor change - 2
- Committee change - 3
- Errata - 2

Let's discuss this in the VM.

**Comment by wgropp** [comment]
Fixed in editorchanges (along with correcting the placement of the captions).
