### ISSUE TITLE
Error: Section 3.3.2 - p. 38 - Replace C process

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#167]
## Problem

"sent by a C or C++ process - I don't know what a "C process" is and I think that the natural interpretation (main written in C) isn't even correct - since it really refers to the language binding used for the specific call that sends the message, e.g., in a program with a C main program but one that calls a library, written in Fortran, that makes MPI calls.

### Suggested Fix

Change "sent by a C of C++ process" to be specific - "sent from a routine using the MPI C language interface" Same for the "Fortran process" in that same sentence.

### References

The PR that implements this change is https://github.com/mpi-forum/mpi-standard/pull/201.

**Comment by wesbland** [comment]
I think this is similar to some of the work already being done in the point-to-point WG. @dholmes-epcc-ed-ac-uk, did you guys already address this?

**Comment by wesbland** [comment]
Voting
* Editor change - 1
* Chapter committee - 4
* Errata - 2

**Comment by dholmes-epcc-ed-ac-uk** [comment]
> I think this is similar to some of the work already being done in the point-to-point WG. @dholmes-epcc-ed-ac-uk, did you guys already address this?

The closest thing is the stalled effort by the Hybrid WG (now unofficially disbanded) that attempted to replace *every* unqualified usage of the "process" with something better, e.g. "MPI process".

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Here is a PDF with change-bars for this change:
[mpi-report-ticket167-2020-APR-22-changebars.pdf](https://github.com/mpi-forum/mpi-issues/files/4515483/mpi-report-ticket167-2020-APR-22-changebars.pdf)

Here is a PDF without change-bars for this change:
[mpi-report-ticket167-2020-APR-22-cleandoc.pdf](https://github.com/mpi-forum/mpi-issues/files/4515487/mpi-report-ticket167-2020-APR-22-cleandoc.pdf)

**Comment by wesbland** [comment]
This passed a "no no" vote on 2020-06-30.
