### ISSUE TITLE
Error: Section 13.7 - p. 584 - Error Handler Inheritance

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#170]
## Problem

This says that error handlers are inherited from MPI_COMM_WORLD.  Didn't this change to MPI_COMM_SELF (see 8.3)? Also see the rationale on the same page.

### Suggested Fix

Change MPI_COMM_WORLD to MPI_COMM_SELF for these references

**Comment by wesbland** [comment]
This one is voted overwhelmingly as an errata:

* Errata - 5
* Chapter committee - 2

**Comment by wesbland** [comment]
I believe the existing text there is mostly correct. Error handler inheritance didn't change. What did change was that we now specify that errors that don't come from communication attached to a comm/win/file use `MPI_COMM_SELF`. Also, the predefined info key / command-line argument `mpi_initial_errhandler` determines the initial value of the error handler for `MPI_COMM_WORLD`, `MPI_COMM_SELF`, and the spawn communicator.

We _could_ add more text to this rationale to describe all this, but I'm not sure that's necessary for the information being conveyed here, which is that error handlers in I/O come from `MPI_FILE_NULL`.

I'm going to go ahead and close this unless @wgropp disagrees or @abouteiller says I said something wrong.

**Comment by wgropp** [comment]
I agree, in looking at this, the text is correct but now a bit confusing, since the phrasing in the rationale made more sense when COMM_WORLD provided the default error handler. I'm ok with this being closed.
