### ISSUE TITLE
Error in text: Section 4.1.1 - p. 87 - INTEGER*8 Extension

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#171]
## Problem

INTEGER*8 is not a Fortran type.  It is a common extension; this should be acknowledged.

### Suggested Fix

Add a footnote after "these arguments" with text "This assumes that the Fortran 77 system accepts the common extension of "INTEGER*8" for 8 byte integers."

**Comment by wesbland** [comment]
The voting on this one is a bit all over the place:

* Editor - 2
* Chapter committee - 3
* Errata - 1
* Full proposal - 1

**Comment by RolfRabenseifner** [comment]
I do not find the pull request on this page.

If this ticket is the ticket About last line of MPI-3.1 Section 4.1.1, then this is related to MPI-3.1 17.1.6 F77

**Comment by abouteiller** [comment]
> I do not find the pull request on this page.

https://github.com/mpi-forum/mpi-standard/pull/196

There was a discussion about foregoing this change, and instead push-back the issue to a future deprecation/removal of F77 support altogether. @jsquyres please clarify this position in writing so that George can react.

**Comment by wesbland** [comment]
This passed an errata vote on 2020-07-01.

https://www.mpi-forum.org/meetings/2020/06/votes
