### ISSUE TITLE
No Change: Section 18.1.20 - p. 681 - Move Examples

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#175]
## Problem

Why are examples 18.5ff at the end of the chapter?

### Suggested Fix

Editor to figure this out

**Comment by wesbland** [comment]
This is split between the editor and chapter committee. I err on the side of the editor and bring in the committee if necessary.
* Editor - 3
* Chapter committee - 4

**Comment by wgropp** [comment]
This was fixed as a side effect of using the listing environment - these examples were improperly placed within a LaTeX table, which caused them to be "floated" to the end of the section.
