### ISSUE TITLE
Omission: p. 690 - MPI_STATUS_F2F08 Binding Fix

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#180]
## Problem

MPI_STATUS_F2F08 and MPI_STATUS_F082F need the types for the arguments, e.g., (Status) or something like that.

### Suggested Fix

Suggest asking the bindings committee to review

**Comment by wesbland** [comment]
This one is probably an errata:
* Chapter committee - 4
* Errata - 3

The committee may be the one to author the change, but it probably needs to go to the forum for confirmation.

**Comment by jsquyres** [comment]
This will require a Python change.

Please contact @martinruefenacht and @jsquyres.

**Comment by puribangalore** [comment]
I see that this defined on Page 833 and 834 in the RC pdf file. If this is what was needed, should this issue be closed?

**Comment by RolfRabenseifner** [comment]
From my perspective, all is clear. If you look for example for MPI_STATUS_F2F08 in whole standard without open questions.
The one errata on page 1031 is new and clearly reflected on all related locations.

**Comment by martinruefenacht** [comment]
In the latest RC version this seems to have migrated to pg 839/840.

I assume the intention was to have the LIS type shown? Other than that I can't find a difference to other interfaces.

I will prepare a PR for that so that it can be merged if that is the problem.

**Comment by martinruefenacht** [comment]
Since this got merged I will close this issue.
