### ISSUE TITLE
Oversight: Section 8.7 - p. 383 - Escape Spaces in Arguments

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#181]
## Problem

for the argv info key, "argv  Space separated arguments to command".  What if the arguments contain spaces? Is there an escape for spaces? Is this case just not handled?

### Suggested Fix

Suggest adding "If an argument contains a space, there is no way to tell from the value of the argv info key whether a space is part of the argument or is separating different arguments."

**Comment by wesbland** [comment]
The voting here had at least a few people saying it's more than an editor change:
* Chapter committee - 4
* Errata - 2
* Full proposal - 1

I think this is probably an errata at least to have the sort of fixed proposed in the description above. If we wanted to do something more extensive, that'd be a full proposal.

**Comment by wesbland** [comment]
This is probably an advice to users.

**Comment by bosilca** [comment]
Fix in [172](https://github.com/mpi-forum/mpi-standard/pull/172)

**Comment by wesbland** [comment]
This passed a "no no" vote on 2020-06-30.

https://www.mpi-forum.org/meetings/2020/06/votes

**Comment by wesbland** [comment]
This passed an errata vote on 2020-07-01.

https://www.mpi-forum.org/meetings/2020/06/votes
