### ISSUE TITLE
Question: Section 5.12.4 - p. 206 - MPI_ISCATTERV sendcounts and displs Consistency

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#182]
## Problem

MPI_ISCATTERV. Are the descriptions of sendcounts and displs consistent with other expressions.

**Comment by jaegerj** [comment]
I can look into this.

**Comment by wesbland** [comment]
@jaegerj Once you have an idea of whether this is an errata or a full proposal, please label the issue accordingly.

**Comment by jaegerj** [comment]
Compared to MPI_GatherV, MPI_Scatterv and MPI_Iscatterv don't always specify when arguments are "significant only at root".

Note: MPI_Gather is not consistant on how it specifies that an argument is "significant only at root" when the type is already present in parentheses.
For the recvbuf argument: (choice, significant only at root)
For the recvtype argument: (significan only at root) (handle)

**Comment by jaegerj** [comment]
Annotated MPI 4.0 pdf with red changebars.
Changes are listed on first page.
[mpi40-report_issue_182.pdf](https://github.com/mpi-forum/mpi-issues/files/4657687/mpi40-report_issue_182.pdf)

**Comment by wesbland** [comment]
This passed an errata vote on 2020-07-01.

https://www.mpi-forum.org/meetings/2020/06/votes
