### ISSUE TITLE
Update: Section 1.13 - p. 8 - JOD is History

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#184]
## Problem

At the end of that section, there is text on the JOD.  This is now even more out-of-date.  It also doesn't mention any other documents, such as the MPIR docs. It should note that the JOD hasn't been updated since MPI-2.0.

### Suggested Fix

Edit to update that the JOD dates from MPI-2 and that this material is mentioned mostly as historical background on the development of the standard

**Comment by wesbland** [comment]
Votes:

* Editor - 1
* Chapter committee - 4
* Errata - 2

Let's discuss this in the virtual meeting.

**Comment by wesbland** [comment]
This probably goes along with #183 and should be fixed at the same time.

**Comment by wgropp** [comment]
Addressed in PR 681
