### ISSUE TITLE
Update: Section 1.13 - p. 8 - Link to Index Pages

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#185]
## Problem

Re-write the last item that starts "Several Index pages..." to be specific about the indices, and to provide links as in the other items in this list.

### Suggested Fix

Edit to update

**Comment by wesbland** [comment]
Almost everyone thinks this is a chapter committee change (I agree):

* Editor change - 1
* Chapter committee - 5
* Full proposal - 1

**Comment by wgropp** [comment]
Fixed already
