### ISSUE TITLE
Update: Section 3.2.4 - p. 31 - Remove Parenthesis

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#186]
## Problem

The (However, it is unsafe...) does not need the parenthesis.

### Suggested Fix

Remove the parenthesis

**Comment by wesbland** [comment]
Everyone voted this as an editor change.

**Comment by naughtont3** [comment]
I saw similar case in sect 11.5.5, pg. 503 "...in the code. (However, ready-send is matched...)".
