### ISSUE TITLE
Update: Section 3.3.2 - p. 38 - Index XDR

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#187]
## Problem

Index XDR

### Suggested Fix

Edit to update

### References

The PR that implements this change is https://github.com/mpi-forum/mpi-standard/pull/202.

**Comment by wesbland** [comment]
Everyone voted this either as chapter committee or editor:

* Editor - 5
* Chapter committee - 2

I'll assign this to both @wgropp and @dholmes-epcc-ed-ac-uk and either can do it pretty quickly.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
The PDF showing this change is here:
[mpi-report-ticket187-2020-APR-22.pdf](https://github.com/mpi-forum/mpi-issues/files/4515713/mpi-report-ticket187-2020-APR-22.pdf)
