### ISSUE TITLE
make MPI_THREAD_MULTIPLE a requirement for all implementations

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#19]
This was https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/371.
# Background

Bill brought this up in the context of various thread-safety and progress discussions this week.  I am not suggesting he proposed this change, merely that he proposed it hypothetically as a solution to both the generalized request progress issue and the contradictory assumptions of "threads exist" and "threads may not exist" among the Forum, which is reflected both in what is in the standard and what is not in the standard.
# Proposed Changes

The text changes in 12.4.3 would be trivial (merely removing the word "thread" from line 25 of page 486 effects this change) but the implications are profound and the impact on implementations substantial.

If the MPI standard assumes threads always exist, this eliminates the need for a number of nonblocking operations that aren't performance critical but merely need to be asynchronous for correctness reasons (e.g. `MPI_Icomm_dup`).

There are two possible ways that `MPI_THREAD_MULTIPLE` be required.  First, we could merely require that all implementations support it (many, but not all implementations currently do).  This would mean that users that require some form of asynchrony (e.g. in generalized requests) would be forced to use `MPI_THREAD_MULTIPLE` instead of a lower level of thread support, at the cost of performance due to locking overhead.  Second, we could require `MPI_THREAD_MULTIPLE` AND deprecate all other levels of thread support, thereby forcing all implementations to implement `MPI_THREAD_MULTIPLE` all of the time.  The ticket author does not favor the latter but it has emerged as one possible solution to a number of issues related to threads in MPI.

**Comment by jeffhammond** [comment]
@wgropp said:

One alternative would be to make explicit that some operations either require a user-level thread (e.g., most uses of generalized requests) and hence MPI_THREAD_MULTIPLE or some sort of active agent at the target (passive target RMA operations, expectations of communication/computation overlap for nonblocking collectives), which in many cases (though not all) may require the implementation to use multiple threads, thus effectively making those implementations support something close to MPI_THREAD_MULTIPLE (including much of the real overhead). Note that locking is not required by MPI, though the broad use of locks is a strategy that some implementations have chosen to provide support for MPI_THREAD_MULTIPLE.

Making the dependencies more explicit is what I believe we need to do as a minimum. In addition, we should consider whether threads will be common and efficient in 5 or more years; if so, we should spend little time catering to the other thread modes. If not, we should be very careful about requiring behavior that is hard to achieve without the use of multiple threads at least in the implementation.

**Comment by pavanbalaji** [comment]
I'm not in favor of this proposal.  The issue with nonblocking operations is not that threads might not exist on systems or that they might not be efficient, but rather that you need one thread per operation if you did not have nonblocking variants.

**Comment by pavanbalaji** [comment]
I should have said, "I don't agree with the comment from Bill", rather than "I'm not in favor of this proposal", since the comment is not directly related to the proposal.

**Comment by ftillier** [comment]
Do we have a list somewhere of the various MPI implementations and their support for MPI_THREAD_MULTIPLE?  Requiring all future MPI implementations to be thread-safe would be a conceptually simple way of addressing some of the issues with generalized requests (rather than specifying that certain functions are always threadsafe, i.e. MPI_Grequest_complete).

**Comment by jeffhammond** [comment]
All the MPICH derivatives I have used support MTM just fine (except for the
occasional bug, obviously).

OpenMPI lacks reliable support for MTM.

Don't know about the rest. I can ask SGI though.

On Tuesday, November 10, 2015, ftillier <notifications@github.com> wrote:

> Do we have a list somewhere of the various MPI implementations and their
> support for MPI_THREAD_MULTIPLE? Requiring all future MPI implementations
> to be thread-safe would be a conceptually simple way of addressing some of
> the issues with generalized requests (rather than specifying that certain
> functions are always threadsafe, i.e. MPI_Grequest_complete).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpi-forum/mpi-issues/issues/19#issuecomment-155547641>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by schulzm** [comment]
At the June 2018 meeting in Austin the forum decided to table this - single threaded implementations should still be valid

**Comment by SamTWhite** [comment]
Adaptive MPI does not currently support MPI_THREAD_MULTIPLE. As an alternative, it supports threading inside its runtime in a rank-as-thread model, akin to the endpoints proposal.

**Comment by hjelmn** [comment]
FWIW, there is no way to disable MPI_THREAD_MULTIPLE support in Open MPI anymore. I personally have no problem with requiring MPI_THREAD_MULTIPLE.

**Comment by pavanbalaji** [comment]
Most MPI implementations support thread multiple in the source, but it is common for vendors to build multiple versions of the library where one library is optimized for thread single and another for thread multiple.  So the builds would be different even though they come from the same source

**Comment by hritzdorf** [comment]
NEC MPI supports MPI_THREAD_SERIALIZED but doesn’t support MPI_THREAD_MULTIPLE.

Hubert

**Comment by hritzdorf** [comment]
I personally think that it is currently not appropriate to support it.
