### ISSUE TITLE
Update: Section 3.7.5 - p. 60 - Replace C-bias with LIS

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#190]
## Problem

The inline of MPI_WAIT(&array_of_request[i], ...) in the description of MPI_WAITANY should (a) be a display and (b) address the C-bias of this code. Similarly for TESTANY and WAITALL

### Suggested Fix

Edit to use language independent version and display mode.  An alternative is to write in C and/or Fortran, and make that clear.

### References

Fixed by PR https://github.com/mpi-forum/mpi-standard/pull/225

**Comment by wesbland** [comment]
This is overwhelmingly voted as chapter committee:
* Chapter committee - 6
* Errata - 1

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Here is a PDF with changebars:
[mpi-report-ticket190-2020-MAY-20-changebars.pdf](https://github.com/mpi-forum/mpi-issues/files/4657574/mpi-report-ticket190-2020-MAY-20-changebars.pdf)

Here is a PDF without:
[mpi-report-ticket190-2020-MAY-20-cleandoc.pdf](https://github.com/mpi-forum/mpi-issues/files/4657576/mpi-report-ticket190-2020-MAY-20-cleandoc.pdf)

**Comment by wesbland** [comment]
This passed a "no no" vote on 2020-06-30.

**Comment by wesbland** [comment]
This passed an errata vote on 2020-07-01.

https://www.mpi-forum.org/meetings/2020/06/votes
