### ISSUE TITLE
Update: Section 4.1.4 - p. 101 - Use LaTeX \code

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#191]
## Problem

r[i] should probably be \code{r[i]}, since it refers to code. Or should this be an mpicodeblock?  Ditto for cyclic()

### Suggested Fix

Edit to update, using code (since examples are in C)

**Comment by wesbland** [comment]
Unanimous editor change.

**Comment by wgropp** [comment]
Fixed in editorchanges
