### ISSUE TITLE
Update: Section 5.1 - p. 144 - Index Collective Semantics

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#192]
## Problem

Consider adding collective semantics to the index (semantics!collective communications)

### Suggested Fix

Edit to update

**Comment by wesbland** [comment]
Votes:
* Editor change - 4
* Chapter committee - 2
* Full proposal - 1

I think the full proposal person misunderstood the problem. I'll assign this one to the chapter committee.

**Comment by tonyskjellum** [comment]
This is implemented with 
PR: https://github.com/mpi-forum/mpi-standard/pull/242
PDF: 
[mpi40-report-ticket192-14jun20.pdf](https://github.com/mpi-forum/mpi-issues/files/4777280/mpi40-report-ticket192-14jun20.pdf)

**Comment by tonyskjellum** [comment]
We think this one is done.  @wesland, please confirm.
