### ISSUE TITLE
Update: Section 5.1 - p. 146 - Index Hidden Communicator

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#193]
## Problem

Index "hidden" communicator

### Suggested Fix

Edit to update (also page 237, 472)

**Comment by tonyskjellum** [comment]
This is implemented
PR: https://github.com/mpi-forum/mpi-standard/pull/243
PDF: [mpi40-report-ticket193-14jun20.pdf](https://github.com/mpi-forum/mpi-issues/files/4777310/mpi40-report-ticket193-14jun20.pdf)
