### ISSUE TITLE
Update: Section 5.12 - p. 199 - Index Progress

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#194]
## Problem

Section 5,12, progression rules.  index progress.

### Suggested Fix

Edit to update

**Comment by tonyskjellum** [comment]
This is implemented:
PR:   https://github.com/mpi-forum/mpi-standard/pull/245
PDF:  [mpi40-report-ticket194-15jun20.pdf](https://github.com/mpi-forum/mpi-issues/files/4780380/mpi40-report-ticket194-15jun20.pdf)
