### ISSUE TITLE
Update: Section 6.2.4 - p. 248 - Remove Host Process

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#196]
## Problem

Host process in the section on 6.2.4.  What is a host process? Probably need to remove that.  Also, remove or change the "machine dependant absolute address" as applied to MPI_COMM_WORLD.  See also 8.1.

### Suggested Fix

Chapter committee to update

**Comment by wesbland** [comment]
The voting here says this is probably a bit more than chapter committee:

* Chapter committee - 4
* Errata - 2
* Full Proposal - 1

Let's discuss this in the VM.

**Comment by GuillaumeMercier** [comment]
Proposed fix : remove last 3 sentences of the first paragraph on page 248.

**Comment by abouteiller** [comment]
I missed the original discussion but I don't see what's wrong with the removed text in pr #176. 

Assuming there are good reasons that escape me, I'd like to raise attention to the attribute on MPI_COMM_WORLD, MPI_HOST 

https://github.com/mpi-forum/mpi-standard/blob/mpi-4.x/chap-inquiry/inquiry.tex line 155 which discusses the same notion.

**Comment by abouteiller** [comment]
There is also a slightly different notion in MPI_INFO_ENV regarding the mpiexec parameter `-host` which contains the name of the machine that runs the MPI process.

**Comment by GuillaumeMercier** [comment]
The plan is to eventually deprecate this MPI_HOST thing. You can get the whole discussion in he recording that Wesley sent a couple days ago. Regarding this PR, the first move was to modify the text and after some discussion, we thought that removing it altogether was better.

**Comment by wesbland** [comment]
If you'd like to get the context @abouteiller, the relevant part of the discussion is here (timestamp included but it's 56:38 in case something goes wrong with the link):

https://youtu.be/P-GDEIpGlw4?t=3398

**Comment by RolfRabenseifner** [comment]
It seems that PR https://github.com/mpi-forum/mpi-standard/pull/176 has done nothing?
And that MPI-4.0 RC still has MPI_HOST as regular MPI constant.

And it seems that deprecation or removal of MPI_HOST was never officially voted and it is still open in Issue #57.
And there, it seems that the proposed PR https://github.com/mpi-forum/mpi-standard/pull/221 is not yet fully correct.
