### ISSUE TITLE
Update: Section 7.6.1 - p. 336 - Replace "ell" with k

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#198]
## Problem

Unnumbered example on page 336 uses "l" (ell) as a variable - this is hard to distinguish from "1" (one). Suggest using a different variable

### Suggested Fix

Suggest using k instead of l (ell), since previous loop uses k. Alternative is to use m and n for the two loops

### Pull request

PR 311 - https://github.com/mpi-forum/mpi-standard/pull/311

**Comment by wesbland** [comment]
This is clearly a editor / chapter committee change:

* Editor - 3
* Chapter committee - 4

I'm going to mark both @wgropp and @RolfRabenseifner and either can fix.

**Comment by RolfRabenseifner** [comment]
I agree, the most simplest fix is to change index "l" into "k", i.e., using only one index variable.
Bill, if you can do it with some minimum effort, then please just do it.
