### ISSUE TITLE
Update: Section 7.6.1 and 7.6.2 - p. 338 - Use LaTeX Math Mode

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#199]
## Problem

Process \mpicode{j} and $j$ are used in different paragraphs. One is in a math context and the other is a code context, but it is jarring.

### Suggested Fix

Since the "j" in "proocess j" is not in the code, use math mode for it in 7.6.1.

**Comment by wesbland** [comment]
Unanimously, this is an editor change.

**Comment by wgropp** [comment]
Fixed with PR 460
