### ISSUE TITLE
Update: Section 7.6.2 - p. 341 - Replace "ell" with k

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#200]
## Problem

Is recvcounts[l] (in sans-serif) recvcounts[ell] or recvcounts[one]? ell should not be used as an index (or most any other) variable. Similar problems in other sections (e.g., 7.6.1)

### Suggested Fix

Suggest using k instead of l (ell), since previous loop uses k. Alternative is to use m and n for the two loops.

### Pull request

PR 311 - https://github.com/mpi-forum/mpi-standard/pull/311

**Comment by wesbland** [comment]
This is another editor/committee change:

* Editor - 5
* Chapter committee - 2
* Errata - 
* Full Proposal - 

@wgropp and @RolfRabenseifner, this goes to you again.

**Comment by RolfRabenseifner** [comment]
I agree again, the most simplest fix is to change index "l" into "k", i.e., using only one index variable.
Bill, if you can do it with some minimum effort, then please just do it.
