### ISSUE TITLE
Update: Section 8.1.2 - p. 361 - Deprecate MPI_HOST

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#201]
## Problem

MPI_HOST - is this obsolete?  What exactly does this mean?  We should deprecate.

### Suggested Fix

Chapter committee to update

**Comment by wesbland** [comment]
This one is pretty clearly a full proposal according to the vote:

* Editor - 0
* Chapter committee - 3
* Errata - 1
* Full Proposal - 3

We'll discuss this in the virtual meeting.

**Comment by abouteiller** [comment]
Relates to issue #196

**Comment by wesbland** [comment]
Closing in favor of #57
