### ISSUE TITLE
Update: Section 8.2 - p. 365 - Index Cray Pointers

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#202]
## Problem

Index cray pointers.  Check whether gfortran (a) supports cray pointers and (b) needs -fcray-pointer (Note that 6.3.0 accepts that without complaint).

### Suggested Fix

Edit to update

**Comment by wesbland** [comment]
This is probably a chapter committee change:

* Editor - 2
* Chapter committee - 4
* Errata - 1
* Full Proposal - 0

I'm going to assign this to the chapter committee chaired by @bosilca.

**Comment by omor1** [comment]
The online documentation says that gfortran [supports Cray pointers](https://gcc.gnu.org/onlinedocs/gfortran/Cray-pointers.html). The man page says that the flag is indeed `-fcray-pointer`; it is unclear from the documentation whether this is required. Whether this support is maintained (i.e. everything works as stated in the documentation) should be confirmed.

**Comment by bosilca** [comment]
GNU fortran (at least up to 9.3) requires _-fcray-pointer_ to successfully compile and execute the following program:
```f90
program alloc_mem
  implicit none
  include 'mpif.h'

  REAL A
  POINTER (P, A(100,100))   ! no memory is allocated
  INTEGER(KIND=MPI_ADDRESS_KIND) SIZE
  integer mpierror

  CALL MPI_INIT(mpierror)
  SIZE = 4*100*100
  CALL MPI_ALLOC_MEM(SIZE, MPI_INFO_NULL, P, mpierror)
  ! memory is allocated

  A(3,5) = 2.71

  CALL MPI_FREE_MEM(A, mpierror) ! memory is freed
  CALL MPI_FINALIZE(mpierror)
end program alloc_mem
```
Therefore I don't think any modification in the chapter is necessary.

**Comment by wesbland** [comment]
If there's no objection from @wgropp, I'll go ahead and close this then.
