### ISSUE TITLE
Update: Section 8.4 - p. 374 - Alphabetize Error Classes

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#203]
## Problem

Why not alphabetize the error classes in table 8.1 and 8.2?

### Suggested Fix

Edit to update

**Comment by naughtont3** [comment]
@wgropp The tables 8.1/8.2 for Error classes have table has mixed use of `\const{}` and `\error{}` macros.  What is the difference in these two macros, and should anything be changed beyond the alpha-sort, i.e., is one version of macro preferred?  Thx

**Comment by wgropp** [comment]
Good catch. They should use \error, not \const.

**Comment by naughtont3** [comment]
@wgropp It appears the `MPI_T_ERR_` items (present in Appendix A.1) are missing from the tables 8.1/8.2.  Do i sweep that into this alpha sort change or is that something separate?

**Comment by naughtont3** [comment]
Actually, I guess that needs to be a separate ticket because the Appendix A.1 only gives the `MPI_T_ERR_xyz` constant names, whereas in Tables 8.1/8.2  the associated definition/description is also needed.  

So assuming these are valid error classes, they should be:
 1. added to alpha sort in tables 8.1/8.2
 1. a description be added for each newly added entry in tables 8.1/8.2

```
MPI_T_ERR_CANNOT_INIT 
MPI_T_ERR_NOT_INITIALIZED 
MPI_T_ERR_MEMORY 
MPI_T_ERR_INVALID 
MPI_T_ERR_INVALID_INDEX 
MPI_T_ERR_INVALID_ITEM 
MPI_T_ERR_INVALID_SESSION 
MPI_T_ERR_INVALID_HANDLE 
MPI_T_ERR_INVALID_NAME 
MPI_T_ERR_OUT_OF_HANDLES 
MPI_T_ERR_OUT_OF_SESSIONS 
MPI_T_ERR_CVAR_SET_NOT_NOW 
MPI_T_ERR_CVAR_SET_NEVER 
MPI_T_ERR_PVAR_NO_WRITE 
MPI_T_ERR_PVAR_NO_STARTSTOP 
MPI_T_ERR_PVAR_NO_ATOMIC
```

**Comment by naughtont3** [comment]
Oh, looks like there are multiple tables with Error classes, e.g., 13.5, 14.5 and in 8.1/8.2.  It looks like the `MPI_T_ERR_` codes are called "Return codes" and listed in 14.5

**Comment by naughtont3** [comment]
So I believe there is nothing else to change for Tables 8.1/8.2 and the PR [170](https://github.com/mpi-forum/mpi-standard/pull/170) is ready.

**Comment by abouteiller** [comment]
This has the effect of mixing the special error constants (MPI_SUCCESS and MPI_ERR_LASTCODE). We could keep MPI_SUCCESS first  and MPI_ERR_LASTCODE last in the list. What about MPI_ERR_IN_STATUS?
