### ISSUE TITLE
Update: Section 8.8 - p. 391 - Remove Archaic References

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#204]
## Problem

Example 8.14/8.15 and surrounding text refers to RS/6000 and Sun workstations. This is archaic text.

### Suggested Fix

Remove references to particular system names

**Comment by wesbland** [comment]
Pretty clearly a chapter committee change:

* Editor - 0
* Chapter committee - 6
* Errata - 0
* Full Proposal - 1

**Comment by bosilca** [comment]
[PR 171](https://github.com/mpi-forum/mpi-standard/pull/171) provides a fix.
