### ISSUE TITLE
Update: Chapter 10 througout; see POE page 404 - p. 399 - Expand Acronyms

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#205]
## Problem

Chapter 10: Old, unexpanded acronyms and terms (e.g., MPP) and very old software (e.g., IBM POE) should be updated (history is fine, but should clearly be in a historical context).

### Suggested Fix

Update text by expanding acronyms and making historical refs clearly historical

**Comment by wesbland** [comment]
Pretty clearly a chapter committee change:

* Editor - 0
* Chapter committee - 6
* Errata - 0
* Full Proposal - 1

**Comment by hppritcha** [comment]
closed via mpi-forum/mpi-standard#164
