### ISSUE TITLE
Update: Section 10.1 - p. 399 - Update PVM Reference

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#206]
## Problem

10.1 Is the extensive reference to PVM still relevant?

### Suggested Fix

Chapter committee to update

**Comment by hppritcha** [comment]
no.  I'll fix.

**Comment by wesbland** [comment]
Pretty clearly a chapter committee change:

* Editor - 0
* Chapter committee - 6
* Errata - 0
* Full Proposal - 1
