### ISSUE TITLE
Update: Section 11.5 - p. 466 - Bulletin Board and Reference

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#208]
## Problem

"billboard" should be "bulletin board" ? plus add a reference.

### Suggested Fix

Change to bulletin board

**Comment by wesbland** [comment]
* Editor - 4
* Chapter committee - 3
* Errata - 0
* Full Proposal - 0

Either way, this goes to @wgropp.

**Comment by wgropp** [comment]
Fixed in editorchanges
