### ISSUE TITLE
Update: Section 11.5.5 - p. 478 - Bit Vector Consistency

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#210]
## Problem

Inconsistent (on the same page!) "bit-vector OR" "bit vector or"; note "bit-vector \texttt{IOR}" (so should OR be in \code{OR}?)

### Suggested Fix

Change to use \code{OR}

**Comment by wesbland** [comment]
* Editor - 5
* Chapter committee - 2
* Errata - 0
* Full Proposal - 0

Either way, this goes to @wgropp.

**Comment by devreal** [comment]
I don't think we should use `\code{OR}` as a) it is not done so in other places (chapter 13) and b) OR is not a language construct (Fortran `IOR` is properly set as code).

**Comment by wgropp** [comment]
Should this be \mpicode{OR} (used consistently)? The all caps OR in the text font is jarring.

**Comment by devreal** [comment]
The sans-serif font of `mpicode` looks better than the default text and makes sense as language-independent code :+1: I will modify https://github.com/mpi-forum/mpi-standard/pull/238 to use `\mpicode{OR}` consistently.
