### ISSUE TITLE
Update: Section 13.2.1 - p. 522 - Clarify Fortran Version Names

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#213]
## Problem

Do we still use "Fortran 90" (page 522)? More generally, how do we refer to Fortran, esp with TS29113.

### Suggested Fix

Change all uses of Fortran 90 to "Fortran" or "Fortran + TS29113" if that TS is required.  Refer only to Fortran 77 if that standard is required, or to a particular version of Fortran (as officially adopted).

**Comment by wesbland** [comment]
Unanimously a chapter committee change.

**Comment by wesbland** [comment]
@tonyskjellum - You might need to consult with the Fortran WG (aka @hritzdorf) to decide the correct solution here.

**Comment by Shinji-Sumimoto** [comment]
This is now located on page 637 line 1 in mpi40-report-RC1.pdf.

**Comment by Shinji-Sumimoto** [comment]
Checked list for PR mpi-forum/mpi-standard#455
Replaced all Fortran 90 words to Fortran, and removed Fortran 77 related texts.

**Comment by wgropp** [comment]
This seems to be in progress, not ready to merge. Other than the PR for the IO chapter (455), are there other PRs?

**Comment by Shinji-Sumimoto** [comment]
@wgropp Thank you for your comment, there is no other PR for this issue. PR 455 only replaced all Fortran 90 words to Fortran, and removed Fortran 77 related texts.
