### ISSUE TITLE
Update: Section 13.6.10 - p. 579 - Index Size Changing

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#216]
## Problem

Index "size changing" (note italics - should this be bold?)

### Suggested Fix

Edit to update

**Comment by wesbland** [comment]
Probably another editor fix.

* Editor - 5
* Chapter committee - 2
* Errata - 0
* Full Proposal - 0

**Comment by wgropp** [comment]
Fixed above
