### ISSUE TITLE
Update: Section 13.8 - p. 584 - Converting Error Classes

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#217]
## Problem

"can be converted into the error classes" - this is not really correct; the correct statement is that the error class can be extracted from the error code.  Should compare with Error Class discussion for RMA or MPI-1.  More generally, some chapters have an explicit section on I/O Error Classes, and others do not.  Should the document be more consistent about this, particularly for classes that are really primarily for operations described in that chapter?

### Suggested Fix

For this sentence and the one after it "In addition, calls …" , replace with: "Each implementation dependent error code returned by the I/O routines belongs to either one of the error classes in Table 13.5 or one of the other MPI error classes." . The more general question requires Forum discussion.

**Comment by wesbland** [comment]
The voting here is inconclusive. Let's discuss it, but this may need a full proposal:

* Editor - 0
* Chapter committee - 2
* Errata - 2
* Full Proposal - 3

**Comment by wesbland** [comment]
The clarification here might say something about the fact that the error classes in Table 13.5 will only be raised by I/O functions, but other errors can be returned too.

If we only change "converted" to say something about using the appropriate functions, that's a small change (chapter committee). If we change the pointer to the table and other lists, it is probably a full proposal because it has a wider-reaching impact.

**Comment by Shinji-Sumimoto** [comment]
This is now located on page 710-711 in  mpi40-report-RC1.pdf.

**Comment by Shinji-Sumimoto** [comment]
Checked list for PR mpi-forum/mpi-standard#455
Replaced with suggested texts:
Each implementation dependent error code returned by the I/O routines belongs to either one of the error classes in Table 14.5 or one of the other MPI error classes.
