### ISSUE TITLE
Update: Section 18.1.17 - p. 674 - Fix Fonts

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#221]
## Problem

What font should be used in paragraph titles for ASYNCHRONOUS, MPI_F_SYNC_REG

### Suggested Fix

Suggest using the same font as for other Fortran code (\texttt). See all paragraph entries in 18.1.17

**Comment by wesbland** [comment]
Seems pretty textbook editor change to me:

* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0

**Comment by wgropp** [comment]
ftype is the most common formatting for ASYNCHRONOUS.  Fixed in editorchanges
