### ISSUE TITLE
Update: General Index - p. 860 - Explain Bold Face Indicies

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#226]
## Problem

General Index.  Better explain "Bold face numbers mark section titles"

### Suggested Fix

Bad usage of `mpitermtitle*` macros fixed by PR: https://github.com/mpi-forum/mpi-standard/pull/477

**Comment by wesbland** [comment]
Probably an editor change, but let's discuss.

* Editor - 4
* Chapter committee - 2
* Errata - 0
* Full Proposal - 1

**Comment by wesbland** [comment]
The forum didn't see the issue here and wanted to see the change proposed by @wgropp so we made this an errata.

**Comment by wgropp** [comment]
Ack! There was a commit that make extensive use of mpitermtitleindex - and this is the *wrong* macro to use for indexing items. It is only to be used for items mentioned in a section title, hence the obscure text about bold face page numbers for this index.

I suggest changing the text to say:

> Terms that appear in a section title have the corresponding page number in bold face.

I'll have to go and fix the misused mpititletermindex macros.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@wgropp I am currently doing a detailed pass on the point-to-point chapter looking at indexing (of semantics but also general tidy up). Almost anything related to indexing that you do concurrently in that chapter will likely just cause merge conflicts.

I was planning to take a look at the Sessions index entries once I'm done with point-to-point because I've noticed a bunch of this title-macro-but-not-title-location was introduced for the Sessions changes. Let's sync up to avoid duplication of effort here.

**Comment by wgropp** [comment]
Ok, I'll hold up on it until you are done.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@wgropp I have finished my over-exuberant contribution to the general index from the point-to-point chapter (see PR https://github.com/mpi-forum/mpi-standard/pull/475). I have not made changes outwith that chapter but I may do a bit of that before the end-of-Monday deadline. If I do anything, it will be limited to Chapter 2 and Sessions. In short, I'm downgrading my lock type from exclusive to shared.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
There are (if my grep skillz are good enough) 121 instances of `mpitermtitle` appearing somewhere other than between a section (or chapter) heading and the corresponding `label` for that heading.

```zsh
find chap* -name '*.tex' -not -name '*-rendered.tex' | xargs pcregrep -nHMv '^\\(chapter|(sub)*section){.*\n(\\.*\n)*\\label' | egrep '\mpitermtitle' | wc -l
     121
```

This assumes a format of:
```latex
\section{...}
\mpitermtitle...%legal
\mpitermtitle...%legal
\label{...}
\mpitermtitle...%NOT legal
```

**Comment by dholmes-epcc-ed-ac-uk** [comment]
All bad usage instances (except in chap-pt2pt, which would conflict with the work I did in https://github.com/mpi-forum/mpi-standard/pull/475) are done in this PR: https://github.com/mpi-forum/mpi-standard/pull/477

**Comment by dholmes-epcc-ed-ac-uk** [comment]
My (flawed) find-and-grep thing does not take into account humans-at-work effects. Its count has decreased to 74 but all those are legal usages.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@wgropp unlock_all.

**Comment by wgropp** [comment]
PR 477 and 475 mare merged.  For MPI 4.1, I propose changing the text to something like "Bold face page numbers are used for entries appearing in a section or subsection title."

**Comment by wgropp** [comment]
PR 673 fixed this.
