### ISSUE TITLE
Update: MPI Constant Index - p. 868 - Explain Underlined Indicies

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#227]
## Problem

In constant index, add text that the underlined entries are the "primary" definitions

### Suggested Fix

Add "Underlined page numbers give the location of the primary definition or use of the indexed term."

**Comment by wesbland** [comment]
Again, probably an editor/chapter committee change (there is no committee). I'm assigning this to @wgropp.

* Editor - 3
* Chapter committee - 3
* Errata - 0
* Full Proposal - 1

**Comment by naughtont3** [comment]
@wesbland Can update project  for "Awaiting Implementation".
