### ISSUE TITLE
Update: Multiple occurances - Fix Example Environment

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#229]
## Problem

The example environment is not used consistently.  See, for example, 6.5.1, "Example #1a" - this should be \begin{example} .... . This continues into 6.5.2, 6.5.3, 6.5.4 (which should *not* be a separate section - "Example #4" is a terrible section title.  6.5.5 ditto. 6.5.6 ditto. 6.6.3 has another "Example 1", "Example 2". 10.4.6 (several places). Section 6.7.6 has an attributes example, but 
does not use the example environment. Page 580, section 13.6.11 also has examples without the environment. Page 584, section 13.9.1 ditto. Also 13.9.2. Page 658, after MPI_Type_create_f90_integer, no example environment. Page 662, ditto.

### Suggested Fix

Update to use the example environment in all cases, and to correctly use the \label and \ref commands in the LaTeX source. Update section title for 6.5.4 to "Communication Safety Example"

## Tracker

* Each committee chair should check the box when they're done. 
* All changes should be grouped into single PR which will be reviewed all at once.
  * The first author of the PR will create a new PR. All other authors will push to the first PR (instructions to be added when the first PR is created).
  * This PR should say that it `Fixes #229` in the description to automatically link it to this issue.

If there is nothing to do in your chapter, just check your box.

* [x] Front matter - @wgropp 
* [x] Introduction - @wgropp 
* [x] Terms - @cblaas 
* [x] Point-to-Point - @dholmes-epcc-ed-ac-uk 
* [x] Datatypes - @bosilca 
* [x] Collectives - @tonyskjellum 
* [x] Communicators - @GuillaumeMercier 
* [ ] #608
* [x] Partitioned Communication - @regrant 
* [x] Environment - @bosilca 
* [x] Info - @schulzm 
* [x] Process Creation - @hppritcha 
* [ ] #609
* [x] External Interfaces - @schulzm 
* [x] I/O - @tonyskjellum 
* [x] Tools - @mahermanns 
* [x] Deprecated - @RolfRabenseifner 
* [x] Removed - @RolfRabenseifner 
* [x] Backward Incompatibilities - @wesbland 
* [ ] #610
* [x] Bindings Summary - @RolfRabenseifner 
* [x] Change Log - @RolfRabenseifner

**Comment by wesbland** [comment]
This one probably goes to the editor:

* Editor - 4
* Chapter committee - 2
* Errata - 1
* Full Proposal - 0

**Comment by tonyskjellum** [comment]
@jaegerj and I have made the PR; he will push it later.

**Comment by tonyskjellum** [comment]
With apologies, Julien and I did this work before the deadline, but did not issue the PR:
https://github.com/mpi-forum/mpi-standard/pull/496

**Comment by mahermanns** [comment]
Tool chapter looks good.

**Comment by RolfRabenseifner** [comment]
Topology chapter:
- MPI-4.0 Section 8.2, page 390, lines 29-32: These lines should be kept as part of the binding text.
- MPI-4.0 Section 8.6.1 Neighborhood Gather, page 419, lines 22-25: These lines should be kept as part of the binding text.
- All other examples are with example environment. There for I hit the checkbox for the Topology chapter.

**Comment by wesbland** [comment]
> Topology chapter:
> 
> - MPI-4.0 Section 8.2, page 390, lines 29-32: These lines should be kept as part of the binding text.
> 
> - MPI-4.0 Section 8.6.1 Neighborhood Gather, page 419, lines 22-25: These lines should be kept as part of the binding text.
> 
> - All other examples are with example environment. There for I hit the checkbox for the Topology chapter.

@RolfRabenseifner If there's a PR needed, let's not check the box until that's done.

**Comment by wesbland** [comment]
Closing this in favor of the chapter-specific issues.

**Comment by RolfRabenseifner** [comment]
No PR needed, therefore I hit the checkbox.
