### ISSUE TITLE
Update: Multiple occurances - Which/That

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#232]
## Problem

Check uses of which and correct to ", which" or "that"

### Suggested Fix

Update to use which and that as appropriate

**Comment by wesbland** [comment]
Probably an editor change. Given that we want consistency in the document, it probably wouldn't be ideal to have chapter committees try to do this. On the other hand, it's probably an intractably huge change that would take forever to implement. What do you think @wgropp?

* Editor - 4
* Chapter committee - 2
* Errata - 0
* Full Proposal - 1

**Comment by wgropp** [comment]
Magic phrase in PR 683 didn't seem to close this.  683 fixes this.

**Comment by GuillaumeMercier** [comment]
I think the magic phrase needs to be located in the description of the PR, not in the title or the comments.

**Comment by wesbland** [comment]
> I think the magic phrase needs to be located in the description of the PR, not in the title or the comments.

Correct
