### ISSUE TITLE
Update: Multiple occurances - Index PVM

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#233]
## Problem

Should PVM and similar items be indexed?

### Suggested Fix

Yes, and index in the general index

**Comment by hppritcha** [comment]
@wesbland do you have an idea of similar terms is?

**Comment by wesbland** [comment]
No idea. I refer you to @wgropp.

**Comment by wgropp** [comment]
Similar in this case is other parallel programming systems and libraries, and other software that is mentioned in the standard.

**Comment by wesbland** [comment]
This was voted an editor change. @hppritcha can just work with @wgropp here.

* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0
