### ISSUE TITLE
Bindings - Shorten Example Index Names

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#235]
## Problem

Some of the index entries in the examples index are much too long.

### Suggested Fix

Propose updates to the chapter committee (primarily tools)

### Instructions

* Each committee chair should check the box when they're done. 
* All changes should be grouped into single PR which will be reviewed all at once.
  * The first author of the PR will create a new PR. All other authors will push to the first PR (instructions to be added when the first PR is created).
  * This PR should say that it `Fixes #235` in the description to automatically link it to this issue.

If there is nothing to do in your chapter, just check your box.

* [x] Front matter - @wgropp 
* [x] Introduction - @wgropp 
* [x] Terms - @cblaas 
* [x] Point-to-Point - @dholmes-epcc-ed-ac-uk 
* [x] Datatypes - @bosilca 
* [x] Collectives - @tonyskjellum 
* [x] Communicators - @GuillaumeMercier 
* [x] Topologies - @RolfRabenseifner 
* [x] Partitioned Communication - @regrant 
* [x] Environment - @bosilca 
* [x] Info - @schulzm 
* [x] Process Creation - @hppritcha 
* [x] RMA - @wgropp 
* [x] External Interfaces - @schulzm 
* [x] I/O - @tonyskjellum 
* [x] Tools - @mahermanns 
* [x] Deprecated - @RolfRabenseifner 
* [x] Removed - @RolfRabenseifner 
* [x] Backward Incompatibilities - @wesbland 
* [ ] Bindings - @puribangalore 
* [x] Bindings Summary - @RolfRabenseifner 
* [x] Change Log - @RolfRabenseifner

**Comment by wesbland** [comment]
The chapter committees will need to work on this. Lots of assignments incoming.

* Editor - 5
* Chapter committee - 2
* Errata - 0
* Full Proposal - 0

**Comment by wesbland** [comment]
Each committee chair should check the box when they're done. Creating a small pull request for each chapter (or group of chapters if you own more than one) is probably as good a way as any to do this. Make sure that in your pull request, you mention this ticket (#235) without saying "Fixes" to avoid automatically closing it since there will be more than one PR to do this work. Also, if there's nothing to be done in your chapter, just check the box.

* [ ] Front matter - @wgropp 
* [ ] Introduction - @wgropp 
* [ ] Terms - @cblaas 
* [ ] Point-to-Point - @dholmes-epcc-ed-ac-uk 
* [ ] Datatypes - @bosilca 
* [ ] Collectives - @tonyskjellum 
* [ ] Communicators - @GuillaumeMercier 
* [ ] Topologies - @RolfRabenseifner 
* [ ] Partitioned Communication - @regrant 
* [ ] Environment - @bosilca 
* [ ] Info - @schulzm 
* [ ] Process Creation - @hppritcha 
* [ ] RMA - @wgropp 
* [ ] External Interfaces - @schulzm 
* [ ] I/O - @tonyskjellum 
* [ ] Tools - @mahermanns 
* [ ] Deprecated - @RolfRabenseifner 
* [ ] Removed - @RolfRabenseifner 
* [ ] Backward Incompatibilities - @wesbland 
* [ ] Bindings - @puribangalore 
* [ ] Bindings Summary - @RolfRabenseifner 
* [ ] Change Log - @RolfRabenseifner

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Checked - all entries from Ch3 are already short enough for single-line display in index.

**Comment by tonyskjellum** [comment]
I added markup of those that appear too long directly in the examples index.

Here is the PDF: 
[mpi40-report.pdf](https://github.com/mpi-forum/mpi-issues/files/4793333/mpi40-report.pdf)

**Comment by tonyskjellum** [comment]
This is implemented for the collective chapter:
PR: https://github.com/mpi-forum/mpi-standard/pull/250
PDF: [mpi40-report-ticket235-coll-17jun20.pdf](https://github.com/mpi-forum/mpi-issues/files/4793429/mpi40-report-ticket235-coll-17jun20.pdf)

**Comment by tonyskjellum** [comment]
I/O chapter does not appear to have any offending index entries.

**Comment by RolfRabenseifner** [comment]
I just checked the topology chapter: all short. Checkbox done.
