### ISSUE TITLE
Update: Throughout - Index Thread-Safe

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#236]
## Problem

Index thread-safe; Index Threads!POSIX and POSIX threads

### Suggested Fix

Edit to update

**Comment by wesbland** [comment]
Editor change, but @hppritcha has it.

* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0

**Comment by hppritcha** [comment]
This issue was closed via mpi-forum/mpi-standard#212
