### ISSUE TITLE
Update: Throughout - Determine Primary Index

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#239]
## Problem

In constant and predefined handle index, many entries do not have a "primary" entry (where the item is first defined; other entries should be where used).

### Suggested Fix

Find relevant entry; could enlist chapter committees

### Instructions

* Each committee chair should check the box when they're done. 
* All changes should be grouped into single PR which will be reviewed all at once.
  * The first author of the PR will create a new PR. All other authors will push to the first PR (instructions to be added when the first PR is created).
  * This PR should say that it `Fixes #239` in the description to automatically link it to this issue.

If there is nothing to do in your chapter, just check your box.

* [x] Front matter - @wgropp 
* [x] Introduction - @wgropp 
* [x] Terms - @cblaas 
* [x] Point-to-Point - @dholmes-epcc-ed-ac-uk 
* [x] Datatypes - @bosilca 
* [ ] #603
* [x] Communicators - @GuillaumeMercier 
* [x] Topologies - @RolfRabenseifner 
* [x] Partitioned Communication - @regrant 
* [x] Environment - @bosilca 
* [x] Info - @schulzm 
* [x] Process Creation - @hppritcha 
* [x] RMA - @wgropp 
* [x] External Interfaces - @schulzm 
* [ ] #604
* [x] Tools - @mahermanns 
* [x] Deprecated - @RolfRabenseifner 
* [x] Removed - @RolfRabenseifner 
* [x] Backward Incompatibilities - @wesbland 
* [x] Bindings - @puribangalore 
* [x] Bindings Summary - @RolfRabenseifner 
* [x] Change Log - @RolfRabenseifner

**Comment by wesbland** [comment]
This needs the help of each chapter committee:

* Editor - 2
* Chapter committee - 5
* Errata - 0
* Full Proposal - 0

**Comment by wesbland** [comment]
Each committee chair should check the box when they're done. Creating a small pull request for each chapter (or group of chapters if you own more than one) is probably as good a way as any to do this. Make sure that in your pull request, you mention this ticket (#239) without saying "Fixes" to avoid automatically closing it since there will be more than one PR to do this work. Also, if there's nothing to be done in your chapter, just check the box.

* [ ] Front matter - @wgropp 
* [ ] Introduction - @wgropp 
* [ ] Terms - @cblaas 
* [ ] Point-to-Point - @dholmes-epcc-ed-ac-uk 
* [ ] Datatypes - @bosilca 
* [ ] Collectives - @tonyskjellum 
* [ ] Communicators - @GuillaumeMercier 
* [ ] Topologies - @RolfRabenseifner 
* [ ] Partitioned Communication - @regrant 
* [ ] Environment - @bosilca 
* [ ] Info - @schulzm 
* [ ] Process Creation - @hppritcha 
* [ ] RMA - @wgropp 
* [ ] External Interfaces - @schulzm 
* [ ] I/O - @tonyskjellum 
* [ ] Tools - @mahermanns 
* [ ] Deprecated - @RolfRabenseifner 
* [ ] Removed - @RolfRabenseifner 
* [x] Backward Incompatibilities - @wesbland 
* [ ] Bindings - @puribangalore 
* [ ] Bindings Summary - @RolfRabenseifner 
* [ ] Change Log - @RolfRabenseifner

**Comment by GuillaumeMercier** [comment]
Does that mean using `\cdeclmainindex` vs `\cdeclindex`? 
I don't quite get what you want to fix here.

**Comment by wgropp** [comment]
Yes, the various xxxmainindex as opposed to index macros.

**Comment by GuillaumeMercier** [comment]
Just a question to be sure: when I introduce the ` \cdeclmainindex` command, the page number appears twice in the index: one number is underlined (first entry in the document) and the other is not  (the word appears at this page number in the document). Is this doubling intentional? It's not the case with the command `mpifuncmainindex` (only the underlined number appears), and I don't understand the discrepancy.

**Comment by wgropp** [comment]
Sort of - the principle entries and the non-principle entries are considered separate, so if there are entries on the same page, you'll see both.  \cdeclmainindex is only adding he one (underlined) entry.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Problem:
MPI_COMPLEX{4|8|16|32} are used in Chapter 5 (alongside MPI_INTEGER{1|2|4} and MPI_REAL{2|4|8}) but not defined in Chapter 3 where MPI_INTEGER{1|2|4} and MPI_REAL{2|4|8} are defined.
Question:
Is adding these to Chapter 3 (in order to designate those new uses as the main index entries) in scope for this issue?

**Comment by wgropp** [comment]
Defining MPI_COMPLEX{4...} should be a separate (minor) issue.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
MPI_INTEGER8 is also missing from Chapter 3 but used elsewhere.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Question:
Should there be a main index (or, indeed, *any* index entry) for a constant that MPI _does not_ define? The question relates to MPI_MESSAGE_PROC_NULL in a rationale at the bottom of page 72.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@wgropp please review PR https://github.com/mpi-forum/mpi-standard/pull/239 --- specifically the creation of new user macros for "constmain" and "typemain".

**Comment by wgropp** [comment]
I approved the constmain and typemain macros

**Comment by wgropp** [comment]
Here is a list of all of the constants, MPI declarations, and typedefs that currently do not have a primary entry. Some of these might be fixed in some pending PRs, but many remain to be fixed: [b.log](https://github.com/mpi-forum/mpi-issues/files/4940658/b.log)

**Comment by GuillaumeMercier** [comment]
PR [mpi-forum/mpi-standard/pull/234](mpi-forum/mpi-standard/pull/234)  already fixes this for chapter 6.

**Comment by devreal** [comment]
I opened https://github.com/mpi-forum/mpi-standard/pull/257 to add main index entries for the `MPI_WIN_*` constants.

@wgropp This PR adds a `\constshortmain` macro for symmetry reasons. Please let me know if that is OK, otherwise I'll be happy to remove it again.

**Comment by bosilca** [comment]
mpi-forum/mpi-standard/pull/341 adds primary indexes for the datatype and env chapters.

**Comment by RolfRabenseifner** [comment]
Dear Bill, 
I just went through the Declarations Index.
I would recommend to **add** as primary indexes (identical page  numbers mainly come from C Type)
(For a few special cases, I added a comment): 
- TYPE(MPI_Comm): 16, 30 (here, 16 is also primary)
- MPI_Data- TYPE: add also same 30 as above
- TYPE(MPI_Data- TYPE): 30
- TYPE(MPI_Errhandler): 453
- TYPE(MPI_File): 633
- TYPE(MPI_Group): 310
- TYPE(MPI_Info): 471
- TYPE(MPI_Message): 83
- TYPE(MPI_Op): 229
- TYPE(MPI_Request): 67
- MPI_Session: 492
- TYPE(MPI_Session): 492
- MPI_Status: 34, 37, 831 should be primary
- TYPE(MPI_Status): 34, 37, 832 should be primary
- TYPE(MPI_Win): 543

**Comment by RolfRabenseifner** [comment]
Only 5 primary index entries for Constants in the Topolpgy chapter:
- On page 392
  - MPI_UNWEIGHTED
  - MPI_WHEIGHTS_EMPTY
- On page 397:
  - MPI_GRAPH 
  - MPI_CART 
  - MPI_DIST_GRAPH

**Comment by RolfRabenseifner** [comment]
Only 3 primary index entries for Callback Function Prototypes in the Deprecated chapter:
- On page 772:
  - MPI_Comm_errhandler_fn
  - MPI_File_errhandler_fn
  - MPI_Win_errhandler_fn

And 10  primary index entries for the Function Index in the Removed chapter:
- On page 775
  - MPI_ADDRESS 
  - MPI_ERRHANDLER_CREATE 
  - MPI_ERRHANDLER_GET 
  - MPI_ERRHANDLER_SET 
  - MPI_TYPE_EXTENT 
  - MPI_TYPE_HINDEXED 
  - MPI_TYPE_HVECTOR 
  - MPI_TYPE_LB 
  - MPI_TYPE_STRUCT 
  - MPI_TYPE_UB 

And 5 primary index entries for the Constants Index in the Removed chapter:
- On page 776
  - MPI_LB
  - MPI_UB
  - MPI_COMBINER_HINDEXED_INTEGER
  - MPI_COMBINER_HVECTOR_INTEGER
  - MPI_COMBINER_STRUCT_INTEGER

**Comment by wesbland** [comment]
Closing this in favor of the chapter-specific issues.
