### ISSUE TITLE
Update: Throughout - Fix Punctuation in Examples

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#240]
## Problem

What is the punctuation for Examples, as in "Example 8.5 The following code is correct
(i.e., is there anything after the number (e.g., 8.5:) or the phrase
  (e.g., is it ...correct or ...correct:)

### Suggested Fix

Edit all to have a period after the example number.

**Comment by wesbland** [comment]
Probably an editor change. Could ask for help if needed. Let us know @wgropp.

* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0

**Comment by wgropp** [comment]
Fixed with PR 678
