### ISSUE TITLE
Update: Throughout - Clarify LaTeX Paragraph

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#241]
## Problem

In use of \paragraph{...}, should the item end with a period, as in \paragraph{The \mpiarg{maxprocs} argument.}? Some do and some don't. Also, should \paragraph or \paragraph* be used?

### Suggested Fix

Edit to end with a period, and to always use \paragraph*

**Comment by wesbland** [comment]
This is probably similar to (and should be resolved with #273).

**Comment by wesbland** [comment]
Unanimous editor change. Again, if you want to distribute this, let us know @wgropp.

**Comment by wgropp** [comment]
Fixed with PR 680
