### ISSUE TITLE
Update: Throughout - Interface Macros

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#243]
## Problem

A macro is needed for the INTERFACE blocks, such as those for INTERFACE MPI_WIN_ALLOCAE_SHARED to ensure uniformity (see page 434 and others)

### Suggested Fix

Need to coordinate with pythonization

**Comment by wesbland** [comment]
Voted as an editor change, but as suggested, this may need to work with Pythonization. We'll discuss in the virtual meeting to make everyone aware.

* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0

**Comment by wesbland** [comment]
@wgropp @martinruefenacht Is this still an issue?

**Comment by wgropp** [comment]
Yes - see the interface blocks in chap-inquiry.tex .  These are still done in an ad hoc fashion.

**Comment by martinruefenacht** [comment]
As I am fixing this I came across an issue with the current existing version. For MPI_ALLOC_MEM, the f90_overload function call in the binding and the interface block in text don't actually match. I assume you either saw this and identified the problem or tried to make sure we wouldn't make exactly this mistake... (this is true in 3.1)

Either way, I will need someone to verify all 4 interface blocks/f90_overloads.

**Comment by martinruefenacht** [comment]
@wesbland Apparently GitHub magic has failed us and doesn't accept capitalized version of the words. This can be closed.
