### ISSUE TITLE
Bindings - Mark Erroneous Examples

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#244]
## Problem

Erroneous examples.  See the example on page 581, section 13.6.  This example is clearly marked as erroneous.  Should all such examples be marked in the same way?

### Suggested Fix

Mark all erroneous examples as the example on 581:

    /* ----------------  THIS EXAMPLE IS ERRONEOUS --------------- */ 

(or the Fortran equivalent)

### Instructions

* Each committee chair should check the box when they're done. 
* All changes should be grouped into single PR which will be reviewed all at once.
  * The first author of the PR will create a new PR. All other authors will push to the first PR (instructions to be added when the first PR is created).
  * This PR should say that it `Fixes #244` in the description to automatically link it to this issue.

If there is nothing to do in your chapter, just check your box.

* [x] Front matter - @wgropp 
* [x] Introduction - @wgropp 
* [x] Terms - @cblaas 
* [x] Point-to-Point - @dholmes-epcc-ed-ac-uk 
* [x] Datatypes - @bosilca 
* [x] Collectives - @tonyskjellum 
* [x] Communicators - @GuillaumeMercier 
* [x] Topologies - @RolfRabenseifner 
* [x] Partitioned Communication - @regrant 
* [x] Environment - @bosilca 
* [x] Info - @schulzm 
* [x] Process Creation - @hppritcha 
* [x] RMA - @wgropp 
* [x] External Interfaces - @schulzm 
* [x] I/O - @tonyskjellum 
* [x] Tools - @mahermanns 
* [x] Deprecated - @RolfRabenseifner 
* [x] Removed - @RolfRabenseifner 
* [x] Backward Incompatibilities - @wesbland 
* [ ] Bindings - @puribangalore 
* [x] Bindings Summary - @RolfRabenseifner 
* [x] Change Log - @RolfRabenseifner

**Comment by wesbland** [comment]
Clearly a chapter committee change.

* Editor - 1
* Chapter committee - 6
* Errata - 0
* Full Proposal - 0

**Comment by wesbland** [comment]
Each committee chair should check the box when they're done. Creating a small pull request for each chapter (or group of chapters if you own more than one) is probably as good a way as any to do this. Make sure that in your pull request, you mention this ticket (#244) without saying "Fixes" to avoid automatically closing it since there will be more than one PR to do this work. Also, if there's nothing to be done in your chapter, just check the box.

* [ ] Front matter - @wgropp 
* [ ] Introduction - @wgropp 
* [ ] Terms - @cblaas 
* [ ] Point-to-Point - @dholmes-epcc-ed-ac-uk 
* [ ] Datatypes - @bosilca 
* [ ] Collectives - @tonyskjellum 
* [ ] Communicators - @GuillaumeMercier 
* [ ] Topologies - @RolfRabenseifner 
* [ ] Partitioned Communication - @regrant 
* [ ] Environment - @bosilca 
* [ ] Info - @schulzm 
* [ ] Process Creation - @hppritcha 
* [ ] RMA - @wgropp 
* [ ] External Interfaces - @schulzm 
* [ ] I/O - @tonyskjellum 
* [ ] Tools - @mahermanns 
* [ ] Deprecated - @RolfRabenseifner 
* [ ] Removed - @RolfRabenseifner 
* [x] Backward Incompatibilities - @wesbland 
* [ ] Bindings - @puribangalore 
* [ ] Bindings Summary - @RolfRabenseifner 
* [ ] Change Log - @RolfRabenseifner

**Comment by tonyskjellum** [comment]
@jaegerj will do a PR for this correction later today.
