### ISSUE TITLE
Update: Throughout - Avoid Incorrect Line Breaks

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#245]
## Problem

Various.  In text, "INTEGER(KIND=...)" and "INTEGER (KIND=...)" are used (and sometimes with a ~ for the space).  Pick one and use consistently.  Also be consistent in the examples.

### Suggested Fix

Use "INTEGER(KIND=…)" to avoid line breaking between INTEGER and (KIND=…)

**Comment by wesbland** [comment]
Editor change:

* Editor - 5
* Chapter committee - 2
* Errata - 0
* Full Proposal - 0

**Comment by martinruefenacht** [comment]
The suggested fix in this case may not prevent line breaking in all cases.
I suggest:
```\mbox{INTEGER(KIND=...)}```

In Pythonization we are wrapping all parameter names in a box to avoid LIS line breaking in the middle of a parameter name.

Also this is another candidate for testing. We can ensure no INTEGER(:?~\w+)(KIND=...) are floating around.

**Comment by wgropp** [comment]
The major issue here is the inconsistency in the spacing. This does have a side effect in line breaks. In the document, the majority use no space (e.g., "INTEGER(KIND=...)" rather than "INTEGER (KIND=...)".  The current fix is to address only the use of ties in these names.

**Comment by wgropp** [comment]
Also, I don't really want to force this to be on the same line, so I don't want to use the mbox solution.
There are 54 uses without the space and 31 with the space. For now, I'll just implement the no-space form (PR 467)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@martinruefenacht Sounds like a candidate for a python test? Look for "(KIND=" and examine the surrounding context?
I did a test with `egrep` but Python can do regex too.

BTW, @wgropp:
```zsh
% egrep -nRi '\(KIND=' --include='*.tex' . | egrep -v 'INTEGER\(KIND=' | wc -l
33
```
The discrepancy is due to lower case.
```zsh
% egrep -nRi '\(KIND=' --include='*.tex' . | egrep -v 'INTEGER\(KIND=' | egrep -v '[[:space:]]+\(KIND='
./chap-binding/binding-2.tex:1904:%%DECL: integer (kind=MPI_OFFSET_KIND) zero
./chap-binding/binding-2.tex:2387:integer(KIND=MPI_ADDRESS_KIND) :: disp(4), base, lb, extent
./chap-io/io-2.tex:1598:integer (kind=MPI_OFFSET_KIND) zero
./chap-io/io-2.tex:1715:integer (kind=MPI_OFFSET_KIND) zero
```

**Comment by martinruefenacht** [comment]
I made an issue in my fork to come around to this in the future.
