### ISSUE TITLE
Update: Throughout - Use Correct Emphasis Macros

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#246]
## Problem

Throughout.  Some chapters use bold for emphasis and new terms, others do not. See, for example, "connected" on page 425 in 10.5.4.

### Suggested Fix

Edit to use proper term macros; search for use of emph

**Comment by wesbland** [comment]
Editor change.

* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0

**Comment by wgropp** [comment]
Use of the mpitermdef macros has addressed this in part.  Still needs a review of the full document as it is now.

**Comment by wgropp** [comment]
I need to update the instructions for the new approach to terms, and make a pass to use the macros for terms, rather than italics or bold as is used sometimes. Not for 4.0, unfortunately.
