### ISSUE TITLE
Formatting: Section 5.12.8 - p. 210 - Fix Misalignment

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#247]
## Problem

MPI_IALLTOALLV.  Note the misalignment of the arg "request" - this is because of bogus spaces in the LaTeX for these.  See also MPI_IREDUCE.

### Suggested Fix

Check that pythonization fixes these

**Comment by wesbland** [comment]
Editor change, but maybe already done with Pythonization. Discuss between @wgropp and @martinruefenacht 

* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0

**Comment by wgropp** [comment]
Confirmed fixed in pythonization.
