### ISSUE TITLE
Clarification: Chapter 2 - p. 12 - Semantic Terms Fixes

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#250]
## Problem

Semantic terms. The group of terms between "predefined" and "equivalent" only describe these terms with respect to datatypes. There are other predefined values (e.g., MPI_COMM_WORLD), and equivalent objects (e.g., Groups).

### Suggested Fix

Add "The following terms apply to MPI datatypes" before "predefined".

**Comment by jaegerj** [comment]
This is currently handled by the "terms" proposal for issue #96 .

If the no-no votes doesn't pass in Munich and the proposal cannot be integrated in MPI 4.0, then I'll do a specific proposal for this.
