### ISSUE TITLE
Clarification: Section 2.10 - p. 22 - Example Clarification

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#251]
## Problem

We could mention that we do endeavor to check the examples, e.g., that they at least compile.

### Suggested Fix

Add "Many of the examples have been compiled by tools that extract the examples from the source files for the MPI Standard."

**Comment by wesbland** [comment]
The voting here is a little unclear:

* Editor - 2
* Chapter committee - 3
* Errata - 0
* Full Proposal - 2

**Comment by dholmes-epcc-ed-ac-uk** [comment]
I agree with this change and the proposed sentence is good, IMHO.

**Comment by cblaas** [comment]
@dholmes-epcc-ed-ac-uk I just created the PR with an additional "However, " and with "\MPI/ standard":

https://github.com/mpi-forum/mpi-standard/pull/465
