### ISSUE TITLE
Clarification: Section 3.2.2 - p. 27 - Datatype Footnote

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#252]
## Problem

The list of MPI datatypes that correspond to REAL*2 etc. should note that REAL*2 etc. are obsolete extensions to the Fortran standard, and are provided for convenience.  Users should take advantage of the "KIND" versions and related MPI routines.

### Suggested Fix

Add a footnote after "additional data types" : These types, such as DOUBLE COMPLEX and INTEGER*4, are not standard Fortran but are common extensions to Fortran."

### References

Fixed by PR https://github.com/mpi-forum/mpi-standard/pull/224

Similar to problem noted in issue https://github.com/mpi-forum/mpi-issues/issues/171
That is fixed by PR https://github.com/mpi-forum/mpi-standard/pull/196

**Comment by wesbland** [comment]
This needs discussion:

* Editor - 3
* Chapter committee - 2
* Errata - 1
* Full Proposal - 1

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Here is a PDF with change-bars:
[mpi-report-ticket252-2020-MAY-20-changebars.pdf](https://github.com/mpi-forum/mpi-issues/files/4657169/mpi-report-ticket252-2020-MAY-20-changebars.pdf)

Here is a PDF without:
[mpi-report-ticket252-2020-MAY-20-cleandoc.pdf](https://github.com/mpi-forum/mpi-issues/files/4657173/mpi-report-ticket252-2020-MAY-20-cleandoc.pdf)

**Comment by wesbland** [comment]
This passed a "no no" vote on 2020-06-30.

**Comment by wesbland** [comment]
This passed an errata vote on 2020-07-01.

https://www.mpi-forum.org/meetings/2020/06/votes
