### ISSUE TITLE
Clarification: Section 3.8.3 - p. 73 - Language Fix

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#253]
## Problem

The "as if a receive from MPI_PROC_NULL..." is odd language and should be improved.

### References

Fixed by: https://github.com/mpi-forum/mpi-standard/pull/302

**Comment by omor1** [comment]
The pedant in me also notes that the word following "MPI_PROC_NULL" ought to be "were" rather than "was"; as this is a counterfactual hypothetical, the subjunctive mood ought to be used.

**Comment by omor1** [comment]
Page listed in title seems to be incorrect—this is on pp. 70 and 71, for MPI_MRECV and MPI_IMRECV.

**Comment by wesbland** [comment]
Probably a committee change. This goes to @dholmes-epcc-ed-ac-uk 

* Editor - 1
* Chapter committee - 6
* Errata - 1
* Full Proposal - 0
