### ISSUE TITLE
Clarification: Section 8.5 - p. 377 - Error Class and Code Advice to Implementors

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#259]
## Problem

(Twice, after description of add_error_class and add_error_code) Why is the advice to implementors made? Why is this a property of a high-quality implementation? Excactly what does "the same deterministic way" mean? Recommend deleting this advice to implementors about deterministic mpi_add_error_class and mpi_add_error_code

### Suggested Fix

Delete the advice to implementors in both places

https://github.com/mpi-forum/mpi-standard/pull/178

**Comment by wesbland** [comment]
This is errata at the least. Maybe a full proposal:

* Editor - 0
* Chapter committee - 3
* Errata - 2
* Full Proposal - 2

**Comment by abouteiller** [comment]
Sounds like a full proposal. Not clear if desired behavior (deterministic at all ranks) can be achieved without making the call synchronizing. Plenty to discuss here.

**Comment by wesbland** [comment]
This will continue as a full ticket. There was a minor change made during the reading that needs a no-no vote:

https://github.com/mpi-forum/mpi-standard/pull/178/commits/44d0ec5b32cf1aec4bf7ba215bb1a3d566d3ac5f

This no-no change is already considered "read".

**Comment by wesbland** [comment]
This passed a first vote on 2020-08-19.

https://www.mpi-forum.org/meetings/2020/08/votes

**Comment by wesbland** [comment]
Since we added meetings to move 4.0, this can now be part of that release instead of 4.1.

**Comment by wesbland** [comment]
This passed a second vote on 2020-09-28.

https://www.mpi-forum.org/meetings/2020/09/votes
