### ISSUE TITLE
Clarification: Section 10.3.2 - p. 402 - Application Types

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#261]
## Problem

What is a "static SPMD or MPMD application" (the "static")? I presume the opposite of dynamic, but I don't believe this is common use, and that doesn't even fit in with the usage here.

### Suggested Fix

Change to say "SPMD or MPMD applications with a fixed number of processes after initialization"

**Comment by schulzm** [comment]
assigned to Howard as the CC chair for Process Creation and Mangement

**Comment by wesbland** [comment]
The answers were all over the place here. We can discuss scope unless @hppritcha wants to just pick one:

* Editor - 2
* Chapter committee - 2
* Errata - 2
* Full Proposal - 1

**Comment by hppritcha** [comment]
closed via mpi-forum/mpi-standard#206
