### ISSUE TITLE
Clarification: Section 11.7 - p. 482 - MPI Exception Clarification

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#263]
## Problem

"MPI exception" is used, but this term is not well defined (and the usage is the "signal an MPI exception" - MPI doesn't signal.

### Suggested Fix

Chapter committee to update

### Associated pull request

https://github.com/mpi-forum/mpi-standard/pull/177

**Comment by wesbland** [comment]
This is probably an errata as well, but needs discussion:

* Editor - 1
* Chapter committee - 2
* Errata - 3
* Full Proposal - 1

**Comment by abouteiller** [comment]
MPI Exception is defined in 8.3. The more common form for the problematic text in the RMA chapter is `the call raises an MPI error`.

**Comment by jsquyres** [comment]
MPI-3.1:8.3 p340:15 says: "Each such error generates an **MPI exception**." (and "MPI exception" is actually bold faced in the spec).

Are you removing all cases of "MPI exception" from the spec except for the place that initially names it?  I'm confused as to what problem this issue is trying to solve...?

**Comment by wesbland** [comment]
Yes. That's a good point. We missed that (and a few other places) before. We made some more changes today in the WG to fix that.

The main goal is to clarify the terms failure, exception, and error, by removing the term "exception" from the MPI side of things (there are still OS exceptions, etc.). So now we don't "signal an exception", "raise an exception", or anything else. We just "raise an error".

**Comment by wesbland** [comment]
This passed a "no no" vote on 2020-06-30.

**Comment by wesbland** [comment]
This passed a "no no" and errata vote on 2020-08-19.

https://www.mpi-forum.org/meetings/2020/08/votes
