### ISSUE TITLE
Clarification: Section 13.2.8 - p. 530 - Additional Definitions

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#264]
## Problem

In I/O (starting collective_buffering), "target nodes" are used without definition or introduction.  This section should provide some definitions and the abstract execution model to which these terms apply

### Suggested Fix

Chapter committee to update

**Comment by wesbland** [comment]
Odd voting here. Need to decide what to do with this:

* Editor - 0
* Chapter committee - 4
* Errata - 0
* Full Proposal - 3

**Comment by rsth** [comment]
It was a term used in the mid-90s to refer to intermediate nodes. Maybe change it to "intermediate or target nodes" at the first occurrence in the collective_buffering hint. Users of that hint will know what that means or will not be using that hint at all. Additional explanation will just make things more complicated. 

I am also ok with making no change at all.

**Comment by Shinji-Sumimoto** [comment]
This is now located on page 645 in MPI_FILE_GET_INFO(fh, info_used), mpi40-report-RC1.pdf.

**Comment by Shinji-Sumimoto** [comment]
Checked list for PR mpi-forum/mpi-standard#455
Change text as follows:
Accesses to the file are performed on behalf of all \MPI/ processes in the group
by a number of nodes which use collective IO.
