### ISSUE TITLE
Clarification: Section 13.2.8 - p. 530 - Unclear Definitions

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#265]
## Problem

Similarly, under the chuncked options, these terms are not precise. E.g., what is an "array entry"?

### Suggested Fix

Chapter committee to update

**Comment by wesbland** [comment]
Probably chapter committee, but we need to talk I guess:

* Editor - 4
* Chapter committee - 1
* Errata - 1
* Full Proposal - 1

**Comment by rsth** [comment]
The hints chunked, chunked_item, and chunked_size go together. The array entry refers to the array mentioned in the chunked hint.

(These hints were added because some research I/O software in the 1996 timeframe supported chunked access. I forget which one. I doubt these hints are actually used. But let them be. They can simply be ignored, or someone may find a use for them.)

**Comment by Shinji-Sumimoto** [comment]
This is now located on page 645 in MPI_FILE_GET_INFO(fh, info_used), mpi40-report-RC1.pdf.

**Comment by Shinji-Sumimoto** [comment]
Here is a related paper written by Rajeev:
https://www.mpich.org/2012/10/24/optimizing-noncontiguous-accesses-in-mpi-io/

And some use cases are in HDF5
https://ecpannualmeeting.com/assets/overview/sessions/HDF5-ECP-AM-2020-Tutorial.pdf

**Comment by Shinji-Sumimoto** [comment]
Checked list for PR mpi-forum/mpi-standard#455
Added reference document index: 
For further information about the key values, we refer the reader to [thakur:mpiio].

@article{thakur:mpiio,
  author    = {Rajeev Thakur and
               William Gropp and
               Ewing L. Lusk},
  title     = {Optimizing Noncontiguous Accesses in {MPI-IO}},
  journal   = {CoRR},
  volume    = {cs.DC/0310029},
  year      = {2003},
  url       = {http://arxiv.org/abs/cs/0310029},
  timestamp = {Fri, 10 Jan 2020 12:59:10 +0100},
  biburl    = {https://dblp.org/rec/journals/corr/cs-DC-0310029.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}
