### ISSUE TITLE
Clarification: Section 13.3 - p. 533 - Language Clarifications

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#266]
## Problem

For MPI_FILE_SET_VIEW, there is a phrase starting "These displacements are not required to be distinct". It should be clearer what "these" refers to.

### Suggested Fix

Needs chapter committee to suggest

**Comment by wesbland** [comment]
The chapter committee can propose text, but maybe this is an errata:

* Editor - 1
* Chapter committee - 2
* Errata - 4
* Full Proposal - 0

**Comment by rsth** [comment]
"These displacements" refers to "The typemap displacements in the filetype".

**Comment by Shinji-Sumimoto** [comment]
Checked list for PR mpi-forum/mpi-standard#455
"These displacements" refers to "The typemap displacements in the filetype".
