### ISSUE TITLE
Clarification: Section 14.3.7 - p. 615 - MPI_T Session Impact Clarifications

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#268]
## Problem

Any call executed in a session must not influence the results in any other session" I do not know how to implement this if *any* timers are used, or in many other cases.  This term is too broad.

Also with the introduction of MPI sessions, the general term *session* is ambiguous.

### Suggested Fix

Perhaps narrow this to any other MPI_T call? Even then, timing results may be influenced, and any counters that depend on message timing.

Explicitly reference MPI_T sessions as *performance experiment (PE) sessions*.

### Associated Pull Request

https://github.com/mpi-forum/mpi-standard/pull/168

**Comment by schulzm** [comment]
Suggestion from the 02/27 Telcon: Replace sentence with:

MPI_T Performance variables  in different PE Session must measure independently,
e.g., starting and stopping in one session must not influence whether a variable is started or stopped in another session.

**Comment by mahermanns** [comment]
Text refinement from the 03/05 Telcon:

Performance variables of the MPI Tool Information Interface across different performance experiment (PE) sessions must measure independently, e.g., starting, stopping, or resetting a variable in one session must not influence whether a variable is started, stopped, or reset in another session.

**Comment by wesbland** [comment]
@mahermanns can take this one, but we should discuss the scope:

* Editor - 0
* Chapter committee - 4
* Errata - 1
* Full Proposal - 2

**Comment by mahermanns** [comment]
@wesbland @schulzm Should be go through the changes in a standard "pre-reading" in one of the next virtual meetings to make sure everyone is OK with the changes in [PR#168](https://github.com/mpi-forum/mpi-standard/pull/168)?

**Comment by wesbland** [comment]
It's up to you. I don't think there have been significant changes since the first discussion, but you're welcome to bring it up if you'd like to do so.

**Comment by mahermanns** [comment]
@wgropp @dholmes-epcc-ed-ac-uk Could you have a look at the current text in [PR#168](https://github.com/mpi-forum/mpi-standard/pull/168/files) and see whether the current wording is clear enough to know what we want to express?

**Comment by wgropp** [comment]
I like that text - it is much more precise about the expectation, and can be implemented :)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
👍

**Comment by wesbland** [comment]
This passed an errata vote on 2020-08-19.

https://www.mpi-forum.org/meetings/2020/08/votes
