### ISSUE TITLE
Clarification: Throughout - Fortran Binding

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#269]
## Problem

Throughout, for consideration.  In the Fortran bindings, we use

```
  <type> a(*), b(*)
```
for anonymous addresses/pointers.  But these need not be of the same
*Fortran* type, e.g., the use might be
```
  INTEGER a(*)
  REAL  b(*)
```
These bindings would be clearer if the were listed as
```
  <type> a(*)
  <type> b(*)
```

### Suggested Fix

Need to coordinate with pythonization

**Comment by wesbland** [comment]
Looks like an editor change with Pythonization:

* Editor - 5
* Chapter committee - 1
* Errata - 0
* Full Proposal - 1

**Comment by martinruefenacht** [comment]
@wesbland Could you expand your explanation above? I don't understand what this issue is meant to be. I may also just not understand Fortran well enough...

**Comment by wesbland** [comment]
@wgropp can clarify since this was originally his note.

**Comment by wgropp** [comment]
I edited the description so critical parts of the description aren't silently eaten.  The point is that when we say `<type> a(),  b()`, it implies that `a` and `b` are the same (unspecified) type. This works in C, since `void *` is an unspecified type. But in Fortran before 2008, there aren't anonymous types. This is a small point, and perhaps not worth changing.

**Comment by martinruefenacht** [comment]
I see, thank you. That should be easy from Python.

Is it per interface? Is it correct to force some interfaces to have `<type> a(*), b(*)`?

For example, MPI_Pack `<type> INBUF(*), OUTBUF(*)` with a single datatype parameter vs MPI_Alltoall with two datatype parameters `<type> SENDBUF(*), RECVBUF(*)`?

**Comment by martinruefenacht** [comment]
Also is this a change for MPI 4.0 or MPI 4.1?

**Comment by wgropp** [comment]
I'd suggest MPI 4.1 just to simplify the review process.

**Comment by martinruefenacht** [comment]
Agreed, I'll tackle this once we get to the next phase and the above question is answered as well.

**Comment by wgropp** [comment]
On the question, I think that `<type> a(), b()` is only appropriate when both have the same associated datatype.  In the case of MPI_Pack, the outbuf implicitly has type MPI_PACKED, so there still are two separate MPI datatypes. MPI_Allreduce is a case where the basic types should be the same.

**Comment by martinruefenacht** [comment]
As a note to future self, this gets complicated with semantic information if we want to automate this behaviour.
- sendtype + sendbuf, recvtype + recvbuf means separable
- single datatype multiple buffers means not separable
- MPI_Pack is exception, may be able to circumvent with a different KIND (inherits BUFFER type)

This all needs to be more thoroughly checked, will probably require chapter committee level approval of implied behaviour.

**Comment by wgropp** [comment]
Note that putting each of these anonymous types on a separate line is always correct. There is no need to try to figure out if it might be correct to use the `<type> a, b` form.  So my question: How easy is it to generate separate lines for each of the anonymous type parameters for the Fortran bindings?

**Comment by RolfRabenseifner** [comment]
I expect that Section 2.5.5 describes clearly that `<type> a, b` is a notation for "choice" and has the same meaning as the official Fortran `TYPE(*), DIMENSION(..) :: a, b`.
As the official Fortran notation does not require that a and b have the same type, I would expect that nobody has a reason to expect this for the non-Fortran-standard notation with `<type> a, b`.
Therefore, I expect there is no need for any change.

**Comment by wgropp** [comment]
No, section 2.5.5 makes clear that the TYPE(*), DIMENSION(..) is for the mpi_f08 module, and this is already used in the Fortran 2008 binding. I'm talking about the bindings currently used for mpif.h and use mpi, and I was only talking about the Fortran, not the Fortran 2008, binding. If we *removed* both of those, this problem goes away. Or we can decide that it isn't worth fixing.

**Comment by RolfRabenseifner** [comment]
2.5.5 says
> For Fortran with the include file mpif.h or the mpi module, the document uses `<type>` to represent a choice
variable; with the Fortran mpi_f08 module, such arguments are declared with the Fortran 2008 + TS 29113 syntax `TYPE(*), DIMENSION(..)`; for C, we use `void*`.

Reading this sentence from the middle, the notation `TYPE(*), DIMENSION(..)` represents a choice variable in mpi_f08, and `<type>` is doing the same in mpif.h or the mpi module, and `void*` is doing the same is in C.

I have nothing agains splitting `<type> a, b` into `<type> a; <type> b`, but I think it isn't worth the effort.

**Comment by wgropp** [comment]
Given the direction to deprecate mpif.h (and maybe the mpi module), this probably isn't worth the effort, though it should be easy - there is no reason to consider whether <type> a.b might be semantically correct - using one variable per line would always be correct.
