### ISSUE TITLE
Consistent use: Chapter 9 (no subsection !) - p. 397 - MPI_INFO_GET_NTHKEY font

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#271]
## Problem

Description of MPI_INFO_GET_NTHKEY.  What is the correct font for $N$, and should it be n (lower case), or should it be a different letter (to avoid confusion with the n and N in the arg list for this routine? Note that the MPI_T routines use \mpicode for these values (page 616).

### Suggested Fix

Use \mpicode instead of math mode; check for consistent use elsewhere in the document.  Alternative - change other uses, such as the one in MPI_T, to use math mode.

**Comment by wesbland** [comment]
Editor change:

* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0

**Comment by wgropp** [comment]
On review, I believe this is fine as is; a better fix might be to use a different name for the value returned by MPI_INFO_GET_NKEYS.
