### ISSUE TITLE
Consistent use: Section 13.27 - p. 530 - Key/Value vs. Key-Value

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#274]
## Problem

key/value used here, other forms (such as key-value, page 320 and (key,value) page 384) elsewhere. How do we refer to key,value in the document?

### Suggested Fix

Change to use (key,value)

**Comment by wesbland** [comment]
Editor change:

* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0

**Comment by wgropp** [comment]
Replaced key/value with (key,value). The rest of the document is split between key-value and (key,value). Recommend key-value as the standard.

**Comment by wesbland** [comment]
Closed by https://github.com/mpi-forum/mpi-standard/pull/321
