### ISSUE TITLE
Consistent use: Section 13.4 - p. 537 - Fix Fonts

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#275]
## Problem

etype and filetype are in the wrong font.  (see, e.g., page 533)

### Suggested Fix

Search for etype and filetype and use correct command (\mpiarg or \mpicode)

**Comment by wesbland** [comment]
Unanimous editor change.

**Comment by wgropp** [comment]
These seem to be already fixed - some uses of the phrase "etype" or "filetype" should be in text font (as they are), because they don't refer to parameters, but to associated properties of the view/file.
