### ISSUE TITLE
Consistent use: Section 18.1.4 - p. 643 - Fix Cases

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#276]
## Problem

Should the itemize list leaders "Define..." be lowercase? What is the consistent (and correct) use?  Ditto page 644 in 18.1.5 rationale.

**Comment by wesbland** [comment]
Probably editor change:

* Editor - 5
* Chapter committee - 2
* Errata - 0
* Full Proposal - 0

**Comment by wgropp** [comment]
Fixed by PR 679
