### ISSUE TITLE
Consistent use: Section 18.1.7 - p. 643 - Set to vs. = vs. ==

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#277]
## Problem

The phrase "set to" used here instead of the use of "=" used elsewhere.  This may be ok, but there is an instance of == here.

### Suggested Fix

Edit to update

**Comment by wesbland** [comment]
@wgropp and @puribangalore can discuss. Probably an editor change though.

* Editor - 4
* Chapter committee - 3
* Errata - 0
* Full Proposal - 0

**Comment by schulzm** [comment]
We decided to push this to MPI 4.1

**Comment by wesbland** [comment]
@wgropp I'm not sure what the action for chapter committees should be here. Is it that we need to go over each chapter and look for `set to`, `=`, and `==` and be more consistent about their use (particularly `set to` and `=` I would think)?

**Comment by wgropp** [comment]
I think the major issue is deciding what the Forum wants as the convention - then the editor can make the updates. Perhaps the first thing to do is to see if we can get the vocal people to agree on a convention - then we can bring to the wider Forum. Off hand, do you know what the C, C++, OpenMP, and/or Fortran standards do? If there is a convention that they use, we should adopt that.

**Comment by wgropp** [comment]
I'm closing this, as either "set to" or "=" is ok, and I've made that clear in the instructions. I've changed the few uses of == in text to =.
