### ISSUE TITLE
Consistent use: Section 19.1.9 - p. 814+816 - Replace <TYPE> by <TYPECLASS>

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#278]
## Problem

Page 661 used MPI_`<TYPE>`n . I believe this is the only use of `<TYPE>`

### Suggested Fix

Edit to use a different format (look at the other uses where different options are included for MPI routines)

**Comment by wesbland** [comment]
Looks like a chapter committee change:

* Editor - 2
* Chapter committee - 5
* Errata - -
* Full Proposal - 0

**Comment by martinruefenacht** [comment]
This now section 19.1.9 on page 808/810 as far as I can tell.

**Comment by puribangalore** [comment]
I do not see any problems with the current usage of MPI_<TYPE>n in these pages.

**Comment by wgropp** [comment]
Something else would be a little better. Perhaps "FTYPE" for (old) Fortran Type.

**Comment by wesbland** [comment]
@puribangalore / @martinruefenacht Did this ever get a PR to fix it or should we push this out to MPI 4.1?

**Comment by puribangalore** [comment]
My suggestion is to move this to MPI 4.1. \<type\> is what is used for the old Fortran types, we can leave that as is for now.

**Comment by RolfRabenseifner** [comment]
It looks like that we discuss 

- MPI-4.0 Section 19.1.9 page 814 lines 23-28

> Support for Size-specific MPI Datatypes
> ...
> We assume that for each **typeclass** (integer, real, complex) and each word size there is
> a unique machine representation. For every pair **(typeclass, n)** supported by a compiler,
> MPI must provide a named size-specific datatype. The name of this datatype is of the form
> MPI_\<TYPE\>n in C and Fortran where \<TYPE\> is one of REAL, INTEGER and COMPLEX, and
> n is the length in bytes of the machine representation. This datatype locally matches all
> variables of type **(typeclass, n)** in Fortran.

and
- MPI-4.0 Section 19.1.9 page 816 lines 19-22

> Communication With Size-specific Types
>
> The usual type matching rules apply to size-specific datatypes: a value sent with datatype
> MPI_\<TYPE\>n can be received with this same datatype on another process.

Based on the existing text, I recommend to substitute \<TYPE\> at the three referenced locations by \<TYPECLASS\>.

I would not use \<typeclass\> because on page 815, 

> MPI_TYPE_MATCH_SIZE(typeclass, size, datatype)

there is an argument of name \mpiarg{typeclass}.

@wesbland @martinruefenacht @puribangalore @wgropp Okay for you?

**Comment by RolfRabenseifner** [comment]
See yellow marker and PR802 marker on pages 777 and 779 in
[mpi41-report_Issue278_PR802.pdf](https://github.com/mpi-forum/mpi-standard/files/10831642/mpi41-report_Issue278_PR802.pdf)

**Comment by RolfRabenseifner** [comment]
Result from the reading, see yellow marker and PR802 marker on pages 777-779 in 
[mpi41-report_Issue278_PR802_final.pdf](https://github.com/mpi-forum/mpi-standard/files/11001255/mpi41-report_Issue278_PR802_final.pdf)
