### ISSUE TITLE
Consistent use: Section 18.1.17 - p. 677 - Intent font/capitalization

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#279]
## Problem

18.1, "Note that if the intent .." intent should be in Fortran font, as INTENT

### Suggested Fix

Use \ftype

**Comment by wesbland** [comment]
Editor change:

* Editor - 6
* Chapter committee - 0
* Errata - 1
* Full Proposal - 0

**Comment by wgropp** [comment]
Part of editorchanges PR
