### ISSUE TITLE
Consistent use: Multiple occurances - Array of Handles Plurality

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#281]
## Problem

In the function defintions for arrays, is the description singular (array of handle) or plural (array of handles)? Pick one and be consistent. See also MPI_TYPE_CREATE_STRUCT - see "array of handles to datatype objects". Is this the format that we use?

### Suggested Fix

Suggest asking the bindings committee to review

**Comment by wesbland** [comment]
Looks like the chapter committee can take this one:

* Editor - 2
* Chapter committee - 4
* Errata - 1
* Full Proposal - 0

**Comment by martinruefenacht** [comment]
This has been addressed in the Pythonization pass. We couldn't replicate every different style so we went with "array of handles" for MPI_TYPE_CREATE_STRUCT. The only exception at the moment is "array of Status" which should really be "array of statuses" according to our American English usage in the text.

In fact 2.5.2 already states this in text: "When a NULL argument is desired for an array of statuses, one uses MPI_STATUSES_IGNORE.". The LIS types are just incorrect. This is an easy switch, the code exists and is commented out.

**Comment by wesbland** [comment]
So we should close this when the Pythonization code is merged? If so, can you add `Closes mpi-forum/mpi-issues#281` to the PR description for Pythonization?

**Comment by martinruefenacht** [comment]
Specific to handles there is "MPI_TYPE_CREATE_STRUCT" as above and "MPI_STARTALL" which is just missing the "s". In that case, yes I can add the closes clause.

If we want to address the plural status we could do that with this ticket or do a separate one?

**Comment by wesbland** [comment]
This may already be addressed, but it needs someone to make a quick pass through the document and see that we address this correctly.

**Comment by martinruefenacht** [comment]
@dholmes-epcc-ed-ac-uk found an instance of (array of integer) in chap-dynamic:2213

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Not perfect, but this is a good rough guess at finding instances of this:
```zsh
egrep -nRi 'array of [[:alpha:]]+[^s][[:>:]]' --include='*.tex' . | egrep -v 'array of size|array of length|array of non-negative integers|array of positive integers|array of undefined values|array of predefined values|array of opaque objects' | egrep -v 'array of predefined \\MPI/ datatypes|array of byte displacements|array of integer triplets'
```

I found exactly one occurrence of "array of non-plural" here:
```
./chap-dynamic/dynamic-2.tex:2213:        desc="one code per process (array of integer)",
```

**Comment by martinruefenacht** [comment]
For some reason the MPI_Comm_spawn array of errcodes still had a hand written LIS type and a suppressed autogenerated LIS type.

**Comment by martinruefenacht** [comment]
The error discovered by @dholmes-epcc-ed-ac-uk is fixed in the PR.

Creating a test for this is not possible, because the descriptions are not generated. I attempted to write a test that find whether an LIS type is written by hand within descriptions, but this is also not possible due to usage of parentheses inside valid descriptions. I need to continue to think over this.

Finally, the "array of status" is still an issue. We just need a decision, it is trivial to change in the LIS binding generator (already existing).

The plurality of all the other LIS types are approved since that was in when we did the big binding review.

**Comment by martinruefenacht** [comment]
I have come to the conclusion no tests can currently be written to catch potential errors. One option would be to prevent writers from using parentheses, which would allow finding erroneous descriptions.

Dan's array of approach only happened to work in that specific case. "array of" is also used in other locations in descriptions which then needs to have a type following them and that is difficult to verify automatically. We can check for "(array of" which need something to follow with an "s", but it is also not perfect.

In the end Jeff and I never intended the descriptions to be verifiable and unless we restrict the state space we can't.

From my point of view the only remaining item for this PR is whether we want to have "array of status" or "array of statuses" (as used throughout in text).

@wgropp I guess you make that decision.

**Comment by wgropp** [comment]
I'm fine with not having a test - in the general case, perfect tests are impossible. Its great to add tests when it is easy, but nothing will replace careful reading of the document.  Thanks, @martinruefenacht, for looking into it.

On array of status vs array of statuses, I prefer array of status. Lets leave it at that.

**Comment by martinruefenacht** [comment]
@wgropp I guess you missed the PR above. mpi-forum/mpi-standard#471

It fixes the issue Dan found mentioned above. I have removed the commit which changed to "array of statuses" so it will remain "array of status".
