### ISSUE TITLE
Add MPI_Delete_error_class, MPI_Delete_error_code, MPI_Delete_error_string

### ISSUE THREAD

**Issue by ZedThree** [mpi-forum/mpi-issues#283]
# Problem

It is currently not possible to remove error classes/codes/strings after adding them. This makes it difficult for libraries to clean up after themselves, for example. Some MPI implementations may have statically allocated error classes, putting a hard upper limit on the number that can be added.

# Proposal

Add these functions, which would remove the corresponding (user) error class/code/string:

* `MPI_Delete_error_class(int error_class)`
* `MPI_Delete_error_code(int error_code)`
* `MPI_Delete_error_string(int error_code)`

I'm less certain what the function signature of `MPI_Delete_error_string` should look like, but I guess it should take the error code use to add the string?

# Changes to the Text

Add appropriate function signatures and descriptions to section 8.5 Error Classes, Error Codes, and Error Handlers

# Impact on Implementations

Addition of three functions.

# Impact on Users

No changes to existing code required. New functionality.

# References

See [here](https://github.com/pmodels/mpich/issues/4341) for some further information on why this would be useful.

Originally opened [on the Fault Tolerance working group repo](https://github.com/mpiwg-ft/ft-issues/issues/14), but it @wesbland suggested to move it here.

Pull Request: https://github.com/mpi-forum/mpi-standard/pull/166

**Comment by wesbland** [comment]
Proposal in PDF form with highlights (where possible due to watermark).

[remove_err.pdf](https://github.com/mpi-forum/mpi-issues/files/4587509/remove_err.pdf)

**Comment by wesbland** [comment]
I just added another patch that includes changes suggested at the virtual meeting on 2020-05-06. I think this is ready to go for an official reading during the meeting at the end of June.

**Comment by wesbland** [comment]
Somehow this got left off the agenda. We'll read it at the next meeting instead.

**Comment by wesbland** [comment]
I failed to update the PDF after the latest changes.

[remove_err.pdf](https://github.com/mpi-forum/mpi-issues/files/5084581/remove_err.pdf)

**Comment by wesbland** [comment]
This passed a first vote on 2020-09-28.

https://www.mpi-forum.org/meetings/2020/09/votes

**Comment by wesbland** [comment]
I forgot to change all of the references on this issue to say that the names of the new functions are "Delete", rather than "Remove". It's been that way on the PR for a while, but it didn't change here. That's been updated now.

**Comment by wesbland** [comment]
There will need to be a no-no vote for the 2020-12 meeting to confirm some changes made after the reading:

https://github.com/mpi-forum/mpi-standard/pull/166/files/470df5150534ecea611930cca9660418abdfc28b..2a0e658a66011e1ab8f6e169532cc41652bebbaf

These were made to correct a copy/paste error with the wrong function name and clarify that you can only delete things that were "successfully" added, rather than just "returned from" a previous function. Thanks to @dholmes-epcc-ed-ac-uk and @jsquyres for the comments.

**Comment by wesbland** [comment]
@abouteiller - Is this something that the FTWG is still considering? Since I stepped back from that position, I've lost track of this issue and PR.

**Comment by abouteiller** [comment]
Wesley, 

Nobody is currently looking into it. I still think it is a valuable addition. 

We could re-add it to the agenda; from my memory, there were problems with it, but they got fixed. Is there anything else we need to look at before re-presenting it?

Aurelien

**Comment by wesbland** [comment]
Yes. I believe I’ve addressed all of the issues from Jeff. I think it probably just needs to be reviewed and re-read.

**Comment by abouteiller** [comment]
I am taking ownership of this issue now. I think the following discussion about the naming convention of the function needs some discussion to decide if the forum is content with current resolution. https://github.com/mpi-forum/mpi-standard/pull/166#issuecomment-918264991

We will advance this item towards MPI 4.1, but it is no a blocker and could be delayed if difficulties are encountered.

**Comment by cniethammer** [comment]
Should a call to the proposed `MPI_Delete_error_code()` also delete the error string associated with the provided error code automatically?
As a user I would assume so as requiring two calls after each other
```
MPI_Delete_error_string(error_code)
MPI_Delete_error_code(error_code)
...
```
looks very strange.

Thinking more - is `MPI_Delete_error_string()` needed at all?
The existing `MPI_Add_error_string()` can be used to overwrite the error string for an error code and does not need to clean it before setting.
Does just removing the string make sense if one wants to keep the error code? A user can set the string to the empty string `""` which would be returned by `MPI_Error_string()` if it is not set anyway.

**Comment by abouteiller** [comment]
Discussion during the 23 Feb 1, we need to either say that 1) incorrect removal order (e.g., removing a class before removing a code) is erroneous, or 2) removing the top-level object also removes all dependent objects (but that has the drawback that MPI would need to track the 1-many association between a class and its codes, which it doesn't have to do today).

New version of the text will be presented next meeting according to these ideas.

**Comment by abouteiller** [comment]
Text has been updated according to idea 1 in commit https://github.com/mpi-forum/mpi-standard/pull/166/commits/fc45250824ef9dd5fd9b21fef509349d41b3819a

You will find in comment a mockup of the idea 2. I do not intend to follow it because I dislike the inconsistency between the behavior of remove_error_class and remove_error_string. If this idea doesn't get a champion, I will remove the comment with this mockup during the post-reading editorial process.

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-08.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 26
	<td> 0
	<td> 5
</table>

**Comment by wesbland** [comment]
I just wanted to call attention to this issue that it didn't get scheduled for anything for the March 2023 meeting. Unfortunately we've passed the deadline for announcements, but this can still be scheduled for a vote at the next Meeting in May.

**Comment by wesbland** [comment]
This passed a [1st vote](https://mpi-forum.org/meetings/2023/05/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 28
    <td> 0
    <td> 4
</table>

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2023/07/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 34
    <td> 0
    <td> 0
</table>
