### ISSUE TITLE
Consistency: spacing around em dashes

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#284]
The use of spaces around em dash is inconsistent:

```
# without spaces
$ egrep "[a-z]\\-\\-\\-[a-z]" *.tex */*.tex | wc -l
9
# with spaces
$ egrep "[a-z] \\-\\-\\- [a-z]" *.tex */*.tex | wc -l
36
```

From what I can see, some style manuals recommend no spaces (Chicago Manual of Style, Oxford Guide to Style) but there are others (NYT, AP) that recommend (small) spaces [1]. My personal preference is having no spaces but that might just be acquired taste (for one, *space*-em dash-*space* is quite large and line breaks before/after an em dash are ugly imo).

Fun fact: the use is inconsistent even in the instructions document.

In any case, the use of spacing around em dashes should be consistent throughout the standard document and documented in the instructions.

[1] https://en.wikipedia.org/wiki/Dash#Spacing_and_substitution

**Comment by wgropp** [comment]
Good point - thanks for the catch. I'll fix this instructions; for the record, I prefer no spaces but obviously don't check :)

**Comment by wgropp** [comment]
Instructions fixed - no spaces around the em dash.

**Comment by martinruefenacht** [comment]
Do we already have a PR to fix the spacing in the document? (Will there be one?)

I think this is another one that would be reasonable to write a test for related to the Python CI PR.

**Comment by wgropp** [comment]
I don't think that we have a PR for this yet - I did just the instructions so I wouldn't forget.

**Comment by martinruefenacht** [comment]
I can take this on and additionally write a test for it to enforce it in future.

I assume this would be part of the editor pass?
