### ISSUE TITLE
Formatting: vertical spacing after example environment

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#285]
In at least one place, text is placed between two examples (found between Example 11.7 and 11.18). The intermittent text is not distinguishable as such and instead could be confused as part of the first example. It would be good to add vertical spacing after the example environment to help make the end of the example environment clear.

See also https://github.com/mpi-forum/mpi-issues/issues/211#issuecomment-613330757

**Comment by wesbland** [comment]
During discussion in the 2020-05-27 virtual meeting, we asked @devreal to show an example of how the document would look if the examples were called out more prominently. He agreed to try out making a small change to the example environment to place bars around the examples so we could see if that makes things more clear.

**Comment by devreal** [comment]
I have dusted off my tikz skills a bit and toyed around with examples in a `tcolorbox` environment. Unfortunately, I am not blessed with design skills so I apologize for the rather crude implementation.

Here are some options with example documents. Interesting examples to look at might be 3.1-3.3 (three in a row on one page), 3.4 (surrounded by text), and 3.5 (breaks across page break):

1) A light gray background: 
[mpi40-report-exbackground.pdf](https://github.com/mpi-forum/mpi-issues/files/4697939/mpi40-report-exbackground.pdf)

2) A full lightgray frame, no filling:
[mpi40-report-fullframe.pdf](https://github.com/mpi-forum/mpi-issues/files/4697956/mpi40-report-fullframe.pdf)

3) Lightgray lines on top and bottom, with vertical ticks:
[mpi40-report-extopbottom.pdf](https://github.com/mpi-forum/mpi-issues/files/4697966/mpi40-report-extopbottom.pdf)

4) Lightgray corners (top left, bottom right):
[mpi40-report-excorners.pdf](https://github.com/mpi-forum/mpi-issues/files/4697968/mpi40-report-excorners.pdf)

5) No decoration, simply putting the example in a `tcolorframe` to achieve the same spacing as with the decorated examples:
[mpi40-report-none.pdf](https://github.com/mpi-forum/mpi-issues/files/4697972/mpi40-report-none.pdf)

Of course, for all of these the margins, line width, and color grading can be adapted. The different implementations can be found at https://github.com/devreal/mpi-standard in the respective `example-spacing-*` branches.

**Comment by rsth** [comment]
The first one with the light gray background looks good. Need to see how it looks on a printed page or whether a lighter shade is needed for the printed version.

**Comment by cniethammer** [comment]
I prefer the gray as well. Makes it a lot easier to identify, read and also follow on page boundaries.

Note: As I see, this affects many page brakes - also inside examples (e.g. widow in example 5.2) - so it will come with some fine tuning work.



----- Original Message -----

**Comment by wesbland** [comment]
My preference is also the grey.

We discussed this in the virtual meeting and made some small suggestions to improve things like text overflowing the boxes and expanding the formatting to include things like advice to users/implementors. 

This probably needs some feedback from @wgropp from a document formatting perspective and @RolfRabenseifner from a printed book perspective (though I printed out a sample page with the grey box and it looks fine to me).

Another option if the book version doesn't work is to have one version for the book version and another for the PDF version.

**Comment by RolfRabenseifner** [comment]
I would prefer the "Lightgray lines on top and bottom, with vertical ticks:"
https://github.com/mpi-forum/mpi-issues/files/4697966/mpi40-report-extopbottom.pdf 
The version with gray background my cause problems with figures within an example.
The versions "none" and "excorners" are too invisible for the reader.
Of course, the "fullframe" is also perfect:
https://github.com/mpi-forum/mpi-issues/files/4697956/mpi40-report-fullframe.pdf
I understand that solid grey looks beautiful, but may degrade readability for some handicaped readers.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
"fullframe" gets my vote - the others give less information to the casual reader.

Is this particular line part of an example or not? "fullframe" and "exbackground" tell me without searching up/down the document.

Where does this example begin/end? "fullframe", "extopbottom", and "excorners" tell me without reading content to figure out if a page-break ends one example and begins another.

Winner: "fullframe"

**Comment by dholmes-epcc-ed-ac-uk** [comment]
This has the CC label - as Point-to-point CC chair, I approve this change for the MPI-4.0 release.

If other CCs approve, please can we change the mpi-4.1 label to mpi-4.0 and merge this into the RC branch ASAP?

**Comment by wesbland** [comment]
This would require a no-no vote since it's after the deadline.

**Comment by wesbland** [comment]
@devreal is this still being worked for 4.0? It looks like everything is done, but it needs approval from @wgropp.

**Comment by wgropp** [comment]
I believe the related PR has already been merged and this can be closed.
