### ISSUE TITLE
Incorrect case in change log

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#286]
# Problem

An entry in the change log incorrectly used mixed case, as in a C binding, for several MPI function names

# Proposal

Correct the text

# Changes to the Text

Change
```
\mpifunc{MPI\_Alloc\_mem}, \mpifunc{MPI\_Win\_allocate}, and
\mpifunc{MPI\_Win\_allocate\_shared}
```

to

```
\mpifunc{MPI\_ALLOC\_MEM}, \mpifunc{MPI\_WIN\_ALLOCATE}, and
\mpifunc{MPI\_WIN\_ALLOCATE\_SHARED}
```

# Impact on Implementations

None.

# Impact on Users

None (other than that the change log will be corrected, and 3 bogus entries will vanish from the index)

# References

See the instructions - \mpifunc should only be used for the language-neutral name.

**Comment by RolfRabenseifner** [comment]
Seems to be resolved by the author of the change-log entry.
Therefore, I expect that this issue can be closed.
