### ISSUE TITLE
All but one URL in bibliography are broken

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#290]
I found that all URLs except for the link to `mpi-forum.org` in the bibliography are broken, namely

- [28] (quick search didn't turn up a replacement), 
- [41] (both URLs gone, TS seems available at https://www.iso.org/standard/45136.html)
- [45] (moved to https://docs.freebsd.org/44doc/psd/21.ipc/paper.pdf)
- [56] (found a copy at http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.49.6283 but the doi doesn't seem to resolve at doi.org).

Not sure what to do about [28] since that was a TR, not a peer-reviewed paper.

**Comment by omor1** [comment]
[28] seems to be retrievable via the [Internet Archive](https://web.archive.org/web/20030811183415/http://www.uni-karlsruhe.de/~Michael.Hennecke/Publications/#MPI_F90). The site seems to have gone offline circa late 2003.

**Comment by devreal** [comment]
@omor1 The page is archived but the paper referenced on it is not. Unless someone has a copy lying around somewhere this one is probably a lost cause. I suggest removing the URL from the reference.

I also noticed that the URL to the comments mailing list is broken: http://lists.mpi-forum.org/mailman/listinfo.cgi/mpi-comments  Is that list gone? Was it moved?

**Comment by wgropp** [comment]
I agree with removing URLs that are no longer valid, even if no replacement can be found, and leaving the reference.
A reminder of how unreliable URLs are for referencing documents in the long term.
