### ISSUE TITLE
Errata: label flag type for Info Object Routines as logical instead of boolean

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#291]
# Problem

For MPI_Info routines, flags are described as (boolean) in the bindings, while in the rest of the standard we use (logical). This was already noticed during the pythonization, but decided to treat this as a separat errate (to avoid any changes during pythonization).

# Proposal

Replace (boolean) with (logical) for all MPI_Info routines that have a flag (in the Info and Deprecated chapters)

# Changes to the Text

see PR

# Impact on Implementations

None

# Impact on Users

None

# References

n/a

**Comment by wesbland** [comment]
According to the PR, this is no longer and errata item, but is now chapter committee. Is that true @schulzm? if so, let's change the tags to reflect that.
