### ISSUE TITLE
Typos in strings of data representations

### ISSUE THREAD

**Issue by hritzdorf** [mpi-forum/mpi-issues#292]
Page 561, Line 33

MPI supports multiple data representations: “native,” “internal,” and “external32.”

should be

MPI supports multiple data representations: “native”, “internal”, and “external32”.

Page 562, Line 22-23

provided by “internal,” an implementation may choose to implement “internal”
as "external32.” (End of advice to implementors.)

should be

provided by “internal”, an implementation may choose to implement “internal”
as “external32”. (End of advice to implementors.)

Page 562, Line 46

If the file data representation is other than “native,” care must be taken in constructing

should be

If the file data representation is other than “native”, care must be taken in constructing

Page 140, Line 27

argument is “external32.”

should be

argument is “external32”.

**Comment by devreal** [comment]
@hritzdorf If you are referring to the comma and full-stop being inside the quotation then this is not a bug but a feature, common use in the English language. See for example rule 4: https://www.grammarbook.com/punctuation/quotes.asp

**Comment by wesbland** [comment]
While it's true that punctuation marks _can_ be inside the quotation marks, in these examples, I don't believe they should be. I think the differentiator is whether the punctuation is part of the thing being quoted or part of the quoting sentence. In these cases, they're not part of the word being quoted.

**Comment by devreal** [comment]
@wesbland I am not a native speaker but afair this is true only for question marks (quoting a question or asking about a quote makes a difference). With comma and full stop it is always inside the quote (as that makes no difference whether or not it is attributed to the quote itself or part of the surrounding text).

**Comment by wesbland** [comment]
> @wesbland I am not a native speaker but afair this is true only for question marks (quoting a question or asking about a quote makes a difference). With comma and full stop it is always inside the quote (as that makes no difference whether or not it is attributed to the quote itself or part of the surrounding text).

Ah, you're correct. I was thinking of the rule for special types of punctuation (e.g. if you have an "exclamation!" inside a quotation but continue the sentence).

**Comment by wgropp** [comment]
I think that the right fix is to make the strings in a code (or mpicode?) format, at which point, it is clearer that the commas should not be within the quotes.

**Comment by devreal** [comment]
@wgropp in that case we might not even need quotation marks around them...

**Comment by wgropp** [comment]
They are strings - the quotes are needed and customary in the standard.

**Comment by rsth** [comment]
Why do periods and commas go inside quotation marks: https://style.mla.org/punctuation-and-quotation-marks/

**Comment by hritzdorf** [comment]
Thanks for the advice. In this case, the following lines are inconsistent:  

MPI 3.1 Page 537, Line 19
even in a heterogeneous environment with “internal”, “external32”, or user defined
Line 11
If the data representation is “native”, then this logical file server runs on the same

Hopefully, there is never a blank string "" in a list or before end of a sentence.

**Comment by hritzdorf** [comment]
Only as note:
modified by prefixing with the letter “P”, e.g., PMPI_Isend.

**Comment by wgropp** [comment]
I'm going to changing these and document this exception to the American English rules on punctuation and quotes.
