### ISSUE TITLE
Consistency: noncollective vs non-collective

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#294]
# Problem

Two ways of spelling are used in the document:

- `non-collective` is used in Section 6.8 (only occurance)
- `noncollective` is used multiple times in Section 13.

There should be a decision on which style to use. It seems that we have "nonblocking" and "non-local" (https://github.com/mpi-forum/mpi-issues/issues/231),  so no consistency at the global scale regarding `non`. I don't have a strong opinion either way for `non-collective` vs `noncollective`.

**Comment by wgropp** [comment]
I did an online search, and non-collective appears to be the more common use, including in articles on grammar (though I did not find one specifically on non-collective vs noncollective).

**Comment by rsth** [comment]
The hyphen is omitted in the I/O chapter because that is how our technical editor, Gail Pieper, prefers it. Wikipedia says "In many cases, especially in American usage, non- is joined without a hyphen." https://en.wiktionary.org/wiki/non-

**Comment by devreal** [comment]
Superseded by https://github.com/mpi-forum/mpi-issues/issues/316, closing this one.
