### ISSUE TITLE
Remove usage of offensive language

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#297]
# Problem

Hi MPI-Forum,

This is request to move away from the master-slave terminology currently
used in the following locations in the 2019 draft specification :

- section 6.4.1 : page 256, line 46
- example 6.5.3 page 272 and page 273

These would be better described by supervisor/executor or manager/worker or
anything the members of "Groups, Contexts, Communicators, Caching" working
group see fit.

Thank You,
Sajid Ali | PhD Candidate
Applied Physics
Northwestern University
s-sajid-ali.github.io

# Proposal

Replace casual usage of unacceptable language.

# Changes to the Text

- section 6.4.1 : page 256, line 46
replace "master-slave model" with "supervisor/executor or manager/worker model" (1 occurrence)
- example 6.5.3 page 272 and page 273
replace variable "commSlave" with variable "commWorker" in example and throughout that section.

# Impact on Implementations

None.

# Impact on Users

A small step towards equity, inclusion, and celebration of diversity.

# References

https://lists.mpi-forum.org/pipermail/mpi-comments/2020-June/000280.html
PR: https://github.com/mpi-forum/mpi-standard/pull/244

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Compiled PDF with change-bars:
[mpi-report-ticket297-2020-JUN-15-changebars.pdf](https://github.com/mpi-forum/mpi-issues/files/4779590/mpi-report-ticket297-2020-JUN-15-changebars.pdf)

Compiled PDF without change-bars:
[mpi-report-ticket297-2020-JUN-15-cleandoc.pdf](https://github.com/mpi-forum/mpi-issues/files/4779591/mpi-report-ticket297-2020-JUN-15-cleandoc.pdf)

**Comment by wgropp** [comment]
Thanks, Dan.  I agree with this change.
