### ISSUE TITLE
Promoting to MPI_Init_thread after MPI_Init?

### ISSUE THREAD

**Issue by ax3l** [mpi-forum/mpi-issues#299]
# Problem

We want to (MPI) initialize an application depending on an input file option. This runtime option might request threaded or non-threaded initialization for various purposes (e.g. I/O).

Typically, we read an input file from an I/O rank that then broadcasts the results to other ranks. But now we have a chicken-egg problem, because we should not read the input file from many, many threads before calling `MPI_Init[_thread]`. But the latter can only be called once.

# Proposal

We could decide to allow promotion of an `MPI_Init` call to `MPI_Init_thread` once in the application lifetime and for the whole comm world communicator. Or an `MPI_Init_thread` from an initially provided `MPI_SINGLE` to `MPI_THREAD_MULTIPLE`.

# Changes to the Text

12.4.3 Initialization: Add an `MPI_COMM_WORLD` collective `int MPI_Promote_threaded(int required, int *provided)` (and equivalent Fortran function). Could require a global barrier so that all started communication is finished.

8.7 Startup: mention the new option for promotion of the initialized MPI context.

Likely more.

# Impact on Implementations

Very likely that local management data needs to be upgraded from single-thread to the equivalent threaded structure. For example, `MPI_SINGLE -> MPI_THREAD_MULTIPLE`.
(Note that we do **not** propose the opposite way here.)

# Impact on Users

Workflows that depend on a "simple" MPI context for an initialization phase, e.g. as described above, would work.

Application developers would not need to work-around the startup phase with binary variants, own starters, etc. and could write consistent, runtime input files for applications.

# References

https://github.com/AMReX-Codes/amrex/pull/808

# Considered Alternatives

We currently implement a full binary variant for this, which is sub-ideal for testing, shipping and using libraries and applications.

We considered passing command line arguments instead, which is problematic since they might only arrive on one rank in some cases. We considered initializing with the most "parallel" threading option by default (`THREAD_MULTIPLE`) which might slow down further communication in the case one decides to never use it from threads(?).

We considered controlling via an environment variable, but that is a bit cumbersome for the following reasons: it's an extra modification of the external startup call, which many applications abstract away from their users (machine-specific templates, etc.); it cannot easily be written or derived from a "central" input file if the input syntax is complex enough (e.g. specific parsers, etc.); startup options such as `-x <env>` are not standardized.

**Comment by devreal** [comment]
Wouldn't that be covered by the Sessions proposal that will be included in MPI 4?

**Comment by ax3l** [comment]
Hi Joseph, thanks for the hint!. Can you point me to that please, have not seen this yet.

**Comment by ax3l** [comment]
cc @jeffhammond as promised.

**Comment by hjelmn** [comment]
Sessions are the exact thing you want. You can create a new MPI session with thread multiple. Session passed a second vote recently making it an official part of the MPI standard.

See #103

**Comment by jeffhammond** [comment]
@ax3l My intent in suggesting a GitHub issue was to fix the application that thinks it needs this change in the MPI standard 😉

**Comment by ax3l** [comment]
We already control the MPI init on the app side.
Even with that, the chicken-egg problem that I want to do something on "rank zero" (open the file) and want to collectively call MPI_Init_thread request with depending input options is not solvable at the moment.

MPI session look really promising though, thank you for the hint and I look forward to those in MPI-4.0.

**Comment by jeffhammond** [comment]
You can cheat and use `getenv(PMI_RANK)` with MPICH here, and whatever the equivalent is for Open-MPI.  Just `#ifdef MPICH` etc.

Source: https://lists.mpich.org/pipermail/devel/2015-April/000549.html
