### ISSUE TITLE
Consistency: replace "task" with "rank" or "MPI process" where appropriate

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#300]
# Problem

The standard document spuriously uses the term `task` instead of `rank` or `MPI process`. The term is never defined as such and quite overloaded these days. 

# Proposal

For the changes for MPI 4.0 please see the PR: https://github.com/mpi-forum/mpi-standard/pull/258

# Impact on Implementations

None. (I am aware that some vendors may use the term `task` to refer to processes. I think it's a terrible choice and not the official MPI speak.)

# Impact on Users

Being more consistent avoids some distraction.

**Comment by wesbland** [comment]
Is this replacing the job that @dholmes-epcc-ed-ac-uk started years ago?

**Comment by dholmes-epcc-ed-ac-uk** [comment]
This is a small piece of the effort by the Hybrid WG (of which I was/am a member). We clocked 2000+ instances of this type of change in the first 600 pages and then ground to a halt. Piecemeal seems like a better approach.

**Comment by cblaas** [comment]
I would like to see the 3 substitutions of "task" by "MPI process" in PR 258 already in MPI-4.0.

Piecemeal indeed seems to be a good approach here as these are the only three occurrences of "task" in a wrong context.

**Comment by wgropp** [comment]
A quick check shows 21 lines that contain the word "task". Historically, as noted above, some vendors used "task" where others were using "process". And the standard was a bit sloppy about saying MPI Process (the only kind of process that the standard discusses). And while multi-threaded processes were considered from the beginning (its why the global state approach in PVM was rejected), they weren't always at the top-of-mind.  If we'd caught this in MPI 1.0, we would have replaced task with process everywhere.

**Comment by wesbland** [comment]
Closing this issue in favor of the chapter-specific issues created on 2021-03-04.
