### ISSUE TITLE
Improve text for MPI_Comm_split_type

### ISSUE THREAD

**Issue by GuillaumeMercier** [mpi-forum/mpi-issues#301]
# Problem

While working on the two new values for the `split_type` parameter of `MPI_Comm_split_type`, the Hardware Topologies Working Group realized that the current text describing the function could be improved.

# Proposal

* Change the description of the behavior of  `MPI_Comm_split_type`.
* Change the description of `MPI_COMM_TYPE_SHARED`

# Changes to the Text

# Impact on Implementations

None.

# Impact on Users

None.

# References

The proposed text is in this PDF (p. 281):  [mpi40-report-issue301-29-07-2020.pdf](https://github.com/mpi-forum/mpi-issues/files/4997924/mpi40-report-issue301-29-07-2020.pdf)
PR is here: mpi-forum/mpi-standard/pull/263

**Comment by GuillaumeMercier** [comment]
New version of the PDF: [mpi40-report-issue301-02-09-2020.pdf](https://github.com/mpi-forum/mpi-issues/files/5164743/mpi40-report-issue301-02-09-2020.pdf)

**Comment by wesbland** [comment]
This passed an errata vote on 2020-09-28.

https://www.mpi-forum.org/meetings/2020/09/votes
