### ISSUE TITLE
Add MPI_INFO argument to PSEND_INIT/PRECV_INIT calls for Partitioned Communication Chapter

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#308]
# Problem

We accidentally left off the MPI_INFO argument in these new APIs.  We are sure we need them for future purposes of per-partitioned communication assertions.

# Proposal

The MPI_INFO argument is added to the text.

# Changes to the Text

The MPI_INFO argument is added to the text in the definition of MPI_PSEND_INIT and MPI_PRECV_INIT.

# Impact on Implementations

Implementations will have to interpret the INFO argument in these APIs.

# Impact on Users

None, the API has not been released yet.

# References

PR: https://github.com/mpi-forum/mpi-standard/pull/275
Local PR vs. Partitioned chapter (useful till Partitioned PR is merged to MPI-4.0):  https://github.com/mpiwg-persistence/mpi-standard/pull/3 (Much simpler reading for the short term)

Latest PDF:  [mpi40-report-ticket308-13sep20.pdf](https://github.com/mpi-forum/mpi-issues/files/5215021/mpi40-report-ticket308-13sep20.pdf)

**Comment by tonyskjellum** [comment]
Please see a new PDF added today after @jaegerj 's suggestions were addressed.

**Comment by wesbland** [comment]
This passed a no-no vote on 2020-09-28.

https://www.mpi-forum.org/meetings/2020/09/votes

**Comment by wesbland** [comment]
This passed an errata vote on 2020-09-30.

https://www.mpi-forum.org/meetings/2020/09/votes
