### ISSUE TITLE
Clarify when to return info objects in MPI_T events chapter

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#309]
# Problem

The original text first described situations in which the info argument is ignored by the library, and continues with situations when an info object is returned. This wording may cause an ambiguity, whether there might be a difference between ignoring an argument and a library choosing not to return an info object.

The original intent was that a library *always* returns an info object, if it is not covered by the scenarios of the first case. That info object must then contain all info keys applicable for the corresponding source or event type, which may result in an empty info object.

# Proposal

Change wording such that the original intent becomes clear.

# Changes to the Text

See PR: https://github.com/mpi-forum/mpi-standard/pull/277

# Impact on Implementations

Clear instructions on how to handle info objects.

# Impact on Users

Clear instructions on what to expect from info objects returned from `MPI_T_event_get_info` and `MPI_T_source_get_info`.

# References

**Comment by wesbland** [comment]
This passed an errata vote on 2020-09-28.

https://www.mpi-forum.org/meetings/2020/09/votes
