### ISSUE TITLE
Clarify MPI object isolation description in Chapter 10.3

### ISSUE THREAD

**Issue by hppritcha** [mpi-forum/mpi-issues#310]
# Problem

The last paragraph of section 10.3 of the current MPI 4.0 draft describes MPI object isolation in the context of the Sessions and World Process Models.  The current text is somewhat ambiguous and can be improved.  

# Proposal

Simplify rewording to clarify restrictions on mixing the use of MPI objects derived from different Sessions or from the World Process Model (MPI_Init) in MPI calls, e.g. MPI_Waitall.

# Changes to the Text

Changes are captured in PR https://github.com/mpi-forum/mpi-standard/pull/269

# Impact on Implementations

Provide clarity to implementors about restrictions on usage of MPI objects derived from different Sessions or from the World Process Model.

# Impact on Users

Provide clarity to users about restrictions on usage of MPI objects derived from different Sessions or from the World Process Model.

**Comment by hppritcha** [comment]
PDF with highlighted change (pages 431,432) attached.
[mpi40-report-diff.pdf](https://github.com/mpi-forum/mpi-issues/files/5220278/mpi40-report-diff.pdf)

**Comment by wesbland** [comment]
This passed a no-no vote on 2020-09-29 and errata vote on 2020-09-30.

https://www.mpi-forum.org/meetings/2020/09/votes

**Comment by hppritcha** [comment]
associated PR https://github.com/mpi-forum/mpi-standard/pull/269 merged into mpi-4.1.x
