### ISSUE TITLE
Fix wrong term "process group with Cartesian structure" in section 7.5.5

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#311]
# Problem
The text describing `MPI_Cart_rank` in Section 7.5.5 uses the term "process group with Cartesian structure".
This is wrong, as topology information is added to communicators as specified in 7.3.
So, the interface of `MPI_Cart_rank` is build around a communicator as input - and not a process group.

# Proposal
Replace  "process group with Cartesian structure" with "communicator with an associated Cartesian topology"

# Impact on Implementations
- Behavior of implementation clarified

# Impacts on Users
- Behavior of implementation clarified

# References
PR: https://github.com/mpi-forum/mpi-standard/pull/280
The latest PDF file (chapter with marked changes): [topol_fix-unspecified-cartesian-process-group.pdf](https://github.com/mpi-forum/mpi-issues/files/5421661/topol_fix-unspecified-cartesian-process-group.pdf)

**Comment by tonyskjellum** [comment]
As discussed, this needs to move to and through a committee.  @GuillaumeMercier --- are you OK with my putting through the Collective et al. WG?  I think you said that :-) Please advise.

We should put this forward as an erratum.  I will look for @cniethammer (Christoph's) other ones too.

@RolfRabenseifner, please do not create crypto-errata without WG :-) 

Thank you all.

**Comment by tonyskjellum** [comment]
@cniethammer , you need to do your PR through the right WG's github, not through your personal one.  That way, it is fully public and shared with the requisite WG.  Once I confirm with @GuillaumeMercier , we will do so under collective or topology github presence, and you can push your branch there, and do a new PR.   Personal forks are not the right process!
Thank you, Tony

**Comment by GuillaumeMercier** [comment]
@tonyskjellum: you can take over this issue/PR in your own WG if you wish.

**Comment by cniethammer** [comment]
> @cniethammer , you need to do your PR through the right WG's github, not through your personal one. That way, it is fully WG-accessible and shared with the requisite WG. Once I confirm with @GuillaumeMercier , we will do so under collective or topology github presence, and you can push your branch there, and do a new PR. Personal forks are not the right process!
> Thank you, Tony

Thanks.
Waiting for a go to move and make the PR at the WG repo.

**Comment by wesbland** [comment]
Is this intended for MPI 4.0 or MPI 4.1?

**Comment by cniethammer** [comment]
@RolfRabenseifner or @tonyskjellum could one of you label this for mpi-4.0

Chapter PDF with marked change is attached to the initial comment.

**Comment by wesbland** [comment]
2020-12-07 Errata vote results

| Yes | 	No	| Abstain | 	Missed |	Result |
| --- | --- | --- | --- | --- |
| 29 |	3	| 0	| 0	| Passed |
