### ISSUE TITLE
Catastrophic errors can cause MPI returning wrong outputs

### ISSUE THREAD

**Issue by abouteiller** [mpi-forum/mpi-issues#313]
# Problem

During proof reading in preparation for 4.0, I noticed that catastrophic errors are listed to produce only deadlocks. But they can also cause MPI returning wrong error codes, among other incorrect outputs.

The second case is not listed in the following text, in the terms chapter.

Presentation material used during Oct. 21, 2020 virtual meeting
[20201021-mpiforum-virtual-post-catastrophic-errcode.pdf](https://github.com/mpi-forum/mpi-issues/files/5416317/20201021-mpiforum-virtual-post-catastrophic-errcode.pdf)

# Changes to the Text

```diff
diff --git a/chap-terms/terms-2.tex b/chap-terms/terms-2.tex
index e55f43e..6e0a6bf 100644
--- a/chap-terms/terms-2.tex
+++ b/chap-terms/terms-2.tex
@@ -998,9 +998,10 @@ in Section~\ref{sec:errorhandler}.
 Several factors limit the ability of \MPI/ calls to return with meaningful error
 codes when an error occurs.
 \MPI/ may not be able to detect some errors;  other errors may be too
-expensive to detect in normal execution mode; finally some errors may be
+expensive to detect in normal execution mode;  some faults (e.g., memory faults)
+may corrupt the state of the \MPI/ library and its outputs; finally some errors may be
 ``catastrophic'' and may prevent \MPI/ from returning control to the caller.
```

https://github.com/mpi-forum/mpi-standard/pull/281

# Impact on Implementations

None

# Impact on Users

Clarification of existing behavior.

# Procedures

This does not change semantics (explains what may happen during undefined states) and thus should be only editorial?

**Comment by abouteiller** [comment]
Discussed during oct. 21, 2020 virtual meeting. Solution retained is to not single out the error as a specific thing that can become undefined.

**Comment by wesbland** [comment]
2020-12-07 Errata vote results

| Yes | 	No	| Abstain | 	Missed |	Result |
| --- | --- | --- | --- | --- |
| 29 |	3	| 0	| 0	| Passed |
