### ISSUE TITLE
Fix undefined behaviour of MPI_Cart/Graph*_get caused by binding to specific communicator creation calls

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#314]
# Problem

The Cartesian topology part of the topology chapter is built around `MPI_Cart_create` and the arguments passed to this function.
This leaves an inconsistent view of the topology information as it ignores possibilities of other functions to influence
the topology information associated with communicators, e.g. by `MPI_Comm_dup`, `MPI_Comm_idup`, and `MPI_Cart_sub`.
As a result this leads to undefined behaviour, e.g. when `MPI_Cartdims_get` or `MPI_Cart_get` are applied to a communicator created with `MPI_Cart_dup` or `MPI_Cart_sub` from a communicator created with `MPI_Cart_create`.

Note 1: `MPI_Cart_sub` should obviously modify the topology information, but the result cannot be exposed to the user.
Note 2: The same applies to `MPI_Graphdims_get` and `MPI_Graph_get` for a communicator created by `MPI_Graph_create`

# Proposal

The following steps resolve this issue:
* State that topology information may be assigned to a communicator at the time of its creation.
* Let communicator creation functions describe what topology information they assign to a communicator
* Let `MPI_Cart/Graph*_get` functions return associated topology information instead of tying them to the arguments passed to the specific `MPI_Cart/Graph_create` calls.

# Changes to the Text

PR: https://github.com/mpi-forum/mpi-standard/pull/285

# Impact on Implementations
Behavior of implementation clarified.

# Impact on Users
Behavior of implementation clarified.

# References
PR: https://github.com/mpi-forum/mpi-standard/pull/285
The latest PDF: [mpi40-report.pdf](https://github.com/mpi-forum/mpi-issues/files/5495643/mpi40-report.pdf)
The latest PDF with changemarks: [mpi40-report_fix-undefined-mpi-cart-get-behaviour-2020-11-05.pdf](https://github.com/mpi-forum/mpi-issues/files/5495629/mpi40-report_fix-undefined-mpi-cart-get-behaviour-2020-11-05.pdf)

**Comment by tonyskjellum** [comment]
@cniethammer : See comments about process under #311.  Thank you!

**Comment by wesbland** [comment]
Is this intended for MPI 4.0 or MPI 4.1?

**Comment by wesbland** [comment]
2020-12-07 Errata vote results

| Yes | 	No	| Abstain | 	Missed |	Result |
| --- | --- | --- | --- | --- |
| 29 |	3	| 0	| 0	| Passed |
