### ISSUE TITLE
Fix not precisely defined topology information for `MPI_Cart_sub`

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#315]
# Problem

The topology information associated with a Cartesian communicator created by a call to `MPI_Cart_sub` is not defined precisely in the text.

Note 1: There is only example 7.8 showcasing two possible outcomes - which leave out the question of periodicity.
Note 2: This is especially important to be included in addition to https://github.com/mpi-forum/mpi-issues/issues/314, which requires precise descriptions for topology information to be associated with a communicator by the creating call.

# Proposal / Changes to the Text

Add the following description:
> The topologies of the new communicators describe the subgrids.
> The dimensionality of the subgrids is the number of remaining dimensions, i.e. the number of true values in remain_dims.
> The dimensions of the subgrids are the remaining dimensions of the grid associated with the original communicator, i.e. the values of the original grid dimensions for which the corresponding entry in remain\_dims is true.
> The periodicity for the remaining dimensions in the new communicator is preserved from the original communicator.

# Impact on Implementations
Behaviour of implementation clarified

# Impact on Users
Behaviour of implementation clarified

# References
PR: https://github.com/mpi-forum/mpi-standard/pull/286
Latest PDF: [mpi40-report.pdf](https://github.com/mpi-forum/mpi-issues/files/5493335/mpi40-report.pdf)
Latest PDF with changemarks: [topol-clarify-mpi-cart-sub-comm-topo-assignment-2020-11-05.pdf](https://github.com/mpi-forum/mpi-issues/files/5493332/topol-clarify-mpi-cart-sub-comm-topo-assignment-2020-11-05.pdf)

**Comment by tonyskjellum** [comment]
@cniethammer , I am not repeating comments/requests from #311, I will work with you to get the WG home, and the get the PR process through that WG.  Thank you! Tony

**Comment by wesbland** [comment]
Is this for MPI 4.0 or MPI 4.1?

**Comment by cniethammer** [comment]
@RolfRabenseifner or @tonyskjellum could one of you label this for mpi-4.0

Chapter PDF with marked change is attached to the initial comment.

**Comment by wesbland** [comment]
2020-12-07 Errata vote results

| Yes | 	No	| Abstain | 	Missed |	Result |
| --- | --- | --- | --- | --- |
| 28 |	4	| 0	| 0	| Passed |
