### ISSUE TITLE
Consistent representation for info strings

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#318]
# Problem

Info strings (keys and values) have been represented in the standard as regular test with a sans serif face, similar to other constants in MPI. However, with the addition of the mpi_thread_support_level key and the associated values MPI_THREAD_SINGLE etc., we now have different objects (the integer value MPI_THREAD_SINGLE, defined in mpi.h and used in MPI_INIT_THREAD and the character string MPI_THREAD_SINGLE, returned as the value associated with the info key) with the *same* appearance in the standard.

This also breaks the indexing, though that could be worked around.  The real issue is the ambiguous appearance. The current text puts quotes around *only* the info values MPI_THREAD_SINGLE etc., which is also inconsistent with the rest of the standard.

# Proposal

The most natural fix is to represent a string as a string - the infokey/infoval macros can be changed to add quotes around the values, making it clear that they are strings.

# Changes to the Text

Info values and keys will appear with double quotes: e.g., "mpi_thread_support_level" instead of mpi_thread_support_level, and "MPI_THREAD_SINGLE" instead of either MPI_THREAD_SINGLE or ``MPI_THREAD_SINGLE'' 

# Impact on Implementations

None.

# Impact on Users

None.

# References

None

**Comment by wesbland** [comment]
@bosilca - Does this solution sound good to you?
