### ISSUE TITLE
Incorrect cross-reference

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#319]
# Problem

The new chapter on partitioned communication includes an incorrect cross reference

# Proposal

The chapter committee needs to review and correct

# Changes to the Text

I recommend something like changing
`The equal partitioning on send-side and receive-side example shown on page \ref{part-example1}`
with
`The equal partitioning on send-side and receive-side communication shown in Example~\ref{part-example1}`

# Impact on Implementations

None

# Impact on Users

None
# References

This error causes a failure for make checklatex .

**Comment by regrant** [comment]
Pull request https://github.com/mpi-forum/mpi-standard/pull/298 should resolve this.
