### ISSUE TITLE
Improper placement of figures and use of colors for text

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#320]
# Problem

There is an inline figure, which is both against the document style and is a problem waiting to happen - it depends on there being enough space on the page for the figure. This needs to use a figure, as is used everywhere else in the document.

# Proposal
In the Topology chapter, the following needs to be replaced:

```
On a Cartesian virtual grid, the buffer usage in a given 
direction \mpicode{d} with \mpicode{dims[d]==3} and \mpicode{1},
respectively during creation of the communicator is described 
in the following figure. 

\vspace*{2mm}
\centerline{\includegraphics[width=6.0in]{figures/cart_neighbor_allgather}}
\vspace*{1mm}%
```
and 

```
For a halo communication on a Cartesian grid, the buffer usage
in a given direction \mpicode{d} with  \mpicode{dims[d]==3} and  \mpicode{1}, 
respectively during creation of the communicator is described
in the following figure. 

\vspace*{2mm}
\centerline{\includegraphics[width=6.0in]{figures/cart_neighbor_alltoall}}
\vspace*{1mm}%
```

Instead, the graphics image must appear in a separate figure environment, with a caption and a \label, and the text in the example must use \ref to refer to the image.

Additionally,  the code example includes of an **inappropriate use of color**. This issue is also addressed by the second commit in the pull request.

This LaTeX code fails the make checklatex test, and causes all build checks to fail.

# Changes to the Text

Make the figures into figures, as is the style of the MPI standard.

# Impact on Implementations

None

# Impact on Users

None

# References

[mpi-report-issue320-PR312.pdf](https://github.com/mpi-forum/mpi-issues/files/5494246/mpi-report-issue320-PR312.pdf)
See dashed arrows in Figures 8.2 and 8.3 on pages 383 + 386 (pdf 423 + 436) and modified text in the paranthesis on page 387 (pdf 427, lines 7-9)

# Pull request

https://github.com/mpi-forum/mpi-standard/pull/304 and https://github.com/mpi-forum/mpi-standard/pull/312

**Comment by RolfRabenseifner** [comment]
Dear Bill,
I hope that I correctly solved both problems. I therefore updated title of both issue and PR and abstract of the issue.
I substituted the use of colors for the sendrecv calls by an additional sentence:

The first call to \mpicode{MPI_Sendrecv} implements the upper (blue) communication pattern in each diagram of Figure~\ref{fig:cart-neighbor-alltoall}, whereas the second call is for the lower (red) pattern.

I hope that now, both problems are resolved.
Best regards
Rolf

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Posted without comment:
https://www.nature.com/articles/s41467-020-19160-7
https://phys.org/news/2020-10-colours-science.html

**Comment by RolfRabenseifner** [comment]
pdf of the current version:
[mpi40-report_Issue320-PR304_v03.pdf](https://github.com/mpi-forum/mpi-issues/files/5487463/mpi40-report_Issue320-PR304_v03.pdf)
I plan to substitute the "blue" and "red" by "solid arrows" and "dashed arrows" in text and figures.

**Comment by RolfRabenseifner** [comment]
I added https://github.com/mpi-forum/mpi-standard/pull/304 to resolve the color problem by using solid and dashed arrows.
For consistency, I did it in both Figures 8.3 and 8.2 although the problem arised only in Fig. 8.3.
For simplicity, I directly decided to used dashed arrows (and not dotted). It seems to works fine.

**Comment by RolfRabenseifner** [comment]
[mpi-report-issue320-PR312.pdf](https://github.com/mpi-forum/mpi-issues/files/5494246/mpi-report-issue320-PR312.pdf)
See dashed arrows in Figures 8.2 and 8.3 on pages 383 + 386 (pdf 423 + 436) and modified text in the paranthesis on page 387 (pdf 427, lines 7-9)

**Comment by RolfRabenseifner** [comment]
Bill, something is wrong with the function index: The just produced (through the Azure pipline)
[mpi-report-issue320-PR312.pdf](https://github.com/mpi-forum/mpi-issues/files/5494246/mpi-report-issue320-PR312.pdf)
has lost most of the references in the function index.

**Comment by wgropp** [comment]
I'll have a look
