### ISSUE TITLE
Code examples improperly marked in the standard

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#325]
# Problem

Code examples should be marked so that the code checker can confirm that they at least compile - the information on this is in the instructions, and there are a zillion example in the document. The code checker has found many problems and helps ensure a higher quality document. I noted problems in binding-2.tex, but will need to review all of the other examples now.
In that chapter, many examples are marked with `%%SKIP` when they should be properly marked for the language etc.

# Proposal

Follow the instructions in instr.tex/pdf . If there are problems or questions, contact the document editor.

# Changes to the Text

No changes to the text.  The code checker uses structured comments.

# Impact on Implementations

None.

# Impact on Users

Improved quality of the document.

# References

This is covered in instr.pdf.

### Instructions

* Each committee chair should check the box when they're done. 
* All changes should be grouped into single PR which will be reviewed all at once.
  * The first author of the PR will create a new PR. All other authors will push to the first PR (instructions to be added when the first PR is created).
  * This PR should say that it `Fixes #228` in the description to automatically link it to this issue.

If there is nothing to do in your chapter, just check your box.

* [x] Front matter - @wgropp 
* [x] Introduction - @wgropp 
* [ ] #591
* [x] Point-to-Point - @Wee-Free-Scot  
* [ ] #592
* [ ] #593
* [x] Communicators - @GuillaumeMercier 
* [ ] #594
* [ ] #595
* [ ] #596
* [ ] #597
* [x] Process Creation - @hppritcha 
* [ ] #598
* [ ] #599
* [ ] #600
* [ ] #601
* [x] Deprecated - @RolfRabenseifner 
* [x] Removed - @RolfRabenseifner 
* [x] Backward Incompatibilities - @wesbland 
* [ ] #602
* [x] Bindings Summary - @RolfRabenseifner 
* [x] Change Log - @RolfRabenseifner

**Comment by RolfRabenseifner** [comment]
@wesbland Dear Wesley, https://github.com/mpi-forum/mpi-standard/blob/mpi-4.x/chap-topol/topol.tex lines 921-960 uses
> \begin{lstlisting}[language={[MPI]C}]
instead of
> \begin{verbatim}
as described in https://www.mpi-forum.org/docs/other/instr-2020-12-09.pdf page 23.

Is this example in topol.tex correctly tested?

Dito for topol.tex, lines 1317-1339, 1521-1540, 1870-1898, 2012-2040, 2113-2143, 2176-2196, 2301-2330, 2450-2478, 3225-3278, 3287-3324, 3335-3376, and 3384-3450

Are all 13 tests positiv?

**Comment by cniethammer** [comment]
@RolfRabenseifner See description and source of the `mpichk` tool:

```
# Several alternatives to verbatim are supported. These include
#  \begin{lstlisting}[language=xxx]
#     where xxx is C or Fortran, usually modified with [MPI], [MPI08], or
#     [MPI08dirs] (if a dialect is included, the form is
#     language={[dialect]language}, as in language={[MPI]C}
#  \begin{Verbatim}[options]
```
and so far for me examples in the topology chapter are tested by `mpichk` without errors.

**Comment by wgropp** [comment]
The current version of instr.pdf details the use of lstlisting instead of verbatim. As @cniethammer notes, mpichk understands this and properly tests the code examples.

**Comment by wesbland** [comment]
Closing this issue in favor of the chapter-specific ones.

**Comment by RolfRabenseifner** [comment]
> The current version of instr.pdf details the use of lstlisting instead of verbatim. As @cniethammer notes, mpichk understands this and properly tests the code examples.

@wgropp I loaded it from https://www.mpi-forum.org/docs/ and there is still the version from Dec 9, 2020.
