### ISSUE TITLE
MPI_T Errata: Scope of guarantees on variable information

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#33]
The MPI standard currently does not explicitly state whether or not it guarantees variable availability once MPI_T is finalized and potentially re-initialized again. The scope of the guarantees given needs to be clarified.

**Comment by mahermanns** [comment]
As discussed in the last meeting, I added text to define "MPI tool epochs" and referenced them at the places where variable scope is discussed. Corresponding text passages are highlighted in the attached file. [mpi32-report_issue_33.pdf](https://github.com/mpi-forum/mpi-issues/files/150868/mpi32-report_issue_33.pdf)

**Comment by kathrynmohror** [comment]
We discussed this in the Chicago Feb 2016 MPI Forum meeting, during the tools WG.

The consensus was that we don't need to add any text to address this.  The value of a variable can change at any time -- even 2 consecutive calls to cvar_read could return different values if someone else wrote a new value.

So: no guarantees are given about the read values.  No text to add here.
