### ISSUE TITLE
Environmental Management Chapter RC Review

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#337]
# Problem

These were discovered by @bgoglin during review:

### Section 9.3.4
In the definition of MPI_SESSION_SET_ERRHANDLER
"INOUT session" misses some text before "(handle)" on the right,
something like "session object (handle)".

same for MPI_SESSION_GET_ERRHANDLER

### Table 9.1: Error classes
The description of MPI_ERR_CONVERSION ends with a point while others don't.

In that table, some descriptions refer to function arguments by their usual names in the function prototypes (e.g. "disp" written in verbatim font for MPI_ERR_DISP, or locktype below, or session, size and datarep on next page) while other descriptions just use normal text for referring to that function argument (e.g. "count" or "dimension" in normal font, but not "displacement" instead of "disp"). I tend to think using the argument name from the function prototypes should only be used in text that is very close to the function definition, hence not here.

**Comment by wesbland** [comment]
I believe everything in this issue is addressed by https://github.com/mpi-forum/mpi-standard/pull/334

Is that correct @bosilca?

**Comment by bosilca** [comment]
Yes, all changes related to this issues are in there.
