### ISSUE TITLE
Process Management Chapter RC Review

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#338]
# Problem

@bgoglin and others found this during the RC review:

- [x]  Section 11.1 "in the presense of" -> presence ?
- [x]  Section 11.2.1 "While MPI initialization" -> "During MPI initialization"
- [x] Section 11.5 there's a use of process set named "mpi://world" should be "mpi://WORLD"
- [x] <s>Section 11.6.2 "cancelled" -> "canceled" at least according to websters </s>
- [x]  Section 11.10.2 another use of mpi://world rather than mpi://WORLD
- [x] Page 533 (482) line 29 and 30, two single quote characters in the uniform typeset should be replaced by a single double quote character.
- [x] Page 531 (491) line 25: For multithreaded applications, the
- [x] Page 540 (500) line 7: hard coded example name no longer matches example number, suggest changing to something that is not related to section number.

From @AOA-Mohammed (pages are PDF pages, not standard pages):

- [x] Page 574, line 2, “int main (int argc, char **argv)” … it is correct but not consistent with the other half of the example in page 573 line 8 “int main(int argc, char *argv[])”
- [x] Page 574, line 14, “while(!done)” … done is not defined, not updated inside the while loop to exit the loop.

striking the her comment as this is really a more general question for the entire standard about whether or not gender neutral pronouns should be used.

- [x] Page 574, line 44: may be a missing “:”
- [x] Page 576, line 4, “(End of advice to implementors.)” is on a new line … in most cases in the standard it is on the same last line of the advice not on a new line itself. Maybe check for consistency.
- [x] Page 576, missing ‘a’
  - [x] line 38, “Before a client and server connect, ” a server?
  - [x] line 41 a “server”
  - [x] line 42, “a parent and child” a child 
- [x] Page 577, line 6, “filehandle” -> file handle

From @mahermanns:
- [x] Page 481l. 16-17: is `IERROR` using the right font? is it using `\mpiarg{IERROR}`? 
- [x] Page 482. l. 27-30: are the double single quotes correct? Shouldn't it rather be "two backticks" and two single quotes to generate proper LaTeX quotes?

From @naughtont3 
Using PDF page number (not printed page num)
 - [x] Page 546, Line 32, extra `the`, "...used to [the] form the group..."
 - [x] Page 556, Lines 29-30, double quotes for "soft" and font are odd.
 - [x] Page 557, Lines 6-7, missing comma, "Of course[,] a program..."
 - [x] Page 560, Line 28,  usage "as for" in last sentence, "Error codes are treated as for ...".  Should this be "treated the same as ..." or "treated as ..."
 - [x] Page 562, Line 13, should this also state the bound?  I am not familiar with this Fortran syntax and not sure what the `10000` is providing in this example.
 - [x] Page 562, should example also include `stdio.h` since example includes `printf()` and `scanf()`?
 - [x] Page 569, Line 43, font face - should `(port_name, service_name)` be same font as in Line 39.
 - [x] Page 524, Lines 10-11, 11-12, 23-24.  line breaks between `provided = ...`, should these be tightend up or maybe change `=` to standard English like `is` - we decided to leave this alone for 4.0.  it is using correct latex per similar sectoins 
 - [x] Page 526, Line 22, missing comma: "active, i.e.[,] until..."
 - [x] Page 526, Line 32, missing text or stray "and"
 - [x] Page 529, Line 28, "To achieve this the function..." there is missing comma after "this", also a possible improvement might be to say,
    "To achieve this determination, the function..." (adds `determination,`)
 - [x] Page 541, Lines 14,20, and Page 542, Lines 6, Should the example be chang
ed to avoid returning negative value from `main`.  Suggestion to return `EXIT_FAILURE` since `stdlib.h` already included in example.
 - [x] Page 542, Line 15, extraneous newline at end of example

From Victor Eijkhout
- [x] various clarifications about when an application can use ```MPI_COMM_WORLD/SELF```
- [x] reference world process usage to the relevant section in chap-dynamic.

Other:
- [x] Page 479: l. 41/44/46: 'Dynamic Process Model' is italics while 'Session Model' and 'World Model' are not. Should we be consistent here?

## changes to leave till finished with other changes (since they are positional related)

- [x] Page 573, line 47, “Here is the client.” comes at the end of the page. Would be better to move to the next page with its code.
- [x] Page 577, line 48, “Fortran binding” comes at the end of the page. It would be better to move it to the next page to be together with the function.
- [x] Page 579, line 26 “(see below)” is on a new line
 - [x] Page 558, Line 48, "C binding" should appear on next page (not sure if possible to tighten LaTeX binding of text)

## Items that require more clarification

 - [x] ~~Page 560, Lines 32-33, inconsistent font usage for program arguments `ocean`, `-gridfile`, `ocean1.grd`, `atmos` and `atmos.grd`.~~
 - [x] ~~Page 553, LIS descriptions - should `root` be formatted as argument, like `command`? (occurs in description for command, maxprocs, info)~~

**Comment by hppritcha** [comment]
I notice the Queen's preference for how to spell the past tense of cancel is used 47 times in the current standard while the American variant is only used once.  So we'll stick to the Queen's preferred spelling - cancelled in the dynamic chapter.

**Comment by hppritcha** [comment]
related to mpi-forum/mpi-standard#351

**Comment by wesbland** [comment]
From @AOA-Mohammed (pages are PDF pages, not standard pages):

- [ ] Page 573, line 47, “Here is the client.” comes at the end of the page. Would be better to move to the next page with its code.
- [ ] Page 574, line 2, “int main (int argc, char **argv)” … it is correct but not consistent with the other half of the example in page 573 line 8 “int main(int argc, char *argv[])”
- [ ] Page 574, line 14, “while(!done)” … done is not defined, not updated inside the while loop to exit the loop.
- [ ] Page 574, line 31, “she will usually” ..maybe a gender neutral form such as, the user ?!
- [ ] Page 574, line 44: may be a missing “:”
- [ ] Page 576, line 4, “(End of advice to implementors.)” is on a new line … in most cases in the standard it is on the same last line of the advice not on a new line itself. Maybe check for consistency.
- [ ] Page 576, missing ‘a’
  - [ ] line 38, “Before a client and server connect, ” a server?
  - [ ] line 41 a “server”
  - [ ] line 42, “a parent and child” a child 
- [ ] Page 577, line 6, “filehandle” -> file handle
- [ ] Page 577, line 48, “Fortran binding” comes at the end of the page. It would be better to move it to the next page to be together with the function.
- [ ] Page 579, line 26 “(see below)” is on a new line

**Comment by wesbland** [comment]
From @mahermanns:

- Page 481:
    - [ ] l. 16-17: is `IERROR` using the right font? is it using `\mpiarg{IERROR}`?

- Page 482:
    - [ ] l. 27-30: are the double single quotes correct? Shouldn't it rather be "two backticks" and two single quotes to generate proper LaTeX quotes?

**Comment by wgropp** [comment]
On the quotes, yes, the double single quotes aren't correct, and these really should be a single unsigned double quote character. \dq (defined in mpi-user-macs.tex) will produce one.

**Comment by hppritcha** [comment]
> From @AOA-Mohammed (pages are PDF pages, not standard pages):
> 
> * [ ]  Page 573, line 47, “Here is the client.” comes at the end of the page. Would be better to move to the next page with its code.

we'll wait till all other changes come into the chapter as this type

> * [ ]  Page 574, line 14, “while(!done)” … done is not defined, not updated inside the while loop to exit the loop.

there's a place holder for all the other code that may go into a real application.  I think not explicitly setting done is fine.

> * [ ]  Page 577, line 48, “Fortran binding” comes at the end of the page. It would be better to move it to the next page to be together with the function.
> * [ ]  Page 579, line 26 “(see below)” is on a new line

These should also be fixed once we're confident no other changes will be made to the chapter.

**Comment by hppritcha** [comment]
> From @mahermanns:
> 
> * Page 481:
>   
>   * [ ]  l. 16-17: is `IERROR` using the right font? is it using `\mpiarg{IERROR}`?

I can't seem to locate this.

> * Page 482:
>   
>   * [ ]  l. 27-30: are the double single quotes correct? Shouldn't it rather be "two backticks" and two single quotes to generate proper LaTeX quotes?

Nor this one either. What's being quoted?

**Comment by tonyskjellum** [comment]
Yes that’s a misspelling :-) 

Anthony Skjellum, PhD
205-807-4968


On Dec 2, 2020, at 11:48 AM, Howard Pritchard <notifications@github.com> wrote:

﻿
related to mpi-forum/mpi-standard#351

**Comment by naughtont3** [comment]
Using PDF page number (not printed page num)
 - [ ] Page 546, Line 32, extra `the`, "...used to [the] form the group..."
 - [ ] Page 553, LIS descriptions - should `root` be formatted as argument, like `command`? (occurs in description for command, maxprocs, info)
 - [ ] Page 556, Lines 29-30, double quotes for "soft" and font are odd.
 - [ ] Page 557, Lines 6-7, missing comma, "Of course[,] a program..."
 - [ ] Page 558, Line 48, "C binding" should appear on next page (not sure if possible to tighten LaTeX binding of text)
 - [ ] Page 560, Line 28,  usage "as for" in last sentence, "Error codes are treated as for ...".  Should this be "treated the same as ..." or "treated as ..."
 - [ ] Page 560, Lines 32-33, inconsistent font usage for program arguments `ocean`, `-gridfile`, `ocean1.grd`, `atmos` and `atmos.grd`.   
 - [ ] Page 562, Line 13, should this also state the bound?  I am not familiar with this Fortran syntax and not sure what the `10000` is providing in this example.
 - [ ] Page 562, should example also include `stdio.h` since example includes `printf()` and `scanf()`?
 - [ ] Page 566, Lines 18-19, should the example be modernized from `IBM SP`?
 - [ ] Page 568, in MPI_COMM_CONNECT - There is no mention of `root` argument in the subsequent description, which seems odd since that kind of matters. Same for MPI_COMM_ACCEPT.  
 - [ ] Page 569, Line 43, font face - should `(port_name, service_name)` be same font as in Line 39.

**Comment by naughtont3** [comment]
Using PDF page number (not printed page num)
 - [ ] Page 521, Line 30, "While MPI initialization, the...",
               change to: "During MPI initialization, the..."
 - [ ] Page 522, Line 29-30: quotes/formatting on `1024` and `MPI_THREAD_SINGLE`
 - [ ] Page 524, Lines 10-11, 11-12, 23-24.  line breaks between `provided = ...`, should these be tightend up or maybe change `=` to standard English like `is`
 - [ ] Page 526, Line 22, missing comma: "active, i.e.[,] until..."
 - [ ] Page 526, Line 32, missing text or stray "and"
 - [ ] Page 529, Line 28, "To achieve this the function..." there is missing comma after "this", also a possible improvement might be to say,
    "To achieve this determination, the function..." (adds `determination,`)
 - [ ] Page 540, Line 7, example has incorrect example number `ex10_8` should be`ex11_81.
 - [ ] Page 541, Lines 14,20, and Page 542, Lines 6, Should the example be chang
ed to avoid returning negative value from `main`.  Suggestion to return `EXIT_FAILURE` since `stdlib.h` already included in example.
 - [ ] Page 542, Line 15, extraneous newline at end of example
 - [ ] Page 544, Table 11.1, should these be alpha sorted?  but probably good to keep the grouping

**Comment by hppritcha** [comment]
okay finally see what's going on with IERROR.  hard for my older eyes to see this.
the double parenthesis issue is already being addressed in PR 367.

**Comment by wgropp** [comment]
IERROR should not be mpiarg - that is for the Language-independent routines.  There are macros, carg and farg, for arguments to C and Fortran bindings of MPI routines respectively, though these are not currently used. I'll note that chap-inquiry uses \mpiarg{IERROR}, which needs to be changed.

**Comment by bosilca** [comment]
@wgropp PR mpi-forum/mpi-standard/pull/391 fixes the issue in the inquiry chapter.

**Comment by naughtont3** [comment]
>  [x] Page 560, Lines 32-33, inconsistent font usage for program arguments ocean, -gridfile, ocean1.grd, atmos and atmos.grd.

Note: Marking this as done as it appears correct when looking at LaTeX and after 2nd review of PDF.

**Comment by naughtont3** [comment]
> [x]  Page 553, LIS descriptions - should root be formatted as argument, like command? (occurs in description for command, maxprocs, info)

Note: Marking this as done as it is correct in LaTeX/PDF, and I misunderstood how binding macro was working.

**Comment by naughtont3** [comment]
@hppritcha FWIW, I used strike-through when marking off the two "Need more info" items.  This was to indicate no change was made/needed to mark the item done, i.e., the item was "invalid" (and done b/c of checkbox).

**Comment by wesbland** [comment]
@hppritcha I found an issue in the Info chapter that should have been in this chapter (missed it by a page). I'm not sure where you prefer it to be in the system above so I'll put it here and let you categorize.

- [ ] Page 479: l. 41/44/46: 'Dynamic Process Model' is italics while 'Session Model' and 'World Model' are not. Should we be consistent here?

**Comment by hppritcha** [comment]
@wesbland what did you have in mind for changing with this bullet?
```

 Section 11.2.1 in section discussing MPI_IS_THREAD_MAIN, the sentence starting with "In the case of applications using" needs to be reworked. This may need an errata reading.
 ```

**Comment by wesbland** [comment]
> @wesbland what did you have in mind for changing with this bullet?
> 
> ```
>  Section 11.2.1 in section discussing MPI_IS_THREAD_MAIN, the sentence starting with "In the case of applications using" needs to be reworked. This may need an errata reading.
> ```

Looking back through the history of this issue, it looks like that comment was originally made by @bgoglin. Maybe he can chime in here?

**Comment by hppritcha** [comment]
moved MPI 4.1 todos to issue #514.
