### ISSUE TITLE
RC issues in chap-topol found by Dan

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#343]
# Problem

(using printed page numbers from mpi40-rc-nov-20.pdf)

* [x] page 403 (lines 15-28): The code fragment is not identified as an example.
* [x] page 405 (line 7 or 8): "Multiply defined edges are" -> "Multiply-defined edges are"
* [x] page 405 (lines 41-42): what happens if `disp` is equal to zero?
* [n/a] page 412 (lines 8-24): The code fragment is not identified as an example.
* [x] page 413 (line 25): "defined as 1 (in C)" -> "defined as non-zero (in C)"
  [c.f. page 24 (lines 6-7):
  Logical flags are integers with value 0 meaning “false” and a non-zero value meaning “true.”
  in §2.6 C Binding Issues]
  Alternatively, "if the dimension is defined to be periodic."
* [n/a] pages 414-415 (lines 40-7): The code fragment is not identified as an example.
* [x] page 415 (line 4): Is `displs[k]*extent(recvtype)` correct even when `displs` is of type `MPI_Aint`?
* [n/a] pages 416-417 (lines 33-1): The code fragment is not identified as an example.
* [n/a] page 417 (line 1): widow/orphan control
* [x] page 417 (line 33): "defined as 1 (in C)" -> "defined as non-zero (in C)"
* [x] page 417 (lines 34-36): sendbuf and recvbuf (etc for all others) are in normal text font, should use \mpiarg macro
* [x] page 417 (lines 37-47): The code fragment is not identified as an example.
* [->4.1 ] page 417 (lines 37-47): formatting of example is skewy (wrong font size and weight, non-standard usage of underline, inconsistent space/no space between comment and code for tags, non-standard vertical gap to main text above and below)
* [x] page 417 (line 48): widow/orphan control
* [x] pages 417-418 (lines 48-1): usage of "upper" and "lower" is not quite right because some solid arrows are on exactly the same level as some dashed ones (the straight diagonal arrows are neither above nor below each other, and are in between the uppermost and lowermost arrows - the wrap-around arrows)
* [x] page 418 (line 5): "and dims[d] is equal to 0 or 1, then" this sentence is also true for 2, right?
* [x] page 418 (lines 9-10): this sentence mixes "must" and "shall" - change "must" to "shall"
* [n/a] pages 419-420 (lines 33-2): The code fragment is not identified as an example.
* [x] page 419 (lines 42-43): Is `sdispls[k]*extent(sendtype)` correct even when `sdispls` is of type `MPI_Aint`?
* [x] page 419 (line 47): Is `rdispls[k]*extent(recvtype)` correct even when `rdispls` is of type `MPI_Aint`?
* [n/a] page 420 (line 2): widow/orphan control
* [n/a] pages 421-422 (lines 45-12): The code fragment is not identified as an example.

**Comment by cniethammer** [comment]
> # Problem
> (using printed page numbers from mpi40-rc-nov-20.pdf)
> 
> page 403 (lines 15-28): The code fragment is not identified as an example.

This is part of example 8.6 starting on previous page (page 402 l. 44).

> page 405 (line 7 or 8): "Multiply defined edges are" -> "Multiply-defined edges are"

fixed

> page 405 (lines 41-42): what happens if `disp` is equal to zero?

0 is not specified as in the text page 405 l.33

> page 412 (lines 8-24): The code fragment is not identified as an example.

This is part of the definition and not an example

> page 413 (line 25): "defined as 1 (in C)" -> "defined as non-zero (in C)"
> [c.f. page 24 (lines 6-7):
> Logical flags are integers with value 0 meaning “false” and a non-zero value meaning “true.”
> in §2.6 C Binding Issues]
> Alternatively, "if the dimension is defined to be periodic."

fixed using first suggestion.

> pages 414-415 (lines 40-7): The code fragment is not identified as an example.

This is part of the definition and not an example

> page 415 (line 4): Is `displs[k]*extent(recvtype)` correct even when `displs` is of type `MPI_Aint`?

`displ[k]` is a displacement of elements and must therefore be multiplied with the extend of one element. The same is true for the normal routine and embiggned routine.

> pages 416-417 (lines 33-1): The code fragment is not identified as an example.

This is part of the definition and not an example

> page 417 (line 1): widow/orphan control

TODO ... 

> page 417 (line 33): "defined as 1 (in C)" -> "defined as non-zero (in C)"

fixed

> page 417 (lines 34-36): sendbuf and recvbuf (etc for all others) are in normal text font, should use \mpiarg macro

fixed

> page 417 (lines 37-47): The code fragment is not identified as an example.

This is part of example 8.10 starting on previous page (page 417 l.12 - 418 l.2).

> page 417 (lines 37-47): formatting of example is skewy (wrong font size and weight, non-standard usage of underline, inconsistent space/no space between comment and code for tags, non-standard vertical gap to main text above and below)

TODO ... maybe in MPI 4.1 as changing this will require new text

> page 417 (line 48): widow/orphan control

TODO ...

> pages 417-418 (lines 48-1): usage of "upper" and "lower" is not quite right because some solid arrows are on exactly the same level as some dashed ones (the straight diagonal arrows are neither above nor below each other, and are in between the uppermost and lowermost arrows - the wrap-around arrows)

TODO....
@dholmes-epcc-ed-ac-uk  Suggest to change
> The first call to MPI_Sendrecv implements the upper (solid arrows) communication pattern in each diagram of Figure 8.3, whereas the second call is for the lower (dashed arrows) pattern.

to

> The first call to MPI_Sendrecv implements the solid arrows communication pattern in each diagram of Figure 8.3, whereas the second call is for the dashed arrows pattern.

> page 418 (line 5): "and dims[d] is equal to 0 or 1, then" this sentence is also true for 2, right?

fixed to "1 or 2"

> page 418 (lines 9-10): this sentence mixes "must" and "shall" - change "must" to "shall"

fixed, using shall

> pages 419-420 (lines 33-2): The code fragment is not identified as an example.

This is part of the definition and not an example

> page 419 (lines 42-43): Is `sdispls[k]*extent(sendtype)` correct even when `sdispls` is of type `MPI_Aint`?

See `MPI_neighbour_allgatherv`

> page 419 (line 47): Is `rdispls[k]*extent(recvtype)` correct even when `rdispls` is of type `MPI_Aint`?

See `MPI_neighbour_allgatherv`

> page 420 (line 2): widow/orphan control

TODO ...

> pages 421-422 (lines 45-12): The code fragment is not identified as an example.

This is part of the definition and not an example

**Comment by cniethammer** [comment]
@dholmes-epcc-ed-ac-uk @wesbland @wgropp I'd like to recall the suggestion from https://github.com/mpi-forum/mpi-issues/issues/285 to prevent confusion with examples in case of page breaks, which we see here again.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
> @dholmes-epcc-ed-ac-uk @wesbland @wgropp I'd like to recall the suggestion from #285 to prevent confusion with examples in case of page breaks, which we see here again.

Approve x100%

**Comment by RolfRabenseifner** [comment]
Yes!! I would prefer the "Lightgray lines on top and bottom, with vertical ticks:"
https://github.com/mpi-forum/mpi-issues/files/4697966/mpi40-report-extopbottom.pdf 
The version with gray background my cause problems with figures within an example.
The versions "none" and "excorners" are too invisible for the reader.
Of course, the "fullframe" is also perfect:
https://github.com/mpi-forum/mpi-issues/files/4697956/mpi40-report-fullframe.pdf

**Comment by RolfRabenseifner** [comment]
All answered or resolved in Issue #405
