### ISSUE TITLE
I/O Chapter Intents are Unclear for Fortran

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#344]
# Problem

From @tonyskjellum:

> @jaegerj and I were [speaking]; he has seen (and I agree) that some of the Intents are wrong in the Fortran bindings in the I/O chapter. We also need a read on (pardon the pun) if file handles are INTENT(IN) when they in fact have indirect file pointers changing due to an API call. In other words, is it really true that the handle that is IN/OUT when it is fully opaque?  For instance, the handles that have * in C, and are filled in are fully OUT (e.g., requests coming out of MPI_Isend), but for an in argument like an fh, for an open file, are they purely IN because they don't literally change, or does it depend on whether the internals of state are altered because of the operation being invoked?

# Proposal

# Changes to the Text

# Impact on Implementations

# Impact on Users

# References

**Comment by tonyskjellum** [comment]
@RolfRabenseifner --have you addressed this under language bindings elsewhere?

**Comment by tonyskjellum** [comment]
See ticket #350; we are closing this one.
