### ISSUE TITLE
Introduction Chapter RC Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#345]
# Problem

From @abouteiller:

- [x] ### pdf 41, Chap 1.1, pp1:29-31

In a distributed memory communication environment in which the higher level… message-passing routines+++,+++ the benefits of standardization are particularly apparent (propose adding a comma at marker +++) 

- [x] ### pdf 41, Chap 1.1, pp1:35-36

The goal of the Message Passing Interface+++,+++ simply stated+++,+++ is to … 
(add commas)

- [x] ### pdf 44, Chap 1.4, pp4:13-14

propose removing “The major work of the current MPI Forum is the preparation of MPI-3.”; this is now obsolete.

- [x] ### pdf 45, Chap 1.8, pp 5:6-7

Missing “Sessions” in the enumeration of major additions to MPI-4.0. 

- [x] ### pdf 46, Chap 1.11, pp6:1

Missing bullet point "Partitioned communications”

- [x] ### pdf 46, Chap 1.11, pp6:16-18

Tool Support and Language bindings are in reverse order w.r.t. the chapter ordering in the TOC. Propose swapping them in this list.

- [x] ### pdf 46, chap 1.13, pp 6:47

Chapter 4 (partition comms) is missing from the bullet list

- [x] ### pdf 47, chap 1.13, pp7:5

MPI-3 adds nonblocking collective operations. +++ MPI-4 adds persistent nonblocking collective operations.+++

(add a mention of the addition of persistent colls).

# Proposal

# Changes to the Text

# Impact on Implementations

# Impact on Users

# References

**Comment by wesbland** [comment]
Further issues were raised by @RolfRabenseifner in #349

**Comment by wgropp** [comment]
Fixed with PR 452. For some reason, could not link this issue with the PR, so closing manually.

**Comment by abouteiller** [comment]
Looking good
