### ISSUE TITLE
Introduction Chapter RC Review Issues

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#349]
# Problem

RC Review - all references refer to the printed page numbers of
https://github.com/mpi-forum/mpi-forum.github.io/raw/master/docs/mpi-4.0/mpi40-rc-nov-20.pdf

For me (Rolf) it is not clear, whether these changes are partially errata or all chapter committee changes.

# Proposal

To change the inconsistencies, but also missing information, ... in Chapter 1. Introduction to MPI
- use *correct* program (used in MPI-2.2 and later) into *valid* program (used until MPI-2.1) 
- show all backward compatibility rules 

# Changes to the text that are needed for MPI-4.0
_________

** This one is needed for MPI-4.0:**

- [x] **Sect. 1.8, the sentence 5:3(-4)** should be deleted:
> The 2020 draft specification is expected to become the MPI-4.0 specification once all features have been merged.
_________

- [x] **Sect. 1.11, the list 5:43-6:18** is incomplete:
  - [x] - Done: After "• Point-to-point communication,"
  add   "• Partitioned point-to-point communication,"
  - [x] - Needed: Text "• Process creation and management,"
  should read "• Process initialization, creation and management,"

_________

- [x] **Sect. 1.13, 6:46**, add
> • Chapter 4, Partitioned Point-to-Point Communication allows for multiple contributions of data to be made, potentially, from multiple actors (e.g., threads or tasks) in an MPI process to a single communication operation. This chapter was added in MPI-4.0.
_________

- [x] **Sect. 1.13, 7:22** reads
> Chapter 11, Process Initialization, Creation, and Management, defines routines that allow for creation of processes.

but should read
> Chapter 11, Process Initialization, Creation, and Management, defines routines that allow for several approaches to MPI initialization, process creation and process management while placing minimal restrictions on the execution environment. MPI-4 adds a new Sessions Model. 
_________

- [x] **Sect. 1.13, 8:11-13** read (the general index is missing!)
> Several Index pages show the locations of examples, constants and predefined  handles, declarations of C and Fortran types, callback routine prototypes, and all MPI functions.

but should read
> Several Index pages show the locations of general terms and definitions, examples, constants and predefined handles, declarations of C and Fortran types, callback routine prototypes, and all MPI functions.
_________

# Changes to the text - proposals that may be delayed until MPI-4.1
_________
- [x] **Sect. 1.6, 4:35-37** reads
> In addition, the deprecated C++ bindings have been removed, as well as many of the deprecated routines and MPI objects (such as the MPI_UB datatype).

and the following sentence should be appended:
> Any valid MPI-2.2 program not using any of these removed MPI routines or objects is a valid MPI-3.0 program.

Comment by @RolfRabenseifner: This one can wait until MPI-4.1, because it is only a supplement to the existing text that it is more consistent to the style of the previous sections.
_________

- [x] **Sect. 1.7, 4:42-46** should be appended by
> Any valid MPI-3.0 program is a valid MPI-3.1 program. 

Comment by @RolfRabenseifner: This one can wait until MPI-4.1, because it is only a supplement to the existing text that it is more consistent to the style of the previous sections.
_________

- [x] **Sect. 1.8, 5:3-8** should be appended by
Any valid MPI-3.1 program is a valid MPI-4.0 program with the exception of backward incompatibilities listed in Chapter 18. 

Comment by @RolfRabenseifner: This one can wait until MPI-4.1, because it is only a supplement to the existing text that it is more consistent to the style of the previous sections.
_________

- ~~[ ] **Sect. 1.11, the list 5:43-6:18** is incomplete:~~
  - ~~[ ] - Nice to have: After "• One-sided communication,"~~
  add   "• A shared memory model within  one-sided communication,"
_________

# Impact on Implementations

None.

# Impact on Users

None.

# References

https://github.com/mpi-forum/mpi-forum.github.io/raw/master/docs/mpi-4.0/mpi40-rc-nov-20.pdf
nn:mm means page nn, line mm

**Comment by RolfRabenseifner** [comment]
Dear Bill, Martin, and Wesley,
I'm not sure, whether all are chapter committee changes.
If yes, then the errata flag is wrong.
If no, then the reading should be announced - latest tomorrow, Monday (and maybe with a PR)
Nevertheless, I expect, we should do a reading, because it should go into the second RC.
Best regards
Rolf

**Comment by wesbland** [comment]
I defer to the chapter committee on this one. I think there will be a number of these conversations going forward from the various reviews.

**Comment by wgropp** [comment]
These are all good things to discuss, but I don't think of all of them as essential for the 4.0 release. 

Clearly missing and needing to be fixed is a short description of Chapter 4 (Partitioned communication).  Sessions should be added to chapter 11.

**Comment by regrant** [comment]
@RolfRabenseifner @wgropp please see the pull request above (https://github.com/mpi-forum/mpi-standard/pull/406) for the section 1.13 missing text issue. I've run check latex on the intro chapter with this new text and it passes.

**Comment by RolfRabenseifner** [comment]
@wgropp wrote:
> These are all good things to discuss, but I don't think of all of them as essential for the 4.0 release.
> 
> Clearly missing and needing to be fixed is a short description of Chapter 4 (Partitioned communication). Sessions should be added to chapter 11.

Yes, I agree. Moreover, several of my issues were wrong. Therefore, I removed them from the abstract and report here my bugs:
__________
- [No] Sect. 1.3, 3:35-37 read
> It is to be emphasized that forward compatibility is preserved. That is, a valid MPI-1.1 program is both a valid MPI-1.3 program  and a valid MPI-2.1 program, and a valid MPI-1.3 program is a valid MPI-2.1 program.

but should read
> It is to be emphasized that forward compatibility is preserved. That is, a valid MPI-1.1 program is a valid MPI-1.2 program, a valid MPI-1.2 program is a valid MPI-1.3 program, a valid MPI-1.3 program is a valid MPI-2.0 program, and a valid MPI-2.0 program is a valid MPI-2.1 program. Consequently, a valid MPI-1.1 program is all, a valid MPI-1.2, 1.3, 2.0, and 2.1 program.

Comment by @RolfRabenseifner: No, because this section is only about "Background of MPI-1.1, MPI-1.2, and MPI-2.0". Therefore, the original text is correct.

- [No] Additionally, the follwowing sentence should be added
> A valid MPI-x.y program hereby means that it is correct and valid according to the MPI-x.y standard plus all errata that apply to this version of the standard.

[The MPI forum may remember MPI-2.2 page 433: https://www.mpi-forum.org/docs/mpi-2.2/mpi22-report-book.pdf#page=457 ]

Comment by @RolfRabenseifner: Same reason as above.

- [No] **Sect. 1.5, 4:22** reads
> • Any correct MPI-2.1 program is a correct MPI-2.2 program.

but should read
> • Any valid MPI-2.1 program is a valid MPI-2.2 program.

Comment by @RolfRabenseifner: No, because this section is only about "Background of MPI-2.2". Therefore, the original text is correct.

**Comment by RolfRabenseifner** [comment]
@wgropp Dear Bill, I revisited my review and sorted the issues in
- needed for MPI-4.0
- may be in MPI-4.1
- wrong issues in my opinion (removed from the abstract, still listed in https://github.com/mpi-forum/mpi-issues/issues/349#issuecomment-765495207)

I hope, that this revisiting and sorting is helpful.

Only to assist you, I'll produce a short PR for the "needed items for MPI-4.0". You may then use this PR, correct it, or do it by yourself with a different PR, just as you prefer.

Kind regards
Rolf

**Comment by RolfRabenseifner** [comment]
PR 508 https://github.com/mpi-forum/mpi-standard/pull/508 added the missing MPI-4.0 issues of the Issue #349.
PDF is [mpi40-report_Issue349_PR508_v01.pdf](https://github.com/mpi-forum/mpi-issues/files/5857270/mpi40-report_Issue349_PR508_v01.pdf)

**Comment by wgropp** [comment]
PR 508 is merged.  Can this be closed?

**Comment by RolfRabenseifner** [comment]
The MPI-4.0 parts are done.
The MPI-4.1 parts are not yet done nor have a final descision.
Therefore, I would keep this issue open for MPI-4.1.

**Comment by RolfRabenseifner** [comment]
I agree that these small things should be added for MPI-4.1.

I try to summarize (all references according to MPI-4.0) and recommend to add them:

- Section 1.6, add at the end:
  > Any valid MPI-2.2 program not using any of these removed MPI procedures or objects is a valid MPI-3.0 program.

- Section 1.7, add at the end:
  > Any valid MPI-3.0 program is a valid MPI-3.1 program.

- Section 1.8, add at the end:
  > Any valid MPI-3.1 program is a valid MPI-4.0 program with the exception of backward incompatibilities listed in Chapter 18.

All the rest mentioned above, I would not recommend.

**Comment by wesbland** [comment]
I've turned the comment from @RolfRabenseifner into a PR (https://github.com/mpi-forum/mpi-standard/pull/728). I'd rather not be the one reading this change @RolfRabenseifner. Can you take it from here?

**Comment by wesbland** [comment]
I'd also be ok with saying this is a chapter committee change if the chapter committee agrees on that (@wgropp, @RolfRabenseifner, @schulzm).

**Comment by RolfRabenseifner** [comment]
> I'd also be ok with saying this is a chapter committee change if the chapter committee agrees on that (@wgropp, @RolfRabenseifner, @schulzm).

@wesbland thank you for generating the PR. 
@wgropp if you agree, we can ask @schulzm for a third review and then handling it by the chapter committee.
I, personally, agree with handling it as chapter committee.

**Comment by wgropp** [comment]
I agree.

**Comment by RolfRabenseifner** [comment]
@schulzm Martin, please can you make a review of PR https://github.com/mpi-forum/mpi-standard/pull/728

If we all three agree (you, Bill, and I) then we can handle it as a chapter committee change (Bill and I already agreed) and then Bill can merge it.
