### ISSUE TITLE
Datatype Chapter RC Review Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#351]
# Problem

Raised by @hritzdorf: 

* Page 158: Page number 118:
  * lines 19-20: unnecessary line break before oldtype
* Page 175: Page number 135:
  * Line 9-10: unnecessary line break before oldtype

From @GuillaumeMercier:

* p 115, 5.1, Line 21-22: "point to point" => "point-to-point"?
Seems inconsistent with previous chapters.

From @RolfRabenseifner:

* Example 5.22, page 175 (printed number) line 38: a[200] instead of a[1000]
  Reason: for 1 int and a maximum of 200 floats one needs a maximum of 804 bytes + some possible header bytes.
  Therefore, buff[1000] should be enough. This example 5.21 does not use MPI_Pack_size. This is okay, because the next example (5.23)  will then teach how to unse MPI_Pack_size.

**Comment by bosilca** [comment]
@RolfRabenseifner  The example 5.22 is incorrect, as it does not set a value for i. Please check the associated PR to see the proposed solution.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@bosilca which is the associated PR for this issue? It does not seem to be linked from here.

**Comment by bosilca** [comment]
The PR is #333, I saw your approval. Thanks.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
I guess you mean PR 333: https://github.com/mpi-forum/mpi-standard/pull/333

**Comment by wgropp** [comment]
Line breaks will be corrected in PR 337.
The "point to point" vs "point-to-point" is a good catch, but is broader than just this chapter. There are just a few uses of "point to point" and I'll correct them in a separate PR.

**Comment by wgropp** [comment]
point-to-point corrected in PR 338

**Comment by bosilca** [comment]
@wgropp the changes for the point-to-point and for the argshort were already implemented and approved in mpi-forum/mpi-standard/pull/333. I will rebase my PR.
