### ISSUE TITLE
Contexts Chapter RC Review Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#352]
# Problem

Raised by @hritzdorf:
~~Page 417 : Page number 377: former argument name was not renamed to comm_name~~
* [X] ~~Line 16 : name should -> comm_name should~~
* [X] ~~Line 18 : in name -> in comm_name~~
* [X] ~~Line 19 : name [resultlen] -> comm_name[resultlen]~~
* [X] ~~Line 20:  name is padded -> comm_name is padded~~

Raised by @jaegerj :
* [x] ~~p.345[305] l.22:
'procedures" is used without the usual meaning that is presented in the Terms chapter. This mey be confusing. I suggest replacing this word by another one, such as 'algorithms' used on the previous sentence.~~
@jaegerj : I don't think it's confusing here, especially when you read the whole sentence. 
* [x] ~~p.346[306] l.14 -> 36
I am not sure to completely understand the formating of the text.
l.14: why is Communicators in bold font? if it is because is it an MPI construct, why Groups (l.25) is not in bold font?
l.14: this paragraph related to communicators is the only paragraph not starting with the form a paragraph title followed by a point.
It should start with "Communicators. Communicators (see...) encapsulated...", like for the Group paragraph l.25.~~
@jaegerj : at first glance, I'd tend to agree with you. But the more I read it, the more I think it's fine as it is now.
* [x] ~~p.347[307] l.14->16
The italic sentence "Users who are satisfied with this practice can plug  in MPI_COMM_WORLD  wherever..." is not very useful and actually wrong.
The remaining of the chapter presents at least two functions which a[]re very revelant to such user: MPI_Comm_size and MPI_Comm_rank.
I suggest to remove this sentence which is part of an "advice to users", so not normative.~~
@jaegerj : I tend to agree.
* [x] ~~p.347[307] l.32-33
In a text related to inter-communicators "A send in the local group is always a receive in the remote group, and vice versa". This sentence is very strange.
I think it means "A send in the local group shall always be matched with a receive in the remote group, and vice versa" or something along this line.~~
@jaegerj : agreed.
* [x] ~~p.347[307] l.47
"... an related manner..." It is either "...a related manner..." or "... unrelated manner...". From the context, I think it is the first possibility "... a related manner..."~~
* [x] ~~p .350[310] l.48
orphan "Fortran 2008 binding" at the end of the page~~
* [x] ~~p.354[314] l.27 and l.30
start of the sentence "all elements" should be "All elements" with a capital A, as for the "union" paragraph l.24.~~
* [x] ~~p.354[314] l.48
orphan "C binding" at the end of the page~~
* [x]  ~~P.345[305] l.28
"We refer the reader to [62] and [4]..." - usually, references are put in increasing order~~

More from @cniethammer:
* [x] ~~page 312 (lines 22-23): "communicator-building function" -> "communicator creation function"~~
* [x]  ~~page 314 (line 1): widow/orphan control~~
* [x] ~~page 314 (lines 34-35): unnecessary line break before "The new group ..."~~
* [x] ~~page 314 (line 40-41): "ranks" missing mpiarg formating~~
* [x] ~~page 314 (line 48): widow/orphan control~~
* [x] ~~page 315 (line 24): "ranks" missing mpiarg formating~~
* [x]  page 318 (line 4): new group -> \mpiarg{newgroup}
GM comment: no, it's fine as it is. 
* [x]  page 318 (line 25): session missing mpiarg formating
GM comment: no, its fine as it is.
* [x] page 319 (lines 5-9): Advice to implementers misses communicator creation functions from topology chapter
@cniethammer : I both agree and disagree. Yes, it's missing, but these functions are not part of this chapter.
It's just an advice (therefore non-normative) for the function that are described in the current chapter. Maybe
the same kind advice should be added in the relevant chapter? 
* [x] ~~page 321 (lines 42, ff.): MPI_Comm_split_type not listed~~
* [x] page 327 (Fig 7.1 and code example below): Confusing to me
    - why the border around "before" and "after"
 @cniethammer: why not? But I agree it doesn't serve a useful purpose. 
    - correspond input groups to the local_group in the code?
  @cniethammer : both the code example and the figure bear the same number but they don't relate to each other.
It doesn't to understand, but that's bad luck.
    - what show the arrows?
 @cniethammer: the links between old and new ranks.
* [x] page 328 (line 31): "group" missing mpiarg formating
GM comment: No, fine as it is.
* [x] page 330 (line 30): "key value zero for all ..." --- couldn't this be "key value the same for all ..." ?
@cniethammer: given the last sentence in the previous paragraph, I would even go further and remove
this sentence.
* [X]  ~~page 330 (line 34): "confict" -> "conflict"~~
* [x] page 331 (Fig 7.2):  Confusing to me
    - maybe improve by placing dots/processes at their original positions from "comm" in the "newcomm"s
 @cniethammer: Since these are new communicators, I think it's fine as is. But maybe we can see that for 4.1?
I don't think it's a dealbreaker for 4.0.
* [x] page 332 (Example 7.2): Confusing to me
    - isn't multiple_server_comm and multiple_client_comm the same except changed roles for local and remote group? Suggest to use better variable name
  @cniethammer: What is your suggestion? 
    - mention round robin client to server assignment in description (line 20, modulo operation in code)
  @cniethammer : I don't think it's necessary, the reading of the code is sufficient in my opinion.
* [x] page 333 (line 37-38): "---" should not be used in lists/description according to section 3.4 in the instructions document
GM comment: no fine as is: em-dash is not to be used to itemize but can be within text, which is the case here.
* [x] page 333 (line 47): "---" should not be used in lists/description according to section 3.4 in the instructions document
GM comment: see comment above
* [x] page 334 (line 10-11): No info key is provided -> ",i.e., MPI_INFO_NULL" ?
@cniethammer : yes, Martin also made the same comment. it should read "No info handle is provided".
* [X] ~~page 334 (line 44): widow/orphan control~~
* [X] ~~page 335 (line 5-10): 3x missing white spaces in code between comma and variables:~~
    - ~~...(MPI_COMM_WORLD, &rank);~~
    - ~~(info, "mpi_hw_resource_type", "NUMANode");~~
* [x]  page 335 (line 13): "---" should not be used in lists/description according to section 3.4 in the instructions document
GM comment: no, fine as is. see comment above.
* [x]  page 335 (line 17-18) "... with comm which utilize that specific ..." -> "... with comm that utilize this specific ..."
GM: @wgropp is a better which-hunter than me. Should be handled by issue 232 and it corresponding PR.
* [X] ~~page 335 (line 18-19): use of incorrect single dashes -> should be em dash "... instance---and ... type---are included ..."~~
* [x] pages 335 (line 47): Confusing to me "... sets the info key "mpi_hw_resource_type" for each MPI process in the group associated with a returned communicator ..." -> I imagine that this could be read also in the way, that the resource info is associated with the newcomm and could be obtained from it via MPI_Comm_get_info. I guess that it it shall only be set in the passed \mpiarg{info}, which is marked as inout.
GM comment:  yes, only the arg info is used, the hints of the communicator itself are not updated.
* [X] ~~page 337 (Fig 7.3): Missplaced, should be moved 1 page forward so it is closer to the text that references it~~
* [x]  page 337 (line 41): large whitespace between "indifferntly. The"
GM comment: there is only a single space in the te file.
* [X] ~~page 337 (line 43): add comma -> "... only one NUMANode, which corresponds to ..."~~
* [X] ~~page 338 (line 48): widow/orphan control~~

Raised by @besnardjb:
* [x] 305:21 `higher level` -> `higher-level` (already used at 115:39)
See comment below
* [x] 305:26 `floating point` -> `floating-point` (already used at 469:38)
See comment below
* [X] ~~307:47 `an related manner` -> `a related manner`~~
* [x] ~~309:20 `The source and destination of a message is` -> `The source and destination of a message are`~~
See comment below.
* [X] ~~312:10 `..the group members and group order is exactly the same..` -> `..the group members and group order are exactly the same..`~~

Raised by @TheMasterDirk:
- [x] I think the sentence at the end of Line 27 on page 325 (or 365 of 1121) should read "with the same group argument"  instead of "with the same group as argument" (remove the word "as" ).
GM comment: fine as it is.

From @devreal:
* [x]  ~~p. 306, line 32 message passing -> message-passing~~

From @jdinan : 
* [x]  ~~mpi-forum/mpi-standard#380~~

**Comment by wgropp** [comment]
I agree with these changes. If the rest agree, I will create a PR for this fix.

**Comment by GuillaumeMercier** [comment]
@wgropp: I can do it if you want.

**Comment by wgropp** [comment]
@GuillaumeMercier that would be great.  I'm creating PR against mpi-4-rc; I can apply the ones that are approved by the Forum to the mpi-4.x branch.

**Comment by GuillaumeMercier** [comment]
Wow. That was fast!

**Comment by wesbland** [comment]
More issues from @jaegerj:

* p.345[305] l.22:
'procedures" is used without the usual meaning that is presented in the Terms chapter. This mey be confusing. I suggest replacing this word by another one,
such as 'algorithms' used on the previous sentence.


* p.346[306] l.14 -> 36
I am not sure to completely understand the formating of the text.
l.14: why is Communicators in bold font? if it is because is it an MPI construct, why Groups (l.25) is not in bold font?
l.14: this paragraph related to communicators is the only paragraph not starting with the form a paragraph title followed by a point.
It should start with "Communicators. Communicators (see...) encapsulated...", like for the Group paragraph l.25.

* p.347[307] l.14->16
The italic sentence "Users who are satisfied with this practice can plug  in MPI_COMM_WORLD  wherever..." is not very useful and actually wrong.
The remaining of the chapter presents at least two functions which a[]re very revelant to such user: MPI_Comm_size and MPI_Comm_rank.
I suggest to remove this sentence which is part of an "advice to users", so not normative.

* p.347[307] l.32-33
In a text related to inter-communicators "A send in the local group is always a receive in the remote group, and vice versa". This sentence is very strange.
I think it means "A send in the local group shall always be matched with a receive in the remote group, and vice versa" or something along this line.

* p.347[307] l.47
"... an related manner..." It is either "...a related manner..." or "... unrelated manner...". From the context, I think it is the first possibility "... a related manner..."

* P.350[310] l.48
orphan "Fortran 2008 binding" at the end of the page

* p.354[314] l.27 and l.30
start of the sentence "all elements" should be "All elements" with a capital A, as for the "union" paragraph l.24.

* p.354[314] l.48
orphan "C binding" at the end of the page


Cosmetic change: 

* P.345[305] l.28
"We refer the reader to [62] and [4]..." - usually, references are put in increasing order

**Comment by wesbland** [comment]
More from @cniethammer:

- page 312 (lines 22-23): "communicator-building function" -> "communicator creation function"
- page 314 (line 1): widow/orphan control
- page 314 (lines 34-35): unnecessary line break before "The new group ..."
- page 314 (line 40-41): "ranks" missing mpiarg formating
- page 314 (line 48): widow/orphan control
- page 315 (line 24): "ranks" missing mpiarg formating
- page 318 (line 4): new group -> \mpiarg{newgroup}
- page 318 (line 25): session missing mpiarg formating
- page 319 (lines 5-9): Advice to implementers misses communicator creation functions from topology chapter
- page 321 (lines 42, ff.): MPI_Comm_split_type not listed
- page 327 (Fig 7.1 and code example below): Confusing to me
    - why the border around "before" and "after"
    - correspond input groups to the local_group in the code?
    - what show the arrows?
- page 328 (line 31): "group" missing mpiarg formating
- page 330 (line 30): "key value zero for all ..." --- couldn't this be "key value the same for all ..." ?
- page 330 (line 34): "confict" -> "conflict"
- page 331 (Fig 7.2):  Confusing to me
    - maybe improve by placing dots/processes at their original positions from "comm" in the "newcomm"s
- page 332 (Example 7.2): Confusing to me
    - isn't multiple_server_comm and multiple_client_comm the same except changed roles for local and remote group? Suggest to use better variable name
    - mention round robin client to server assignment in description (line 20, modulo operation in code)
- page 333 (line 37-38): "---" should not be used in lists/description according to section 3.4 in the instructions document
- page 333 (line 47): "---" should not be used in lists/description according to section 3.4 in the instructions document
- page 334 (line 10-11): No info key is provided -> ",i.e., MPI_INFO_NULL" ?
- page 334 (line 44): widow/orphan control
- page 335 (line 5-10): 3x missing white spaces in code between comma and variables:
    - ...(MPI_COMM_WORLD, &rank);
    - (info, "mpi_hw_resource_type", "NUMANode");
- page 335 (line 13): "---" should not be used in lists/description according to section 3.4 in the instructions document
- page 335 (line 17-18) "... with comm which utilize that specific ..." -> "... with comm that utilize this specific ..."
- page 335 (line 18-19): use of incorrect single dashes -> should be em dash "... instance---and ... type---are included ..."
- pages 335 (line 47): Confusing to me
    - "... sets the info key "mpi_hw_resource_type" for each MPI process in the group associated with a returned communicator ..." -> I imagine that this could be read also in the way, that the resource info is associated with the newcomm and could be obtained from it via MPI_Comm_get_info. I guess that it it shall only be set in the passed \mpiarg{info}, which is marked as inout.
- page 337 (Fig 7.3): Missplaced, should be moved 1 page forward so it is closer to the text that references it
- page 337 (line 41): large whitespace between "indifferntly. The"
- page 337 (line 43): add comma -> "... only one NUMANode, which corresponds to ..."
- page 338 (line 48): widow/orphan control

**Comment by wesbland** [comment]
More from @besnardjb:

## Typos (to my knowledge)

* 305:21 `higher level` -> `higher-level` (already used at 115:39)
* 305:26 `floating point` -> `floating-point` (already used at 469:38)
* 307:47 `an related manner` -> `a related manner`
* 309:20 `The source and destination of a message is` -> `The source and destination of a message are`
* 312:10 `..the group members and group order is exactly the same..` -> `..the group members and group order are exactly the same..`

**Comment by GuillaumeMercier** [comment]
> More from @besnardjb:
> ## Typos (to my knowledge)
> 
>     * [ ]  ~305:21 `higher level` -> `higher-level` (already used at 115:39)~

No, the context is different. It's used as an adjective at 115:39, not here.

>     * [ ]  305:26 `floating point` -> `floating-point` (already used at 469:38)

Same here.

>     * [ ]  307:47 `an related manner` -> `a related manner`

Ok; 

>     * [ ]  309:20 `The source and destination of a message is` -> `The source and destination of a message are`

Ok.

>     * [ ]  312:10 `..the group members and group order is exactly the same..` -> `..the group members and group order are exactly the same..`
Ok.

**Comment by wesbland** [comment]
One more from @TheMasterDirk:

- [ ] I think the sentence at the end of Line 27 on page 325 (or 365 of 1121) should read "with the same group argument"  instead of "with the same group as argument" (remove the word "as" ).

**Comment by GuillaumeMercier** [comment]
> One more from @TheMasterDirk:
> 
>     * [ ]  I think the sentence at the end of Line 27 on page 325 (or 365 of 1121) should read "with the same group argument"  instead of "with the same group as argument" (remove the word "as" ).

I would even remove the wotrd "that" just before:  "all processes in ~~that~~ \mpishortarg{group} must call ..."

**Comment by GuillaumeMercier** [comment]
From @devreal:
*[x] p. 306, line 32 message passing -> message-passing

**Comment by jdinan** [comment]
Proposed edits from review: https://github.com/mpi-forum/mpi-standard/pull/380

**Comment by GuillaumeMercier** [comment]
Other edit proposed by @jdinan: mpi-forum/mpi-issues/issues/383

**Comment by GuillaumeMercier** [comment]
> One more from @TheMasterDirk:
> 
>     * [ ]  I think the sentence at the end of Line 27 on page 325 (or 365 of 1121) should read "with the same group argument"  instead of "with the same group as argument" (remove the word "as" ).

@TheMasterDirk :On second thoughts, I think it's fine as is.

**Comment by GuillaumeMercier** [comment]
> Proposed edits from review: [mpi-forum/mpi-standard#380](https://github.com/mpi-forum/mpi-standard/pull/380)

@jdinan: PR done, waiting for editor approval and merge.

**Comment by wesbland** [comment]
@GuillaumeMercier is this issue done?

**Comment by GuillaumeMercier** [comment]
Nope, I'm actually working on it! A PR is coming to fix the last items.

**Comment by GuillaumeMercier** [comment]
I need to fix Christoph's last items too.
