### ISSUE TITLE
Topologies Chapter RC Review Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#353]
# Problem

Raised by @hritzdorf:

* [x] Page 441: Page number 401:
Lines 9-10: unnecessary line break before coords

* [x] Page 442: Page Number 402: (I don’t know whether this is intended)
Lines 18-19: edges[index[rank-1]] is split over 2 lines.

**Comment by cniethammer** [comment]
The line break on page 441/401 line 9-10 seems intentionally to me. The same text is used at other places in a separate paragraph, too. Also, there is a special `%mansplit` mark in the tex source at this place.

The line break on page 442/402 line 18-19 seems accidental and `\gb` or `\vlgb` are not doing a good job here. I would go for an `\mbox` here...

**Comment by wgropp** [comment]
The line break on 442/402 line 18-19 is not the best but acceptable. If breaking the expression across a line is not desired, it is better to put this in display mode. I'm going to leave these as is.

**Comment by wesbland** [comment]
@RolfRabenseifner This also needs to be double checked with #405.

**Comment by RolfRabenseifner** [comment]
All answered or resolved in Issue #405
