### ISSUE TITLE
LoF RC Review Issues

### ISSUE THREAD

**Issue by mknobi** [mpi-forum/mpi-issues#356]
# Problem

Figures are captioned inconsistently. Some have punctuation marks at the end, most doesn't. The ones with punctuation marks are: 8.1 - 8.7 and 12.1

**Comment by wgropp** [comment]
Good catch. This will be fixed with the PR that also addresses https://github.com/mpi-forum/mpi-issues/issues/357

**Comment by wgropp** [comment]
PR https://github.com/mpi-forum/mpi-standard/pull/343 addresses this issue.
