### ISSUE TITLE
LoT RC Review Issues

### ISSUE THREAD

**Issue by mknobi** [mpi-forum/mpi-issues#357]
# Problem

Tables are captioned inconsistently. Some have punctuation marks at the end, most doesn't. The ones with punctuation marks are: 12.1, 15.5, 15.6, and 17.2

**Comment by wgropp** [comment]
Another good catch. I'll update the instructions - they don't need to be consistent, but there are rules, and the ones with periods appear to violate those rules. Tables and Figures will be fixed by PR https://github.com/mpi-forum/mpi-standard/pull/343
