### ISSUE TITLE
Backward Incompatibilities Chapter RC Review Issues

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#358]
# Problem

If 4.0-RC 
 - Sect. 2.2, page 10 lines 9-10 is changed, i.e., the maximum MPI identifier is exetended from 30 (with PMPI 31) characters to a larger value,  and/or
 - Sect 2.2, an additional wording for the C specific function names ..._c (which are 2 characters longer) is added, and/or
 - Sec19.1.5, page 789 lines 44-45 is changed, i.e., the maximum Fortran specific procedure name (35 characters) is extended to a larger value,

then this must be mentioned as a **backward incompatibility**.  

This must be also mentioned in a change-log entry, i.e., Sections 2.2, 18.1, 19.1.5, and B.1.2 need to be consistently modified to fit to the final set of MPI-4.0 MPI procedure names and their specific procedure names in C and Fortran, reflecting the PMPI, _c, _f08ts.  

For more details, see issue https://github.com/mpi-forum/mpi-issues/issues/335, details on Chap. 2.2 pp 10:9

Concerning the removal of the name-length limit see issue https://github.com/mpi-forum/mpi-issues/issues/403 and PR 432 https://github.com/mpi-forum/mpi-standard/pull/432

# Proposal

Describe the ideas of the proposal.

# Changes to the Text

Describe the text changes here.

# Impact on Implementations

Describe changes that implementations will be required to make here.

# Impact on Users

Tools implementors may be affected from such non-backward compatible changes.

# References

See issue https://github.com/mpi-forum/mpi-issues/issues/335, see Details on Chap. 2.2 pp 10:9

Concerning the removal of the name-length limit see issue https://github.com/mpi-forum/mpi-issues/issues/403 and PR 432 https://github.com/mpi-forum/mpi-standard/pull/432

**Comment by wesbland** [comment]
I'm not sure why this is an incompatibility. This is certainly a change, but codes that worked previously will still work.

**Comment by wgropp** [comment]
Agreed. This is a change (for the change log) but not a backward incompatibility.

**Comment by RolfRabenseifner** [comment]
Are you sure? A tool that stores function names in a fixed size array with 30 characters per name must be modified. Therefore, it is not backward compatible for tools that rely on the sentence in Section 2.2.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
How does such a tool obtain the list of names?

A list generated from MPI-3.1 (or any previous version) will still work with any MPI-4.0 library but will not be complete (backwards compatible).

Attempting to update the tool by adding the new names without increasing the size of the array elements will not work (not forwards compatible) but that requires a change to the tool, which must be done correctly to obtain a useful result.

If there was an MPI procedure that returned all/some/each procedure name(s) and the size of its return parameter changed, then that would be a backwards incompatible change. However, we have no such MPI procedure to worry about.

**Comment by wgropp** [comment]
I agree with Dan - this is not a backward incompatibility because the tool would still work with any MPI 3.x code. It is expected that tools that need to work with MPI-4.x features, including longer function names, will need to be changed.

**Comment by RolfRabenseifner** [comment]
After the discussionand decision in the Forum meeting yesterday, Dec. 8, 2020,
- I reopen this ticket
- I want to provide the following text proposal that reflects the discussion with a rationale as we normally do after such controversial discussions and to prevent repeating such discussions every year:

> The limit for MPI identifiers was removed. Until MPI-3.1, MPI identifiers were limited to 30 characters (31 with the profiling interface). This was done to avoid exceeding the limit on some compilation systems.
> 
> _Rationale._ For Fortran, this limit was already relaxed for the Fortran specific function names, see Section 19.1.5, and the Fortran language specification .... allows 64 characters for internal and external names.
For C, the language specification .... allows internal names up to 64 characters, but requires only 31 characters to be significant for external names. With the release of MPI-4.0, most or nearly all compilers allow function names longer than 31 characters.Therefore, the restiction could be removed. In MPI-4.0, the longest internal name has 34 characters, the longest specific function name have 35 characters in C and 38 characters in Fortran. _End of rationale._

**Comment by hritzdorf** [comment]
For Fortran, the limit is 63 characters since Fortran 2003.

**Comment by wesbland** [comment]
This was resolved in https://github.com/mpi-forum/mpi-standard/pull/434
