### ISSUE TITLE
Change-log Chapter RC Review Issues

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#359]
# New entry is needed for

If 4.0-RC 
 - Sect. 2.2, page 10 lines 9-10 is changed, i.e., the maximum MPI identifier is exetended from 30 (with PMPI 31) characters to a larger value,  and/or
 - Sect 2.2, an additional wording for the C specific function names ..._c (which are 2 characters longer) is added, and/or
 - Sec19.1.5, page 789 lines 44-45 is changed, i.e., the maximum Fortran specific procedure name (35 characters) is extended to a larger value,

then this must be mentioned as a **backward incompatibility**.  

This must be also mentioned in a change-log entry, i.e., Sections 2.2, 18.1, 19.1.5, and B.1.2 need to be consistently modified to fit to the final set of MPI-4.0 MPI procedure names and their specific procedure names in C and Fortran, reflecting the PMPI, _c, _f08ts.  

For more details, see issue https://github.com/mpi-forum/mpi-issues/issues/335, details on Chap. 2.2 pp 10:9.
See also issue https://github.com/mpi-forum/mpi-issues/issues/358 on "Backward Incompatibilies chapter RC review issues"

Concerning the removal of the name-length limit see issue https://github.com/mpi-forum/mpi-issues/issues/403 and PR 432 https://github.com/mpi-forum/mpi-standard/pull/432 

# Section combining and sorting

See also https://github.com/mpi-forum/mpi-issues/issues/331

B.1 shall be "Changes from Version **3.1** to Version 4.0" and not from "3.2"
B.1.1 and B.2.1 shall be combined
B.1.2 and B.2.2 shall be combined
and the items in both sections should be **sorted** mainly according to the **first section** they refer to.

B1.2 Item 2, page 1031 line 44: reference may need an update when Sections 16.3 and 16.4 are combined to one Section 16.3.

B.2.2 item 2, page 1032 line 46 should read (adding the new combined Section 16.3)
| Section 3.8.4 on page 88 and Section 16.3 on page 772.

B.2.2 item 9, page 1033 line 25 should read (adding the new combined Section 16.3)
| Section 15.3.10, Table 15.7, and Section 16.3 on pages 766, 768, and 772.

B.2.2 item 16, page 1034 line 5 should read 
| Section 10 on page 471.

B.2.2 item 17, page 1034 line 10 should read (new combined Section 16.3 instead of Sect. 16.4)
| Section 10 on page 471 and Section 16.3 on page 772.

**Comment by hritzdorf** [comment]
Concerning #237: An index entry for semantics is created for Page Number 1031, Line 44. This was not done for Page Number 1073, Line 22; Page Number 1034, Line 18; Page Number 1042; Line 13 (and Page Number 1039, Line 4). Don't know whether this should be done consistently for Change log. In this case, "semantic" in Page Number 1034, Line 18 should be probably indexed with "semantics".

**Comment by wgropp** [comment]
Good catch.  Not every occurrence of a term need be indexed, and in particular, most uses in the change log should not be indexed, as the text is where readers should refer. My preference is to remove the indexing of most items in the change log, rather than add additional ones.

**Comment by RolfRabenseifner** [comment]
For procedures, constants, types and callbacks, the indexing of the change-log is important because you can find, when things were added, clarified or (e.g. in case of errata) changed. Especially for the new version, it is important to easily find whether a feature may be in the MPI standard, but not yet in the MPI-3.1 library, and at the same time to be able to use all the advantages you and others could implement in the MPI-3.1 parts of the MPI-4.0 standard.

**Comment by mahermanns** [comment]
@RolfRabenseifner @wgropp I am not sure what my action items are on this. Is this about the maximum length of identifiers that we discussed yesterday?

**Comment by RolfRabenseifner** [comment]
All resolved in Issue #405
