### ISSUE TITLE
Collective Communications Chapter RC Review Issues

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#360]
MPI 4.0 RC Section 6.13 page 272 line 29 reads
| The collective persistent API signatures include an MPI_INFO object in order to support
but should read (MPI_Info is a type; nevertheless, \const should be used to get the right reference in the *MPI Constant and Predefined Handle* index)
| The collective persistent API signatures include an MPI_Info object in order to support

**Comment by wgropp** [comment]
I agree that MPI_INFO isn't correct.  But neither is MPI_Info. Elsewhere in the standard, we use simply "info object". Those aren't indexed, and I do not believe this occurrence should be indexed either.

**Comment by wgropp** [comment]
I can make a PR to change this to info object.  What does the chapter committee think?

**Comment by tonyskjellum** [comment]
No objection !! 

Anthony Skjellum, PhD
205-807-4968


On Nov 30, 2020, at 8:53 PM, William Gropp <notifications@github.com> wrote:

﻿
I can make a PR to change this to info object. What does the chapter committee think?

**Comment by wgropp** [comment]
Done. PR 348
