### ISSUE TITLE
Process Creation and Management Chapter RC Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#361]
# Problem

@artpol84 noted (and corrected) a number of issues in https://github.com/mpi-forum/mpi-standard/pull/351

Rather than listing them all here, the conversation can happen on the PR.

**Comment by wesbland** [comment]
More comments from @regrant:

Page 521 (481): Consider making the MPI_Init code a formal example, while pt2pt does this in the opening section, most other code snippets are defined as proper examples.

Page 521 (481) line 30: “While MPI initialization” -> During MPI initialization

Page 533 (482) line 29 and 30, two single quote characters in the uniform typeset should be replaced by a single double quote character.

Page 531 (491) line 9 & 10. Consider combining sentences as such “MPI_COMM_WORLD is not valid for use as a communicator and MPI_INFO_ENV is not valid for use as an info object when only using the Sessions Model”

Page 531 (491) line 25: For multithreaded applications, the 

Page 540 (500) line 7: hard coded example name no longer matches example number, suggest changing to something that is not related to section number.

**Comment by hppritcha** [comment]
closing as dup of #338
