### ISSUE TITLE
RMA Chapter RC Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#362]
# Problem

Raised by @regrant:

- [x] Page 599 (559) line 17: info objects are not just hints anymore, so it should say hints/assertions. Also throughout this paragraph “hints” is used.

- [x] Page 599 (559) line 35: check use of nonblocking, under the semantics revision, I think this should be non-completing.

- [x] Page 611 (571) line 26: ( ending line spacing error

- [x] Page 614 (574) line 8: several minor line termination/spacing issues on this page with undefiled boxes

From @AOA-Mohammed (pages are PDF pages, not standard pages):

- [x] Page 581, line 34, “Message-passing” some instances are hyphenated and some are not throughout the document, such as on page 41, line 38, page 4 line 16, etc.
- [x] Page 582, line 6, “high-performance” some instances are hyphenated and some are not throughout the document, such as page 42, line 35 and page 42, line 42.
- [x] Page 590, line 5, “noncontiguous” some instances are hyphenated and some are not throughout the document, such as page 848, line 11 and page 821 line 35.
- [x] Page 591, line 30, “= 0” … maybe make “size = 0" on the same line
- [x] Page 593, line 48, “Fortran binding” is at the last line of the page and the function definition comes in the next page …maybe keep them on the page is better.
- [x] Page 594, line 5, “Attaches a local …” incomplete sentence, missing the subject, i.e., the function name
- [x] Page 595, line 11, “Detaches a previously .. ” -> MPI_WIN_DETACH detaches a previously …
- [x] Page 595, line 39, “Frees the window object …” -> MPI_WIN_FREE frees the window object

Raised by @gpapaure:
- [x] page 626,627 : figure 12.4 should be before § 12.5.1

- [x] page 631 : figure 12.5 is in the middle of MPI_Win_test bindings declaration, it may be better placed before

**Comment by wgropp** [comment]
The last 2 line spacings are as designed - we don't hyphenate routines or variables, and we choose to prefer a short line to terrible interword spacing (the other option).

**Comment by wesbland** [comment]
From @AOA-Mohammed (pages are PDF pages, not standard pages):

- [x] Page 581, line 34, “Message-passing” some instances are hyphenated and some are not throughout the document, such as on page 41, line 38, page 4 line 16, etc.
- [x] Page 582, line 6, “high-performance” some instances are hyphenated and some are not throughout the document, such as page 42, line 35 and page 42, line 42.
- [x] Page 590, line 5, “noncontiguous” some instances are hyphenated and some are not throughout the document, such as page 848, line 11 and page 821 line 35.
- [x] Page 591, line 30, “= 0” … maybe make “size = 0" on the same line
- [x] Page 593, line 48, “Fortran binding” is at the last line of the page and the function definition comes in the next page …maybe keep them on the page is better.
- [x] Page 594, line 5, “Attaches a local …” incomplete sentence, missing the subject, i.e., the function name
- [x] Page 595, line 11, “Detaches a previously .. ” -> MPI_WIN_DETACH detaches a previously …
- [x] Page 595, line 39, “Frees the window object …” -> MPI_WIN_FREE frees the window object

**Comment by devreal** [comment]
@regrant

> Page 599 (559) line 35: check use of nonblocking, under the semantics revision, I think this should be non-completing.

I cannot find the term `nonblocking` on page 599 of the current v4.x or v4-rc branch. Which procedures are you referring to? My understanding in general is that all RMA procedures are nonblocking:

```
Nonblocking procedure: An MPI procedure is nonblocking if it is incomplete and local.
```

**Comment by devreal** [comment]
> Page 581, line 34, “Message-passing” some instances are hyphenated and some are not throughout the document, such as on page 41, line 38, page 4 line 16, etc.

Fix posted in https://github.com/mpi-forum/mpi-standard/pull/382

**Comment by devreal** [comment]
> Page 590, line 5, “noncontiguous” some instances are hyphenated and some are not throughout the document, such as page 848, line 11 and page 821 line 35.

This is in the works, see https://github.com/mpi-forum/mpi-issues/issues/316

**Comment by devreal** [comment]
> Page 591, line 30, “= 0” … maybe make “size = 0" on the same line

IIRC, the document does not force the two parts to be on the same line.

**Comment by devreal** [comment]
> Page 594, line 5, “Attaches a local …” incomplete sentence, missing the subject, i.e., the function name
> Page 595, line 11, “Detaches a previously .. ” -> MPI_WIN_DETACH detaches a previously …
> Page 595, line 39, “Frees the window object …” -> MPI_WIN_FREE frees the window object

It is not uncommon in the document to not repeat the procedure name in the sentence following the interface defintion (see `MPI_Irecv` and `MPI_Get_count` for examples).

**Comment by devreal** [comment]
> Page 599 (559) line 17: info objects are not just hints anymore, so it should say hints/assertions. Also throughout this paragraph “hints” is used.

The only place I could find that uses the term `assertion` in the context of `info` objects is in the description of `MPI_Comm_create_from_group`. If this is an issue then it is a global one (esp. in Section 7.4.4, which uses `key` and `hints` but not `assertion`). However, the RMA chapter does not have info assertions so I think it's fine here.

**Comment by gpapaure** [comment]
- [x] page 626,627 :  figure 12.4 should be before § 12.5.1

- [x] page 631 : figure 12.5 is in the middle of MPI_Win_test bindings declaration, it may be better placed before

**Comment by devreal** [comment]
@gpapaure The figure placement is done by LaTeX and it seems that the figures you mention are too large to put two of them on the same page. That means we would have to shrink them to change the placement, which will make them harder to read. Their placement is not ideal but I don't think that warrants major reformatting.

**Comment by gpapaure** [comment]
@devreal I agree

**Comment by devreal** [comment]
All points here have been addressed or are not relevant (anymore). I will close this issue.
