### ISSUE TITLE
Datatype Chapter RC Review Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#363]
# Problem

Raised by @jjhursey:

 * p 160/120 (Line 26): The ", n arbitrary." is unclear and dangling. Should it be ", where n is an arbitrary integer value." ?
 * p 168/128 (Line 28-29): Maybe pedantic, but I think the parenthetical should read "In this example, we assume...". Thus not making a general statement about an assumption standard wide, but specific to this example. Further, I don't think the parenthesis are necessary here.
 * p 173/133 (Line 16): The link behind "See Example 5.7" links the user to PDF page 171 instead of PDF page 176 where Example 5.7 is located. Additionally the parenthetical should be part of the preceding sentence - "... set to 1 (See Example 5.7.)."
 * p 173/133 (Line 31): Remove period from the "Dimension not distributed" bullet to make it consistent with the two before it.
 * p 176/136 (Line 19): Bracket needs to be left-shifted by 4 spaces to align with the "else" and not the nested "if"
 * p 182/142 (Line 6): Should the example here be numbered? "Example: Instead of" be "Example 5.10: Instead of"

**Comment by wgropp** [comment]
PR 352 fixes the problem with referencing example (p 173/133).

**Comment by schulzm** [comment]
Additional review items:

- Page 148, line 31, “The newtype has the same committed state as the old oldtype. „ – may need to rephrase? What is committed state?
- Page 149, example 5.11: looks like code from one process, which is odd
- Page 149, line 41: “The use of such a datatype in a receive operation is erroneous. „ - this should probably be extended to all collectives, RMA, …
- Page 151, line 10-12: „if the OUT parameter cannot express the value to be returned (e.g., if the parameter is too small to hold the output value), it is set to MPI_UNDEFINED.“ – should this really be allowed for MPI_GET_ELEMENTS_X?
- Page 152, line 24-26: this seems too restrictive for C/C++ - malloced regions are not the same array, what about RMA windows?


Formatting changes address in PR 376 https://github.com/mpi-forum/mpi-standard/pull/376

- Page 144, line 46, comma before which
- Page 148, line 24, comma before which
- Page 148, line 35, “count > 1” over two lines
- Page 148, line 36, comma before which
- Page 150, line 2, comma before which
- Page 151, line 42: no comma
- Page 152, line 38: remove „A“
- Page 157, line 26: no comma
- Page 157, line 30: no comma
- Page 157, line 33: no comma
- Page 158, line 44: comma before which
- Starting on page 159, extra lines would be good between the different cases to make it more readable

Formatting issues for final pass:

- Page break 142/143 breaks prototype
- Page 154/155: page break odd
- Page 163, line 48, page break is odd

**Comment by bosilca** [comment]
1. It is defined few pages above that reference, in the `MPI_Type_commit` description.
1. It simply shows how to use these datatypes, it does not provide a working distributed code. The reader should imagine that the other process would need to follow the standard when posting the corresponding receives.
1. ok, receive might indicate a point-to-point operation. I have pushed a more open definition of what is erroneous.
1. not sure which text you are referring to.

PR mpi-forum/mpi-standard/pull/381 provides some fixes.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@bosilca is this issue now fully addressed or are there outstanding points to be dealt with later?

**Comment by bosilca** [comment]
The only thing left is the comment you made on the combiner PR. Once we have a resolution there, we can close this issue.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@bosilca Do you like the resulting look of the first one? Do you want me to do the rest of the combiners the same way?

**Comment by bosilca** [comment]
Sure, visually a single, contiguous line of text looks better than two parts separated by a table. If you want to fix the rest of the combiners the same way, you're more than welcome. Otherwise, I can take a stab in few hours.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
I created a pull request from my personal mpi-standard fork into yours (because I don't have write access to your repo).
If you accept it then your branch will be affected and that will automatically feed into the PR.

dholmes-epcc-ed-ac-uk:issue_363 -[agent:me;done]-> https://github.com/bosilca/mpi-standard/pull/1 -[agent:bosilca;todo]-> https://github.com/bosilca/mpi-standard/tree/issue/363 -[agent:auto]-> https://github.com/mpi-forum/mpi-standard/pull/381 -[agent:bill]-> https://github.com/mpi-forum/mpi-standard/tree/mpi-4-rc

**Comment by dholmes-epcc-ed-ac-uk** [comment]
> The only thing left is the comment you made on the combiner PR. Once we have a resolution there, we can close this issue.

@bosilca the latest commit that combines the sentence fragments for the combiner descriptions seems to have been merged into the canonical mpi-4-rc branch. Is this issue now completely complete? Can it be closed?
