### ISSUE TITLE
Removed interfaces chapter RC review

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#367]
From reviewing pages 775-776 in the Nov 2020 4.0 RC document:

* [x] p775 48: "There are no MPI-2 replacements" --> "There are no replacements."
* [x] p776 21: "and their MPI-2 replacements" --> "and their replacements".
* [n/a] p775 29 and p776: 4 and 26: three tables have left-justified column headings.  But many other tables in the doc (including one on p776 12) have centered column headings.  I don't have an opinion on which way they should be, but they should probably be consistent.
(See comment below)

**Comment by RolfRabenseifner** [comment]
Alternatives:
p775 48: There are no replacements in MPI-2 and later.
p776 21: ... and there replacements since MPI-2.
p775 29 and p776: 4 and 26: All double column tables in A.1 have left bound column headers, i.e., as in these three tables.

**Comment by wesbland** [comment]
@RolfRabenseifner Are these now being tracked in #405 as well?

**Comment by RolfRabenseifner** [comment]
All resolved in Issue #405
