### ISSUE TITLE
Language Bindings (partial) chapter RC review

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#368]
From reviewing pages 779-780 in the Nov 2020 4.0 RC document:

* [ ] p779 31, 37, and 41: I've long-thought that the "USE mpi_f08", "USE mpi", and "INCLUDE 'mpif.h'" were in the wrong font.  Shouldn't they be fixed-width instead of boldface?
* [ ] p780 1: "Compliant MPI-3 implementations..." --> "Compliant MPI implementations"
    * Meaning: this doc is MPI-4.0.  We're talking about the MPI implementation in this doc, which is 4.0.  If we only talk about MPI-3 implementations, this doesn't technically include MPI-3.1 or MPI-4.0.

**Comment by wgropp** [comment]
I agree with both.  Though there is some inconsistency in exactly how these are shown in text, but they are consistently in \code{}, which is a fixed-width font.

Good catch on the "Compliant MPI-3 implementations"!

**Comment by RolfRabenseifner** [comment]
Through Change-log and the rules about MPI_Get_version (can return from 1.1? until 4.0), and other wording in this standard, the better wording may be:
> p780 1: "Implementations compliant to MPI-3.0 and later providing a Fortran interface must provide one or both of the following:" 

or
> "Since MPI-3.0, compliant MPI implementations providing a Fortran interface must provide one or both of the following:"
