### ISSUE TITLE
Tools chapter problem: MPI_ERROR_CLASS _can_ be called early (4.0 RC review)

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#369]
In discussion with @mahermanns, @wesbland, and @dholmes-epcc-ed-ac-uk, we concluded that this issue is a definite problem -- more than a minor word smith that you're looking for in a RC review -- so it probably warrants its own issue.

p766 of the Nov 2020 4.0 RC document has the following rationale starting on line 46:

> Rationale.  All MPI tool information interface functions must return error classes, because applications cannot portably call MPI_ERROR_CLASS before MPI initialization to map an arbitrary error code to an error class. (End of rationale.)

This is no longer true: due to sessions, you _can_ call MPI_ERROR_CLASS very early in the process.

On the one hand, you could just remove this rationale.  But there is still the question of what to do with the restriction: is it ok for MPI_T functions to return error classes now?  🤷‍♂️

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Discussion that led to deciding this is a thorny issue:

> The MPI procedures that can be used before MPI is initialised are listed in Table 11.1 in chapter 11 (page 504 in the RC doc) --- MPI_ERROR_CLASS is listed there.

**Comment by mahermanns** [comment]
We discussed this in the WG, and we had consensus on just removing the erroneous rationale for 4.0 altogether and think about whether we want to actually relax restrictions now or provide a better rationale for the restriction (potentially bringing forth backwards compatibility)

**Comment by jsquyres** [comment]
Is there a PR for this that will be brought up in this week's MPI Forum meeting?

**Comment by mahermanns** [comment]
Unfortunately I don't have one ready today. I could come up with one for tomorrow though. (would that be in time for this meeting?)

**Comment by mahermanns** [comment]
As discussed in the meeting yesterday, I removed the now erroneous rational for MPI_T functions to return error codes. I will create a new ticket for MPI 4.1 to revisit the situation and discuss possible improvements.

**Comment by mahermanns** [comment]
I'll close this issue as the discussion on this should be continued on Issue https://github.com/mpi-forum/mpi-issues/issues/385
