### ISSUE TITLE
Environment Management Chapter RC Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#372]
- [x] p. 463-464 - The bounding box for Table 9.1 seems inconsistent between the two pages
- [x] p. 469, line 44 - "and carries no unnecessary baggage." - This is a very strange thing to say since it's almost certainly not true and is definitely opinion.

From @mahermanns:

Page 469:
- [x]  l. 3-4: IERROR has wrong font (should be typewriter)
- [x]  l. 7-13: The second part of this advice to users reads overly complicated and redundant.

**Comment by bosilca** [comment]
I don't see any inconsistency between the 2 tables. Can we have a more detailed comment about what is inconsistent ?

**Comment by wesbland** [comment]
> I don't see any inconsistency between the 2 tables. Can we have a more detailed comment about what is inconsistent ?

The second table has a much larger bounding box than the first table. I know the PDF is in "book form" so things move from left to right, but this one looks like it's bigger in both directions. Maybe @wgropp knows what I mean here.

**Comment by wgropp** [comment]
That's because the second table includes the error class MPI_ERR_UNSUPPORTED_OPERATION, which makes the first column much wider. LaTeX is also centering the table, so it the centerline moves as well. I don't see a problem here, though I can force the first table to have an equally wide first column - but that will then look odd because of the greater apparent gap between the first and second column.

**Comment by wesbland** [comment]
That makes sense. It's not a problem then. It just looked odd to me when I was reading through it, but if this is the intended formatting, then we're done.

**Comment by wesbland** [comment]
From @mahermanns:

Page 469:

- [ ]  l. 3-4: IERROR has wrong font (should be typewriter)
- [ ]  l. 7-13: The second part of this advice to users reads overly complicated and redundant.

**Comment by bosilca** [comment]
I am not sure how to track these page references on a document that changes with each merge.

1. Assuming you are referring to the IEEROR in the description of the function invocation for the error handler, the IERROR is tagged with the expected mpiarg command so it should be in the correct font.
1. The only 'Advice to users' I see around the page 469 are one or two line long, certainly not overly complicated. That being said I don't think that advice really belongs in the call error handler part, but should be instead clearly specified in the corresponding MPI object creation function.

While reading through to find the text pointed by these comments, I came across our awful explanation for the return of the `MPI_*_call_errhandler`. Here is what we say
> This function returns MPI_SUCCESS in C and the same value in IERROR if the error handler was successfully called
(assuming the process is not aborted and the error handler returns).

1. We have drastically different behaviors in C and Fortran. We could have returned the code updated by the callback in C, to have the same capabilities as in Fortran.
1. How do we fail to call an errhandler ? I don't think this is a behavior supported by MPI.
1. `assuming the process is not aborted and the error handler returns` is unclear and almost mysterious. Are we trying to cover the case where the errhandler calls `longjmp`?

**Comment by wesbland** [comment]
> I am not sure how to track these page references on a document that changes with each merge.

All page numbers are from the MPI 4.0 RC document published in November. Sometimes they're PDF pages and sometimes they're the page numbers in the corner though, so that part can be a bit confusing.

**Comment by wgropp** [comment]
Some people have taken to listing the pages as PDF/Document just to make it easier to reference.

**Comment by wesbland** [comment]
It seems to me the everything we're going to do on this issue has been addressed. @bosilca do you want to try to address the rest of this?

> While reading through to find the text pointed by these comments, I came across our awful explanation for the return of the `MPI_*_call_errhandler`. Here is what we say
> 
> > This function returns MPI_SUCCESS in C and the same value in IERROR if the error handler was successfully called
> > (assuming the process is not aborted and the error handler returns).
> 
> 1. We have drastically different behaviors in C and Fortran. We could have returned the code updated by the callback in C, to have the same capabilities as in Fortran.
> 2. How do we fail to call an errhandler ? I don't think this is a behavior supported by MPI.
> 3. `assuming the process is not aborted and the error handler returns` is unclear and almost mysterious. Are we trying to cover the case where the errhandler calls `longjmp`?

If so, I think this is something for MPI 4.1 and should have a new issue.

**Comment by bosilca** [comment]
I have no intention of fiddling with this anymore for the 4.0. If anybody's interested in working out a better version of the error handlers for the 4.1, one that maintains backward compatibility, I would love to see their PR.

**Comment by wesbland** [comment]
Fine with me. I'm going to close this issue then.
