### ISSUE TITLE
Info Chapter RC Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#373]
# Problem

- [x] p. 477, lines 36-38 - The text about interpreting the values of the info object every time are now buried in between sections in a way that's odd. Perhaps this text should move to a different part of the chapter?
- [x] p. 471 line 48: missing Oxford comma in "read, modified or freed".  (ADDED BY JSQUYRES DURING 10 DEC FORUM READING)
- [x] Page 475: l. 27: 'key' should be \mpiarg{key}

**Comment by wesbland** [comment]
- Page 475:
    - [ ] l. 27: 'key' should be \mpiarg{key}

- Page 479:
    - [ ] l. 41/44/46: 'Dynamic Process Model' is italics while 'Session Model' and 'World Model' are not. Should we be consistent here?

**Comment by wesbland** [comment]
I created a PR to address these here: https://github.com/mpi-forum/mpi-standard/pull/457.

The last two bullets above were trivial. 

> p. 477, lines 36-38 - The text about interpreting the values of the info object every time are now buried in between sections in a way that's odd. Perhaps this text should move to a different part of the chapter?

For this one, there was similar text earlier in the chapter. I combined the two statements to have the same coverage.

**Comment by schulzm** [comment]
This looks good and complete to me - the first item (the moved text) could probably benefit from a few more eyes or a quick discussion in the forum
