### ISSUE TITLE
TOC missing space for Section 11.10

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#374]
# Problem

Page 11: The spacing in the TOC for Section 11.10 is of (see screenshot below), maybe we can add some space there? (and for all other entries to keep them consistent)

![Screenshot from 2020-12-03 12-17-54](https://user-images.githubusercontent.com/10974502/101007775-d1081600-3561-11eb-88ce-1a7e4d6d9c9e.png)

**Comment by wgropp** [comment]
Fixed with PR 359

**Comment by devreal** [comment]
This has been fixed with https://github.com/mpi-forum/mpi-standard/pull/359 as mentioned by @wgropp. Closing.
