### ISSUE TITLE
Language Bindings Summary - Appendix A (partial) RC review

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#375]
From reviewing pages 859-884 in the Nov 2020 4.0 RC document:

* [x] p859 16: remove comma
* [x] p860 3: remove comma
* [x] p862 4: The text mentions `MPI_Op_create` (with lower case, not the upper-case language-neutral name), but then lists both the `int` version of the callback and the embiggened callback.  It is worth mentioning the embiggened callback and/or the embiggened `MPI_Op_create_c`.  Otherwise, it's a little confusing to see just the `MPI_Op_create` routine name and both the small and embiggened callbacks.
* [x] p863 41-44: `MPI_File_errhandler_function` is listed twice.  One of them should be removed.
* [x] p864 4-7: `MPI_Session_errhandler_function` is listed twice.  One of them should be removed.
* [x] p864 27-48: Similar issue with `MPI_Register_datarep` as with `MPI_Op_create` -- the embiggened callback prototypes are listed, but not explained at all.
* [x] p865 13: strange indent before `SUBROUTINE`
* [x] p865 43-48 - p866 1: `MPI_SESSION_CREATE_KEYVAL` does not exist (I confirmed this with @dholmes-epcc-ed-ac-uk).  This chunk of text should be removed.
    * This chunk of text is left over from a prior proposal, but was not included in the final 4.0.

**Comment by wesbland** [comment]
@RolfRabenseifner This needs to be combined with your #405 issue I think.

**Comment by RolfRabenseifner** [comment]
My apologies, I oversaw this ticket, i.e., the 4 open items need an additional PR.

**Comment by wesbland** [comment]
Please coordinate with @wgropp on whether there's still time to do that or not given that the deadline has passed.

**Comment by tonyskjellum** [comment]
Hi I will follow up circa 10pm est - traveling this pm - thx Tony 

Anthony Skjellum, PhD
205-807-4968


On Jan 13, 2021, at 2:11 PM, Wesley Bland <notifications@github.com> wrote:

﻿
Please coordinate with @wgropp on whether there's still time to do that or not given that the deadline has passed.

**Comment by RolfRabenseifner** [comment]
I implemented the changes in [PR497](https://github.com/mpi-forum/mpi-standard/pull/497)

**Comment by RolfRabenseifner** [comment]
All done - therefore closed.
