### ISSUE TITLE
Language Bindings partial 4.0 RC review

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#376]
- Page 808
    - [ ] l. 4-5: unusual use of italics. Should/could probably also be normal font
    - [x] l. 11: non-contiguous -> noncontiguous
    - [x] l. 20: non-contiguous -> noncontiguous
    - [x] l. 25: non-contiguous -> noncontiguous
- Page 809
    - [x] l. 47: non-contiguous -> noncontiguous
- Page 810
    - [x] l. 12: non-trivial -> nontrivial
    - [ ] l. 30: does **vector** have the right font and weight?
- Page 811
    - [ ] l. 13-14: arrays of interoperable derived type -> arrays of an interoperable derived type
- Page 812
    - [x] l. 20: non-standardized -> nonstandardized
- Page 816:
	- [x] l. 34: a MPI-3.0 -> an MPI-3.0
- Page 828:
    - [x] l.12 beyone what existed in MPI-4.0 <-- shouldn't this be MPI-3.1?
- Page 829:
    - [x] l. 33 The MPI initialization code need perform -> The MPI initialization code needs to perform

**Comment by puribangalore** [comment]
non-contiguous is used 9 times in the standard, 8 of which appear in Language Bindings chapter and once in the datatype chapter. 

non-standard is used 16 times across the standard and nonstandard is used 2 times in the Language Bindings chapter.

@wgropp will you be making such changes across the entire document or should I just fix this in this chapter?

**Comment by wgropp** [comment]
I've merged a PR addressing most non-xxx issues, leaving ones that common use still seems to use the hyphen.

**Comment by puribangalore** [comment]
OK. We can close this issue then. Thanks!
