### ISSUE TITLE
Env / Info / Process Mgmt. 4.0 RC partial review comments

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#377]
## Pages 469-494

- Page 469:
    - [ ] l. 3-4: IERROR has wrong font (should be typewriter)
    - [ ] l. 7-13: The second part of this advice to users reads overly complicated and redundant.
- Page 475:
    - [ ] l. 27: 'key' should be \mpiarg{key}

- Page 479:
    - [ ] l. 41/44/46: 'Dynamic Process Model' is italics while 'Session Model' and 'World Model' are not. Should we be consistent here?

- Page 481:
    - [ ] l. 16-17: is `IERROR` using the right font? is it using `\mpiarg{IERROR}`?

- Page 482:
    - [ ] l. 27-30: are the double single quotes correct? Shouldn't it rather be "two backticks" and two single quotes to generate proper LaTeX quotes?

**Comment by wesbland** [comment]
I'm going to separate these out by chapter and move them to existing issues.
