### ISSUE TITLE
Cleanup Bib Backward Refs

### ISSUE THREAD

**Issue by jdinan** [mpi-forum/mpi-issues#381]
# Problem

Section/page reference generated at the end of each bibliography entry are not labeled as "Section" or "Page" and are a little confusing. E.g. "7.4.2" and "1.2" below:

![Screen Shot 2020-12-06 at 9 33 17 PM](https://user-images.githubusercontent.com/3397618/101302833-a987a680-380a-11eb-8eb9-30c35bd0a53d.png)

# Proposal

Update formatting to minimally say "Section x.y.z". Might be nice to say "Referenced in Section x.y.z".

**Comment by wgropp** [comment]
These backrefs are a feature of the hyperref package. Due to other challenges with them, we've switched to using page numbers instead of sections. We can turn these off entirely if that is preferred.

**Comment by jdinan** [comment]
The backrefs are nice and it looks like the backref package can add "Pages" to go along with the number. But, it looks like there may be some tinkering needed because of the coupling between backref and hyperref.

**Comment by wgropp** [comment]
PR 450 fixes this.
