### ISSUE TITLE
Inter-Communicator Local/Remote Overlap

### ISSUE THREAD

**Issue by jdinan** [mpi-forum/mpi-issues#383]
# Problem

Page 352 of MPI 4.0 RC:

> Overlap of local and remote groups that are bound into an inter-communicator is
prohibited. If there is overlap, then the program is erroneous and is likely to deadlock. (If
a process is multithreaded, and MPI calls block only a thread, rather than a process, then
"dual membership" can be supported. It is then the user's responsibility to make sure that
calls on behalf of the two "roles" of a process are executed by two independent threads.)

The parenthetical is speculating on a possible extension to MPI that has ill-defined semantics, e.g. if collectives were to be performed on a communicator with overlapping local/remote groups. 

# Proposal

Delete the text in parenthesis.

# Changes to the Text

Keep this text only:
> Overlap of local and remote groups that are bound into an inter-communicator is
prohibited. If there is overlap, then the program is erroneous and is likely to deadlock.

# Impact on Implementations

None

# Impact on Users

Remove potentially confusing passage from the spec.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
IMHO, this hinges on the intention for "can be supported":
1) capability: it seems technically possible but it isn't really specified as currently supported functionality in this version of the MPI Standard, it's just sketched out as a curiosity
2) permission: if an MPI implementation chooses to support this optional functionality then here are the requirements for that support
3) instruction: if an MPI implementation and execution environment conforms to these conditions, then it is required to support this functionality

I suggest/guess that (1) was meant by the original author(s) and it therefore has no place in any version of the MPI Standard.

If (2) or (3) was/is meant, then it is very poorly defined and should be improved. Given the status of the RC procedure for MPI-4.0, such an improvement would be a full proposal for MPI-next. Should the existing inadequate text be left alone until it can be fixed properly? Or a note added to the effect "we're gonna fix this"? Or should this parenthesis be removed pending a future addition?

I favour excision without a plenary vote.

**Comment by wgropp** [comment]
IIRC, case 1 was the intent (gee, we could do something in this particular case) and removing it from the standard is the appropriate fix.

**Comment by GuillaumeMercier** [comment]
Should that be a CC Change or an errata?
