### ISSUE TITLE
Revise restriction for MPI_T functions to return error classes

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#385]
# Problem

Before MPI 4.0 and the introduction of sessions, `MPI_Error_class` was not in the set of functions callable before MPI initialization. Therefore, in MPI 3.0 we introduced the restriction on functions of the Tool Information Interface (MPI_T) to return error classes instead of error codes.

The rationale for this restrictions---which is not correct for MPI 4.0 onwards---has been removed without replacement.

This issue shall provide discussion ground for a suitable clarification of the situation.

# Proposal

tbd.

# Changes to the Text

tbd.

# Impact on Implementations

Depends on the solution we decide for.

# Impact on Users

Depends on the solution we decide for.

# References

- Issue in the 4.0 RC Process: https://github.com/mpi-forum/mpi-issues/issues/369
  - Corresponding PR: https://github.com/mpi-forum/mpi-standard/pull/396

**Comment by schulzm** [comment]
The non existence of error handling routines before Init was only part (or rather a side effect) of the use of error classes in MPI_T - the main goals were to have a more defined set of return values for tools to operate with and the non fatality in all cases, to not impact MPI operations of a tool return goes wrong. If I remember, we started with something completely new and then later said, might as well just call those error classes

**Comment by mahermanns** [comment]
@schulzm  Revisiting this after the Sep 2022 meeting, would you propose to leave the semantics as it is (apart from changes that are necessary to fulfill https://github.com/mpi-forum/mpi-issues/issues/542 and close this issue?

This would mean everything would stay the same for MPI_T function, always return something of `MPI_T_ERR_*` sorts. Correct?

**Comment by schulzm** [comment]
I think this is indeed resolved by 542 and we can probably close this one - the rationale should in any case be deleted, but this seems to have happened in 542 already

**Comment by mahermanns** [comment]
Closing this issue as it will be resolved by the fixes for #542.
