### ISSUE TITLE
Fix type for `MPI_T_event_dropped_cb_function` argument

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#388]
# Problem

MPI 4.0 introduced new functionality for the MPI Tool Information Interface (MPI_T).

The callback function `MPI_T_event_dropped_cb_function` receives a count argument, counting the number of dropped event invocations for a specific event type. (See [MPI 2020 Draft](https://www.mpi-forum.org/docs/drafts/mpi-2020-draft-report.pdf), pages 758-760) 

This argument (named `count`) is currently of type: `int`

```C
typedef void MPI_T_event_dropped_cb_function(int count,
                      MPI_T_event_registration event_registration, int source_index,
                      MPI_T_cb_safety cb_safety, void *user_data);
```

During discussion of embiggenment the argument for keeping this `int` over a conversion to `MPI_Count` was that if this would ever overflow, the user has other problems that an incorrect number of dropped events (clearly with 2^31-1 events dropped in one stretch, the measurement is garbled). At the same time, this count is also just of 'best-effort accuracy', kind of a 'lower bound', in case the implementation is not capable of observing/capturing all dropped events (See page 759, line 31-32).

This enables implementation to avoid overflowing, e.g., by just keeping this at `INT_MAX` once that is reached (and the rest just falls in the 'wasn't able to observe' pile.

However, in the 4.0 RC review the question came up (next to the `MPI_Count` suggestion) whether this should rather be an `unsigned int`, as negative values are not needed, allowing for accurately reporting more dropped events.

# Proposal

Fix to `unsigned int` before the MPI 4.0 release.

# Changes to the Text

https://github.com/mpi-forum/mpi-standard/pull/472

# Impact on Implementations

Change existing prototype implementations

# Impact on Users

Users can have know up to 2^32-1 events dropped, rather than 2^31-1.

# References

tbd.

**Comment by wesbland** [comment]
This seems like an errata to me. Apologies if I missed some of the discussion on this yesterday, but is that the expectation?

**Comment by mknobi** [comment]
That was discussed in the tools wg call last Thursday.

**Comment by mahermanns** [comment]
Yes, I will bring this up as an Erratum next meeting, hoping that this still finds its way into MPI 4.0.

**Comment by mahermanns** [comment]
During the MPI Forum we discussed this and decided that the savings in storage per registration is not really relevant in practice (as the number of registrations will impact measurement overhead much earlier than where *"number of registrations x 4 bytes"* becomes a problem. Following the credo of *least astonishment* here, we will therefore change this to `MPI_Count` as that would be expected for a `count` argument.

**Comment by mahermanns** [comment]
I implemented the change to the datatype in a separate branch off https://github.com/mpi-forum/mpi-standard/pull/409 to avoid a conflict. Once that is merged, I will rebase https://github.com/mpiwg-tools/mpi-standard/pull/9 off the mpi-4-rc in the main repo.

**Comment by wgropp** [comment]
I'm still awaiting reviews on https://github.com/mpi-forum/mpi-standard/pull/409 .

**Comment by mahermanns** [comment]
@wgropp Yes. I think they are not yet aware that they have a request for review. I reminded Rolf via email.

**Comment by mahermanns** [comment]
@wgropp As https://github.com/mpi-forum/mpi-standard/pull/409 is merged now, I created a new [PR#472](https://github.com/mpi-forum/mpi-standard/pull/472) that implements the change.

**Comment by mahermanns** [comment]
@wesbland @wgropp Just be be sure of the pending process. This will have to be announced as an Errata reading/vote on the next meeting, right?

**Comment by wesbland** [comment]
That may end up being unnecessary depending on what I end up with for how to organize the votes, but to be safe, yes, plan on announcing this.
