### ISSUE TITLE
Additional INTENT(IN) for callback parameters

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#396]
# Problem

During RC review, it was noted that some callback parameters have acquired `INTENT(IN)` in their Fortran bindings, which was not present in MPI-3.1; this is probably an incorrect/unintended addition/change.

# Proposal

Revert all occurrences.

# Changes to the Text

Removal of INTENT(IN): see F08 bindings for MPI_Datarep_register and MPI_Op_create

# Impact on Implementations

None - this change avoids unintended consequences/impacts for implementations.

# Impact on Users

None - this change avoids unintended consequences/impacts for users.

# References

Fixed by: https://github.com/mpi-forum/mpi-standard/pull/414

**Comment by jsquyres** [comment]
`MPI_Register_datarep` is an example to look at to see if there's an error in the Pythonization rendering code or if the error is out in the Python code embedded in the Latex:

1. The `MPI_Datarep_conversion_function` parameter is marked as `INTENT(IN)`, but
1. The `MPI_Datarep_extent_function` parameter is _not_ marked as `INTENT(IN)`.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@jsquyres there is a difference in Python kind "POLYFUNCTION" vs. "FUNCTION"

Next steps:
1) dive into the Python code to discover the coding difference that causes the visible effect
2) list all other uses of these two KINDs and determine which appearance is desired for each

**Comment by jsquyres** [comment]
Yes, there is a difference between the two: one has 4 more letters than the other.

![fozzie](https://user-images.githubusercontent.com/617316/101784256-49725800-3ac9-11eb-82a0-5eb394294f93.gif)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Task (2) results: POLYFUNCTION is used 3 times, FUNCTION is used once.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Task (1) results: POLYFUNCTION emits `{postfix}` but FUNCTION does not
"binding-tool/bindingf08.py" line 265 of 308

What is postfix?

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Task (1) further result:

``` Python
    if (kind == 'FUNCTION' and
            param['param_direction'] == 'in'):
        # ...Jeff does not remember why we do not specify
        # INTENT for FUNCTION (i.e., PROCEDURE) types, but we
        # don't...
        return ""
```
"binding-tool/bindingf08.py" line 205-210 of 308

**Comment by jsquyres** [comment]
I'm not sure about this.  My $0.02 is that we should remove `POLYFUNCTION` altogether and `s/POLYFUNCTION/FUNCTION/g`.  Yes, it's a slightly larger change, but it's still pretty small, and it prevents punting an issue down the road for Future Someone to handle.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@jsquyres

MPI_Datarep_conversion_function is POLYFUNCTION because it has been Embiggened and has two `typedef`s and two `ABSTRACT INTERFACE`s (one with `_c` and one without).

MPI_Datarep_extent_function is FUNCTION because it has not been Embiggened and has one `typedef` and one `ABSTRACT INTERFACE` (without `_c`).

**Comment by jsquyres** [comment]
Ok.  Then this PR is likely the correct fix.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Latest `cleandoc` PDF including the changes from this issue:
[mpi-report-ticket396-2020-DEC-14-cleandoc.pdf](https://github.com/mpi-forum/mpi-issues/files/5688709/mpi-report-ticket396-2020-DEC-14-cleandoc.pdf)
