### ISSUE TITLE
Hard to read code in Example 8.10 due to split caused by Figure 8.3

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#398]
# Problem

Figure 8.3 is placed inside Example 8.2 and splits the code at a page boundary with page flip making the actual code hard to read.

# Proposal

Move figure 8.3 before or after example 8.10 as it is properly referenced in the example text.

# Changes to the Text

None

# Impact on Implementations

None

# Impact on Users

Improved readability

**Comment by wgropp** [comment]
I don't see this is the most recent version of the RC. This may have been fixed by the change to encapsulate the examples. If I'm missing the problem, let me know by Jan 10th.  Otherwise, I'll close this.
