### ISSUE TITLE
MPI_MPI_INFO_GET / MPI_INFO_GET_VALUELEN deprecated but not moved out of normative text

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#399]
# Problem

MPI_MPI_INFO_GET / MPI_INFO_GET_VALUELEN deprecated, but it was not moved out of normative text into the deprecated chapter.

# Proposal

This should be fixed.

# Changes to the Text

tbd

# Impact on Implementations

Not any additional changes than those already decided on.

# Impact on Users

Not any additional changes than those already decided on.

# References

Insert any internal (other issues) or external (websites, papers, etc.) references here.

**Comment by wesbland** [comment]
This was fixed by https://github.com/mpi-forum/mpi-standard/pull/443
