### ISSUE TITLE
Remove advice about local MPI_COMM_FREE

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#4]
The advice to implementors for `MPI_COMM_FREE` mentions this:

> Though collective, it is anticipated that this operation will normally be implemented to be local, though a debugging version of an MPI library might choose to synchronize.

This text is confusing and somewhat meaningless as it basically removes the collective nature in advice. How the implementor chooses to have `MPI_COMM_FREE` is up to them as long as they implement the correct semantics.

**Comment by abouteiller** [comment]
I tend to think that this advice to implementors is somewhat useful in reminding that the spec does not command that COMM_FREE is a synchronization barrier (unlike say, WIN_FREE, which is).

**Comment by wesbland** [comment]
After more discussion, we decided to drop this issue.
