### ISSUE TITLE
Remaining Issues

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#400]
# Problem

Keeping Track of other items to be fixed for MPI 4.0 / Found during the Dec Meeting

* [x] MPI 3.2 in Table 2.1 (is this fixed with PR 402?)
* [ ] Fix spacing, if possible, before the C-Bindings heading (page 830) - STILL OPEN
* [x] Rolf to check on max length of Fortran identifiers (35?, 38?) - ASKED ROLF
* [x] Need changelog entry for RMA; in particular for locks being usable in all memory regions
* [x] Add comma after that on Page 773, line 44-47, chapter 16.4 - FIXED IN PR
* [n/a] INOUT Split Type, comments made by Wesley and Guillaume - can't find it anymore, let it go for now
* [x] Remove FROM_GROUP_STRINGTAG (Issue 382??? - adjust example on page 500)
* [ ] All CCs check history text in intro
* [x] Removing the length limits for C
* [x] Issue that needs to be added to Issue 280 (remove P2P after rank translate)
* [x] Fix the IN/INOUT item for info routines (with small fix now and new issue to cover MPI 4.1)
* [x] Intro text for backwards incompatibility chapter
* [x] Look at Diff for Collectives Chapter
* [x] Look at Diff for I/O Chapter
* [x] Sort changelog entries (at the end)
* [x] Rolf to talk to Martin Ruefenacht about Python Issues in Appendix A (regarding hyperlinks/references)
* [x] Datatypes chapter: "input datatype" should be "old datatype" again - FIXED IN PR
* [x] Decide on how to add space in datatype chapter between COMBINER tables
* [x] After binding for MPI_Cart_rank, remove "as they are used by the point-to-point routines"

Keeping Track of other items to be fixed for MPI 4.0 / Found after the Dec Meeting

* [x] PSET_NAME_LEN should have a minimum, too 
* [x] Fix first item in list when MPI_COMM_SPLIT_TYPE returns NULL communicator - first item "No info key is provided." seems wrong - ASKED GUILLAUME

**Comment by wesbland** [comment]
@schulzm I'm not sure how to track which, if any of these are being / have been addressed. Do you know about the status of any of this? Maybe we should discuss it during the virtual meeting on Friday, but it'll be to late to do anything about it if things aren't done.

**Comment by hppritcha** [comment]
FROM_GROUP_STRINGTAG issue was fixed via https://github.com/mpi-forum/mpi-standard/pull/400

**Comment by RolfRabenseifner** [comment]
Chapter 1, page 8: Chapter 17, Removed Interfaces, describes routines and constructs that have been
removed from MPI. Some of these were deprecated in MPI-2, and the MPI Forum
decided to remove these from the MPI-3 standard. **Others of these were deprecated
in MPI-3, and the MPI Forum decided to remove these from the MPI-4 standard.**

The highlighted sentence is completely wrong and should be removed.
Table 2.1 on page 23 and Chapter 17 does not show any deprecated feature inMPI-3.0 or 3.1 and also no removed stuff in MPI-4.0.

**Comment by wesbland** [comment]
> Chapter 1, page 8: Chapter 17, Removed Interfaces, describes routines and constructs that have been
> removed from MPI. Some of these were deprecated in MPI-2, and the MPI Forum
> decided to remove these from the MPI-3 standard. **Others of these were deprecated in MPI-3, and the MPI Forum decided to remove these from the MPI-4 standard.**
> 
> The highlighted sentence is completely wrong and should be removed.
> Table 2.1 on page 23 and Chapter 17 does not show any deprecated feature inMPI-3.0 or 3.1 and also no removed stuff in MPI-4.0.

This is a good point. Let's make this a new issue and make sure it gets fixed.

**Comment by GuillaumeMercier** [comment]
Fix first item in list when MPI_COMM_SPLIT_TYPE returns NULL communicator - first item "No info key is provided."
was addressed by PR 484 ( mpi-forum/mpi-standard/pull/484 ). It now has an issue attached to it (mpi-forum/mpi-issues/issues/430) so that @wesbland  can keep track of it.
