### ISSUE TITLE
Adjust RMA Chapter to New Terms or vice versa (and remove interims statement)

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#407]
# Problem

In MPI 4.0 we punted on terms in the RMA chapter - this needs to be fixed.

# Proposal

tbd.

# Changes to the Text

tbd.

# Impact on Implementations

Hopefully none

# Impact on Users

Hopefully none

# References

Insert any internal (other issues) or external (websites, papers, etc.) references here.

**Comment by wesbland** [comment]
Had a no-no reading on 2022-12-05

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-06.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 28
	<td> 0
	<td> 5
</table>

**Comment by wesbland** [comment]
This passed a [second vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-08.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 27
	<td> 0
	<td> 4
</table>
