### ISSUE TITLE
extend MPI_WIN_SYNC for Fortran

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#41]
# Problem

As noted in #40, there are serious issues with `MPI_WIN_SYNC`, particularly in Fortran.  The Fortran compiler is permitted to rearrange function calls that do not affect variables that may be the target of out-of-thin-air stores.

### Fortran

What prevents the compiler from transforming this
```
type(c_ptr) :: p
type(MPI_Win) :: w
call MPI_Win_allocate_shared(.., p, w)
do i=1,1000
  if (rank.eq.0) then
    ! assign i to p
    call MPI_Win_sync(w)
    call MPI_Send(to rank 1)
  else if (rank.eq.1) then
    call MPI_Recv(from rank 0)
    call MPI_Win_sync(w)
    ! reference i
  endif
enddo
call MPI_Win_free(w)
```
into
```
type(c_ptr) :: p
type(MPI_Win) :: w
call MPI_Win_allocate_shared(.., p, w)
do i=1,1000
  if (rank.eq.0) then
    ! assign i to p
    call MPI_Send(to rank 1)
  else if (rank.eq.1) then
    call MPI_Recv(from rank 0)
    ! reference i
  endif
enddo
if ((rank.eq.0).or.(rank.eq.1)) then
  call MPI_Win_sync(w)
endif
call MPI_Win_free(w)
```

# Proposal

Extend `MPI_WIN_SYNC` within Fortran 2008 to _add to it_ the features of `MPI_F_SYNC_REG` with respect to thwarting dangerous code rearrangements.  These functions cannot achieve the desired effect separately, as only by fusing them can the user pin `MPI_WIN_SYNC` with respect to data operations on a given variable, by virtue of adding that variable as the dummy argument.

Since Fortran does not have varargs (according to Hubert - Jeff will verify), it is possible that some codes may need to call this function multiple times, or we need to add multiple prototypes with enough optional arguments to meet the practical need.

This is not unlike the interface for GCC atomic intrinsics, although for different reasons.

# Changes to the Text

Describe the text changes here.

# Impact on Implementations

It is no harder than what is done for `MPI_WIN_SYNC` and `MPI_F_SYNC_REG` today.

# Impact on Users

MPI shared memory might become reliable from Fortran.

# References

GCC's [Built-in functions for atomic memory access](https://gcc.gnu.org/onlinedocs/gcc-4.4.5/gcc/Atomic-Builtins.html)

**Comment by RolfRabenseifner** [comment]
The Fortran Problems are resolved with MPI-3.0 through the use of 
   <TYPE>, ASYNCHRONOUS :: shared-window-variable
As long as the accompanying compiler does not support  Fortran TS 29113, then the MPI constant
MPI_ASYNC_PROTECTS_NONBLOCKING must be .FASLE. and the user has to issue additional calls to MPI_F_SYNC_REG for the shared-window-variable. This is correctly described in MPI-3.1 Example 11.21 on pages 468-469. 
Therefore, the precondition of this ticket is wrong and the ticket should be withdrawn.

**Comment by RolfRabenseifner** [comment]
The Fortran Problems are resolved with MPI-3.0 through the use of 
      some-fortran-type, ASYNCHRONOUS :: shared-window-variable
 As long as the accompanying compiler does not support Fortran TS 29113, then the MPI constant
 MPI_ASYNC_PROTECTS_NONBLOCKING must be .FASLE. and the user has to issue additional calls to MPI_F_SYNC_REG for the shared-window-variable. This is correctly described in MPI-3.1 Example 11.21 on pages 468-469. 
Therefore, the precondition of this ticket is wrong and the ticket should be withdrawn.

**Comment by jeffhammond** [comment]
Ah, so we say in MPI 3.1 that one cannot use shared-memory windows without a Fortran 2008 + TS 29113 compiler?

Your proposed solution of using `MPI_F_SYNC_REG` does not work, which is exactly the motivation here.  There is nothing that prevents the compiler from moving `MPI_WIN_SYNC` far away from `MPI_F_SYNC_REG` because they share no arguments, and the `win` argument in `MPI_WIN_SYNC` is not known to the compiler to be related to the loads and stores that need to be made consistent by such calls.

An alternative solution would be to require `MPI_F_SYNC_REG` to always perform a memory barrier.  That some Fortran folks will protest against that is why I have proposed a new function that fuses `MPI_WIN_SYNC` and `MPI_F_SYNC_REG`.

**Comment by RolfRabenseifner** [comment]
> Ah, so we say in MPI 3.1 that one cannot use shared-memory windows without a Fortran 2008 + TS 29113 compiler?

No, with TS29113, it is more elegant, i.e. MPI_F_SYNC_REG is no more needed.
Without TS 29113, one must Workaround with MPI_F_SYNC_REG.

To be optimal, now without TS 29113 and in the future with TS 29113, the recommendation is
- to always declare the asynchronously used variables as ASYNCHRONOUS, and
- between a memory access to an asynchronously used varable X and the use of X in an MPI Routine without X, there must be a call like
IF (.NOT.MPI_ASYNC_PROTECTS_NONBLOCKING) CALL MPI_F_SYNC_REG(X)

> Your proposed solution of using  MPI_F_SYNC_REG  does not work, which is exactly the motivation here. There is nothing that prevents the compiler from moving  MPI_WIN_SYNC  far away from  MPI_F_SYNC_REG  because they share no arguments, and the  win  argument in  MPI_WIN_SYNC  is not known to the compiler to be related to the loads and stores that need to be made consistent by such calls. 
In principle, the Memory barrier MPI_WNIN_SYNC must be surrounded by a MPI_F_SYNC_REG before and after the call. With that all Memory accesses due to assigments or expressions are before the MPI_F_SYNC_REG called before the MPI_WIN_SYNC, or after the MPI_F_SYNC_REG called after the MPI_WIN_SYNC. See example 11.21 on page 469.  

> An alternative solution would be to require  MPI_F_SYNC_REG  to always perform a memory barrier. That some Fortran folks will protest against that is why I have proposed a new function that fuses  MPI_WIN_SYNC  and  MPI_F_SYNC_REG .

Therefore, this is not needed.

**Comment by RolfRabenseifner** [comment]
> Ah, so we say in MPI 3.1 that one cannot use shared-memory windows without a Fortran 2008 + TS 29113 compiler?

No, with TS29113, it is more elegant, i.e. MPI_F_SYNC_REG is no more needed.
Without TS 29113, one must Workaround with MPI_F_SYNC_REG.

To be optimal, now without TS 29113 and in the future with TS 29113, the recommendation is
•to always declare the asynchronously used variables as ASYNCHRONOUS, and
•between a memory access to an asynchronously used varable X and the use of X in an MPI Routine without X, there must be a call like IF (.NOT.MPI_ASYNC_PROTECTS_NONBLOCKING) CALL MPI_F_SYNC_REG(X)


> Your proposed solution of using MPI_F_SYNC_REG does not work, which is exactly the motivation here. There is nothing that prevents the compiler from moving MPI_WIN_SYNC far away from MPI_F_SYNC_REG because they share no arguments, and the win argument in MPI_WIN_SYNC is not known to the compiler to be related to the loads and stores that need to be made consistent by such calls. 

In principle, the Memory barrier MPI_WNIN_SYNC must be surrounded by a MPI_F_SYNC_REG before and after the call. With that all Memory accesses due to assigments or expressions are before the MPI_F_SYNC_REG called before the MPI_WIN_SYNC, or after the MPI_F_SYNC_REG called after the MPI_WIN_SYNC. See example 11.21 on page 469. 

> An alternative solution would be to require MPI_F_SYNC_REG to always perform a memory barrier. That some Fortran folks will protest against that is why I have proposed a new function that fuses MPI_WIN_SYNC and MPI_F_SYNC_REG .

Therefore, this is not needed.

**Comment by jeffhammond** [comment]
Please tell me what prevents Fortran compilers from hoisting `MPI_WIN_SYNC` outside of the protecting `MPI_F_SYNC_REG` calls.  They have completely independent arguments.  You are not allowed to make an empirical argument.  You must show the specific lines in ISO Fortran 1977, 1990, 1995, 2003 and 2008 that make such compiler transformations illegal.

**Comment by RolfRabenseifner** [comment]
Dear Jeff,

Very simple: both are library calls and Fortran cannot analyse the content of
these calls, i.e., must expect that they modify an internal state,
and such modifications must be done in the given sequence.
Therefore, they must be called in the given sequence,
similar to two MPI_Send calls with different buffers.

Of course, an MPI library implementation must prevent
that the source code of the MPI library routines is available
in the Fortran mpi_f08 and mpi modules.
All MPI libraries are implemented as wrappers to C and
therefore this precondition is always given.

Best regards
Rolf

----- Original Message -----
> From: "Jeff Hammond" <notifications@github.com>
> To: "mpi-forum" <mpi-issues@noreply.github.com>
> Cc: "Rolf Rabenseifner" <rabenseifner@hlrs.de>, "State change" <state_change@noreply.github.com>
> Sent: Saturday, September 24, 2016 3:26:36 AM
> Subject: Re: [mpi-forum/mpi-issues] extend MPI_WIN_SYNC for Fortran (#41)

> Please tell me what prevents Fortran compilers from hoisting `MPI_WIN_SYNC`
> outside of the protecting `MPI_F_SYNC_REG` calls.  They have completely
> independent arguments.  You are not allowed to make an empirical argument.  You
> must show the specific lines in ISO Fortran 1977, 1990, 1995, 2003 and 2008
> that make such compiler transformations illegal.
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/mpi-forum/mpi-issues/issues/41#issuecomment-249336565

-- 
Dr. Rolf Rabenseifner . . . . . . . . . .. email rabenseifner@hlrs.de
High Performance Computing Center (HLRS) . phone ++49(0)711/685-65530
University of Stuttgart . . . . . . . . .. fax ++49(0)711 / 685-65832
Head of Dpmt Parallel Computing . . . www.hlrs.de/people/rabenseifner
Nobelstr. 19, D-70550 Stuttgart, Germany . . . . (Office: Room 1.307)

**Comment by jeffhammond** [comment]
Are you saying that the Fortran standard prohibits the reordering of subroutine calls with independent arguments?

Link-time optimization and interprocedural optimization both allow the compiler to analyze the contents of library calls.

While all MPI libraries today are implemented in C, the C memory model disallows out-of-thin-air stores, so if the Fortran compiler knows that MPI is implemented in C, it might actually have more license to hoist `MPI_WIN_SYNC`...

**Comment by jeffhammond** [comment]
Steve Lionel convinced me that I am wrong.
