### ISSUE TITLE
Decide on proper reference to prior MPI versions in the standard

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#410]
# Problem

In the 4.0 review, we noticed that references to prior versions of the standard vary greatly (e.g., references like "Since MPI 3.0")

Example we used during the MPI 4.0 review was on page 780 of the draft

# Proposal

Go over all mentions and decide on what should be in there - should we keep history as well or just talk about the current version?

# Changes to the Text

tbd

# Impact on Implementations

tbd

# Impact on Users

tbd

# References

Insert any internal (other issues) or external (websites, papers, etc.) references here.

**Comment by wesbland** [comment]
@wgropp @schulzm - Is this a problem we want to solve? If so, we need to put together some guidance for chapter committees to make these changes.

I was reading through the instructions document and it seems that we don't have a particularly relevant passage at the moment, though the section describing the macros for referencing MPI (e.g., `\mpiiii/`) are the closest.

**Comment by wgropp** [comment]
I can add guidance to be specific as to version unless the context clearly means all versions of MPI. I did just review the occurrences of "since" and I don't see a real problem. Unless there are some very specific examples, I believe this should be closed.

**Comment by wesbland** [comment]
I think I agree. I know there were some specific concerns when people say things like, "We introduce a new API..." since text like that becomes dated quickly, but I don't think that's what's being referred to here. I'm going to close this and let @schulzm reopen it if he thinks it's necessary.
