### ISSUE TITLE
Mixed Case is Sometimes Causing Function Index Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#416]
# Problem

Alphabetically, upper-case letters come before lower-case letters, which means that for some pages with functions that share many of the same first few words, the order of the index can be a little odd. For example:

<img width="481" alt="Screen Shot 2021-01-06 at 12 50 33 PM" src="https://user-images.githubusercontent.com/1561207/103808564-c7207980-501d-11eb-9c2c-33a882e96075.png">

# Proposal

The names of the `_c` functions should come directly after the non-embiggened function, regardless of case.

# Changes to the Text

See above

# Impact on Implementations

None

# Impact on Users

None

# References

None

**Comment by wesbland** [comment]
I'm not sure who the correct person is to address this. In my mind, this is a minor document editor issue, so I'll assign @wgropp for now. I'm also open to agreeing that this is fine.

**Comment by wgropp** [comment]
I'll take it.  The easy fix is to alphabetize without concern for case.  Ordering in a way that isn't alphabetical is harder (and the wrong choice, IMO). I'll do the easy fix for MPI 4.0.

**Comment by wesbland** [comment]
That's all I was looking for anyway. It would accomplish the same thing for the function index.

**Comment by wgropp** [comment]
In fact, it isn't the letter case that is the problem - these are ordered alphabetically now, ignoring case. I'll push my "fix" because it improves the formatting of the entries, but it doesn't change the order.

**Comment by wgropp** [comment]
PR 459 uses uppercase for the sort order.

**Comment by wesbland** [comment]
Yep...that makes sense. I guess it will just look a little odd for now. I guess we could consider something else in the future like having "subindices" or something (not sure what the correct term is when you have subtopics underneath other index entries. Something like this:

```
MPI_SEND    1
    MPI_Send_c    2
```

**Comment by wgropp** [comment]
The subindex is an interesting idea, and relatively easy to implement. I suggest a straw vote by the Forum after MPI 4.0 is done.

**Comment by wesbland** [comment]
I'll mark this for 4.1 then.

**Comment by wgropp** [comment]
The next step here is a straw vote from the forum on the subindex.

**Comment by wesbland** [comment]
Do you want to discuss this in a VM? Or should we make this a topic for the September meeting?

cc: @schulzm

**Comment by wgropp** [comment]
A VM is fine - just getting a straw vote would help - and in fact, an email straw vote might be more representative, particularly if it includes "don't care".

**Comment by wesbland** [comment]
You're probably right. Email makes the most sense.

**Comment by wgropp** [comment]
I'm just going to do this.  In reviewing the document, I found many erroneous uses of \mpifunc, and I think the fix is appropriate.
