### ISSUE TITLE
Incorrect non-2008 Fortran binding for MPI_BUFFER_DETACH

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#417]
# Problem

Page 57 §3.6 of MPI-4.0-RC
"
In Fortran with the \code{mpi} module or \code{mpif.h}, the type of the \mpiarg{buffer\_addr} argument is
wrongly defined and the argument is therefore unused.
"

# Proposal

We should fix the definition of the non-2008 Fortran binding.

# Changes to the Text

Any ideas?

# Impact on Implementations

Implementations can create a valid procedure that works as intended.

# Impact on Users

Users can use the functionality in non-2008 Fortran.

# References

Insert any internal (other issues) or external (websites, papers, etc.) references here.

**Comment by wgropp** [comment]
There's no way to implement this without a pointer - that's why the F08 binding uses ISO_C_BINDING C_PTR. And that would be the fix.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@wgropp so, you're saying that the pre-2008 Fortran binding is impossible to define correctly and is therefore guaranteed to be unimplementable as currently specified and utterly useless in its current form? In which case the fix is to remove it from the standard or to change its specification/form so that the useful part of its intended functionality (it will not return until the buffer is drained of all buffered mode send data) can be implemented correctly and subsequently relied on by users.

I suggest, for example, that the pre-2008 Fortran binding could have the buffer_addr parameter removed to make it clear to users & implementers that it cannot carry useful information. This is only just backward incompatible because any pre-2008 Fortran program currently using this procedure must define some random non-useful thing to pass in, must ignore the value of it after the call, and must keep an independent record of the location of the buffer that was attached. Deleting the argument from the call site would fix the compilation error and no other change would be required.

The standard should not include "this is a bear trap; please (don't) step here, just so---gotcha!"

**Comment by wgropp** [comment]
See the discussion of MPI_ALLOC_MEM - this has the same issue, and the pragmatic choice was to allow the use of non-standard features - admittedly beyond the scope of the standard.  See example 9.2, which describes the use of "Cray pointers" to implement MPI_ALLOC_MEM for the mpif/mpi module Fortran interface. The difference is that MPI_ALLOC_MEM exists only to return that pointer, whereas with MPI_BUFFER_DETACH, returning a pointer to the buffer is a secondary function.

I agree this is ugly. It is also something that has been in MPI from the beginning. And we haven't had users or implementors clamoring for a fix.

**Comment by Wee-Free-Scot** [comment]
I'm going to close this one without pushing for any change.
