### ISSUE TITLE
BUG in description of nonblocking point-to-point send completion

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#418]
# Problem

Page 59 lines 42-45, §3.7 Nonblocking communication
"
If the send mode is \mpitermdefni{standard}\mpitermdefindex{standard send mode!nonblocking} then the send-complete call may
return before a matching receive
is posted,
if the message is buffered.  On the other hand, the
receive-complete may not complete until a matching receive
is posted,
and the message was copied into the receive buffer.
"

This seems like a clear erratum: "receive-complete" should be "send-complete" here.

# Proposal

Fix the bug.

# Changes to the Text

Replace "receive-complete" with "send-complete" here.

# Impact on Implementations

Additional clarity.

# Impact on Users

Additional clarity.

# References

Fixed in MPI-4-RC by PR: https://github.com/mpi-forum/mpi-standard/pull/462
Fixed in MPI-3.x by PR: https://github.com/mpi-forum/mpi-standard/pull/463

**Comment by rsth** [comment]
No, it is correct. The last sentence describes what happens on the receiver side.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
No, it is telling the story of how the completion procedure at the sender process might be delayed until the starting procedure for the matching receive operation is posted and that operation has been matched with the send envelope and the data has been copied into the receiver's buffer, because (if it is not buffered in some other way) that is the only way to clear the sender's buffer so that the sender can re-use it, which is needed for the sender's completion procedure to guarantee the required blocking semantic.

The first sentence says "this call might sometimes act like it is local" but the second sentence says "however, sometimes this call depends on an MPI procedure call at another MPI process, which makes this call non-local".

The fact that the receive-complete call must not return before the data has arrived is given explicitly elsewhere and need not be repeated here.

**Comment by rsth** [comment]
Yes, you are right. I misread it. How did this typo get introduced in MPI-3? It was not there in MPI 2.2 (and hence not in MPI-1). Someone must have tried to correct what they thought was an error, and now we are fixing it back.

**Comment by wgropp** [comment]
I believe this is done, merged into both MPI 3.x and mpi-4-rc

**Comment by dholmes-epcc-ed-ac-uk** [comment]
I concur.
