### ISSUE TITLE
Incorrect usage of operation when procedure is intended

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#419]
# Problem

It is incorrect to refer to MPI_WAIT as an operation---it is a procedure.
It is incorrect to refer to MPI_TEST as an operation---it is a procedure.
Edit: It is incorrect to refer to MPI_REQUEST_FREE as an operation---it is a procedure.
Edit: Included several other instances.

# Proposal

Fix the incorrect usage of terms.

# Changes to the Text

§3.7.3 MPI_WAIT and MPI_TEST

Change (page 69, lines 37-38)
"MPI_WAIT is a non-local operation."
to
"MPI_WAIT is a non-local procedure."

Change (page 69, lines 43-44)
"In this case the operation returns immediately with empty status."
to
"In this case the procedure returns immediately with empty status."

Change ()
"MPI_TEST is a local operation."
to
"MPI_TEST is a local procedure."

Change ()
"In such a case the operation returns with flag = true and empty status."
to
"In such a case the procedure returns with flag = true and empty status."

Change ()
"The functions MPI_WAIT and MPI_TEST can be used"
to
"The procedures MPI_WAIT and MPI_TEST can be used"

Change ()
"MPI_REQUEST_FREE is a local operation."
to
"MPI_REQUEST_FREE is a local procedure."

Change ()
"The use of this routine for generalized requests"
to
"The use of this procedure for generalized requests"

# Impact on Implementations

Clarity.

# Impact on Users

Clarity.

# References

Fixed by PR: https://github.com/mpi-forum/mpi-standard/pull/464

**Comment by wgropp** [comment]
I believe this is done.
