### ISSUE TITLE
Clean up Separation of items in Deprecated, Deleted and Backwards compatibility chapters

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#420]
# Problem

The three chapters deprecated, deleted and backward incompatible contain several unrelated topics. During the review for MPI 4.0 we detected that this led to having no space between, which makes the chapters hard to read. For MPI 4.0 we added a quick hack to add seperators, but this is not the ideal solution

# Proposal

Add special latex environments with headings (tbd. whether they should be in the TOC or nor) that adds separate headings for each item

# Changes to the Text

Add headers between items in chapters 16-18

# Impact on Implementations

None

# Impact on Users

Standard more readible

# References

[PR 745](https://github.com/mpi-forum/mpi-standard/pull/745)

**Comment by RolfRabenseifner** [comment]
In MPI-4.0, Section 16.3 _Deprecated since MPI-4.0_, I would add the following subsubsections:

- 16.3.1 Formerly in Section~\ref{sec:cancel}                      % 3.8.4: Cancel of send requests
- 16.3.2 Formerly in Section~\ref{subsec:info}                    % 10: MPI_INFO_GET and MPI_INFO_GET_VALUELEN
- 16.3.3 Formerly in Section~\ref{sec:mpit:retcodes}          % 15.3.10: MPI_T_ERR_INVALID_ITEM
- 16.3.4 Formerly in Section~\ref{f90:types}                        % 19.1.9: MPI_SIZEOF

In addition, in the change-log, B.1.2 Changes in MPI-4.0, Item 33
>  Section 16.3 on page 786.
>  MPI_SIZEOF was deprecated.

the references should be 
> Sections 16.3 and 19.1.9 on page 786 and 809.

That's all what I would add/change in this issue.

**Comment by wgropp** [comment]
I would not add subsections. This is really an example of something where an unnumbered list (itemize environment) is probably most appropriate.

**Comment by RolfRabenseifner** [comment]
Okay, I'll check whether it can be done as a pure formatting change (your proposed itemize), i.e., without new words.

**Comment by RolfRabenseifner** [comment]
@wgropp I hope, the result is what you expected.
@wesbland and @schulzm You are my chapter committee for Deprecated and Removed, please approve that @wgropp  can merge.
@wesbland and @schulzm You are chapter committee lead and member of Backward Incompatibilities, please approve that @wgropp  can merge.
Then it is hopefully done.

**Comment by RolfRabenseifner** [comment]
PDF file for review, see the added bullet points in Chap. 16 and 18: [mpi41-report_Issue420_PR745.pdf](https://github.com/mpi-forum/mpi-standard/files/10023634/mpi41-report_Issue420_PR745.pdf)

**Comment by RolfRabenseifner** [comment]
Reading is only scheduled for the case that this issue is not approved by the chapter committee and merged before the Dec. 2022 meeting (as fallback).

**Comment by RolfRabenseifner** [comment]
**@ chapter committee**:  @schulzm @wesbland  : 
**Please reply** whether you approve this issue (yes/no/abstain).

**Comment by wesbland** [comment]
Bill and I have already approved the PR.

**Comment by RolfRabenseifner** [comment]
chapter committee vote:
- 3x Yes: Bill, Wes, and myself (Rolf)
- 1x no answer: Martin

@wesbland I would recommend to take this as a positive chapter committee vote and therefore to merge it.
