### ISSUE TITLE
Include Hyperlinks in Language Bindings

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#422]
# Problem

The current document produced by the `mpi-4-rc` Makefile does not produce correct links in the bindings chapter. @wgropp has said this is something that gets added manually later, but there was a request by the Forum during the 2021-01-08 meeting to see this in the MPI 4.0 RC 2 document produced for the FRM in February.

# Proposal

See above

# Changes to the Text

See above

# Impact on Implementations

N/A

# Impact on Users

N/A

# References

N/A

**Comment by wgropp** [comment]
Fixed by PR 473. Note that this requires an obscure program, so if that's not available, no links will be generated.

**Comment by wesbland** [comment]
I can confirm that this works if you install [Sowing](http://wgropp.cs.illinois.edu/projects/software/sowing/) as the comments now mention. There are now links from each function to its definition. Is this PDF what you were looking for @dholmes-epcc-ed-ac-uk and @RolfRabenseifner?

[mpi40-report-binding_links.pdf](https://github.com/mpi-forum/mpi-issues/files/5789451/mpi40-report-binding_links.pdf)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Partially, yes. The MPI handles types---MPI_Datatype, etc---were also hyperlinks in the previous MPI standard document.

**Comment by wgropp** [comment]
Ok, I must have changed something else that broke the handle mapping.  I'll fix that this weekend.

**Comment by wgropp** [comment]
Fixed in PR 476
