### ISSUE TITLE
Sessions: need to update sections of standard describing initial error handler

### ISSUE THREAD

**Issue by hppritcha** [mpi-forum/mpi-issues#424]
# Problem

The initial error handler feature came in to the MPI 4.0 standard at nearly the same time as the Sessions additions to the standard so some things were missed.  In particular,  in the existing text there is no description of how this initial error handler is used in the context of the Sessions model.

Places that need to be checked are:

- [x] Section 2.8
- [x] Section 9.3
- [x]  Section 11.2
- [x] Section 11.8

# References

https://github.com/mpi-forum/mpi-standard/pull/519

**Comment by abouteiller** [comment]
Theres the same issue in 9.3 as the one for which Howard has a fix in 2.8.

I went over 11.2 and 11.8 didn't find anything problematic.

**Comment by martinwjschulz** [comment]
discussed on 3/17, no further comments, needs a rebase/conflict resolution (Howard)

**Comment by martinwjschulz** [comment]
Discussed on 3/17 - Example needs a change from SF(ses) to SF(sesX) in the last sentence of the caption (@hppritcha)
