### ISSUE TITLE
Revisit the use of return code vs. error class in MPI_T

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#426]
# Problem

When we introduced the MPI_T interface in MPI 3.0, we decided to use return codes for all MPI_T functions instead of error classes, to allow continued operation on error and to enable the usage before Init. With recent changes this may be obsolete. 

# Proposal

Change occurrences of error code to return code to make clear that these return codes behave differently from the "usual" MPI return codes.

# Changes to the Text

[See PR#646](https://github.com/mpi-forum/mpi-standard/pull/646)

# Impact on Implementations

Should be none.

# Impact on Users

Should be none, except for consistency - possible better usage of error handling.

# References

**Comment by mahermanns** [comment]
@schulzm The introduction of this issue suggests this to be very close to this one: https://github.com/mpi-forum/mpi-issues/issues/385 and could be a duplicate.

So the 4.1 part of handling return codes should probably discussed there, and this issue is more about fixing the language/typo? Is that already fixed by some other PR?

**Comment by mahermanns** [comment]
This might be a duplicate of #385 or should at least be handled in the same way.

**Comment by mahermanns** [comment]
Tools WG, Dec 2, 2021: We favor to keep the current semantics but maybe make it clearer in the text that MPI_T behaves different than the rest of MPI. The text should rather talk about "MPI_T error codes" to make the difference clear to the user.

**Comment by mahermanns** [comment]
Let's close this as a duplicate of #542 and continue discussion there.
