### ISSUE TITLE
RMA: Replace 'operation' with 'operator' where appropriate

### ISSUE THREAD

**Issue by jaegerj** [mpi-forum/mpi-issues#429]
# Problem

"Operation" is used to describe the op argument for MPI_Accumulate, MPI_Get_accumulate and MPI_Fetch_and_op.
MPI 4.0 introduces an new meaning for "operation", and "operator" should be prefered instead. 

# Proposal

Replace "operation" and "reduce operation" with "\MPI/ operator" where appropriate

# Changes to the Text

Replace "operation" and "reduce operation" with "\MPI/ operator" where appropriate

# Impact on Implementations

None

# Impact on Users

Better clarity in the standard

# References

PR https://github.com/mpi-forum/mpi-standard/pull/490 provides a similar modification for the collective chapter (and a few references in other chapters, excluding RMA)

**Comment by devreal** [comment]
@jaegerj This does not only affect the RMA chapter but also applies to the collectives chapter, where *reduction operations* should become *reduction operators* (including *user-defined reduction operators*) to distinguish from *reduction operations* such as `MPI_Reduce`.

**Comment by devreal** [comment]
Argh, I just noticed that there was a separate PR for the collectives chapter. However, that PR and the associated issue are closed without the fix being merged. Is there an updated PR/issue for MPI 4.1?

**Comment by martinruefenacht** [comment]
This also affects the DSL as noted by @devreal in #637. I will create a branch for that aspect touching the binding blocks in chap-binding, chap-one-sided and chap-collective.

**Comment by jaegerj** [comment]
> 

Collective chapter, in branch mpi-4.x, already contains the change operation -> operators. However, I just found some discrepancies.
With Dan, we have a branch to change "operators" to "\MPI/ Operators". I'll add the correction of the discrepancies in this branch.

**Comment by RolfRabenseifner** [comment]
Please be careful: We have MPI builtin operators like MPI_SUM and user defined operators defined with MPI_Op_create.
Please be careful that the changed wording does not look like that user defined operators  are in future forbidden where they are currently allowed.

**Comment by devreal** [comment]
@jaegerj I guess I had found the instances where reduction operation is still used, e.g., 

> Reduction operations can be queried for their commutativity.
or
> Predefined Reduction Operations

> With Dan, we have a branch to change "operators" to "\MPI/ Operators"

I agree with Rolf. Not sure what problem that would solve.

**Comment by jaegerj** [comment]
Noted. I'll just fix the missed "operations"->"operators" in a new branch and PR

**Comment by devreal** [comment]
@wesbland This had a reading in Chattanooga. I changed the tags from scheduled-reading to had-reading.

**Comment by wesbland** [comment]
> @wesbland This had a reading in Chattanooga. I changed the tags from scheduled-reading to had-reading.

Thanks. Sorry I missed this.

**Comment by wesbland** [comment]
Had a no-no reading on 2022-12-05

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-06.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This passed a [second vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-08.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 27
	<td> 0
	<td> 4
</table>
