### ISSUE TITLE
Bug in Fortran embiggening MPI_CONVERSION_FN_NULL

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#432]
# Problem

I'm pretty sure that the embiggened API for MPI_CONVERSION_FN_NULL
is broken:

In our MPI-4.0 RC
  https://www.mpi-forum.org/docs/drafts/mpi-2020-draft-report.pdf
on p980:37 and p980:46, you can find two different definitions
for MPI_CONVERSION_FN_NULL.

Normally, this is no problem, because it is usual function overloading.

But MPI_CONVERSION_FN_NULL is a predefined callback procedure function
(see p853:39 - there defined of type
  PROCEDURE(MPI_Datarep_conversion_function) )
that can be used
- in MPI_Register_datarep
  - as read_conversion_fn and
  - as write_concversion_fn
  both defined of tpye PROCEDURE(MPI_Datarep_conversion_function)
- and in MPI_Register_datarep_c
  - as read_conversion_fn and
  - as write_concversion_fn
  both defined of tpye PROCEDURE(MPI_Datarep_conversion_function_c)

One constant MPI_CONVERSION_FN_NULL cannot be both.

# Proposal

I expect, that it can be "easily" fixed by introducing an new constant
MPI_CONVERSION_FN_NULL_C
- duplicating all of MPI_CONVERSION_FN_NULL really everywhere
- and also adding it to the large cont change-log entry.

I detected this when going through all the new "!(_c)" markups
for all embiggened mpi_f08 interfaces in the A.4.

and from @hritzdorf :
https://github.com/mpi-forum/mpi-standard/pull/499#issuecomment-760905419

# Changes to the Text

Describe the text changes here.

# Impact on Implementations

Without solvoling this problem, an MPI-4.0 implementation of MPI_CONVERSION_FN_NULL is not possible.

# Impact on Users

Describe the changes that will impact users here.

# References

Thanks to Claudia who found the bug reported in
https://github.com/mpi-forum/mpi-issues/issues/364#issuecomment-739087747
which led to the idea with these new "!(_c)" markups, see
https://github.com/mpi-forum/mpi-issues/issues/364#issuecomment-759655188
and implemented in https://github.com/mpi-forum/mpi-standard/pull/499

For me, it is clear that it is an MPI-4.0 issue.

**Comment by hritzdorf** [comment]
The constant  C function "MPI_CONVERSION_FN_NULL_c" has also a problem. This function is only defined in I/O C bindings

**Comment by RolfRabenseifner** [comment]
I want to remember that a similar problem in the MPI-2 C++ interface caused at the end that this C++ interface was more or less broken.
In other words, we have to fix this problem before finalizing MPI-4.0.

**Comment by hritzdorf** [comment]
I vote for 2 different functions MPI_CONVERSION_FN_NULL and MPI_CONVERSION_FN_NULL_C in Fortran in order to be compatible with C.

**Comment by RolfRabenseifner** [comment]
I would recommend, that for C and Fortran, the name of the new callback procedure constant should be MPI_CONVERSION_FN_NULL_C (i.e., also in C with uppercase "_C" postfix).

**Comment by RolfRabenseifner** [comment]
Because this routine is an exception from the nomal naming scheme, I would take it easy and produce both routines (MPI_CONVERSION_FN_NULL and MPI_CONVERSION_FN_NULL_C) individually and have them themselves without embiggening.

**Comment by RolfRabenseifner** [comment]
Who will produice the PR, please do not forget to also look at the locations where the exceptions for MPO_Op_create_c and MPI_Register_datarep_c are discussed (and not only at MPI_CONVERSION_FN_NULL locations).

**Comment by tonyskjellum** [comment]
If we change
int MPI_CONVERSION_FN_NULL_c(void *userbuf, MPI_Datatype datatype,
MPI_Count count, void *filebuf, MPI_Offset position, 
void *extra_state) 

on pp 898-99,

to

int MPI_CONVERSION_FN_NULL_C(void *userbuf, MPI_Datatype datatype,
MPI_Count count, void *filebuf, MPI_Offset position, void *extra_state) 

this solves the problem; we need to say that this is an exceptional naming strategy.

This enables the mpi and mpi_F08 modules to work correctly.

However, as far as we understand from the above, @hritzdorf seems to indicate that we are missing the ability to have a pure Fortran program, since we only accept C pointers in the APIs.  We do not solve this problem in this ticket.  It requires a separate, future ticket.   In other words, non-default versions of the callback must be written in C at present.  Let's solve in MPI-4.1.

**Comment by RolfRabenseifner** [comment]
No, we always have a pair or trio of constants:
- MPI_COMM_NULL in C, f08 and f90
- MPI_CONVERSION_FN_NULL in C, f08 and f90
- MPI_CONVERSION_FN_NULL_C in C, f08 (and NOT in f90)

But currently, MPI_CONVERSION_FN_NULL_C does not yet exist.
Only by a, let's say bug, we can see in the Annex A.3 showinbg up an additional C-function MPI_CONVERSION_FN_NULL_c, and in Annex A.4 a double definition of the same Fortran subroutinev name MPI_CONVERSION_FN_NULL.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
To aid my understanding of Fortran (and not as a proposed fix for this issue), the "Fortran" way to fix this would be to make the `read_conversion_fn` and `write_conversion_fn` parameters in the `MPI_Register_Datarep` and  `MPI_Register_Datarep_c` procedures into *optional* parameters and to remove the Fortran constant MPI_CONVERSION_FN_NULL entirely. Discuss.

(Obviously, not viable for MPI because back-compat)

**Comment by tonyskjellum** [comment]
@puribangalore Please look at Rolf's follow-up to our proposed solution.

**Comment by RolfRabenseifner** [comment]
@dholmes-epcc-ed-ac-uk 
> To aid my understanding of Fortran (and not as a proposed fix for this issue), the "Fortran" way to fix this would be to make the `read_conversion_fn` and `write_conversion_fn` parameters in the `MPI_Register_Datarep` and `MPI_Register_Datarep_c` procedures into _optional_ parameters and to remove the Fortran constant MPI_CONVERSION_FN_NULL entirely. Discuss.
> 
> (Obviously, not viable for MPI because back-compat)

No, because it does not fit to existing f08 and f90 interfaces.
We just have to do in Fortran the same as in C: two constants MPI_CONVERSION_FN_NULL and MPI_CONVERSION_FN_NULL_C.
It is trivial, and the only thing is to write a PR that does not miss any location with this doubling of the two constants, and also not to miss 19.2 and changelog, to mention this special case - the only _C constant that is added for large counts.

**Comment by RolfRabenseifner** [comment]
I start to provide a pull request to resolve the problems reported above. Then we have a base for the MPI telcon on Jan 20, 2021.

**Comment by RolfRabenseifner** [comment]
@martinruefenacht @dholmes-epcc-ed-ac-uk Please can you help with [PR501](https://github.com/mpi-forum/mpi-standard/pull/501)

**Comment by RolfRabenseifner** [comment]
All changes can be reviewed in [mpi40-report_Issue405_PR501_v04_commented.pdf](https://github.com/mpi-forum/mpi-issues/files/5842618/mpi40-report_Issue405_PR501_v04_commented.pdf)
There are a few additional Latex comments on how to use the bindings with the exceptions.

**Comment by RolfRabenseifner** [comment]
All is done and therefore closed.
