### ISSUE TITLE
Handling of extra state in dropped event handler for MPI_T

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#433]
# Problem

In the MPI 4 RC document, the current text states that the dropped event handler function gets the `user_data` pointer provided at callback registration. There can be different `user_data` pointers provided to different safety levels of callbacks for an event registration handle, and higher safety level registrations can fill in for lower ones, so a user is not required to register a callback for all safety levels.

While this should work fine if the user has only callbacks registered for safety levels that are *lower* than what the MPI implementation will ever use in a dropped handler invocation.

In such a situation, it's unclear with the MPI 4.0 RC specification, whether the dropped handler will ever be invoked.

# Proposal

After discussions both in the working group and the larger forum, we agreed that in general the currently specified behavior is OK in that dropped callback invocations may not occur, yet this should be clarified to the user.

- Dropped handler callback functions may never called if the user didn't register event callbacks for the safety levels used by the implementation to invoke those.

# Changes to the Text

See https://github.com/mpi-forum/mpi-standard/pull/584

# Impact on Implementations

Clearer on how to implement this functionality. 
 
# Impact on Users

Clearer on what to expect from implementations in some of the corner cases of use.

# References

[E-Mail Thread on Tools Mailing List "[mpiwg-tools] question about MPI_T_EVENT_SET_DROPPED_HANDLER"](https://lists.mpi-forum.org/pipermail/mpiwg-tools/2021-January/003097.html)

**Comment by wesbland** [comment]
This was informally read at the Feb 2021 meeting with general consent.
