### ISSUE TITLE
Issue I - Is definition of local Session_init + collective Session_finalize pair broken?

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#435]
# Solution

The described problem is now solved via PR https://github.com/mpi-forum/mpi-standard/pull/547  

Issue I=435 "sessions" - exactly based on the result of PR547
(but without the change in Issue E, and but with the additional correction discussed Feb. 26, 2021)
i.e., https://github.com/mpi-forum/mpi-standard/pull/547
now to be committed with a new PR https://github.com/mpi-forum/mpi-standard/pull/563 to RC-4-June

For latest commented pdf, see  [Issue 405](https://github.com/mpi-forum/mpi-issues/issues/405)

# Problem

I know that the new sessions API has a large number of reviewers and members in the Sessions WG and the Chapter 11 committee, plus two votes by the whole forum. Therefore I hope that my question can be easily answered based on the current specification mpi40-rc-feb-21.pdf (release candidate for MPI-4.0), see email from Wesley, "MPI 4.0 RC 2 Published".

**CASE A**

`WI=MPI_Init`, i.e., in **W**orld Model
`WF=MPI_Finalize`, i.e., in **W**orld Model
`SI=MPI_Session_init`, a local call (in the **S**essions Model)
`SF=MPI_Session_finalize`, by definition collective over all connected processes
`GfS=MPI_Group_from_session_pset (..., "mpi://WORLD", ...)`
`CfG=MPI_Comm_create_from_group (..., "x", MPI_INFO_NULL , MPI_ERRORS_ARE_FATAL , ...)`

This example has three processes A, B and C, the following session. group and communcator handles: S1, S2, S12; G1, G2; C1, C2

1. Important is, that the middle process B uses only one session handle **S12**.
This may be never intended, but seems not to be forbidden, because from one session handle, one my derive several groups and communicators.
2. The sequence of SF in process C is contrary to the sequence used to generate the session, group and communicator handles in process A.
  
`___A_____________B______________C____`
`___WI____________WI_____________WI___`
`_SI(S1)_______SI(S12)________SI(S1)__`
`_SI(S2)______________________SI(S2)__`
`_GfS(S1,G1)__GfS(S12,G1)__GfS(S1,G1)_`
`_GfS(S2,G2)__GfS(S12,G2)__GfS(S2,G2)_`
`_CfG(G1,C1)__CfG(G1,C1)___CfG(G1,C1)_`
`_CfG(G2,C2)__CfG(G2,C2)___CfG(G2,C2)_`
`_____________________________________`
`_SF(S1)_______SF(S12)________SF(S2)__` Comment 1.
`_SF(S2)______________________SF(S1)__`  Comment 2.
`___WF____________WF_____________WF___` Comment 3.

**Comments:**
1) These calls are collective over all connected processes and independent from which communicators are derived from the sessions
2) There isn't any opened session handle in process B, but the call is collective over all three still connected processes,
i.e., **this is a deadlock situation implied by the definition of MPI-4.0**
3) If this WF line is done before the second SF line, is then anything different?
If yes then the independence of Sessions and the World Model would be broken.

**CASE B**

The same initialization, but the Finalize with the contrary sequence in process C:

`_SF(S1)_______SF(S12)________SF(S1)__` 
`_SF(S2)______________________SF(S2)__`
`___WF____________WF_____________WF___`

There should not be a significant difference.

**CASE C**

My problem is that the definition of "connected" in MPI-4.0 Release Candidate 2 - Feb 3, 2021 (after PR513), page 502, line 30-32 seems to be independent from the definition in 11.10.4. Lines 30-32 does not define a transitive property. On the other hand, 11.10.4 defines a transitive hull, but completely independent from Session handles.

In the following example, I only show the communicators based on a Session handle and the we look at Session_finalize.

`___A______B______C______D______E______F___`
`__S1=====S12=====S1_______________________`
`__S2=====S12===========S2_________________`
`_______________________S2=====S2__________`
`______________________________S3=====S3___`

Lines 30-32 read:
_"MPI_SESSION_FINALIZE is collective over all MPI processes that are connected via MPI Communicators [...] that were created as part of the Session and still exist."_

SF(S1) in process A is by lines 30-31 collective over A, B(with S12), and C(with S1).
SF(S12) in process B is by lines 30-31 collective over A(with S1 & S2), B, C(with S1), and D(with S2).
SF(S1) in process C is by lines 30-31 collective over A(with S1), B(with S12), and C.
SF(S2) in process D is by lines 30-31 collective over A(with S2), B(with S12), D, and E(with S2).
SF(S2) in process E is by lines 30.-31  collective over D(with S2) and E.

**Comments:**

4. This means, nearly each process defines another group for the collectivity of the call.
Only the connectivity between E and F is independent.

5. Using the additional definition in 11.10.4 with the transitive hull defined independently from session handles, then all 6 processes A-F are connected, whic would destroy the independence of Session S3.

6. I miss a definition on connected based on a session handle that has a transitivity property, because without this, a collective MPI_Session_finalize cannot be defined.

7. I propose:

_A process A using a session handle S.A is connected to a process B using a session handle S.B if there exist a communicator that between A and B that is derived from S.A in A and S.B in B._
_If a process A using a session handle S.A is connected to a process B using a session handle S.B **and** process B using a session handle S.B is connected to a process C using a session handle S.C then also process A using a session handle S.A is connected to process C using a session handle S.C._

Based on this definition, we can state (in the MPI standard) similar to 11.10.4: (corrected on Feb. 17, 2021)
_By the above definitions, connectivity based on session handles is a transitive property. It defines minimal groups of processes that are connected with each other by communicators derived from a minimal set of session handles in each process. 
We name such a group of processes derived from a set of session handles in each process as a **sessions connectivity group**.
Within a given process, such sets of session handles belonging to different sessions connectivity groups are disjunct._
 
In Case C, we have two such **sessions connectivity groups**:
- A(S1,S2) + B(S12) + C(S1) + D(S2) + E(S2)
- E(S3) + F(S3)

8. We should also state:
_Note that the set of sessions connectivity groups may be modified at runtime with each newly established communicator.
MPI_SESSION_FINALIZE is collective over a sessions connectivity group. The group may still be modified by members of the group during the call, but each process shall not (e.g., by another thread) create or free communicators belonging to its related set of session handles after it has started MPI_SESSION_FINALIZE._

Example:

`___A______B______C______D______E______F___`
`__S1=====S12=====S1_______________________` Line I.
`__S2=====S12===========S2_________________` Line II.
`SF(S1)_SF(S12)_SF(S1)_____________________` Line III.
`_______________________S2=====S2__________` Line IV.
` ____________________SF(S2)________________` Line V.
`______________________________S3=====S3___` Line VI.
`____________________________SF(S3)_SF(S3)_` Line VII.
`____________________________SF(S2)________` Line VIII.
`SF(S2)____________________________________` Line IX.

Notes on Lines:
I. The only sessions connectivity group is A(S1) + B(S12) + C(S1)
II. Now, the only sessions connectivity group is A(S1,S2) + B(S12) + C(S1) + D(S2)
III. The whole sessions connectivity group will be known not before all members have started their SF
IV. Although D is member of the already finalizing sessions connectivity group is A(S1,S2) + B(S12) + C(S1) + D(S2), process D still can enlarge this group. In this case to  A(S1,S2) + B(S12) + C(S1) + D(S2) + E(S2)
V. D has now also called SF.
VI. Now, there are two sessions connectivity groups is A(S1,S2) + B(S12) + C(S1) + D(S2) + E(S2) and E(S3) + F(S3)
VII. The finalizing in each sessions connectivity group is independent from each other. Therefore process E can freely choose whether it first finalizes S3 or S2. A process must be aware that such SF calls may synchronize over the whole finally defined sessions connectivity group.
VIII. Now all processes of the sessions connectivity group A(S1,S2) + B(S12) + C(S1) + D(S2) + E(S2) called SF and therefore must return.
IX. After returned from SF(S1), the call to SF with other members of the session handles set of the finalized sessions connectivity group (here S2) is now a local call.

9. In principle, the MPI forum has several options:
 - To define that it is okay that this minimal set of session handles can be more than one session handle,
 - or to allow only exactly one session handle in such a minimal set in each process for each such sessions connectivity group.
 - To define that a Session_finalize is collective over the sessions connectivity group using one of session handle in each process.
 - After such collective Session_finalize, 
    - all communicators on the connectivity cloud are stale handles,
    - all further Session_finalize with the other session handles are local,
    - but must be done (or must not? or need not, or is a no-operation).

(Further cases may arise based on the discussion in this issue.)

# Proposal

Resolved by https://github.com/mpi-forum/mpi-standard/pull/547 which applis to RC-1/2

Issue I=435 "sessions" - exactly based on the result of PR547
(but without the change in Issue E and with the additional correction discussed Feb. 26, 2021),
i.e., https://github.com/mpi-forum/mpi-standard/pull/547
now to be committed with a new PR https://github.com/mpi-forum/mpi-standard/pull/563 to RC-4-June

# Changes to the Text

See https://github.com/mpi-forum/mpi-standard/pull/563 (and former https://github.com/mpi-forum/mpi-standard/pull/547)

# Impact on Implementations

Describe changes that implementations will be required to make here.

# Impact on Users

Describe the changes that will impact users here.

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/563

**Comment by schulzm** [comment]
I think/fear this is a really good catch, but I don't think this is actually a problem - it certainly needs some clarification, though.

I think Comment 1 is not correct: the operation is not collective over all connected processes, but over all processes in communicators derived from the session (Section 11.3.1 at the end). This is basically describing the concept of the bubble.

However, this alone doesn't change the example, as all three processes are involved in all communicators. Hence, the first session finalize is certainly collective and "cleans up" but not "frees" all communicators in S1/P1, S12/P2 and S2/P3. The question is now what this means - I would argue this "deactivates" C1 and C2 in P2 and with that in all processes, so that one couldn't use either communicator after the first round of session_finalize.

Also, this make the processes connected to P1 via objects controlled by session S2 just P1, and similarly for P3 - which would then mean the second round of finalizes are only collective with each other.

As Howard said in the email, the WG will look at that in more detail and report back.

**Comment by hppritcha** [comment]
The answer to comment/question 3 is no.

**Comment by hppritcha** [comment]
We discussed comments 1 and 2 in the working group this week and agreed that @schulzm interpretation of the situation in the above comment best describes how the above scenario would work.  We will modify the text around the ```MPI_Sesssion_finalize``` description to cover cases where an application is using communicators, files, or windows which were derived from different sessions in different processes.   Basically, all communicators, files, windows associated with the session handles supplied to session_finalize will no longer be usable upon return from the call.  Note in the event that the association of communicators, files, or windows to session handles is different for the processes invoking ```MPI_Session_finalize```, it is possible that for some processes, communicators other than those it had locally associated with the supplied session handle may become invalid for further use.  A subsequent call to session finalize for those processes using a session handle that is associated with such _deactivated_ communicators will be a local call.

**Comment by RolfRabenseifner** [comment]
I added a Case C, which may not be resolved by the current wording of MPI-4.0.
(Case B was only for completeness for the previous discussion).

**Comment by schulzm** [comment]
Reading it again, I agree with Rolf that the transitivity is not clearly defined and the text can be interpreted the other way as well. We should fix this.

However, I don't think the following is correct, or not as intended:

By the above definitions, connectivity based on session handles is a transitive property, and divides the universe
of MPI processes into disconnected (independent) sets (equivalence classes) of processes that are connected based on a minimal set of session handles in each process.

With 3 processes (A,B,C), if A and B create a session each and then create a communicator, and then B and C create a session each and then create a second communicator, A and B are "one bubble" and are collective in case of a session finalize, and B and C as well.

**Comment by RolfRabenseifner** [comment]
Yes, you are absolutely right:
_"By the above definitions, connectivity based on session handles is a transitive property, and divides the universe
of MPI processes into disconnected (independent) sets (equivalence classes) of processes that are connected based on a minimal set of session handles in each process."_ 
is wrong. 
I'll substitute it by a correct text based on that it defines such transivity bubbles and that within each process that belong to such a bubble, the bubble is based on a set of one ore more session handles. Witin a given process, such sets of session handles belonging to different bubbles are disjunct.

In Case C, we have two such bubbles:
- A(S1,S2) + B(S12) + C(S1) + D(S2) + E(S2)
- E(S3) + F(S3)

**Comment by RolfRabenseifner** [comment]
Based on Martin's comment, I updated Case C, see Comments 7-8 (including last example and its notes I. - IX.

**Comment by RolfRabenseifner** [comment]
Results from MPI Forum telcon Feb. 17, 2020:
Instead of the concept of the **sessions connectivity group**, @dholmes-epcc-ed-ac-uk proposed to define MPI_Finalize not as collective over a group, but behaving as if internally forking threads, each executing one MPI_COMM_DISCONNECT for each communicator that were build with group handles derived from the given session handle, followed by a join of thease threads.
(Wording as with MPI_SENDRECV.)

With this definition, **Case A** would be a **wrong program**, because the MPI_Session_finalize calls in processes A and C may deadlock, whereas **the program in Case B is correct**. 

The sequence of calls in **Case C is also correct**:
- SF(S12) in process B may be blocked until the last call of SF(S1) in A and C, and additionally,
- SF(S12) in process B, SF(S2) in D,  and SF(S2) in E may be blocked until the last call of SF(S2) by process A in line IX.

As a **Case C'** one can exchange the two SF calls in process A, i.e., SF(S2) in line I and SF(S1) in line IX.
This Case C' is **also correct**:
- SF(S12) in B and SF(S1) in C may be blocked until SF(S1) in A in line IX, and
- SF(S12) in B, SF(S2) in A, and SF(S2) in D may be blocked until SF(S2) in E in line VIII.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Suggested resolutions:

0) leave the text alone for MPI-4.0 and address/clarify this as an MPI-4.0 erratum instead (probably a non-viable option)
1) add new text that disallows any usage of MPI_SESSION_FINALIZE that causes it to be non-local (the draconian option)
2) add new text that describes the semantics for MPI_SESSION_FINALIZE differently, either (note 2b is preferred):
 a) like MPI_WAITALL - as if: execute nonblocking variant of all object destructors, then execute wait for all
 b) like MPI_SENDRECV - as if: fork lotsa threads, execute one blocking object destructor on each thread, join threads

Identified problems:

0) leaves known confusion/stumbling-block in the MPI-4.0 standard document, which must be addressed later
1) requires MPI-4.0 is delayed at least one more voting meeting and breaches rule of least astonishment (especially for users)
2) requires MPI-4.0 is delayed at least one more voting meeting and:
 a) although the ordering of wait calls constituting wait-all can be arbitrary, the ordering of nonblocking destructors is critically important (they are collective initiation procedures and must be ordered across their group - MPI must match user ordering if user needs multiple calls elsewhere)
 b) implies threads - but does not mandate usage of them - no worse than MPI_SENDRECV

Chosen option: 2b

Target: if MPI-4.0 is ratified next week (Feb 2021) then option (0) has been chosen by default and this issue will implement option (2b) as an MPI-4.0 erratum, else this issue will delay MPI-4.0 - in both cases, it will be read Feb 2021 and voted June 2021.

Timeline: write needed new text this week, read at MPI Virtual Voting meeting next week.

**Comment by RolfRabenseifner** [comment]
Resolved in https://github.com/mpi-forum/mpi-standard/pull/547
PDF: [mpi40-issue435-PR547-sessions-2021-FEB-25-v1.pdf](https://github.com/mpi-forum/mpi-issues/files/6043469/mpi40-issue435-PR547-sessions-2021-FEB-25-v1.pdf)  (see pages 502+503)
