### ISSUE TITLE
LIS inout and C&Fortran IN fix for Partitioned Communication

### ISSUE THREAD

**Issue by regrant** [mpi-forum/mpi-issues#437]
# Problem

MPI_Pready, MPI_Parrived, MPI_Pready_list and MPI_Pready_range had INOUT defintions for the C and Fortran interfaces. This ticket resolves that by making the LIS have an INOUT parameter on them while the C and Fortran interfaces do not. There is no intention to change the requests in these function calls.

# Proposal

Revise to have INOUT in LIS and IN in C & Fortran

# Changes to the Text

see above

# Impact on Implementations

Minimal, as most implementations have not yet implemented these functions. For ones that have, the impact is nil.

# Impact on Users

No impact, interface is not a part of a formal release yet.

# References and Pull Requests

pull request: [mpi-forum/mpi-standard/#517](https://github.com/mpi-forum/mpi-standard/pull/517)

**Comment by RolfRabenseifner** [comment]
You can find my commented pdf with especially the discussion results on MPI_Parrived / MPI_Ptest (and MPI_Request_get_status) in https://github.com/mpi-forum/mpi-issues/files/6050186/mpi40-rc-feb-21_rab.pdf on pages 111 (and 75 + 83)
