### ISSUE TITLE
Handling of enum argument on MPI_T_event_get_info

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#438]
# Problem

The current specification states that users should pass `MPI_T_ENUM_NULL` to `MPI_T_event_get_info` to have the MPI library ignore this argument. However, this is different to the other calls vor CVARs and PVARs, where the argument fulfills a similar purpose and is also an OUT argument.

# Proposal

Instead of `MPI_T_ENUM_NULL` the user should pass in the null pointer here.

# Changes to the Text

See https://github.com/mpi-forum/mpi-standard/pull/518

# Impact on Implementations

Symmetric behavior of enum argument

# Impact on Users

Symmetric behavior of enum argument

# References and Pull Requests

**Comment by wesbland** [comment]
I can't recall, but I don't think this issue was discussed in a virtual meeting yet. Correct?

If not, we should have a quick discussion with the full forum before we merge it.
