### ISSUE TITLE
Odd text about ERR_IN_STATUS in wait/waitall

### ISSUE THREAD

**Issue by abouteiller** [mpi-forum/mpi-issues#44]
# Problem

Hybrid working group discovered the following odd text in 3.7.3, page 55. This has been raised to the wg-ft by Pavan during the march Chicago Meeting.

> Error codes belonging to the error class MPI_ERR_IN_STATUS should be returned only by the MPI completion functions that take arrays of MPI_Status. For the functions MPI_TEST, MPI_TESTANY, MPI_WAIT, and MPI_WAITANY, which return a single MPI_Status value, the normal MPI error return process should be used (not the MPI_ERROR field in the MPI_Status argument).

"error return process" is weird. While looking at a fix for this issue, I noticed that Probes and possibly other functions are missing from the explicit list of functions that return a single status. 

# Proposal

There are multiple options
1. change the text and keep the list as-is (on the premise that we are in section 3.7.3 so the qualifier implicitly applies to operations defined in this section).
2. change the text and scoot the standard for any other missing function that has a single status argument to complete the list.
3. remove the list, as it is redundant: Section 3.2.5 already defines what should happen for operations that do not return ERR_IN_STATUS. 
>In general, message-passing calls do not modify the value of the error code field of status variables. This field may be updated only by the functions in Section 3.7.5 which return multiple statuses. The field is updated if and only if such function returns with an error code of MPI_ERR_IN_STATUS.

# Changes to the Text

The WG decided on option 3 and the following text was presented in Bellevue and amended according to plenary comments: 
See mpi-forum/mpi-standard#19

# Impact on Implementations

None

# Impact on Users

None

# References

# Procedural notes

This is not even an errata, as it is only text smithing with no standard semantic changes. Need to think under what procedure we move it forward.

**Comment by abouteiller** [comment]
This issue has been presented in plenary at Bellevue in June 2016. 
The forum feedback is to move forward as a chapter author edition.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
What are the arguments for and against each of the 3 options?

**Comment by abouteiller** [comment]
The options have been discussed in the WG, and we came up with the text in the PR (a variant of Option3), which is the one that I presented at the plenary.

**Comment by abouteiller** [comment]
Issue resolved, thanks Daniel and Bill.
