### ISSUE TITLE
IBcast and friends without tag argument?

### ISSUE THREAD

**Issue by zerothi** [mpi-forum/mpi-issues#441]
# Problem

The `IBcast` and friends routines that lets one do collective communications do not have the `tag` argument that lets individual calls distinguishable.

Consider a template code looking like this:
```c
for (i = 0 ; i < n ; i++)
{
    b_node = <determine broadcast node>;
   MPI_IBcast(array[index], size, MPI_INT, b_node, MPI_COMM_WORLD, request[nb++]);
}
```
this will fail if the same `b_node` calls.

In the above case one could argue `AllGather` is better suited, but that will be weird since you have to figure out whenever you hit the same `b_node` twice, also it requires way more book-keeping.

# Proposal

I know we can't have the interfaces changed, but perhaps a variation of `IBcast` and friends with `tags` enabled? `MPI_ITBcast` or?

# Changes to the Text

# Impact on Implementations

I don't have a clue as to the implementation impacts :(

# Impact on Users

Users get a more versatile usage of the collective operations for b-casting. and removes quite a bit of clutter code with respect to `AllGather`.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
The source code you have given is not complete enough to make definite comments.

However, if I intuit correctly what you might mean by the template code given, it seems likely to be a correct program that does not require tagged collective operations or recourse to a different collective operation , such as all-gather.

The key component that is missing, perhaps, in your reasoning here is that the ordering of these nonblocking collective initiation procedures is significant and is sufficient to distinguish these operations from each other.

As long as the buffers given to each of the broadcast operations is distinct from all the others and the sequence of values provided for the root parameter is identical at all ranks, then this appears to be a valid usage of MPI (modulo the absence of completion for the nonblocking operations as well as initialisation and finalisation of MPI itself).

If you wish to specify more than one root process for a broadcast operation, then that is erroneous in MPI. The issue, I guess, is an agreement problem - all MPI processes must be able to determine which one of them will be root for each of the sequence of broadcast operations.

Thus, if the `<determine broadcast node>` is deterministic enough to produce the same sequence of values at every MPI process, there is no problem here that needs tags.

If the computation of which MPI process should be root can be done independently by all MPI processes, then `<determine broadcast node>` is probably fairly simple and definitely local (in the sense defined in the MPI Standard).

If the computation of which MPI process should be root requires non-local knowledge from one or more other MPI processes, then `<determine broadcast node>` probably needs some communication to resolve the ambiguity for each broadcast operation.

Personally, I do not see a justification or need for tagged collectives in this issue.

**Comment by zerothi** [comment]
> However, if I intuit correctly what you might mean by the template code given, it seems likely to be a correct program that does not require tagged collective operations or recourse to a different collective operation , such as all-gather.
> 
> The key component that is missing, perhaps, in your reasoning here is that the ordering of these nonblocking collective initiation procedures is significant and is sufficient to distinguish these operations from each other.

Thanks for your insight, this was exactly the problem and my use case. I had missed this in the standard.

> Thus, if the `<determine broadcast node>` is deterministic enough to produce the same sequence of values at every MPI process, there is no problem here that needs tags.

Yes, in this use case it is deterministic enough. :)

Thanks!
