### ISSUE TITLE
Update verbatim examples to example environment

### ISSUE THREAD

**Issue by naughtont3** [mpi-forum/mpi-issues#442]
# Problem

The grey box formatting around examples (added in MPI-4.0) raises that many examples use verbatim instead of the example environment, which means the example is not formatted consistently.  This seems like something for the MPI-4.1 cleanup efforts.

# Proposal

Review example listings without a grey box and update to use correct `\begin{example}...\end{example}` formatting.

# Changes to the Text

Update LaTeX throughout the document, e.g., Section 7.6.3 Example 1: "Three-Group Pipeline".

# Impact on Implementations

None.

# Impact on Users

None.

# References and Pull Requests

## Instructions

* Each committee chair should check the box when they're done. 
* All changes should be grouped into single PR which will be reviewed all at once.
  * The first author of the PR will create a new PR. All other authors will push to the first PR (instructions to be added when the first PR is created).
  * This PR should say that it `Fixes #442` in the description to automatically link it to this issue.

If there is nothing to do in your chapter, just check your box.

* [x] Front matter - @wgropp 
* [x] Introduction - @wgropp 
* [x] #624
* [x] Point-to-Point - @Wee-Free-Scot  
* [x] #625
* [x] #626
* [x] Communicators - @GuillaumeMercier 
* [x] Topologies - @RolfRabenseifner
* [x] #627
* [x] #628
* [x] #629
* [x] Process Creation - @hppritcha 
* [x] #630
* [x] #631
* [x] #632
* [x] Tools - @mahermanns 
* [x] Deprecated - @RolfRabenseifner 
* [x] Removed - @RolfRabenseifner 
* [x] Backward Incompatibilities - @wesbland 
* [x] #633
* [x] Bindings Summary - @RolfRabenseifner 
* [x] Change Log - @RolfRabenseifner

**Comment by hppritcha** [comment]
@wesbland i found an example in chap-dynamic that seemed to need the fix @naughtont3 describes here.  so I opened a PR since I didn't see an open one related to it.

**Comment by RolfRabenseifner** [comment]
No verbatim or verbatim in topology or deprecated chapter. I hit the checkbox.

**Comment by wesbland** [comment]
Closing in favor of the chapter-specific issues.
