### ISSUE TITLE
LIS entries in MPI_T chapter not reflecting IN vs. INOUT as defined in Term 2.3 chapter

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#443]
# Problem

As part of the discussion to changes to the IO chapter a discussion emerged about incorrect IN vs. INOUT arguments listed in LIS descriptions of the calls, not adhering to the terms chapter section 2.3 (4.0 RC, p. 10):

> [...] if  an  argument  is  a  handle  to  an  opaque  object  (these terms are defined in Section 2.5.1), and the object is updated by the procedure call, then the argument is marked INOUT or OUT. It is marked this way even though the handle itself is  not  modified  —  we  use  the INOUT or OUT attribute  to  denote  that  what  the  handle references is updated. [...]

Some calls of the MPI_T PVAR/CVAR interface introduced with MPI 3.0 do not adhere to this definition and should be adapted.

**Note:** *The LIS for MPI_T events calls are focused on in [Issue#500](https://github.com/mpi-forum/mpi-issues/issues/500) and [PR#592](https://github.com/mpi-forum/mpi-standard/pull/592).*

# Proposal

Update the IN handle arguments in the LIS of MPI_T calls where appropriate.

# Changes to the Text

https://github.com/mpi-forum/mpi-standard/pull/548

# Impact on Implementations

none

# Impact on Users

Better/Correct reflection of which routines actually modify the opaque objects of MPI_T handles.

# References and Pull Requests

I/O PRs & discussion:
- [PR#455](https://github.com/mpi-forum/mpi-standard/pull/455): Initial PR with changes to LIS
- [PR#425](https://github.com/mpi-forum/mpi-standard/pull/425): Fixup PR to revert some of the changes

**Comment by mahermanns** [comment]
@puribangalore @RolfRabenseifner The remaining LIS entries in the MPI_T chapter were not yet fixed, as it was unclear whether they would satisfy the *modified opaque object* rule in Terms 2.3. Could you advise here?

**Comment by mahermanns** [comment]
During the discussion at the December'22 meeting, we agreed that we need to have a closer look especially on the second commit.

**Comment by mahermanns** [comment]
@wesbland After the discussion of last week on this ticket during the Feb 1 meeting, shouldn't it have the "scheduled vote" tag or do we need to re-read this?

**Comment by wesbland** [comment]
Yep. Sorry about that. This was the only errata item and I forgot to tag it for a reading and a vote.

**Comment by wesbland** [comment]
This passed an [errata vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-08.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 27
	<td> 0
	<td> 4
</table>
