### ISSUE TITLE
Fix undefined behaviour of MPI_Info_get_string caused by binding to MPI_Info_set

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#444]
# Problem

The outcome of `MPI_Info_get_string` is currently bound to the keys added by `MPI_Info_set` and therefore undefined for info objects which may have already associated default (key,value) pairs.

E.g., the info of `MPI_COMM_WORLD` in Open MPI 4.0.5 shows the following defaults for my system:
```
$ ./mpi_info 
MPI_COMM_WORLD info:
-----
mpi_assert_no_any_source: false
mpi_assert_allow_overtaking: false
```

# Proposal

Remove binding to `MPI_Info_set` from the `MPI_Info_get_string` description.

# Changes to the Text
see PR https://github.com/mpi-forum/mpi-standard/pull/545/files

# Impact on Implementations

Behavior of implementation clarified.

# Impact on Users

Behavior of implementation clarified.

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/545

**Comment by wesbland** [comment]
@cniethammer You can go ahead and make your branch into a PR.

**Comment by wesbland** [comment]
Is this an issue that needs to be addressed in MPI 4.0? Or is this targeting 4.1?

**Comment by cniethammer** [comment]
I'd be happy to have this in 4.0 but would also be fine if it get's onto the list for MPI 4.1 as I see that time and resources should be spent to more important topics

**Comment by devreal** [comment]
I think this needs to be in 4.0. `MPI_Info_get_string` is a new function and it should be correct from the beginning.

**Comment by devreal** [comment]
I just checked the text that we have for `MPI_Info_get_string` and what was there for `MPI_Info_get` 3.1. The text is the same:

```
This function retrieves the value associated with key in a previous call to `MPI_INFO_SET`.
```

I suggest to change this to

```
This function retrieves the value associated with key, e.g., as set in a previous call to `MPI_INFO_SET` or default values provided by the implementation for info objects associated with communicator, window, and file objects.
```

There is another quibble in the description of `MPI_Info_get_string` that was copied over from `MPI_Info_get`:

```diff
- If key is larger than MPI_MAX_INFO_KEY , the call is erroneous.
+ If key is longer than MPI_MAX_INFO_KEY , the call is erroneous.
```

**Comment by cniethammer** [comment]
I guess, the question here is then if a corresponding change to `MPI_Info_get` should go into an errata back to MPI 2.1 where it was introduced.

**Comment by martinwjschulz** [comment]
Discussed on 3/17 - will add suggested change from above, after that, additional reviews from CC needed

**Comment by cniethammer** [comment]
@schulzm I included the suggested change and addressed two more places with the same spelling issue.
