### ISSUE TITLE
Fix to the Collective Chapter for the rank/process/group/file/win/communicator nomenclature

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#448]
# Problem

Terminology requires that "rank" and "process rank" and "task" be eliminated in favor of new, canonical nomenclature that always scopes the process to have a rank w.r.t. a group of a communicator, group, or underlying group of a file, window, or communicator.

# Proposal

The Forum agrees the nomenclature must be updated as proposed

# Changes to the Text

Naming of processes is always with regard to ranks related to the underlying object, not as an absolute.

# Impact on Implementations

None.

# Impact on Users

The user community gets better nomenclature and the standard improves considerably.

# References and Pull Requests

TBD.

**Comment by tonyskjellum** [comment]
Latest PDF:

[mpi40-report-PR541-f1c78b3-23feb21.pdf](https://github.com/mpi-forum/mpi-issues/files/6032098/mpi40-report-PR541-f1c78b3-23feb21.pdf)

**Comment by wesbland** [comment]
This wasn't read at the December 2022 meeting. The last opportunity for MPI 4.1 is to have it ready at the March 2022 meeting (and it needs to "pass" the reading).

@tonyskjellum Are you (or is someone else) planning to push this forward or should we move it out of the plan for MPI 4.1?
