### ISSUE TITLE
Fix wrong term "Cartesian process group" in section 8.5.6

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#449]
# Problem
The text describing `Cartesian Shift Coordinates` in MPI-4 Section 8.5.6 uses the term "Cartesian process group".
This is wrong, as topology information is added to communicators as specified in MPI-4 Section 8.3 .

# Proposal
PR https://github.com/mpi-forum/mpi-standard/pull/632 (rebase of https://github.com/mpi-forum/mpi-standard/pull/542)

# Impact on Implementations
- Behavior of implementation clarified

# Impacts on Users
- Behavior of implementation clarified

# References
* new PR rebased on 4.x branch: https://github.com/mpi-forum/mpi-standard/pull/632
* original PR: https://github.com/mpi-forum/mpi-standard/pull/542
* previous fix of this kind in issue #311

**Comment by wesbland** [comment]
This issue had an errata vote on 2021-12-07, which passed:

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 1
</table>
