### ISSUE TITLE
Errata: MPI_Wait

### ISSUE THREAD

**Issue by jdinan** [mpi-forum/mpi-issues#45]
# Problem

There is a typo in MPI_Wait on page 53, line 25:

> Any other type of request is ___ and the request handle is set to MPI_REQUEST_NULL. MPI_WAIT is a non-local operation.

The word "deallocated" should be in the underlined blank.

# Proposal

Add "deallocated" to this sentence.

# Changes to the Text

> Any other type of request is _deallocated_ and the request handle is set to MPI_REQUEST_NULL. MPI_WAIT is a non-local operation.

# Impact on Implementations

None

# Impact on Users

None

# References

**Comment by rsth** [comment]
This has been reported before (http://lists.mpi-forum.org/mpiwg-p2p/2015/12/index.php) and has already been fixed in the source. It is also in the MPI 3.1 errata.

**Comment by jdinan** [comment]
Thanks, and sorry that I missed this.  I'll make sure to check the errata document next time.
