### ISSUE TITLE
Clarifications of PR#423 uses wrong language

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#453]
# Problem

[PR#423](https://github.com/mpi-forum/mpi-standard/pull/423) introduced text that uses "must" where it should have used "shall".

# Proposal

Replace "must" with "shall"

# Changes to the Text

https://github.com/mpi-forum/mpi-standard/pull/523

# Impact on Implementations

none

# Impact on Users

none

# References and Pull Requests

**Comment by mahermanns** [comment]
Closed as the corresponding [PR#523](https://github.com/mpi-forum/mpi-standard/pull/523) is already merged.

**Comment by wesbland** [comment]
This should stay open until we've finished voting. I've moved it to the "Merged and Ready to Vote" project column.

**Comment by wesbland** [comment]
I'm moving this back to "in progress". Unfortunately the PR needed to be-targeted for the `mpi-4-rc-june` branch and now needs to be recreated and re-merged.
