### ISSUE TITLE
Fix to the Entire Standard for the rank/process/group/file/win/communicator nomenclature

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#455]
# Problem

We will agree on a means to rename "rank," "task" etc to be fully specified and reflective of the underlying
group, communicator, file, window.

***EDIT:*** From @jsquyres: my intent with raising the issue during the Feb 2021 meeting was more about clarifying where the text mis-uses "rank" to indicate a unique ID for an MPI process.  E.g., cleaning up places where the text is incontrovertibly incorrect, such as "MPI process rank X".  That somehow got translated into "we must append every single use of 'rank' in the document to be "rank in communicator|window|file", which was not my intent.

# Proposal

Agree on and implement changes.  Make it part of the defined, approved nomenclature. Agree on if for MPI-4.0 or MPI-4.1. 

# Changes to the Text

The text will be appropriately changed throughout.

None.

The user community will get better nomenclature.

# References and Pull Requests

Tickets for I/O, Partitioned, and Collective were done as demonstrations but may be mooted by this Ticket once the Forum votes on its preferred way of capturing the process naming vs. rank vs. group vs. other opaque handle..

https://github.com/mpi-forum/mpi-issues/issues/448
https://github.com/mpi-forum/mpi-issues/issues/446
https://github.com/mpi-forum/mpi-issues/issues/445
https://github.com/mpi-forum/mpi-standard/pull/549

**Comment by cniethammer** [comment]
Adding for reference suggested improvements/fixes in Process Topologies chapter: https://github.com/mpi-forum/mpi-standard/pull/543

**Comment by tonyskjellum** [comment]
@cniethammer thank you.

**Comment by wesbland** [comment]
Based on the discussion from the 2021-03-03 virtual meeting, I'm going to close this issue in favor of the chapter-specific discussions listed above.
