### ISSUE TITLE
Improvements around the word 'rank' in the Process Topologies chapter

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#457]
# Problem

The word "rank" is often used incorrectly in the MPI standard as it has only meaning in the context of a group.

# Proposal
* provide alternative text for unclear formulations that are not covered in Terms and other parts, e.g., "ranking", "process rank", "group rank"
* add group context information to "rank" usage where necessary
* reference the communicator to which a group belongs where necessary
* think about additions of new (short) terms for long formulations that make reading descriptions hard.

# Changes to the Text
Suggested improvements can be found in
https://github.com/mpi-forum/mpi-standard/pull/543/files

# Impact on Implementations
Behavior of implementation clarified.

# Impact on Users
Behavior of implementation clarified.

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/543

**Comment by cniethammer** [comment]
New PR based on the current mpi-4.x version targeting MPI 4.1 is in preparation. Discussion of changes draft within the Topology WG planed before presentation to the forum at the December meeting.

Branch in preparation under https://github.com/cniethammer/mpi-standard/tree/chap-topol-cleanup

**Comment by wesbland** [comment]
This wasn't read at the December 2022 meeting. The last opportunity for MPI 4.1 is to have it ready at the March 2022 meeting (and it needs to "pass" the reading).

@cniethammer / @RolfRabenseifner Are you (or is someone else) planning to push this forward or should we move it out of the plan for MPI 4.1?

**Comment by RolfRabenseifner** [comment]
See yellow marker and PR804 marker on pages 367, 370-372, 375-378, 380, 383, 388 in
[mpi41-report_Issue669_PR788.pdf](https://github.com/mpi-forum/mpi-standard/files/10758712/mpi41-report_Issue669_PR788.pdf)[mpi41-report_Issue457_PR804.pdf](https://github.com/mpi-forum/mpi-standard/files/10831527/mpi41-report_Issue457_PR804.pdf)

**Comment by cniethammer** [comment]
@jeffhammond  Thanks for bringing this up!

Yes, we tried to address this in MPI 4.0 alread with the mentioned PR.
I quickly updated https://github.com/mpi-forum/mpi-standard/pull/98 to reflect the latest mpi-4.x and be happy to see support for bringing this forward.

**Comment by wesbland** [comment]
This passed a [1st vote](https://mpi-forum.org/meetings/2023/05/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 28
    <td> 0
    <td> 4
</table>

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2023/07/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 34
    <td> 0
    <td> 0
</table>
