### ISSUE TITLE
Issue J-a "I/O + refs" - PR455 + PR425 + PR552 (formerly PR540) applied to RC-4-June

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#466]
# Problem

Issue J "I/O" - exactly the io.tex and refs.bib in PR552, which automatically combines PR455 + PR425 + PR552,
i.e., https://github.com/mpi-forum/mpi-standard/pull/455 + https://github.com/mpi-forum/mpi-standard/pull/425 + https://github.com/mpi-forum/mpi-standard/pull/552
now to be committed with a new PR https://github.com/mpi-forum/mpi-standard/pull/558 to RC-4-June

PR552 contains the first three commits from PR540 (https://github.com/mpi-forum/mpi-standard/pull/540). These three commits were successfully read at the feb. 2021 forum meeting.

On March 30, 2021 and later, Issue J was split into 4 parts:
- Remove LIS Changes in I/O Chapter (new Issue https://github.com/mpi-forum/mpi-issues/issues/495 with PR https://github.com/mpi-forum/mpi-standard/pull/587) 
- J-a: all content without the "process --> \MPI/ process" changes (this Issue https://github.com/mpi-forum/mpi-issues/issues/466 with PR https://github.com/mpi-forum/mpi-standard/pull/558)
- J-b: all the "process --> \MPI/ process" changes (new Issue https://github.com/mpi-forum/mpi-issues/issues/494 with PR https://github.com/mpi-forum/mpi-standard/pull/586)
- remaining stuff that may be removed from previous three parts and that may or should be address in MPI-4.1 (PR https://github.com/mpi-forum/mpi-standard/pull/588)

For latest commented pdf, see also  [Issue 405](https://github.com/mpi-forum/mpi-issues/issues/405)

# Proposal

# Changes to the Text

# Impact on Implementations

# Impact on Users

# References and Pull Requests

PR  https://github.com/mpi-forum/mpi-standard/pull/558 is now closed.
All remaining proposed changes are now in PR https://github.com/mpi-forum/mpi-standard/pull/588.

**Comment by tonyskjellum** [comment]
https://github.com/mpi-forum/mpi-standard/pull/552 contains the first three commits from PR540 that were read successfully at the February, 2021 meeting.

**Comment by RolfRabenseifner** [comment]
@wesbland Please see https://github.com/mpi-forum/mpi-standard/pull/558#issuecomment-809520221

Therefore, I put this issue 466 back into 4.0 "Ready to merge"

**Comment by tonyskjellum** [comment]
@RolfRabenseifner and I have decided to mark this ticket as "overtaken by events" as we streamline the solution in PR https://github.com/mpi-forum/mpi-standard/pull/588 and Issue mpi-forum/mpi-issues#350 .
