### ISSUE TITLE
Issue K - MPI_REQUEST_GET_STATUS with same progress as MPI_TEST

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#468]
# Problem

Issue K "Progress of MPI_REQUEST_GET_STATUS" - PR553,
i.e., https://github.com/mpi-forum/mpi-standard/pull/553
now to be committed with a new PR https://github.com/mpi-forum/mpi-standard/pull/564 to RC-4-June

New PR: https://github.com/mpi-forum/mpi-standard/pull/667

# Proposal

For latest commented pdf, see  [Issue 405](https://github.com/mpi-forum/mpi-issues/issues/405),
especially see page 83:
The new additional sentence for MPI_REQUEST_GET_STATUS is

> The progress rule for MPI_TEST, as described in Section 3.7.4, also applies to MPI_REQUEST_GET_STATUS.

It had a sucessful reading at the MPI Forum meeting Feb. 2021 

The MPI forum decision on adding this clarification to MPI-4.0 is based on three reasons:
- This clarification is missing since MPI-1, but with now adding MPI_Parrived, we have 4 of these test routines.
  - MPI_Test with the explicit "eventually flag=true" rule,
  - MPI_Win_test/wait refering to MPI_Test/Wait,
  - MPI_Parrived with the explicit "eventually flag=true" rule, and
  - **only for MPI_Request_get_status there is no such explicit "eventually flag=true" rule

although:
- Major use-cases of MPI_Request_get_status are explicitly telling that the  "eventually flag=true" rule applies:
  https://cpp.hotexamples.com/examples/-/-/MPI_Request_get_status/cpp-mpi_request_get_status-function-examples.html
  >     int flag = 0;
  >     while (!flag)
  >     {
  >         nanosleep(&ts, nullptr);
  >         ts.tv_nsec = std::min(size_t(ts.tv_nsec << 1), nsec_max);
  >         MPI_Request_get_status(req, &flag, status); // Always returns success
  >     }
  >     return MPI_Wait(&req, status); // release the request object

  Two out of the three hottest uses of MPI_Request_get_status using it in a while loop!

- During the meeting, the members checked that
   - mpich internally calls the progress engine during MPI_Request_get_status, and
   - OpenMPI also internally calls the progress engine during MPI_Request_get_status.

- By @Wee-Free-Scot: The introduction of Section 3.7.6 *Non-Destructive Test of status*
  > This call is useful for accessing the information associated with a request, without freeing the request (in case the user is expected to access it later). It allows one to layer libraries more conveniently, since multiple layers of software may access the same completed request and extract from it the status information. 

  In principle, this introduction requires the same progress rule as MPI_Test already has.

The proposal was discussed during the MPI Forum meeting on Feb. 23-24, 2021, see 
recordings
- https://www.youtube.com/watch?v=T3ZoegAoBDw  Day 3 time-slot 2:40:12 - 2:41:30 (major discussion)
- https://www.youtube.com/watch?v=woTNuYEj64k    Day 4 time-slot 1:33:30 - 1:35:30 (reading)

# Changes to the Text

The new additional sentence for MPI_REQUEST_GET_STATUS is

> The progress rule for MPI_TEST, as described in Section 3.7.4, also applies to MPI_REQUEST_GET_STATUS.

# Impact on Implementations

None, because existing MPI applications and the used MPI libraries already use respectively implemented progress for MPI_Request_get_status.

# Impact on Users

Clarity that existing usage is correct.

# References and Pull Requests

~~PR https://github.com/mpi-forum/mpi-standard/pull/564~~
PR https://github.com/mpi-forum/mpi-standard/pull/667

**Comment by RolfRabenseifner** [comment]
@schulzm @wesbland @wgropp and all,

> Please let us know if you have any questions or concerns - we will also address
> this in the meeting next week.

I detected that also Issue (K=) 468 was moved to MPI-4.1.

I updated the issues's abstract with a summary of the discussion
(which was partially within the Parrived progress discussion)
at the Feb. 2021 meeting.

Adding a 4th such test routine (after MPI_Test, Request_get_status, Win_test, Parrived),
it gets significantly more evident if for only one routine, Request_get_status, 
there is no such written progress guarantee in the standard.

Therefore, we did this analysis and reading of adding at the Feb. meeting 
for voting it into the standard in June.

There is no reason to break this result from the Feb. 2021 meeting.

Therefore, I put https://github.com/mpi-forum/mpi-issues/issues/468
back to the triage.

@schulzm  please put it for tomorrow on the agenda.

**Comment by wesbland** [comment]
To avoid cross-talk, I'm going to refer people to the email thread for this conversation. If a change needs to be made, it will be brought back here.

https://lists.mpi-forum.org/pipermail/mpi-forum/2021-March/007348.html

**Comment by RolfRabenseifner** [comment]
Comments from the virtual MPI meeting April 14, 2021:
- The progress text on MPI_TEST should be generalized.
- Only with this, we can refer to it also for MPI_Win_test.
- Alternatively, the wording for MPI_Win_test can be with its own "eventually" rule.
- By @tonyskjellum: MPI_REQUST_GET_STATUS may/should be appended by ANY/ALL/SOME variants.
- We should do a general section in terms on progress.
- Also dealing with the text on wait.

This should by the **semantic terms** working group.

**Comment by wesbland** [comment]
@RolfRabenseifner Which PR is addressing this? Can that PR have test in the description to close this issue (i.e., "Fixes #468")?

**Comment by Wee-Free-Scot** [comment]
I have re-created the PR for this issue because all previous PRs for it have been closed without merging.

Intent: revive this topic for the next voting meeting. It has been through a lot of procedure already, perhaps we can dispatch this quickly (@schulzm)?

**Comment by wesbland** [comment]
This one is marked as having had a reading, but given that it sat for a year and needed a new PR, does it need to be re-read? Has anything changed since the last reading?

If nothing has changed, my opinion is that doing an "quick" unofficial re-reading during a VM and publishing it on the mailing list is probably enough. It's relatively small, even if the semantics are more extensive so giving people some time to think about it would be a good idea.

**Comment by Wee-Free-Scot** [comment]
@wesbland the new PR was only needed because the RC->release procedure for MPI-4.0 closed all open PRs. I recreated Rolf's PR with exactly the same changes (except the change-log is for MPI-4.1 not for MPI-4.0). AFAIK, there are no material changes since Rolf's reading. (IMHO, this should have made it into MPI-4.0)

**Comment by wesbland** [comment]
I agree. I meant it mostly because of the fact that it's been more than a year since the reading. I don't necessarily think it needs a new official reading. Just a reminder before we vote.

**Comment by Wee-Free-Scot** [comment]
I'll set the milestone for this one to Dec 22 -- we need to figure out if that will be a reading or a 1st vote.

**Comment by RolfRabenseifner** [comment]
@Wee-Free-Scot Thank you for re-creating the PR based on now MPI-4.0.

@ all assignees, if you not complain, I would propose to go to the 1st vote. It was discussed and read very late during the MPI-4.0 process. It is independent on what we'll propose as an additional section on progress in the terms chapter, and based on the analysis during an MPI forum meeting, users already use this progress rule and all implementors have it also implemented.

**Comment by RolfRabenseifner** [comment]
@raffenet @isubsmith
 @regrant @wgropp @cblaas

 @Wee-Free-Scot,
if you not complain, I would propose to go to the 1st vote. It was discussed and read very late during the MPI-4.0 process. It is independent on what we'll propose as an additional section on progress in the terms chapter. Based on the analysis during an MPI forum meeting, users already use this progress rule and all implementors have it also implemented.

**Comment by Wee-Free-Scot** [comment]
I personally have no objection to either option but I cannot speak for the whole MPI Forum.

My point is that the MPI Forum need to decide whether doing a 1st vote without re-reading:
1) fits with the MPI Forum's rules (determined by the chair and secretary) and
2) feels acceptable to a majority of voting members (assessed by the chair and secretary).

@wesbland @schulzm I will announce either a reading or a 1st vote, whichever you decide.

**Comment by wesbland** [comment]
The rules are intentionally vague on this to give the authors latitude to decide what they want to do. If you'd like to move forward with the first vote, that's fine. It's up to each voter to decide how they feel about the issue and whether or not they had any remaining questions. Feel free to announce this one as a first vote.

**Comment by RolfRabenseifner** [comment]
I'll try to also do a short re-reading Nov.2, in the "progress" virtual meeting

**Comment by schulzm** [comment]
This, plus a summary before we vote (as Wes suggested), sound OK to me - if there are complaints in the December meeting, we can always pull the vote and count it as a new reading, as it will have been announced two weeks earlier anyway

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 28
	<td> 0
	<td> 5
</table>

**Comment by wesbland** [comment]
This passed a [second vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-08.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 26
	<td> 0
	<td> 5
</table>
