### ISSUE TITLE
Fix Incorrect Usage of Rank/Task/etc. in Process Management Chapter

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#478]
# Problem

Replace the incorrect usage of the words "rank", "task", etc. to be correctly specified and reflective of the underlying group, communicator, file, or window.

# Proposal

Read through the entire chapter to find all problematic instances and correct them.

# Changes to the Text

There is unlikely to be a one-size-fits-all solution so the chapter committee will need to consider each occurrence.

# Impact on Implementations

None

# Impact on Users

We will hopefully begin the process of avoiding the incorrect terminology of referring to processes as ranks and other incorrect usages.

# References and Pull Requests

There was a catch-all issue to correct this in https://github.com/mpi-forum/mpi-issues/issues/455, but this is being divided up to cover all chapters.

**Comment by Wee-Free-Scot** [comment]
I added the suggested ticket 0 label -- we can upgrade to errata if we discover controversial instances or need guidance from the wider MPI Forum.

**Comment by Wee-Free-Scot** [comment]
I added a PR review with some additional terminology fixes. I have not examined the entire chapter, just the PR diff.

@hppritcha IMHO. we should push on this, targeting the MPI-4.1 release.

**Comment by wesbland** [comment]
This passed a [1st vote](https://mpi-forum.org/meetings/2023/05/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 28
    <td> 0
    <td> 4
</table>

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2023/07/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 34
    <td> 0
    <td> 0
</table>
