### ISSUE TITLE
RMA Notification

### ISSUE THREAD

**Issue by jdinan** [mpi-forum/mpi-issues#48]
## Problem Statement

In passive target mode, notifying the target that data has been transmitted is currently inefficient. It requires sending additional messages after operations that are to be notified have been remotely completed.
## Proposed Solution 1: Sync-and-Notify, Window Counter

Addition of new "synchronize-and-notify" routines:

```
int MPI_Win_flush_notify(int rank, MPI_Win win);
int MPI_Win_unlock_notify(int rank, MPI_Win win);
int MPI_Win_flush_all_notify(MPI_Win win);

int MPI_Win_get_notify(MPI_Win win, long count);
int MPI_Win_set_notify(MPI_Win win, long count);
int MPI_Win_wait_notify(MPI_Win win, long geq_value);
```

A notification counter is associated with the window, and is incremented at the target after the given passive target epoch has completed at the target (i.e. data is visible to the target process). Get, set, and wait functions are provided to enable a process to query the number of notifications it has received.

Criticism: Since the notification is separate from communication operations, e.g. put-and-notify, this can require two separate operations, which will not improve performance.
## Proposed Solution 2: Op-and-Notify, Window Counter

Addition of new "communicate-and-notify" routines:

```
int MPI_Put_notify(..., MPI_Win win); /* Identical args as MPI_Put */
int MPI_Get_notify(... , MPI_Win win);
int MPI_Accumulate_notify(..., MPI_Win win);

int MPI_Win_get_notify(MPI_Win win, long count);
int MPI_Win_set_notify(MPI_Win win, long count);
int MPI_Win_wait_notify(MPI_Win win, long geq_value);
```

A notification counter is associated with the window, and is incremented at the target after the given RMA operation has completed at the target (i.e. data is visible to the target process). Get, set, and wait functions are provided to enable a process to query the number of notifications it has received.

Criticism: Only one counter per window.
## Proposed Solution 3: Op-and-Notify, Matched Counter

Torsten's proposal. Details to come...
## Impact on Implementations

Describe changes that implementations will be required to make here.
## Impact on Users

Describe the changes that will impact users here.
## References

[Original Trac Ticket](https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/439)
[Reducing Synchronization Overhead Through Bundled Communication](http://rd.springer.com/chapter/10.1007%2F978-3-319-05215-1_12)

**Comment by jeffhammond** [comment]
MPI_Get_notify and MPI_Win_get_notify - no that's not confusing at all :-)



-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by jdinan** [comment]
Duplicate of #59
