### ISSUE TITLE
Fix Incorrect Usage of Rank/Task/etc. in Language Bindings Chapter

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#485]
# Problem

Replace the incorrect usage of the words "rank", "task", etc. to be correctly specified and reflective of the underlying group, communicator, file, or window.

# Proposal

Read through the entire chapter to find all problematic instances and correct them.

# Changes to the Text

There is unlikely to be a one-size-fits-all solution so the chapter committee will need to consider each occurrence.

# Impact on Implementations

None

# Impact on Users

We will hopefully begin the process of avoiding the incorrect terminology of referring to processes as ranks and other incorrect usages.

# References and Pull Requests

There was a catch-all issue to correct this in https://github.com/mpi-forum/mpi-issues/issues/455, but this is being divided up to cover all chapters.

**Comment by RolfRabenseifner** [comment]
I looked for instances and found only MPI-4.0 page 816 line 40 and page 817 line 33:

- Page 816, begin of line 40 reads 
> same on process 1 and process 0.

but should read
> same on the processes with \code{myrank=1} and \code{myrank=0}.

- Page 817, begin of line 33 reads 
> If processes 0 and 1 are on different machines

but should read
> If the processes with \code{myrank=1} and \code{myrank=0} are on different machines

**Comment by wesbland** [comment]
This wasn't read at the December 2022 meeting. The last opportunity for MPI 4.1 is to have it ready at the March 2022 meeting (and it needs to "pass" the reading).

@tonyskjellum / @RolfRabenseifner / @puribangalore Are you (or is someone else) planning to push this forward or should we move it out of the plan for MPI 4.1?

**Comment by RolfRabenseifner** [comment]
See yellow marker and PR803 marker on pages 779-780, 802 in
[mpi41-report_Issue485_PR803.pdf](https://github.com/mpi-forum/mpi-standard/files/10831598/mpi41-report_Issue485_PR803.pdf)

**Comment by wesbland** [comment]
This passed a [1st vote](https://mpi-forum.org/meetings/2023/05/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 28
    <td> 0
    <td> 4
</table>

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2023/07/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 34
    <td> 0
    <td> 0
</table>
