### ISSUE TITLE
Incomplete listing of communicator duplication functions

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#489]
# Problem

Section 7.7.2 in the current 4.0 draft states:

> The comm_copy_attr_fn function is invoked when a communicator is duplicated by `MPI_COMM_DUP` or `MPI_COMM_IDUP`.

This list is missing `MPI_COMM_DUP_WITH_INFO` and `MPI_COMM_IDUP_WITH_INFO`. 

There are other instances of this problem that I found:

- AtoI at the end of Section 7.3.3
- Beginning of Section 7.7.1
- Section 7.7.5
- Description of `MPI_COMM_DELETE_ATTR`

# Proposal

To avoid naming all functions explicitly, I suggest to simply refer to the duplication functions described in Section 7.4.2, e.g., 

> The comm_copy_attr_fn function is invoked when a communicator is duplicated by any of the communicator duplication functions described in Section 7.4.2.

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/578

**Comment by martinwjschulz** [comment]
Discussed on 3/17, CC will propose change and bring this to next virtual meeting

**Comment by GuillaumeMercier** [comment]
@devreal : I disagree with what you propose and I would prefer to explicitly list the functions. If we write "communicator duplication functions described in Section 7.4.2.",  readers might overlook the _duplication_ word in there and think wrongly that it applies also to communicator _creation_ functions. @wgropp, @tonyskjellum @pavanbalaji : what is your take on this? I will create the PR accordingly.

**Comment by GuillaumeMercier** [comment]
@devreal: however, I agree with what you propose for the AtoI at the end of Section 7.3.3, because it lists not only communicator duplication functions, but also communicator creation ones.

**Comment by wgropp** [comment]
In most cases, I prefer to avoid a list that will have to be maintained (witness this very list), but I don't believe we have a short, precise way to describe the functions that duplicate a communicator as opposed to creating a new version of the communicator with the identical group (MPI_IDENT from MPI_GROUP_COMPARE) (e.g., with MPI_COMM_SPLIT and the right choice of arguments). In this special case, an explicit list is probably the best choice. Maintenance of that list should not be too hard, as I hope we don't need to add to it.
