### ISSUE TITLE
Issue L - Progress references in General Index - for RC-4-June

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#491]
# Problem

This is an addendum to Issue K=[#468](https://github.com/mpi-forum/mpi-issues/issues/468) and [PR564](https://github.com/mpi-forum/mpi-standard/pull/564),
see last item of the comment there: https://github.com/mpi-forum/mpi-standard/pull/564#issuecomment-799978311

# Proposal

Adding references about "progress" to the global index for: 
  - In Chapter 3 _Point to Point Communication_: small updates
  - In Chapter 6 _Collective Communication_, Section 6.14 _Correctness_:
     Examples 6.31 and 6.36 on pages 306 and 308
  - In Chapter 11 _Process Initialization, Creation, and Management_, Section 11.2 _The World Model_, 11.2.2 _Finalizing MPI_:
     Example 11.6 + advice to implementors, page 496 lines 28-48
  - In Chapter 11 _Process Initialization, Creation, and Management_, Section 11.3 _The Sessions Model_, 11.3.1 _Session Creation and Destruction Methods_:
     MPI_SESSION_FINALIZE (here, the final wording does not yet exists)
  - In Chapter 11 _Process Initialization, Creation, and Management_, Section 11.6 _MPI and Threads_, 11.6.1 _General_:
     Page 517 line 28
  - In Chapter 12 _One-Sided Communications_, Section 12.7.3 _Progress_: The section title should be referenced.
     (This section includes the interesting rationale on page 619 lines 5-25, which helped a lot to understand the _weak-local_ characteristics of the definition of MPI's _local procedure_ and this rationale includes the summary sentence cited above.)
  - Chapter 13 _External Interfaces_, Section 13.2 _Generalized Requests_: Page 631 lines 25
  - Chapter 14 _I/O_, Section 14.6.3 _Progress_: Page 711, line 8 
  - Chapter 14 _I/O_, Section 14.6.5 _Nonblocking Collective File Operations_: Page 711, line 48. 

Page refs to https://github.com/mpi-forum/mpi-issues/files/6136676/mpi40-report-rc-4-june-F-PR560.pdf

# Changes to the Text

Important: **This issue does not change any binding text, advice, rationale or example.** 
It only adds missing references to the general index. And it formats the referenced keyword "progress" as \mpiterm, i.e., _italic_. 

See PR https://github.com/mpi-forum/mpi-standard/pull/569 and [mpi40-report-rc-4-june-L-PR569.pdf](https://github.com/mpi-forum/mpi-issues/files/6150100/mpi40-report-rc-4-june-L-PR569.pdf)

# Impact on Implementations

None.

# Impact on Users

Progress rules are easier to be found in the MPI standard

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/569

**Comment by Wee-Free-Scot** [comment]
This might be an issue that should be postponed into the MPI-4.1 timeframe.

There are no "emergencies" here, except perhaps for the new API being added for MPI_SESSION_FINALIZE (because it is new text). However, that is a blocking procedure and is therefore covered by the general statement of progress that all blocking procedures must guarantee progress for all outstanding operations (@RolfRabenseifner found the reference, page 619 lines 5-6).

**Comment by RolfRabenseifner** [comment]
See also pdf: [mpi40-report-rc-4-june-L-PR569.pdf](https://github.com/mpi-forum/mpi-issues/files/6150100/mpi40-report-rc-4-june-L-PR569.pdf)

**Comment by RolfRabenseifner** [comment]
> This might be an issue that should be postponed into the MPI-4.1 timeframe.
> 
> There are no "emergencies" here, except perhaps for the new API being added for MPI_SESSION_FINALIZE (because it is new text). However, that is a blocking procedure and is therefore covered by the general statement of progress that all blocking procedures must guarantee progress for all outstanding operations (@RolfRabenseifner found the reference, page 619 lines 5-6).

Especially for MPI_SESSION_FINALIZE, it is more than only to guarantee progress:
MPI_SESSION_FINALIZE (same as FINALIZE) must guarantee the completing of all needed progress before it returns.
See [mpi40-report-rc-4-june-L-PR569.pdf](https://github.com/mpi-forum/mpi-issues/files/6150100/mpi40-report-rc-4-june-L-PR569.pdf) page 496, lines 26-48.
For the moment, we provided the possibility that MPI_SESSION_FINALIZE can do this _final progress_, but we mention it only for MPI_FINALIZE. Of course this issue add the required entry to the genaral index, see 
progress --> finalize --> buffered data, 496

**Comment by RolfRabenseifner** [comment]
I'm not sure whether we treated index entries as chapter committee or editor changes.

**Comment by Wee-Free-Scot** [comment]
The "final progress" is a good point. IMHO, that one item should be split out into its own issue and PR, so that it can be proposed as an "emergency fix" for MPI-4.0 -- but the rest look like existing carry-overs from MPI-3.1 and before.

We will need to iterate on wording for that today, so it can be presented to the Forum at tomorrow's virtual meeting.

**Comment by Wee-Free-Scot** [comment]
At this stage of MPI-4.0, I suspect *all* changes require a vote -- @wesbland can help us with the rules.

**Comment by wesbland** [comment]
> I'm not sure whether we treated index entries as chapter committee or editor changes.

@RolfRabenseifner Is fine here. My general philosophy was that anything that didn't change the PDF (I know this adds entries in the index, but those are extremely minor), I marked as something that we didn't necessarily have to vote on. If it's inside of the 4-week window, the ruling gets tighter.

**Comment by RolfRabenseifner** [comment]
Okay, I'll try to get my reviews before the 4-week-deadline.

**Comment by RolfRabenseifner** [comment]
@wesbland This means, the wish to change "Progression rule" into "The progress rule" in normal chapter text is a text change and therefore will require a non-no-vote on next meeting? Or can such chapter committee changes still go witout a vote before the 4 week deadline?

**Comment by wesbland** [comment]
Yes. It will need an issue to track it and a no-no reading/vote.

**Comment by RolfRabenseifner** [comment]
@wesbland, @Wee-Free-Scot, and @tonyskjellum:
I removed all text changes from this issue and started a new one only on coll.tex to substitute the 4 locations of _progression_ into _progress_. See [Issue M = #492](https://github.com/mpi-forum/mpi-issues/issues/492).

**Comment by RolfRabenseifner** [comment]
@wesbland It looks like that you removed a wrong issue from "ready to merge".
In the protocol pptx from last meeting, https://github.com/mpi-forum/mpi-forum.github.io/raw/master/slides/2021/03/2021-03-24-rcm-frm-procedures.pptx
you wrote on slide 11:
> Issues to continue for MPI 4.0 (12):
> ......, #491

i.e., this issue here.
Its pull request https://github.com/mpi-forum/mpi-standard/pull/569 is ready and 5x approved (including Bill Gropp).
There is also no comment that these general index entries should not be done. As co-author of the general index, it is also my duty to add such entries (as also Bill did over the time). 

Therefore, I expect that you removed this issue by mistake. I was the last days completely busy, therefore I catch this only now. Therefore, please can you put it back to 4.0 Ready to Merge.

**Comment by wesbland** [comment]
Yes, that's correct. This one should be in the "In Progress" column until it's been reviewed by everyone that needs to review it.
