### ISSUE TITLE
Issue M - progression->progress in coll.tex

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#492]
# Problem

Only in coll.tex, the word (5x) _progression_ is used instead of _progress_ (3x in coll.tex and ~30x in other chapters).
It should be substituted by _progress_.

The problem was detected during the work for the _progress_ general index entries in [Issue L = #491](https://github.com/mpi-forum/mpi-issues/issues/491). 

# Proposal

See https://github.com/mpi-forum/mpi-standard/pull/672

# Changes to the Text

See https://github.com/mpi-forum/mpi-standard/pull/672/files

# Impact on Implementations

None

# Impact on Users

Better readable MPI standard. No confusion through a possible difference between _progression_ in MPI and _progress_ in MPI.

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/570 (closed on completion of mpi-4.0)
https://github.com/mpi-forum/mpi-standard/pull/672 (replacement, targeting mpi-4.1)

**Comment by wesbland** [comment]
@RolfRabenseifner Can the relevant PR get the text "Fixes #492" in the description please?

**Comment by wesbland** [comment]
I'm not sure who still owns this issue, but there isn't a PR for it. @Wee-Free-Scot, is this on your list?

**Comment by tonyskjellum** [comment]
I can work on it with @Wee-Free-Scot? This is news to me apologies

**Comment by Wee-Free-Scot** [comment]
Steps:
1. Re-create Rolf's branch from scratch, based off the mpi-4.x branch and pushed into the collectives fork on GitHub
2. Decide whether imprecise language "similar to" is sufficient for MPI-4.1
3. If not, propose a larger change -- codify holistic progress rules (in terms chapter?) and specialise those rules in each chapter (needs all/most chapter committees involved)

Step (1) is simple, I can do that, perhaps later today.
Step (2) needs broader engagement -- we need at least a presentation at a virtual meeting, possibly at a voting meeting.
Step (3) needs a lot of work from many stakeholders, but it's the best long-term outcome/objective, IMHO.

@tonyskjellum we should raise this at an upcoming collectives/persistent/omnibus WG meeting -- please could you put that on the schedule?

**Comment by RolfRabenseifner** [comment]
I recommend to clearly split Step 1 from 2 and 3. Steps 2+3 should be a different ticket and has nothing todo with the wording correction of the 5 remaining _progression_ into _progress_. In other words, I recommend to keep this issue simple, aas the title says.

**Comment by Wee-Free-Scot** [comment]
Step (1) is complete, see https://github.com/mpi-forum/mpi-standard/pull/672

I agree with @RolfRabenseifner that step 2+3 can & should wait for a separate issue.

**Comment by Wee-Free-Scot** [comment]
I've fixed merge conflicts -- this is a clean-up issue that should target the MPI-4.1 release.

**Comment by RolfRabenseifner** [comment]
@tonyskjellum Please can you review the 6 small changes proposed in https://github.com/mpi-forum/mpi-standard/pull/672. If all is fine (what I expect) then Bill can merge this small chapter committee change.
