### ISSUE TITLE
MPIR: Update MPIR_being_debugged scope to include MPI processes

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#5]
# Problem

`MPIR_being_debugged` is an optional global variable for the starter process. If it exists, the debugger sets this variable to 1 after attaching to the starter process and reset it to 0 immediately before detaching from it. The rationale is that some optimization can be enabled if the starter process knows it is not being debugged.

The same rationale can be applied to MPI processes as well (e.g., an MPI implementation can choose to not track the outgoing message queue if it is not being debugger).

# Proposed solution

This ticket makes a slight change to say that `MPIR_being_debugged` can be defined in the starter process *and* the MPI processes.

The original text in the MPIR-1.0 document, section 9.3, page 16:

> Global variable definition:
>
> VOLATILE int MPIR_being_debugged;
>
>> Definition is not required.
>> Definition is contained within the address space of the starter process.
>> Variable is written by the tool, and read by the starter process.
>
> MPIR_being_debugged is an integer variable that is set or cleared by the tool to notify the starter process that a tool is present.
>
> The tool sets the variable to 1 immediately after spawning or attaching to the starter process. The tool sets the variable to 0 immediately before detaching from the starter process.
>
> The starter process may monitor the state of the variable and perform certain opera- tions differently. For example, this variable might control whether or not the starter process forces the MPI processes to wait for the MPIR_debug_gate to be set.

This ticket changes that text to:

> Global variable definition:
>
> VOLATILE int MPIR_being_debugged;
>
>> Definition is not required.
>> Definition is contained within the address space of the starter process and/or any of the MPI processes which it started. 
>> Variable is written by the tool in any process where it exists.
>
> MPIR_being_debugged is an integer variable that is set or cleared by the tool to notify a process that a tool is present. If the variable exists in any MPI process, it is required that the variable is present in all MPI processes.
>
> The tool only changes the value of the variable in any process where it exists in two cases:
>
> 1. Immediately after spawning or attaching to a process, the tool sets the value to 1.
> 2. Immediately before detaching from a process, the tool sets the value to 0.
>
> Any processes defining this variable may monitor its value and perform certain opera- tions differently. For example, this variable might control whether or not the starter process forces the MPI processes to wait for the MPIR_debug_gate to be set.

See p16-17 of [the attached PDF (as of 22 Oct 2015)](https://github.com/mpi-forum/mpi-issues/files/18681/mpi-report.pdf)

# Implementation

Minimal implementation effect on MPI implementations (i.e., they can now define `MPIR_being_debugged` in MPI processes).  Slightly more implementation effort required of debuggers.

# References

Original ticket (on the old Trac system): https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/484#no3

**Comment by wesbland** [comment]
Is this ticket mpi-<next> or mpi-4.0?

**Comment by jsquyres** [comment]
@wesbland Neither -- it's for the MPIR document.

**Comment by wesbland** [comment]
Oh right…stupid question. My batch processor got over-eager.

On Dec 1, 2015, at 2:05 PM, Jeff Squyres <notifications@github.com<mailto:notifications@github.com>> wrote:


@wesbland<https://github.com/wesbland> Neither -- it's for the MPIR document.

**Comment by jsquyres** [comment]
Here is the corresponding pull request: https://github.com/mpi-forum/mpir/pull/1
