### ISSUE TITLE
Fix LIS for MPI_T events functions

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#500]
# Problem

As part of the discussion to changes to the IO chapter a discussion emerged about incorrect IN vs. INOUT arguments listed in LIS descriptions of the calls, not adhering to the terms chapter section 2.3 (4.0 RC, p. 10):

> [...] if  an  argument  is  a  handle  to  an  opaque  object  (these terms are defined in Section 2.5.1), and the object is updated by the procedure call, then the argument is marked INOUT or OUT. It is marked this way even though the handle itself is  not  modified  —  we  use  the INOUT or OUT attribute  to  denote  that  what  the  handle references is updated. [...]

Some calls of the MPI_T events interface introduced with MPI 4.0 do not adhere to this and should be fixed before they are initially published.

# Proposal

Update the IN handle arguments in the LIS of MPI_T calls where appropriate.

# Changes to the Text

https://github.com/mpi-forum/mpi-standard/pull/592 (<-- Initial PR with most of the changes)
https://github.com/mpi-forum/mpi-standard/pull/594 (<-- Amending PR with one change that got overlooked in the previous PR)

# Impact on Implementations

none

# Impact on Users

Better/Correct reflection of which routines actually modify the opaque objects of MPI_T event handles.

# References and Pull Requests

##### I/O PRs & discussion:
- [PR#455](https://github.com/mpi-forum/mpi-standard/pull/455): Initial PR with changes to LIS
- [PR#425](https://github.com/mpi-forum/mpi-standard/pull/425): Fixup PR to revert some of the changes

##### MPI_T PVAR/CVARs
- [PR#548](https://github.com/mpi-forum/mpi-standard/pull/548)

**Comment by wesbland** [comment]
This will use the errata vote system as it's a follow-on issue from #443 which was discussed at the February meeting.
