### ISSUE TITLE
Add xref in 4.0 ChangeLog for LargeCount

### ISSUE THREAD

**Issue by naughtont3** [mpi-forum/mpi-issues#501]
# Problem

The MPI 4.0 ChangeLog (B.1.2) lacks a specific reference for the large-count changes due to them being spread throughout the document.

# Proposal

Suggestion to add a cross-ref for the MPI 4.0 large-count ChangeLog entry that points to Section 19.2 (similar to how it is done in Rationale text in Sect 2.5.6).

# Changes to the Text

Suggested change in text:

"Section 19.2 and throughout the entire document"

# Impact on Implementations

# Impact on Users

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/593

**Comment by wesbland** [comment]
This seems like it might be a good idea to me to specifically mention the new section since it has a bunch of the text describing the rationale. What do you think @RolfRabenseifner and @puribangalore?
