### ISSUE TITLE
Fix Wrong Examples in Partitioned Communications Chapter

### ISSUE THREAD

**Issue by GuillaumeMercier** [mpi-forum/mpi-issues#509]
# Problem

Examples 4.2, 4.3 and 4.4 are wrong : the parameters passed to `MPI_Psend_init` and `MPI_Precv_init` are not in the right order when compared to the LIS prototype w.r.t info and communicator.

# Proposal

Change the aforementioned examples.

# Changes to the Text

N/A

# Impact on Implementations

N/A

# Impact on Users

N/A

# References and Pull Requests

See PR#607:  mpi-forum/mpi-standard/pull/607

**Comment by wesbland** [comment]
This passed an errata vote on 2021-09-10:

<table>
<tr>
	<td> Yes </td>
	<td> No </td>
	<td> Abstain </td>
<tr>
	<td> 29 </td>
	<td> 0 </td>
	<td> 1 </td>
</table>
