### ISSUE TITLE
Deprecate MPI_SIZEOF in MPI-4.0

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#51]
# Problem

MPI_SIZEOF is a Fortran-only subroutine in MPI that was created in the mid-90s because the Fortran language didn't have a way to get the size of a type.

F08 has defined both `storage_size()` and `c_sizeof()`. Neither are exactly the same as MPI_SIZEOF, but they're close enough (`storage_size()` returns the size of an individual element in bits, and `c_sizeof()` is exactly like C's `sizeof()`, in that it will return the size of an entire array if you pass it an array -- not an individual element).

Regardless, the language itself provides mechanisms to get the size of the type, so we should stop providing the MPI workaround.
# Proposal

This ticket is about deprecating MPI_SIZEOF in MPI-4.
# Changes to the Text
- Add MPI_SIZEOF to deprecated chapter
- Remove MPI_SIZEOF definition from bindings chapter
- Remove a few text references to MPI_SIZEOF
- Update a few examples to use `storage_size()` instead of MPI_SIZEOF

See the PR: mpi-forum/mpi-standard#17

[See the PDF (updated 21 May 2018)](https://github.com/mpi-forum/mpi-issues/files/2023337/deprecate-mpi-sizeof-2018-05-21.pdf)

# Impact on Implementations

None (this is just deprecation).
# Impact on Users

Technically: none (this is just deprecation).  But the small number of users who are actually using it should convert to `storage_size()` and/or `c_sizeof()`.
# References

In the Dec 2014 MPI Forum meeting (California, USA), Forum Feedback was given to overwhelmingly deprecate MPI_SIZEOF (yes: 25, no: 0, abstain: 2).

**Comment by ftillier** [comment]
Don't forget the change log entry!

**Comment by jsquyres** [comment]
@ftillier Check page 697 in the attached PDF.  :smile:

**Comment by ftillier** [comment]
Ah, it wasn't in the bulleted list for changes to the text, carry on!

**Comment by RolfRabenseifner** [comment]
I'm also good with this, but technically, in my opinion,
the following changes are needed:

- Page 604, lines 19-20 of
  https://github.com/mpi-forum/mpi-issues/files/221301/mpi-report-deprecate-mpi-sizeof.pdf
  read

    The following Fortran subroutines are deprecated; 
    the Fortran language storage_size() and c_sizeof() 
    intrinsic functions provide this functionality.

  but should read (proposal)

    The following Fortran subroutines are deprecated; 
    the Fortran language storage_size() and c_sizeof() 
    intrinsic functions provide similar functionality.
    Whereas MPI_SIZEOF() and c_sizeof() provide the size
    in bytes, the intrinsic storage_size() provides the
    size in bits.  

  Otherwise it is a direct path to the hell when people
  updating there deprecated source code.


- Page 631, lines 5-8 read

    MPI_TYPE_MATCH_SIZE can be used to obtain a size-specific
    type that matches a Fortran numeric intrinsic type by 
    first calling storage_size()in order to compute the
    variable size, and then calling MPI_TYPE_MATCH_SIZE to find
    a suitable datatype. In C, one can use the C function 
    sizeof(), instead of storage_size().

  It is necessary to mention that storage_size() returns 
  bits and not bytes. It should be written in a way that a 
  Fortran reader Need not to read the C text and vice versa.
  Proposal:

    MPI_TYPE_MATCH_SIZE can be used to obtain a size-specific
    type that matches a Fortran numeric intrinsic type by 
    first calling storage_size() in order to compute the
    variable size in bits, deviding it by 8, 
    and then calling MPI_TYPE_MATCH_SIZE to find
    a suitable datatype. In C, one can use the C function
    sizeof(), which returns the size in bytes, 
    instead of storage_size() (which returns the size in bits).


- On page 18 in Table 2.1 the following mail should be added:

   MPI_SIZEOF  MPI-4.0   ____  storage_size() 5)

  With footnote 
   5) Fortran intrinsic. It returs the size in bits instead of bytes. 
 

- In the General index on page 721, I would recommend to add 
  the keyword "MPI_SIZEOF and storage_size()"
  and all Locations of the both routines.

**Comment by jsquyres** [comment]
@RolfRabenseifner All your suggestions accepted.  PR and PDF updated.  Thanks.

**ALL YOUR FORTRAN ARE BELONG TO US.**

**Comment by jsquyres** [comment]
Two ticket 0 changes were accepted at the Bellevue, WA, USA June 2016 MPI Forum meeting:

1. In the new text, we said `dividing it by 8`.  We'll change that to `dividing it by eight`.
1. Change the new text from:

> The following Fortran subroutines are deprecated; the Fortran language storage_size() and c_sizeof() intrinsic functions provide similar functionality.

to (emphasis added just for clarity):

> The following Fortran subroutines are deprecated ***because*** the Fortran language storage_size() and c_sizeof() intrinsic functions provide similar functionality.

[New PDF after the meeting](https://github.com/mpi-forum/mpi-issues/files/305958/mpi-report-2016-06-08.pdf)

**Comment by jsquyres** [comment]
Rebased on top of `mp-3.x` branch, but no other content changes.

[New version of PDF: 2018-05-21](https://github.com/mpi-forum/mpi-issues/files/2023337/deprecate-mpi-sizeof-2018-05-21.pdf)

**Comment by schulzm** [comment]
Passed first vote at Barcelona meeting in Sep. 2018

**Comment by wesbland** [comment]
Passed second vote at San Jose meeting in December 2018
