### ISSUE TITLE
Provide a "How to Cite"

### ISSUE THREAD

**Issue by christgau** [mpi-forum/mpi-issues#512]
# Problem

IMO, this is not really a serious problem and it might be trivial, but I wonder if the forum could provide a - let's call it - recommended way to cite the standard. A quick look on the website and the doc didn't reveal such an information. Maybe that's one reason why one can find different ways the standard is referenced. Some examples (sorry, if the sources are behind paywall for you):

* [Message Passing Interface Forum: MPI: A Message-Passing Interface Standard Version 3.1 (2015). https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf](https://link.springer.com/chapter/10.1007/978-3-030-59851-8_3) -- the ideal version (?!)
* [MPI Forum (2012) MPI: a message-passing interface standard. version 3.0](https://link.springer.com/content/pdf/10.1007/s00607-013-0324-2.pdf) -- shortened author
* [2015. MPI: A Message-Passing Interface Standard Version 3.1](https://dl.acm.org/doi/pdf/10.1145/3343211.3343217) -- no real author
* [Forum, Message P. 1994. “MPI: A Message-Passing Interface Standard.” Knoxville, TN, USA: University of Tennessee.](https://joss.theoj.org/papers/10.21105/joss.00357.pdf) -- paper from 2017 references very early standard, "last name" of author comes first, "given names" truncated and abbreviated
* [Forum, M.P.I.: MPI: A Message-Passing Interface Standard. http://www.mpi-forum.org/ (September 2012)](https://hal.inria.fr/hal-01583498/document) -- similar to the example above; unclear which version is referenced (date gives a hint), "given names" get abbreviated with dots
* [The MPI Forum, MPI: A Message-Passing Interface**r** Standard, version 3.1 (2015), http://www.mpi-forum.org](https://www.epj-conferences.org/articles/epjconf/pdf/2019/19/epjconf_chep2018_04059.pdf) -- forum gets an extra "The", typo in title, URL for homepage only
* [MPI, “MPI 2.2: A Message-Passing Interface Standard”, MPI Forum, www.mpi-forum.org/docs/mpi-2.2/mpi22-report.pdf (2009).](https://link.springer.com/chapter/10.1007/978-981-10-7245-1_8) -- version number in between, author is missing forum
* [Forum, M. P. Mpi: A message-passing interface standard. Tech. rep., Knoxville, TN, USA, 2015. Version 3.1.](https://dl.acm.org/doi/pdf/10.1145/3310273.3322824) - author truncated, technical report with location "Knoxville, TN, USA" (likely the address field of the bib entry).

Putting aside diverse citation styles, some of the strange-looking appearances are very likely caused by incorrect bib entries. This is primarily a problem of authors and not one of the standard, but the standard or the forum may help people out there...

# Proposal

The official standard document as well as the website could provide a "how to cite" section, paragraph, info box, or similar things. In the standard document, the white space on page ii above the copyright notice might be a good place. Ideally, the website would provide a Bibtex file or entry for quick copy/paste. 

This probably does not eliminate different appearances due to citation styles and "home-made" bib entries, but it may help authors if there exists an approved citation note/bib entry they can use. 

A good citation of the standard would include the version number. If the citation style outputs URLs, using a URL to the standard document would be great as well. Thus, a possible straight-forward bib entry could look like this:

```bibtex
@manual{mpi40,
    author = "{Message Passing Interface Forum}",
    title  = "{MPI}: A Message-Passing Interface Standard Version 4.0",
    url    = "https://www.mpi-forum.org/docs/mpi-4.0/mpi40-report.pdf",
    year   = 2021,
    month  = jun
}
```
I chose `manual` as entry type here. I also considered `booklet` but this may not be appropriate... `misc` might be an option as well. Nevertheless, the example produces good looking results for different citation styles.

btw: What about a DOI for the standard document(s)? 

# Changes to the Text

As outlined above a citation note at the beginning of the standard document would nice. My proposal would be very much like the first example from above. Generalized for citing version X.Y from ZZZZ this may look like this:

> Message Passing Interface Forum: MPI: A Message-Passing Interface Standard Version X.Y (Month, ZZZZ). https://www.mpi-forum.org/docs/mpi-X.Y/mpiXY-report.pdf

# Impact on Implementations

None.

# Impact on Users

Users who write papers are relieved from writing an own bib entry or retrieving an old one from their repo. 😉

**Comment by schulzm** [comment]
Thanks, I added it to the MPI 4.1 board

**Comment by jprotze** [comment]
Going into a similar direction, permalinks/permalabels for specific sections would be helpful to cite sections independent of the document version. C/C++ standards use a kind of URI notion: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/n4885.pdf
Although the URI encodes the initial structure and location of a (subsubsub)section, the label is permanent and does not change when a section is moved or pro/demoted. (e.g., class.dtor seems to be demoted and now part of class.mem)

Such permalink might be useful for citing in papers, but also for MPI implementations and correctness tools when giving context for an error/diagnosis message.

**Comment by wgropp** [comment]
We can certainly add such permanent and visible labels. Do you know if there is a latex package for these, or did the C++ folks generate their own? We have a lot of our own definitions and could certainly add this, but I'd prefer to reduce the number of custom TeX definitions in the source.

**Comment by jprotze** [comment]
Looks like some costum-defined macros:
https://github.com/cplusplus/draft/blob/main/source/macros.tex#L90
Here the use for the `class.dtor` example:
https://github.com/cplusplus/draft/blob/main/source/classes.tex#L2002

**Comment by devreal** [comment]
See also: https://github.com/mpi-forum/mpi-issues/issues/384

**Comment by p-costa** [comment]
Dear all,

I need to cite the 4.0 MPI standard (thank you for taking care of the large counts issues!). Would the way indicated by the OP be fine:

```tex
@manual{mpi40,
    author = "{Message Passing Interface Forum}",
    title  = "{MPI}: A Message-Passing Interface Standard Version 4.0",
    url    = "https://www.mpi-forum.org/docs/mpi-4.0/mpi40-report.pdf",
    year   = 2021,
    month  = jun
}
```
or do you have another preferred way?

Thank you in advance.

**Comment by christgau** [comment]
Just a quick thought on the original issue: Since the MPI report is actually a private repo here at Github, adding a citation file in that repo might be helpful. It could be used as source file for the citation which finally appears in the report. On the other hand, the [raw citation file(s)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) can be easily transferred to [mpi-forum/mpi-forum.github.io](https://github.com/mpi-forum/mpi-forum.github.io).

**Comment by jeffhammond** [comment]
FWIW I don't really care how people cite MPI as long as they don't use anything that's obviously wrong.

Since no authors are listed, it's not like this contributes to our citation count.

**Comment by wesbland** [comment]
@wgropp I don't see a canonical citation for the C++ Standard, only community contributed ones (e.g., https://www.bibsonomy.org/bibtex/24b660c16d9a5ab0ad595b1555402c797/gron).

Do we need a LaTex package for this or just post an entry on the Docs page on the website like what's in the example above?

**Comment by wgropp** [comment]
The LaTeX package comments were for an upgraded way to mark and cite specific sections.  Just providing a "use this to cite" can be a simple entry.

**Comment by wesbland** [comment]
> The LaTeX package comments were for an upgraded way to mark and cite specific sections. Just providing a "use this to cite" can be a simple entry.

That makes more sense. My understanding of the ask here is to just put a note on the website for how to cite the document as a whole.

**Comment by wgropp** [comment]
I've updated the website to include a bibtex file for MPI 4.0.  We can add other formats and make this easier later, but for now, I think this is complete. The fancier label issue, if we want to pursue it, should be added as an MPI 5.0 option for consideration.

**Comment by wesbland** [comment]
Sounds like this is done to me. 👍
