### ISSUE TITLE
Process management chapter changes for 4.1

### ISSUE THREAD

**Issue by hppritcha** [mpi-forum/mpi-issues#514]
# Problem

Originally part of #338 (found during MPI 4.0 RC review), these items were deferred to MPI 4.1.

# Proposal

Address these items for MPI 4.1.

# Changes to the Text

- [ ] Section 11.2.1 in section discussing MPI_IS_THREAD_MAIN, the sentence starting with "In the case of applications using" needs to be reworked. This may need an errata reading.
- [ ]  Page 521 (481): Consider making the MPI_Init code a formal example, while pt2pt does this in the opening section, most other code snippets are defined as proper examples.
- [ ] Page 531 (491) line 9 & 10. Consider combining sentences as such “MPI_COMM_WORLD is not valid for use as a communicator and MPI_INFO_ENV is not valid for use as an info object when only using the Sessions Model”
- [ ] Page 568, in MPI_COMM_CONNECT - There is no mention of root argument in the subsequent description, which seems odd since that kind of matters. Same for MPI_COMM_ACCEPT.
- [ ]  Page 544, Table 11.1, should these be alpha sorted? but probably good to keep the grouping
- [ ]  There's a lot of use of "you" in the dynamic process part of the chapter. This doesn't really fit with the language used throughout the rest of the document. There's also one use of you in the tools chapter.
- [ ] There's a reference to an IBM SP switch. This sounds really outdated and should probably be replaced with some more general terminology at some point.

# Impact on Implementations

None.

# Impact on Users

Additional clarity.

# References and Pull Requests

Related to PR: https://github.com/mpi-forum/mpi-standard/pull/617

**Comment by hppritcha** [comment]
items in this issue are addressed by https://github.com/mpi-forum/mpi-standard/pull/617

**Comment by Wee-Free-Scot** [comment]
@hppritcha I fixed the merge conflicts for this one -- it looks like a MPI-4.1 clean up.

**Comment by wesbland** [comment]
This was read on 2022-12-08 and needs a small no-no change for the March meeting.

**Comment by wesbland** [comment]
This was re-read cleanly at the 2023-02-08 meeting.

**Comment by hppritcha** [comment]
when is this issue finally going to get voted on?

**Comment by wesbland** [comment]
It was read at the last meeting so it could be voted on any time it's announced.
