### ISSUE TITLE
Forgotten MPI_Status_set_elements_c

### ISSUE THREAD

**Issue by martinruefenacht** [mpi-forum/mpi-issues#517]
# Problem

The Embiggenment missed the introduction of MPI_Status_set_elements_c.

This was noted by a user of MPICH: https://github.com/pmodels/mpich/issues/5413

# Proposal

Correctly introduce the required embiggened procedure.

# Changes to the Text

An additional language expression.

# Impact on Implementations

Need to implement another procedure.

# Impact on Users

Can use an embiggened version of the procedure.

**Comment by Wee-Free-Scot** [comment]
In addition to adding the [_C] embiggened interface, the text describing MPI_STATUS_SET_ELEMENTS[_X|_C] needs to mention MPI_GET_ELEMENTS_C and MPI_GET_COUNT_C when listing the query procedures.

This is an opportunity to replace the inline code with simple `\mpifunc` references -- i.e. remove the argument list, which seems to be entirely superfluous (p 641, lines 29-31).

**Comment by wgropp** [comment]
+1 on using mpifunc and removing arg lists from inline text

**Comment by martinruefenacht** [comment]
@Wee-Free-Scot I removed the parameter lists, but they were already using mpifunc. No mention of _x in the text anymore. Is this better?

**Comment by wesbland** [comment]
This passed an errata vote on 2021-09-10:

<table>
<tr>
	<td> Yes </td>
	<td> No </td>
	<td> Abstain </td>
<tr>
	<td> 29 </td>
	<td> 0 </td>
	<td> 1 </td>
</table>
