### ISSUE TITLE
Incorrect use of MPI_Get_count_c, MPI_Get_elements_c, and MPI_Status_set_elements_c

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#523]
# Problem

A change that we made introduced an error in referring to the C bindings for MPI_Get_count and MPI_Get_elements for MPI_Count parameters. See https://github.com/mpi-forum/mpi-standard/pull/620 

# Proposal

Text only - remove MPI_GET_COUNT_C and MPI_GET_ELEMENTS_C from the list of MPI routines (they are not MPI routines), and add a parenthetical comment to remind the user that these C-bindings are included.

# Changes to the Text

In ei-2.tex, remove MPI_GET_COUNT_C and MPI_GET_ELEMENTS_C from

These functions modify the opaque part of \mpiarg{status} so calls
to \mpifunc{MPI\_GET\_ELEMENTS}, \mpifunc{MPI\_GET\_ELEMENTS\_X}, or \mpifunc{MPI\_GET\_ELEMENTS\_C}
will return \mpiarg{count}.

and

Calls to
\mpifunc{MPI\_GET\_COUNT} or \mpifunc{MPI\_GET\_COUNT\_C} will return a compatible value.

and 

Subsequent calls to \mpifunc{MPI\_GET\_COUNT}, \mpifunc{MPI\_GET\_COUNT\_C},
\mpifunc{MPI\_GET\_ELEMENTS}, \mpifunc{MPI\_GET\_ELEMENTS\_X}, or \mpifunc{MPI\_GET\_ELEMENTS\_C}

and 

\mpifunc{MPI\_GET\_COUNT}, \mpifunc{MPI\_GET\_COUNT\_C}, \mpifunc{MPI\_GET\_ELEMENTS}, \mpifunc{MPI\_GET\_ELEMENTS\_X}, and \mpifunc{MPI\_GET\_ELEMENTS\_C} must use a

Also note that there is no \mpifunc{MPI\_STATUS\_SET\_ELEMENTS\_C} - This is a C-binding for \mpifunc{MPI\_STATUS\_SET\_ELEMENTS}, and this should also be removed.

To remind the user that there are these special _c routines, this could be added with text such as

The C-binding routines \mpifunc{MPI\_Get\_count\_c}, \mpifunc{MPI\_Get\_elements\_c}, and \mpifunc{MPI\_Status\_set\_elements\_c} are behave as defined by their \MPI/ definitions---\mpifunc{MPI\_GET\_COUNT}, mpifunc{MPI\_GET\_ELEMENTS}, and \mpifunc{MPI\_STATUS\_SET\_ELEMENTS} respectively.

# Impact on Implementations

No change

# Impact on Users

No impact
# References and Pull Requests

See https://github.com/mpi-forum/mpi-standard/pull/620 for the PR that introduced the problem.

**Comment by Wee-Free-Scot** [comment]
> The C-binding routines \mpifunc{MPI_Get_count_c}, \mpifunc{MPI_Get_elements_c}, and \mpifunc{MPI_Status_set_elements_c} are[sic] behave as defined by their \MPI/ definitions---\mpifunc{MPI_GET_COUNT}, mpifunc{MPI_GET_ELEMENTS}, and \mpifunc{MPI_STATUS_SET_ELEMENTS} respectively.

This is a superfluous tautology, IMHO. Perhaps, if any text is needed at all, we should give advice to the user?

``` latex
\adviceToUsers{%
Whenever the value of \mpiarg{count} might be large,
the procedures \mpifunc{MPI_GET_COUNT} and \mpifunc{MPI_GET_ELEMENTS} should be called,
in Fortran, using a variable/parameter/argument[ED:please select correct word] of type \fcode{INTEGER(KIND=MPI_COUNT_KIND)} or,
in C, using the \mpifunc{MPI_Get_count_c} and \mpifunc{MPI_Get_elements_c} C-binding, respectively.%
}
```

**Comment by wgropp** [comment]
My thinking is that if the Forum got this wrong (and we did by not catching this earlier), we should take some pity on the reader. I'm good with an advice to users, in fact, I find that preferable.

**Comment by RolfRabenseifner** [comment]
@wgropp This issue can be closed, because all reported problems in ei-2.tex are resolved as a side effect of https://github.com/mpi-forum/mpi-issues/issues/518 and its merged PR623, PR829 and the finally merged [PR832](https://github.com/mpi-forum/mpi-standard/pull/832)
