### ISSUE TITLE
Add new error class MPI_ERR_ERRHANDLER 

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#525]
# Problem

There exist error classes to report invalid arguments for nearly every MPI handler and MPI type:
`MPI_ERR_COMM`, `MPI_ERR_FILE`, `MPI_ERR_INFO`, `MPI_ERR_OP`, `MPI_ERR_REQUEST`, `MPI_ERR_SESSION`, ... (see MPI 4.0 Tables 9.1 and 9.2, pp. 471-472)
However, there is missing a corresponding error class for MPI_Errhandler, which can be reported, e.g., in case of calling, e.g., `MPI_Comm_create_from_group` with an invalid `MPI_Errhandler` argument.

For reference here a list of functions that take an `MPI_Errhandler` as argument and may use this:
- MPI_Comm_create_from_group
- MPI_Comm_set_errhandler
- MPI_Errhandler_c2f
- MPI_Errhandler_free
- MPI_File_set_errhandler
- MPI_Intercomm_create_from_groups
- MPI_Session_init
- MPI_Session_set_errhandler
- MPI_Win_set_errhandler

Note: This came up during the discussion of https://github.com/mpi-forum/mpi-issues/issues/511 in the 2021-10-20 TelCo.

# Proposal / Changes to the Text

Add a new error class `MPI_ERR_ERRHANDLER`.
see PR in https://github.com/mpi-forum/mpi-standard/pull/633

# Impact on Implementations

Adds the possibility to report in more detail an error caused by an invalid error handler instead of using the generic error code, i.e., `MPI_ERR_ARG`.

# Impact on Users

Makes it easier for the user to identify the origin of a problem caused by a provided invalid error handler.

# References and Pull Requests
https://github.com/mpi-forum/mpi-standard/pull/633

**Comment by wesbland** [comment]
This issue had a "no-no" vote on 2021-12-07, which passed:

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 29
	<td> 0
	<td> 2
</table>

**Comment by wesbland** [comment]
This issue had a "no-no" vote on 2022-03-03, which passed:

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This issue had a 1st vote on 2022-03-03, which passed:

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This issue had a second and final vote on 2022-05-26, which passed:

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 25
	<td> 0
	<td> 4
</table>
