### ISSUE TITLE
Language bindings chapter needs updating for Sessions model

### ISSUE THREAD

**Issue by hppritcha** [mpi-forum/mpi-issues#535]
The subsection of the language bindings chapter concerning initialization - section 19.3.3 of the MPI 4 standard - needs to be updated to cover cases where the Sessions model is used to allocate MPI resources.  Ideally these changes should make it in to the MPI 4.1 standard.

**Comment by wesbland** [comment]
This issue had a first vote on 2022-09-29, which passed:

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 27
	<td> 0
	<td> 2
</table>

**Comment by wesbland** [comment]
This passed a [second vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>
