### ISSUE TITLE
Allow MPI_*_GET_NAME functions to accept MPI_*_NULL handles

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#544]
# Problem

The `MPI_*_SET_NAME` and `MPI_*_GET_NAME` functions were created to aid debugging.  However, similar to most other MPI functions, it is (likely?) invalid to pass the `MPI_*_NULL` handles to the `MPI_*_GET_NAME` functions.  For example:

```c
MPI_Datatype dt = MPI_DATATYPE_NULL;
char name[MPI_MAX_OBJECT_NAME];
int outlen = 0;

// ...
MPI_Type_get_name(dt, name, &outlen);
printf("The datatype is: %s\n", name);
```

If `dt` is still `MPI_DATATYPE_NULL`, Open MPI v4.1.x and MPICH 4.0.0 will both invoke errors.  Indeed, a user reported this behavior as a bug to Open MPI: https://github.com/open-mpi/ompi/issues/10028

Instead, users must add an alternate code path to make the above snipit valid, perhaps something like this:

```c
if (dt == MPI_DATATYPE_NULL) {
    strcpy(name, "MPI_DATATYPE_NULL");
} else {
    MPI_Type_get_name(dt, name, &outlen);
}
printf("The datatype is: %s\n", name);
```

# Proposal

We propose making it permissible to pass in the `MPI_*_NULL` handles to the `MPI_*_GET_NAME` functions.

Note: we do _not_ propose making it permissible to pass in the `MPI_*_NULL` handles to the `MPI_*_SET_NAME` functions.

# Changes to the Text

Add sentences to the `MPI_*_GET_NAMES` definitions.  See [the PDF built from https://github.com/mpi-forum/mpi-standard/pull/652](https://artprodcus3.artifacts.visualstudio.com/A2828b64d-12fe-4a97-80aa-ee05571c42af/e4892c7b-d2a0-47ff-8ddf-bb703647cdc2/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21waWZvcnVtYm90L3Byb2plY3RJZC9lNDg5MmM3Yi1kMmEwLTQ3ZmYtOGRkZi1iYjcwMzY0N2NkYzIvYnVpbGRJZC8yMDE1L2FydGlmYWN0TmFtZS9CdWlsdCtQREY1/content?format=zip), pages:

* 361: MPI_COMM_GET_NAME
* 362: MPI_TYPE_GET_NAME
* 363: MPI_WIN_GET_NAME
* 1001: changelog

# Impact on Implementations

Allow the `MPI_*_NULL` handles in the `MPI_*_GET_NAME` functions.  This will involve relaxing the error checking of these 3 functions, and possibly special-casing the string that is returned in the case of `MPI_*_NULL` inputs.

# Impact on Users

Users no longer need to special-case the use of these functions.

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/652

**Comment by wesbland** [comment]
@jsquyres I'm assuming that you're not going to be doing the reading here?

In the absence of any other owner, I'm going to assign this issue to @GuillaumeMercier since he's the CC chair for the impacted chapter.

**Comment by Wee-Free-Scot** [comment]
Curious: Why is there no equivalent GET|SET_NAME functionality for FILE objects in MPI?

Files have a name in the filesystem; I guess that is seen as sufficient? The MPI_FILE_NULL handle exists. To get the "filename" of an MPI_FILE, we need to use MPI_FILE_GET_INFO so we can look for the "filename" key-value pair. Can MPI_FILE_NULL be passed to MPI_FILE_GET_INFO?

The MPI_FILE object might benefit from a name that is not identical to its "filename" in the filesystem. For example, I might name one MPI_FILE with "input data file" (its role in my program), even though the filesystem name is "data_128x1024_molecule007.bin"

**Comment by wesbland** [comment]
This issue had a "no-no" vote on 2022-05-26, which passed:

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 26
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
@devreal - This passed a no-no reading at the last meeting. Do you want to schedule it for a first vote at the upcoming September 2022 meeting?

**Comment by devreal** [comment]
Ahh, I completely forgot about that one. Thanks for the reminder, I sent out the vote request.

**Comment by wesbland** [comment]
This issue had a first vote on 2022-09-29, which passed:

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 27
	<td> 0
	<td> 2
</table>

**Comment by wesbland** [comment]
This passed a [second vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>
