### ISSUE TITLE
MPI_LASTUSEDCODE not covered in the sessions model

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#545]
# Problem

Users can register their own error classes and codes. The number of error classes including these user created once is made accessible via the attribute `MPI_LASTUSEDCODE` associated with `MPI_COMM_WORLD`.
This information is not accessible in the sessions model.

# References and Pull Requests

MPI-4.0 section 9.5 page 473 lines 42-48

**Comment by wesbland** [comment]
This issue had a errata vote on 2022-09-29, which passed:

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 28
	<td> 0
	<td> 1
</table>
