### ISSUE TITLE
Example 5.19 (datatype chapter) is incorrect

### ISSUE THREAD

**Issue by bosilca** [mpi-forum/mpi-issues#547]
# Problem
In the datatype chapter the example 5.19 claims to show how to handle C-like unions in MPI. 
```c
union {
    int ival;
    float fval; 
} u[1000];

```
However, the example itself is technically incorrect as union can have each element of a different type while the datatype built in the example cannot.

# Proposal

We can fix this issue either by removing the example (does not bring much benefit and it is incorrect in a heterogeneous environment) or by changing the struct to have each element an array by itself as below.
```c
union {
    int ival[1000];
    float fval[1000]; 
} u;

```

# Changes to the Text

Not many changes to the text for any of the two proposed approaches. 

# Impact on Implementations

None.

# Impact on Users

Assuming they are reading the datatype examples, they might get less confused about the "magic" of handling C-like unions.

# References and Pull Requests

None yet.

**Comment by jprotze** [comment]
Is it true that `ival` and `fval` have the same offset of 0?
I thought that the c standard would allow implementations to use different offsets.

**Comment by bosilca** [comment]
Yes, `union`, like `struct`, will inherit the most restrictive alignment.

**Comment by wesbland** [comment]
This wasn't read at the December 2022 meeting. The last opportunity for MPI 4.1 is to have it ready at the March 2022 meeting (and it needs to "pass" the reading).

@bosilca Are you (or is someone else) planning to push this forward or should we move it out of the plan for MPI 4.1?

**Comment by bosilca** [comment]
I am not sure we really need to fix the example. As there is no way to know if each element of the union can be a different type, it is safe to assume that the entire array of unions contains elements of the same type. In this case the example is correct.

**Comment by jeffhammond** [comment]
Shouldn't this be an erratum or CC change?  It corrects a simple error that has no impact on MPI semantics or syntax.

**Comment by bosilca** [comment]
I was planning to merge it in the next few days as a CC change, but wanted to provide an opportunity to comment.

**Comment by wesbland** [comment]
I agree that this is a CC change. If the CC is ok with it, we can give Bill the PR to merge.
