### ISSUE TITLE
Remove obsolete example

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#548]
# Problem

Example 14.1 shows how to query for bits in Fortran 77. Fortran has included a BTEST since Fortran 95 that accomplishes the same operation (in fact, does it better by returning a LOGICAL value).

# Proposal

Remove this example. It should not be necessary to remind users about BTEST.

# Changes to the Text

Simply delete the entire example. There are no references to it.

# Impact on Implementations

None

# Impact on Users

None, other than removing a distracting example from the standard

# References and Pull Requests

**Comment by wesbland** [comment]
Assigning to @tonyskjellum as the CC chair.

**Comment by wesbland** [comment]
This wasn't read at the December 2022 meeting. The last opportunity for MPI 4.1 is to have it ready at the March 2022 meeting (and it needs to "pass" the reading).

@tonyskjellum Are you (or is someone else) planning to push this forward or should we move it out of the plan for MPI 4.1?

**Comment by jeffhammond** [comment]
Can't we just do this as a CC change?  Do we really need to read this to the whole forum?

**Comment by wesbland** [comment]
The lines for what we allow as CC changes have always been fuzzy. Examples are non-normative and therefore *could* be considered CC, but that's usually when all we're doing is fixing one.

I'd want to know what others think about making this a CC change.

**Comment by wgropp** [comment]
I think this is fine as a CC change.  It does not affect the standard at all.

**Comment by bkmgit** [comment]
Can remove this. A related pull request is https://github.com/mpi-forum/mpi-issues/issues/606 maybe easier to remove once that is merged/rejected.
