### ISSUE TITLE
broken link for rfc1832

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#55]
# Problem

The link to XDR in 13.5.2 (`ftp://ds.internic.net/rfc/rfc1832.txt`) is broken.
# Proposal

Change the link to `https://www.ietf.org/rfc/rfc1832.txt` or remove the link in favor of a reference that has more persistence.
# Changes to the Text

TODO
# Impact on Implementations

The following text will be more effective.

> _Advice to implementors._
> The MPI treatment of "NaN" is similar to the approach used in XDR...
# Impact on Users

None.
# References

https://www.ietf.org/rfc/rfc1832.txt

**Comment by jeffhammond** [comment]
I think this is an errata.  Anyone disagree?

**Comment by wgropp** [comment]
No, I agree. This is a simple errata.
Bill

William Gropp
Director, Parallel Computing Institute
Thomas M. Siebel Chair in Computer Science
Chief Scientist, NCSA
University of Illinois Urbana-Champaign

**Comment by schulzm** [comment]
Text submitted as
https://github.com/mpi-forum/mpi-standard/pull/40
scheduled for Austin in June 18

**Comment by schulzm** [comment]
Passed errata vote at Austin 2018 meeting

**Comment by wgropp** [comment]
This fix is merged.  It is not included in the errata document because it doesn't address an important errata that affects users.
