### ISSUE TITLE
Erratum/Ticket 0 change in chapter 7 (`MPI_COMM_CREATE`): wrong font fix

### ISSUE THREAD

**Issue by GuillaumeMercier** [mpi-forum/mpi-issues#550]
# Problem

In the definition of `MPI_COMM_CREATE`, one instance of the word *group* is in true type font whilst it should be in normal
font. This makes the text harder to understand. The text in the definition of  `MPI_COMM_CREATE_GROUP` is correct, though.
I propose to change this for consistency purpose and improve readability altogether.

# Proposal

Change the font.

# Changes to the Text

Replace  `\mpishortarg{group}` with `group`
This change is purley formal and does not impact the semantics if the function.

# Impact on Implementations

None

# Impact on Users

None

# References and Pull Requests

PR: mpi-forum/mpi-standard/pull/660

**Comment by devreal** [comment]
The problem is reversed in the text of `MPI_COMM_CREATE_GROUP`:

> Each process must provide a group argument that is a subgroup of the group associated with comm

Should be
> Each process must provide a `group` argument that is a subgroup of the group associated with comm

**Comment by GuillaumeMercier** [comment]
Good catch @devreal. PR updated  accordingly.
