### ISSUE TITLE
MPI_Win_free is synchronizing, except when it isn't

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#551]
# Problem

The current normative text for `MPI_Win_free` does not state explicitly whether the procedure is synchronizing or not. Instead there is a lengthy description in an AtoI. 

# Proposal

Explicitly state when calls to `MPI_Win_free` can and must be assumed to be synchronizing.

# Changes to the Text

Move the text out of the AtoI into normative text and rephrase it for clarity.

# Impact on Implementations

Implementations will have to verify the synchronizing property of their `MPI_Win_free` implementation. Most likely, no change will be needed though. 

# Impact on Users

Clarity regarding whether `MPI_Win_free` is synchronizing and when they can rely on it.

# References and Pull Requests

PR: https://github.com/mpi-forum/mpi-standard/pull/659

**Comment by devreal** [comment]
@wesbland This issue had a reading in Chattanooga so I added the label for it.

**Comment by wesbland** [comment]
> @wesbland This issue had a reading in Chattanooga so I added the label for it.

Missed this one too... Thanks.

**Comment by wesbland** [comment]
Had a no-no reading on 2022-12-05

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-06.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 28
	<td> 0
	<td> 5
</table>

**Comment by wesbland** [comment]
This passed a [second vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-08.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 27
	<td> 0
	<td> 4
</table>
