### ISSUE TITLE
RMA: Add missing win-sync calls to Example 12.21

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#553]
# Problem

@RolfRabenseifner pointed out that Example 12.21 is missing calls to `MPI_WIN_SYNC` around the second P2P synchronization. They are required to ensure that subsequent updates of X on process A won't happen before the load of X completed on process B. 

# Proposal

Add the missing calls to `MPI_WIN_SYNC` to Example 12.21. Update the advice to users to reflect that `MPI_WIN_SYNC` should be called in between non-RMA synchronization and accesses to shared memory variables. Also add that these calls can be replaced by language-level constructs if available.

# Changes to the Text

See above.

# Impact on Implementations

None. The existing text already requires implementations to issue a full memory barrier.

# Impact on Users

Little. The previous example was incorrect so this change would present a correct example of using non-RMA synchronization with shared-memory variables.

# References and Pull Requests

https://github.com/mpiwg-rma/rma-issues/issues/20

**Comment by wesbland** [comment]
Had a no-no reading on 2022-12-05

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-06.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This passed a [second vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-08.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 27
	<td> 0
	<td> 4
</table>
