### ISSUE TITLE
RMA: both MPI_WIN_ALLOCATE and MPI_WIN_ALLOCATE_SHARED allocate memory

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#554]
# Problem

It was pointed out by @VictorEijkhout that the following text in the RMA chapter is incomplete:

> `MPI_WIN_ALLOCATE` differs from `MPI_WIN_CREATE` in that the user does not pass allocated memory; `MPI_WIN_ALLOCATE` returns a pointer to memory allocated by the MPI implementation.

The same is true for `MPI_WIN_ALLOCATE_SHARED` and should be added accordingly.

# Proposal

Mention both `MPI_WIN_ALLOCATE` and `MPI_WIN_ALLOCATE_SHARED` in the sentence above.

# Changes to the Text

> `MPI_WIN_ALLOCATE` and `MPI_WIN_ALLOCATE_SHARED` differ from `MPI_WIN_CREATE` in that the user does not pass allocated memory; `MPI_WIN_ALLOCATE` and `MPI_WIN_ALLOCATE_SHARED` return a pointer to memory allocated by the MPI implementation.

# Impact on Implementations

None, they are doing the right thing already.

# Impact on Users

Proper enumeration of function characteristics helps readability.

# References and Pull Requests

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This passed a [second vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-08.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 27
	<td> 0
	<td> 4
</table>
