### ISSUE TITLE
No description of MPI_LOCK_EXCLUSIVE lock type in RMA

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#566]
# Problem

The RMA chapter talks about exclusive locks (which aren't what most people think) but never explicitly says that MPI_LOCK_EXCLUSIVE is how an exclusive lock is specified. While it is a natural assumption, the standard should be explicit about these constants

# Proposal

Add a description of both MPI_LOCK_EXCLUSIVE and MPI_LOCK_SHARED, similar to those provided for other such constants.

# Changes to the Text

Something like this would work, after the description of MPI_WIN_LOCK:

The value of \mpiarg{lock\_type} in \mpifunc{MPI\_WIN\_LOCK} may be one of
\begin{constlist}
\constmainitem{MPI\_LOCK\_SHARED}{Lock is shared, which is the same as not exclusive}
\constmainitem{MPI\_LOCK\_EXCLUSIVE}{Lock is exclusive, as described below}
\end{constlist}

# Impact on Implementations

None

# Impact on Users

None

# References and Pull Requests

N/A

**Comment by devreal** [comment]
@wgropp 

The current text below `MPI_WIN_UNLOCK_ALL` describes the lock types:

> Locks are used to protect accesses to the locked target window effected by RMA calls
issued between the lock and unlock calls, and to protect load/store accesses to a locked local
or shared memory window executed between the lock and unlock calls. Accesses that are
protected by an exclusive lock will not be concurrent at the window site with other accesses
to the same window that are lock protected. Accesses that are protected by a shared lock
will not be concurrent at the window site with accesses protected by an exclusive lock to
the same window.

I think this captures everything well, except for mentioning the actual symbols used to acquire the locks. We could move this paragraph to the beginning of Section 12.5.3 to introduce the lock types (with the symbol names) before mentioning them in the LIS. I think it would also serve as a good introduction to the topic, which is missing right now. In the end, this could be an editor change and I'll be happy to prepare that.

**Comment by wgropp** [comment]
I like this idea. This text, with the addition of the (missing!) symbol names, would be sufficient. I also agree that this is an editor change.
