### ISSUE TITLE
What is "target node"?

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#570]
Section 12.3, page 571 (MPI40) refers to "target node".  This probably should be "target process".  The troublesome text is

> to the target node specified by the win, target_rank pair.

**Comment by devreal** [comment]
I believe this will be addressed in https://github.com/mpi-forum/mpi-standard/pull/611.

**Comment by wesbland** [comment]
I'm going to go ahead and close this as a duplicate of #407 then and if someone disagrees, they can reopen it.
