### ISSUE TITLE
Clarification of errhandler fallback with Sessions

### ISSUE THREAD

**Issue by abouteiller** [mpi-forum/mpi-issues#588]
# Problem

Fallback for error handler association when no error handler is available has been found unclear, especially since we have more error handler associations since the addition of the Sessions. We are trying to clarify existing MPI-4.0 behavior, and fix some uncertainty with Session behavior. 

# Changes to the Text

inquiry chapter: add a figure that details error handler associations, and fallback cases
terms chapter: reword the fallback cases to split the two cases: 1) the operation doesn't refer to an error-handler associated object (e.g., comm) 2) the error arise after any procedure related to an operation returned. 

# Impact on Implementations

Implementations need to track session provenance on groups.

# Impact on Users

Users are not confused as to what error handler is invoked in what conditions.

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/644

This Issue is a spinoff from #511

**Comment by abouteiller** [comment]
This is important for MPI 4.1 and will be progressed accordingly

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-08.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 26
	<td> 0
	<td> 5
</table>

**Comment by wesbland** [comment]
I just wanted to call attention to this issue that it didn't get scheduled for anything for the March 2023 meeting. Unfortunately we've passed the deadline for announcements, but this can still be scheduled for a second vote at the next Meeting in May.

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2023/05/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 28
    <td> 0
    <td> 4
</table>

**Comment by abouteiller** [comment]
Received second vote May 2nd https://www.mpi-forum.org/meetings/2023/05/votes

| Yes	| No	| Abstain	| Result |
| --- | --- | --- | --- |
| 28	| 0	| 4	| Passed |
