### ISSUE TITLE
Issues with Partitioned Communication Example-4.4

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#589]
# Problem

The Partitioned Communication Example-4.4 is erroneous and has some issues that should be corrected:

* The variable 'flag' is used incorrectly multiple times resulting in erroneous program behaviour
* The check for partitions with index `j+1 < recv_partitiones` is superfluous, here
* Regrading OpenMP all used variables in an OpenMP block should declare data-sharing attributes (the use of `default(none)` is seen as best practice for OpenMP beginners)
* Misses `stdlib.h` include defining the used `EXIT_FAILURE` macro

# Proposal and Changes to the Code:

See https://github.com/mpi-forum/mpi-standard/pull/726

# Impact on Implementations

None

# Impact on Users

Corrects erroneous example; eases understanding of example; shows OpenMP best practice

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/726

**Comment by cniethammer** [comment]
Attaching 

pdf version: [mpi41-report-issue-589-pr-726.pdf](https://github.com/mpi-forum/mpi-issues/files/10159355/mpi41-report-issue-589-pr-726.pdf)

pdf version with highlighted diffs: [mpi-report-diff-issue-589-pr-726.pdf](https://github.com/mpi-forum/mpi-issues/files/10159356/mpi-report-diff-issue-589-pr-726.pdf)

**Comment by wesbland** [comment]
Had a no-no reading on 2022-12-06

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-06.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This passed an [errata vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by RolfRabenseifner** [comment]
@wgropp and @wesbland Can this be merged? Or what is still to do by Christoph or me?

**Comment by wesbland** [comment]
I left a comment on the pull request yesterday. There are some things that need to be resolved over there, but it can be merged after that.

**Comment by RolfRabenseifner** [comment]
@cniethammer @wesbland Christoph, please can you look on it?
