### ISSUE TITLE
Partitioned Communication - Code examples improperly marked

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#595]
# Problem

Code examples should be marked so that the code checker can confirm that they at least compile - the information on this is in the instructions, and there are a zillion example in the document. The code checker has found many problems and helps ensure a higher quality document. I noted problems in binding-2.tex, but will need to review all of the other examples now.
In that chapter, many examples are marked with `%%SKIP` when they should be properly marked for the language etc.

# Proposal

Follow the instructions in `instr.tex/pdf`. If there are problems or questions, contact @wgropp.

# Changes to the Text

No changes to the text.  The code checker uses structured comments.

# Impact on Implementations

None.

# Impact on Users

Improved quality of the document.

# References

This is covered in instr.pdf.

### Instructions

If there is nothing to do in your chapter, just comment and close this issue. Otherwise, create a PR to address the problems.

**Comment by Wee-Free-Scot** [comment]
There are no occurrences of "verbatim" in this chapter.

All the occurrences of "begin{lst" have `%%ENDHEADER` on the previous line.
$ grep -B1 "begin{lst" chap-part/part.tex

There is nothing to do in this chapter. Change my mind.
