### ISSUE TITLE
MPI_T: Deprecate Error Code MPI_T_ERR_INVALID_ITEM

### ISSUE THREAD

**Issue by kathrynmohror** [mpi-forum/mpi-issues#60]
# Problem

We inadvertently added two error codes for MPI_T that essentially have the same meaning. We want to deprecate MPI_T_ERR_INVALID_ITEM:

page 589 line 13 remove:

MPI_T_ERR_INVALID_ITEM The item index queried is out of range (for MPI_T_ENUM_GET_ITEM only)
# Proposal

Deprecate MPI_T_ERR_INVALID_ITEM
# Changes to the Text

Add deprecation line in Table 2.1, page 18.
Note deprecation in Table 14.5, page 597.
Add to Chapter 15, Section 15.3
# Impact on Implementations

Implementations will need to support MPI_T_ERR_INVALID_ITEM until it is removed from interface.
# Impact on Users

If tools use MPI_T_ERR_INVALID_ITEM they should change to use MPI_T_ERR_INVALID_INDEX
# References

- https://github.com/mpiwg-tools/tools-issues/issues/6

# Pull Request

- https://github.com/mpi-forum/mpi-standard/pull/22

**Comment by kathrynmohror** [comment]
Additional change to text: Chapter 15 title should be Deprecated Interfaces instead of Deprecated Functions

**Comment by kathrynmohror** [comment]
pull request: https://github.com/mpi-forum/mpi-standard/pull/22

**Comment by kathrynmohror** [comment]
Read again at March 2017 meeting since there was confusion in the voting record from Sept 2016 meeting. Issues raised at reading:
- Typo: superseeded -> superseded
- Need change log
- Need to check what goes in the appendix
Group agreed these are no/no vote issues so we can vote on it next time in June.

**Comment by schulzm** [comment]
Passed a no-no-vote on 9/22
Passed first vote on 9/22

**Comment by schulzm** [comment]
Passed 2nd vote on 12/6/17
