### ISSUE TITLE
Topologies - Add Example Titles

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#605]
## Problem

Examples. Some do not have titles, others do (instead, beginning with text).  Do we care? Example 7.1 consists solely of a table.  There should be a short description, at least. Example 11.5 starts with code.  There should be a short description. Example 14,1 starts with code. Example 14.2 starts with code. Example 14.3 starts with code. Example 18.12 starts with code Example 18.13 starts with code Example 18.14 starts with 4 parts; it needs an intro to the parts. Ditto 18.15

### Suggested Fix

Chapter committees to update:

The agreement in the virtual meeting was that **all code samples** that are not simple inline things (anything that uses the `\mpicode{}` macros) should have the example label and a title.

See [PR 746](https://github.com/mpi-forum/mpi-standard/pull/746)

**Comment by RolfRabenseifner** [comment]
PDF File: [mpi41-report_Issue605_PR746.pdf](https://github.com/mpi-forum/mpi-standard/files/10024811/mpi41-report_Issue605_PR746.pdf)

**Comment by wesbland** [comment]
This ticket had a no-no reading on 2022-12-07.

**Comment by RolfRabenseifner** [comment]
**@ chapter committee**:  @GuillaumeMercier @cblaas @htorst @tonyskjellum, @ Mahdieh Ghazimirsaeed, @cniethammer : 
**Please reply** whether you approve this issue (yes/no/abstain).

**Comment by tonyskjellum** [comment]
@RolfRabenseifner I am fine with this---yes.

**Comment by wesbland** [comment]
Guillaume, Christoph, and I have approved the PR.

**Comment by RolfRabenseifner** [comment]
chapter committee vote:
- 5x Yes: Guillaume, Christoph, and Wes, Tony, myself (Rolf)
- 2x no answer: Claudia and Torsten
- 1x vote-request could not be delivered: Mahdieh Ghazimirsaeed

@wesbland I would recommend to take this as a positive chapter committee vote and therefore to merge it.

**Comment by RolfRabenseifner** [comment]
@wgropp Thank you - you are extremely fast :-) / All the best for the new year for you and your family / Kind regards, Rolf
