### ISSUE TITLE
RMA - Fix Example Environment

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#609]
## Problem

The example environment is not used consistently.  See, for example, 6.5.1, `Example #1a` - this should be \begin{example} .... . This continues into 6.5.2, 6.5.3, 6.5.4 (which should *not* be a separate section - `Example #4` is a terrible section title.  6.5.5 ditto. 6.5.6 ditto. 6.6.3 has another `Example 1`, `Example 2`. 10.4.6 (several places). Section 6.7.6 has an attributes example, but 
does not use the example environment. Page 580, section 13.6.11 also has examples without the environment. Page 584, section 13.9.1 ditto. Also 13.9.2. Page 658, after MPI_Type_create_f90_integer, no example environment. Page 662, ditto.

### Suggested Fix

Update to use the example environment in all cases, and to correctly use the \label and \ref commands in the LaTeX source. Update section title for 6.5.4 to "Communication Safety Example"

**Comment by devreal** [comment]
I believe this does not apply to the RMA chapter, closing.
