### ISSUE TITLE
Tools - Index Operation Semantics

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#613]
## Problem

The tools chapter has several occurrences of the word *operation* that not all reference the defined term of an *MPI operation*.

~Index all (relevant) references to semantics of operations.  See, e.g., page 523.~

### Suggested Fix

Reduce the use of 'operations' in the tools chapter for anything but what the terms chapter defines as 'operation'.
(the remaining references of 'operations' were checked and found not in need of indexing)

**Comment by mahermanns** [comment]
Tools WG 2022-10-27:
- [x] p 725: operation of MPI processes -> execution of MPI processes
- [x] p 731: control their operation -> control their execution
- [x] p 740: Table 15.4: local operation -> only affects the local MPI process
- [x] p 742: query operation -> query procedure
- [x] p 754: atomic operation -> If the variable cannot be read and reset atomically, ...
- [x] p 766: This operation has no effect -> Calling this procedure has no effect
- [x] p 768: This operation has no effect -> Calling this procedure has no effect

**Comment by wesbland** [comment]
@mahermanns Was the decision in the end that this is a chapter committee change?

**Comment by mahermanns** [comment]
I assume so after silent consensus. :thinking:
