### ISSUE TITLE
Partitioned Communication - Export "outcome is as if..." code fragments as proper examples

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#617]
# Problem

Some codes are presented in the document as example implementations but not in example format.
It is usually the case for the purpose of presenting what the function output should look like, and is preceded by a sentence such as "The outcome is _as if_ ..."

Also, how such codes are presented are not coherent throughout the whole document.
In collective:  one or two isolated lines of codes
In topology: _functional_ complete pseudo code

# Proposal

Export these fragment of codes as proper examples

# Changes to the Text

Export these fragment of codes as proper examples

# Impact on Implementations

Should be none

# Impact on Users

Should be none

**Comment by Wee-Free-Scot** [comment]
The only occurrence of "as if" is unrelated. This is a non-issue.
