### ISSUE TITLE
Environment - Update verbatim examples to example environment

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#628]
# Problem

The grey box formatting around examples (added in MPI-4.0) raises that many examples use verbatim instead of the example environment, which means the example is not formatted consistently.  This seems like something for the MPI-4.1 cleanup efforts.

# Proposal

Review example listings without a grey box and update to use correct `\begin{example}...\end{example}` formatting.

# Changes to the Text

Update LaTeX throughout the document, e.g., Section 7.6.3 Example 1: "Three-Group Pipeline".

# Impact on Implementations

None.

# Impact on Users

None.

**Comment by raffenet** [comment]
I created https://github.com/mpi-forum/mpi-standard/pull/766. IMO, it is at the level of a chapter committee change. There are 2 other grey boxes at the beginning of the chapter, but those are illustrating what an implementation might do. I did not modify them to use the example environment.

**Comment by wesbland** [comment]
I agree that this is a chapter committee change.
