### ISSUE TITLE
External Interfaces - Update verbatim examples to example environment

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#631]
# Problem

The grey box formatting around examples (added in MPI-4.0) raises that many examples use verbatim instead of the example environment, which means the example is not formatted consistently.  This seems like something for the MPI-4.1 cleanup efforts.

# Proposal

Review example listings without a grey box and update to use correct `\begin{example}...\end{example}` formatting.

# Changes to the Text

Update LaTeX throughout the document, e.g., Section 7.6.3 Example 1: "Three-Group Pipeline".

# Impact on Implementations

None.

# Impact on Users

None.

**Comment by schulzm** [comment]
This is already complete
