### ISSUE TITLE
Bindings - Update verbatim examples to example environment

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#633]
# Problem

The grey box formatting around examples (added in MPI-4.0) raises that many examples use verbatim instead of the example environment, which means the example is not formatted consistently.  This seems like something for the MPI-4.1 cleanup efforts.

# Proposal

Review example listings without a grey box and update to use correct `\begin{example}...\end{example}` formatting.

# Changes to the Text

Update LaTeX throughout the document, e.g., Section 7.6.3 Example 1: "Three-Group Pipeline".

# Impact on Implementations

None.

# Impact on Users

None.

**Comment by wesbland** [comment]
This wasn't read at the December 2022 meeting. The last opportunity for MPI 4.1 is to have it ready at the March 2022 meeting (and it needs to "pass" the reading).

@puribangalore Are you (or is someone else) planning to push this forward or should we move it out of the plan for MPI 4.1?

**Comment by RolfRabenseifner** [comment]
See yellow marker and PR805 marker on  pages 776, 779-780, 783, 785-787, 794-795, 809, 812-813, 1035, 1039-1040, and 1047 in
[mpi41-report_Issue235+607+244+610+633_PR805-v03.pdf](https://github.com/mpi-forum/mpi-standard/files/10832007/mpi41-report_Issue235%2B607%2B244%2B610%2B633_PR805-v03.pdf)
