### ISSUE TITLE
Fix MPI_WIN_SYNC text

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#634]
# Problem

This text is horrible:

> The call MPI_WIN_SYNC synchronizes the private and public window copies of win. For the purposes of synchronizing the private and public window, MPI_WIN_SYNC has the effect of ending and reopening an access and exposure epoch on the window (note that it does not actually end an epoch or complete any pending MPI RMA operations).

# Proposal

Make it clear what WIN_SYNC actually does.

# Changes to the Text

Say it's a memory barrier for unified, something else for separate.

# Impact on Implementations

Nothing.

# Impact on Users

Users can reason about RMA correctness in a useful way.

# References and Pull Requests

TODO

**Comment by wesbland** [comment]
Had no-no reading on 2022-12-06

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-06.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This passed an [errata vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>
