### ISSUE TITLE
deprecate (with the intent to fix) MPI_Buffer_{attach,detact}

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#643]
# Problem

MPI_Bsend has been determined to be useful (https://github.com/mpi-forum/mpi-issues/issues/282) although we also agree that the global scope of the buffer makes it impossible to use this in libraries, because a library has no idea if the buffers are used by other parts of the application.

We need a properly scoped buffer attach mechanism, and communicators are the appropriate scope for this.

We should fix this and deprecate the old mechanism.  The fix may not be backwards compatible, because it will now be ambiguous which buffer is intended to be used.  We could fix this by adding a new Bsend function, but that just seems stupid.

We have to deprecate `MPI_Buffer_{attach,detach}` in MPI 4.1 in order to implement the breaking change.

# Proposal

1. deprecate `MPI_Buffer_{attach,detach}` in MPI 4.1
2. delete `MPI_Buffer_{attach,detach}` in MPI 5.0
3. add `MPI_Comm_buffer_{attach,detach}` in MPI 5.0

# Changes to the Text

# Impact on Implementations

This is trivial to implement.

# Impact on Users

Users of `MPI_Bsend` will need to change their code starting in MPI-5.

# References and Pull Requests

https://github.com/mpi-forum/mpi-issues/issues/282

**Comment by RolfRabenseifner** [comment]
Due to the many applications in the world model, the deprecation should be only for the session model. But I would allow also the comm attach for the world model and then it takes precidence on the globally defined buffer for the world model.

----- Original Message -----
> From: "github notifications" ***@***.***>
> To: "mpi-forum" ***@***.***>
> Cc: "Subscribed" ***@***.***>
> Sent: Friday, November 18, 2022 9:57:24 AM
> Subject: [mpi-forum/mpi-issues] fix buffered send (Issue #643)

> # Problem
> 
> MPI_Bsend has been determined to be useful
> (https://github.com/mpi-forum/mpi-issues/issues/282) although we also agree
> that the global scope of the buffer makes it impossible to use this in
> libraries, because a library has no idea if the buffers are used by other parts
> of the application.
> 
> We need a properly scoped buffer attach mechanism, and communicators are the
> appropriate scope for this.
> 
> We should fix this and deprecate the old mechanism.  The fix may not be
> backwards compatible, because it will now be ambiguous which buffer is intended
> to be used.  We could fix this by adding a new Bsend function, but that just
> seems stupid.
> 
> We have to deprecate `MPI_Buffer_{attach,detach}` in MPI 4.1 in order to
> implement the breaking change.
> 
> # Proposal
> 
> 1. deprecate `MPI_Buffer_{attach,detach}` in MPI 4.1
> 2. delette `MPI_Buffer_{attach,detach}` in MPI 5.0
> 3. add `MPI_Comm_buffer_{attach,detach}` in MPI 5.0
> 
> # Changes to the Text
> 
> 
> 
> # Impact on Implementations
> 
> This is trivial to implement.
> 
> # Impact on Users
> 
> Users of `MPI_Bsend` will need to change their code starting in MPI-5.
> 
> # References and Pull Requests
> 
> https://github.com/mpi-forum/mpi-issues/issues/282
> 
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/mpi-forum/mpi-issues/issues/643
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

-- 
Dr. Rolf Rabenseifner . . . . . . . . . .. . . ***@***.*** .
High Performance Computing Center (HLRS) . . . ++49(0)711/685-65530 .
University of Stuttgart . . . . . . www.hlrs.de/people/rabenseifner .
Nobelstr. 19, 70569 Stuttgart, Germany

**Comment by jeffhammond** [comment]
I looked on GitHub and saw no usage. Please share projects you know that use this.

**Comment by jeffhammond** [comment]
I agree we can fix this by saying something like "BSEND uses the buffer attached to the communicator if it exists, and falls back on the global buffer otherwise."

This preserves backwards compatibility while allowing proper library usage. The cost is low, a lookup and a branch, I guess. Cheaper than comm_get_ate for sure.

**Comment by RolfRabenseifner** [comment]
There is already an issue https://github.com/mpi-forum/mpi-issues/issues/586 .
The discussion should take place there and probabliy this issue should be closed.
