### ISSUE TITLE
API to access and update MPI_Status public fields

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#645]
# Problem

`MPI_Status` is the only non-opaque handle and users are expected to access and update the three public fields directly.

This is not good for users of languages that are not C/C++ or Fortran.  Currently, users are working around this by writing their own get/set functions (e.g. mpi4py's [pympistatus.h](https://github.com/mpi4py/mpi4py/blob/master/src/pympistatus.h)) or linking `libclang` to parse header files and generate these functions (e.g. `rsmpi`).

# Proposal

Add `MPI_Status_{get,set}_{source,tag,error}` functions that allow non-first-party languages to support the field access.

I don't know if the `set` routines make sense, but we have them for `elements` and `cancelled`, which are the "hidden" status fields.

# Changes to the Text

Add the following in LIS way and define them in the obvious way.
```c
int MPI_Status_get_source(MPI_Status * status, int * source);
int MPI_Status_set_source(MPI_Status * status, int source);
int MPI_Status_get_tag(MPI_Status * status, int * tag);
int MPI_Status_set_tag(MPI_Status * status, int tag);
int MPI_Status_get_error(MPI_Status * status, int * error);
int MPI_Status_set_error(MPI_Status * status, int error);
```

# Impact on Implementations

These are trivial to implement.

# Impact on Users

Users of C/C++ and Fortran are not required to use these.

Implementers of MPI support for Python, Julia, Rust, etc. will find it easier to use MPI.

# References and Pull Requests

**Comment by simonbyrne** [comment]
This would be very helpful for those of us maintaining 3rd-party language bindings, and it makes it consistent with other accessors like `MPI_Get_count`.

**Comment by Wee-Free-Scot** [comment]
Latest PDF, see section 13.3 page 608-610:

[mpi41-report_Issue645_API_access_for_status_public_fields.pdf](https://github.com/mpi-forum/mpi-issues/files/10187569/mpi41-report_Issue645_API_access_for_status_public_fields.pdf)

**Comment by Wee-Free-Scot** [comment]
Should these new procedures be referenced within the text of section 3.2.5?
That is the first (lexically) mention of status and of how obtain the values of the fields.

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-01.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 31
	<td> 0
	<td> 0
</table>

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2023/02/votes) on 2023-02-08.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 27
	<td> 0
	<td> 4
</table>

**Comment by wesbland** [comment]
I just wanted to call attention to this issue that it didn't get scheduled for anything for the March 2023 meeting. Unfortunately we've passed the deadline for announcements, but this can still be scheduled for a second vote at the next Meeting in May.

**Comment by jeffhammond** [comment]
I'll add here that I _think_ these are required to support generalized requests in an ABI compatibility layer like Mukautuva. The GR callback takes a status object and I'm not sure when I can translate it, although I haven't tried yet.

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2023/05/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 28
    <td> 0
    <td> 4
</table>

**Comment by dalcinl** [comment]
Folks, given that these functions are really trivial and intended as a replacement for direct attribute access, IMHO users should be allowed to call them outside of the MPI_INIT/MPI_FINALIZE bracket, just as direct attributes access work. Is this a reasonable request and expectation? If yes, should this be clarified in the standard? Moreover, should these functions be added to Table 11.1?

**Comment by jeffhammond** [comment]
What is the use case for that? Status cannot mean anything before init. What action would require the contents of status after finalize?

I agree this is implementable but it seems pointless.

**Comment by dalcinl** [comment]
> What is the use case for that? 

Initializing status objects, for example in constructors within OOP languages. Moreover, checking for MPI init/fini will actually introduce runtime overhead to these routines.

**Comment by jeffhammond** [comment]
Error checking is not required but I think you make good points anyways and I suppose the proposal. It needs a new issue though.

**Comment by dalcinl** [comment]
As a very specific example, in mpi4py you can create any MPI object before `MPI_Init`. Handles are initialized to MPI_XXX_NULL, and status is initialized with (ANY_SOURCE, ANY_TAG, MPI_SUCCESS), which elsewhere in the standard is referred as an "empty status".
