### ISSUE TITLE
MPI_CANCEL and completion

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#656]
# Problem

Section 3.8 (`MPI_CANCEL`) contains this sentence at the end of the description of `MPI_CANCEL`:

> If the operation has been *cancelled*, then information to that effect will be returned in the status argument of the operation that *completes* the communication.

I have tried to understand this sentence but questions remain:

- Which **operation** (second use) does this sentence refer to? And how does it complete a communication?
- Which communication is **completed**? 
- What **communication** is meant here after all? (no communication without matching send and receive). 

This sentence seems to have been overlooked during the adaptation to the semantic terms. My assumption is that the sentence should be:

> If the operation has been cancelled, then information to that effect will be returned int he status argument of the **procedure** that completes the **operation**.

Is that correct? Is cancellation a form of completion, after all? The rest of standard seems to be silent about it (e.g., the semantic terms state diagrams don't mention cancellation at all and only deal with completion). 

# Proposal

Adapt this sentence to the 4.0 semantic terms. The sentence is either wrong or (at least) badly written (by today's standards).

# Changes to the Text

Proposal above, needs eyes from the P2P WG.

# Impact on Implementations

None, should not involve functional changes.

# Impact on Users

Improved readability of `MPI_CANCEL`.

# References and Pull Requests

Cancellation is handled as a special case (instead of completion) in https://github.com/mpi-forum/mpi-standard/pull/752, which spurred a discussion about this sentence.

**Comment by Wee-Free-Scot** [comment]
My understanding has always revolved around the difference between completing an MPI operation and completing an MPI communication. In the success case, these coincide, but it other cases they do not.

```
MPI_Cancel marks for cancellation a pending, nonblocking communication operation
```
Calling `MPI_Cancel` does not (guarantee to) cancel an operation -- the operation may not be cancelled when the call returns, or ever. The communication may happen or may be cancelled.

The operation is completed (even if the communication is cancelled) by calling a completion procedure for the request that represents that operation.

The `MPI_Status` obtained when completing the MPI operation, will say whether the communication happened or was cancelled. That information about the communication is not known (to the user) until the the operation is completed.

"The MPI operation completed ..." does not imply "... successfully" -- it might complete with an error or with a cancellation.

**Comment by Wee-Free-Scot** [comment]
Closing as won't-fix because existing text is technically correct.
