### ISSUE TITLE
MPI_MAX_STRINGTAG_LEN and MPI_MAX_PSET_NAME_LEN aren't listed as compile-time constants

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#658]
# Problem

MPI_MAX_STRINGTAG_LEN and MPI_MAX_PSET_NAME_LEN should probably be in the list of "The constants that are required to be compile-time constants" in Section 2.5.4.

# Proposal

# Changes to the Text

# Impact on Implementations

# Impact on Users

# References and Pull Requests

**Comment by schulzm** [comment]
This seems like a clear oversight and like an errata item to me.

**Comment by wgropp** [comment]
Agreed.

**Comment by wesbland** [comment]
Had errata reading on 2023-05-02.

**Comment by wesbland** [comment]
This passed a [errata vote](https://mpi-forum.org/meetings/2023/05/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 30
    <td> 0
    <td> 2
</table>
