### ISSUE TITLE
Question about MPI_VAL in example

### ISSUE THREAD

**Issue by VictorEijkhout** [mpi-forum/mpi-issues#661]
Now that we're on the topic of non-normative code anyway....

Example 6.21 has the line
```
if (type%MPI_VAL == MPI_REAL%MPI_VAL) then
```

Section 2.5.1 explains this single member of the various Fortran2008 types that used to be opaque INTEGERs. It also states that (among others) the `==` operator is overloaded for types.

Therefore should that line in the example read
```
if (type == MPI_REAL) then
```
and we should not bother the reader with what is really an (albeit standardized) implementation detail?

**Comment by jeffhammond** [comment]
This example should be fixed. We should not shown users the wrong way to do things. I suspect this happened because a C programmer wrote the example 😏

**Comment by jeffhammond** [comment]
@RolfRabenseifner do you agree on the fix? If so, I'll create a PR next week.

**Comment by RolfRabenseifner** [comment]
I agree. Good catch!

**Comment by jeffhammond** [comment]
@VictorEijkhout I created the pull request to fix this already, although you can't see it unless you are in the MPI GH org.  If you're not, we can fix that.

**Comment by VictorEijkhout** [comment]
> MPI GH org

“GH”?

I see your pull request 785.

V.

**Comment by jeffhammond** [comment]
GH=GitHub
