### ISSUE TITLE
Consistency: MPI Standard vs MPI standard

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#668]
# Problem

The standard is not consistent in the capitalization of S in `MPI Standard`.

Examples in Chapter 9
- MPI Standard: https://github.com/mpi-forum/mpi-standard/blob/mpi-4.x/chap-inquiry/inquiry.tex#L17
- MPI standard: https://github.com/mpi-forum/mpi-standard/blob/mpi-4.x/chap-inquiry/inquiry.tex#L56

# Proposal

Decide on a common style and be consistent (probably an editor change)

# Changes to the Text

See above

# Impact on Implementations

None

# Impact on Users

None

# References and Pull Requests

None

**Comment by wgropp** [comment]
The vast majority of uses are "MPI standard". I propose that form.
