### ISSUE TITLE
MPI_T: Consistent reference to MPI processes

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#67]
# Problem

Throughout the tools chapter, different wordings are used when describing MPI processes.

# Proposal

We change references where the MPI processes of one 'job' are meant to the term _connected MPI processes_.

# Changes to the Text

mpi-forum/mpi-standard/pull/30

# Impact on Implementations

None.

# Impact on Users

None.

# References

mpiwg-tools/tools-issues/issues/10

**Comment by mahermanns** [comment]
### Chicago meeting notes

* Forum was generally OK with the text
* Changes to the table remove normative text not otherwise present in the document. Specifically MPI_T_SCOPE_CONSTANT, MPI_T_SCOPE_READONLY, and MPI_T_SCOPE_LOCAL.
* Table should be restored and fixed in respect to process references

**Comment by wesbland** [comment]
@mahermanns - Would it be possible to itemize the "no no" changes that will be voted on? If it's just a few of the commits, you can link to that diff.

**Comment by mahermanns** [comment]
It's the newest commit: https://github.com/mpi-forum/mpi-standard/pull/30/commits/f116e2122c33dc8653a61c12a07320c5a2865bde

**Comment by schulzm** [comment]
Passed no-no vote for final changes during Austin Forum Meeting in June 2018

**Comment by schulzm** [comment]
Passed first vote during Austin Forum Meeting in June 2018

**Comment by schulzm** [comment]
Passed second vote at Barcelona meeting in Sep. 2018, ready to be merged into golden copy

**Comment by schulzm** [comment]
Vote tally: 16 yes, 0 abstain, 0 no - full results at https://www.mpi-forum.org/meetings/2018/09/votes

**Comment by wgropp** [comment]
PR 30 merged.
