### ISSUE TITLE
Error code from some Fortran procedures are referred to as return code

### ISSUE THREAD

**Issue by abouteiller** [mpi-forum/mpi-issues#671]
# Problem

@mahermanns identified while working on error/return codes for MPIT procedures (https://github.com/mpi-forum/mpi-issues/issues/542) that some Fortran procedure have the converse problem of referring to the error code returned in `ierror` as the `return code`. This should be made uniform using error code in all cases. 

# Proposal

Review the text and remove all references to 'return codes' in Fortran procedure descriptions to use 'error code' appropriately.

# Changes to the Text

https://github.com/mpi-forum/mpi-standard/pull/814

# Impact on Implementations

None

# Impact on Users

Clarification of text

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/814

**Comment by abouteiller** [comment]
Forum to decide if this is chapter-commitee level change.

**Comment by wesbland** [comment]
Read on 2023-05-02 and agreed that this would be a chapter committee change going forward.

**Comment by abouteiller** [comment]
Forum confirmed to go ahead with chapter committee procedure; minor changes discussed during plenary have been implemented.

**Comment by abouteiller** [comment]
@wesbland I changed the status for the 4.1 milestone tracker to 'passed 2nd vote' although this does not require a vote, it is ready for editors review and merger. Please undo if that is not appropriate for that type of tickets.
