### ISSUE TITLE
'Pending operation' not defined, pending proper definition

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#676]
# Problem

The text uses the term "pending operation" in some places to refer to an "active operation" (as in: it's completion is pending). Nowhere is it defined in what state a pending operation is supposed to be so in some contexts this can be confusing. With semantic terms, the proper term to use differ, for example "active" und "decoupled MPI activities", or soemthing else.

Examples: 

§11.10.4
> `MPI_COMM_DISCONNECT` has the same action as `MPI_COMM_FREE`, except that it waits for *pending communication* to finish internally and enables the guarantee about the behavior of disconnected processes.

would be

> `MPI_COMM_DISCONNECT` has the same action as `MPI_COMM_FREE`, except that it waits for *decoupled MPI activities* to finish internally and enables the guarantee about the behavior of disconnected processes.

(see also https://github.com/mpi-forum/mpi-issues/issues/536)
(may be resolved in https://github.com/mpi-forum/mpi-issues/issues/710)

§6.12:
>That is, an MPI implementation should be able to support a large number of *pending* nonblocking operations.

would be

> That is, an MPI implementation should be able to support a large number of *active* nonblocking operations.

§7.1.2
> This allows the invocation of the library even if there are *pending* communications on “other” communicators, and avoids the need to synchronize entry or exit into library code. *Pending* point-to-point communications are also guaranteed not to interfere with collective communications within a single communicator.

would be

> This allows the invocation of the library even if there are *active* communications on “other” communicators, and avoids the need to synchronize entry or exit into library code. *Active* point-to-point communications are also guaranteed not to interfere with collective communications within a single communicator.

§7.4.3
> Any *pending* operations that use this communicator will complete normally

would be

> Any *active* operations that use this communicator will complete normally

(resolved in https://github.com/mpi-forum/mpi-issues/issues/543)

§...
There are many more locations using 'pending'

# Proposal

See also solution in issue https://github.com/mpi-forum/mpi-issues/issues/543

One must be careful, because *active* may be wrong (as in https://github.com/mpi-forum/mpi-issues/issues/543).

# Changes to the Text

See above. This should be part of the "cleanup" for MPI 4.1.

Alternatively, the term "pending" could be properly in the terms section.
(Risky, because its meaning may be different in different contexts)

# Impact on Implementations

None (unless there it renders some implementations non-compliant due to confusion stemming from the usage of the term "pending") 

# Impact on Users

Clear use of terms helps users better understand the text without having to reason about what a "pending operation" is.

# References and Pull Requests

**Comment by wesbland** [comment]
I'm moving this to MPI 5.0. If you think we can make this edit as a CC change, we can bring it back in.

**Comment by RolfRabenseifner** [comment]
The changes of [PR 824](https://github.com/mpi-forum/mpi-standard/pull/824) are marked with PR824 and also in yellow color on pages 56, 62, 76, 81, 83, 92, 240, 294-296, 310, 497, 626, 688, 804, 810, 1023, 1051, 1052, 1055 in
[mpi41-report_Issue676_PR824.pdf](https://github.com/mpi-forum/mpi-standard/files/11443976/mpi41-report_Issue676_PR824.pdf)

**Comment by RolfRabenseifner** [comment]
The changes of [PR 824](https://github.com/mpi-forum/mpi-standard/pull/824) are marked with PR824 and also in yellow color on pages 56, 62, 76, 81, 83, 92, 240, 294-296, 310, 497, 626, 688, 804, 810, 1023, 1051, 1052, 1055 in
[mpi41-report_Issue676_PR824.pdf](https://github.com/mpi-forum/mpi-standard/files/11668075/mpi41-report_Issue676_PR824.pdf)

There is a counter proposal in [PR 825](https://github.com/mpi-forum/mpi-standard/pull/825) (see my next comment below).

**Comment by RolfRabenseifner** [comment]
[PR 825](https://github.com/mpi-forum/mpi-standard/pull/825) is a counter proposal to [PR 824](https://github.com/mpi-forum/mpi-standard/pull/824) (for its pdf, see my comment above).

The changes of [PR 825](https://github.com/mpi-forum/mpi-standard/pull/825) are marked with PR825 and also in yellow color on pages **12**, 17, 56, 62, 63, 76, 81, 83, 92, 240, 294-296, 310, 497, 626, 688, 804, 810, 1023, 1051, 1052, 1055 in
[mpi41-report_Issue676_PR825.pdf](https://github.com/mpi-forum/mpi-standard/files/11669354/mpi41-report_Issue676_PR825.pdf)

I clearly prefer PR825 because it defines **pending (communication) operations**. This term exists since MPI-1 and may be used in many software documentations, research papers, book, etc. Therefore, defining **pending (communication) operations** as "an operation in active state" is better than substituting "pending" by "active".

**Comment by RolfRabenseifner** [comment]
The results of the  virtual MPI forum meeting, June 7, 2023 are

- Withdrawing the [PR 824](https://github.com/mpi-forum/mpi-standard/pull/824), which tried to substitute all "pending operation" by "active operation".

- This version v3 of [PR 825](https://github.com/mpi-forum/mpi-standard/pull/825) includes all proposed changes at the virtual MPI forum meeting, June 7, 2023.

  The changes of [PR 825](https://github.com/mpi-forum/mpi-standard/pull/825) are marked with PR825 and also in yellow color on pages 12, 17, 56, 62, 63, 76, 81, 83, 92, 240, 294-296, 310, 497, 626, 688, 803, 804, 810, 1023, 1051, 1052, 1055 in
[mpi41-report_Issue676_PR825_v3.pdf](https://github.com/mpi-forum/mpi-standard/files/11732752/mpi41-report_Issue676_PR825_v3.pdf)

**Comment by RolfRabenseifner** [comment]
This version v4 includes all proposed changes at the virtual MPI forum meeting, June 7, 2023 together with changes from the review process of this [PR 825](https://github.com/mpi-forum/mpi-standard/pull/825).
The changes are marked with PR825 and also in yellow color on pages 12, 17, 56, 62, 63, 76, 81, 83, 92, 240, 294-296, 310, 497, 626, 688, 803, 804, 810, 1023, 1051, 1052, 1055 in
[mpi41-report_Issue676_PR825_v4.pdf](https://github.com/mpi-forum/mpi-standard/files/11760940/mpi41-report_Issue676_PR825_v4.pdf)

**Comment by RolfRabenseifner** [comment]
PDF files
- from reading, July 10, 2023: [mpi41-report_Issue676_PR825_v6_from-reading.pdf](https://github.com/mpi-forum/mpi-standard/files/12015237/mpi41-report_Issue676_PR825_v6_from-reading.pdf)
- final grammer/type changes from reading / for voting: [mpi41-report_Issue676_PR825_v7_for-voting.pdf](https://github.com/mpi-forum/mpi-standard/files/12015254/mpi41-report_Issue676_PR825_v7_for-voting.pdf)

**Comment by wesbland** [comment]
This passed a [errata vote](https://mpi-forum.org/meetings/2023/07/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 32
    <td> 0
    <td> 2
</table>
