### ISSUE TITLE
are scalar arguments "buffers" in nonblocking collectives?

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#678]
# Problem

The nonblocking collective text (§6.12) says that buffers and _array_ arguments can't be modified or freed until the operation has completed.

Can _scalar_ datatype arguments be freed before nonblocking collectives complete, in the same way that they can in the context of point-to-point (§5.1.9)?

## §6.12

> As in the nonblocking point-to-point case, all calls are local and return immediately, irrespective of the status of other processes. The call initiates the operation, which indicates that the system may start to copy data out of the send buffer and into the receive buffer. Once initiated, all associated send buffers and buffers associated with input arguments (such as arrays of counts, displacements, or datatypes in the vector versions of the collectives) should not be modified, and all associated receive buffers should not be accessed, until the collective operation completes. The call returns a request handle, which must be passed to a completion call.

## §5.1.9

> Marks the datatype object associated with datatype for deallocation and sets datatype to MPI_DATATYPE_NULL. Any communication that is currently using this datatype will complete normally. 

## Example

```c
void fn(.., MPI_Datatype * dt)
{
  // How can we dereference dt if the type to which it points
  // is set to MPI_DATATYPE_NULL when MPI_Type_free is called?
  int nl;
  char name[MPI_MAX_OBJECT_NAME] = {0};
  MPI_Type_get_name(*dt,name,&nl);
  ...
}

...
MPI_Type_contiguous(..,&dt);
MPI_Type_commit(&dt);
MPI_Type_set_name(dt,"NAME");
MPI_Op_create(fn,1,&op);
MPI_Iallreduce(..,&dt,&op,..,&r)
MPI_Type_free(&dt);
MPI_Wait(&r);
MPI_Op_free(&op);
```

# Proposal

## Option 1

§5.1.9 is almost certainly wrong in the context of nonblocking reductions with user-defined reduction operations.  This needs to be fixed.

Assuming §5.1.9 is fixed, it would be slightly more clear that the user cannot free the scalar datatype arguments to nonblocking collectives, but we should still say so explicitly.

## Option 2

The alternative is to say that §5.1.9 is actually correct, which implies that the datatype pointer argument of `MPI_User_function` points to a duplicate handle of the user-defined type, not the original handle.

# Changes to the Text

# Impact on Implementations

Option 1 requires no implementation change.  Option 2 requires straightforward but unappealing changes.

# Impact on Users

The standard is currently logically inconsistent, although the use case that might be broken is uncommon.

# References and Pull Requests

**Comment by bosilca** [comment]
1. You need to commit the datatype before using it in any communications.a
2. Calling the datatype argument a `scalar` seems like a language extravaganza.
3. The text is 5.1.9 is correct, the **user** is losing the reference to the datatype, which means it cannot use it directly, but the **MPI library** will maintain one as long as necessary as clearly indicated by `Any communication that is currently using this datatype will complete normally.` This means the MPI library will retain and use a copy of the datatype until all usages of the datatype are consumed by having their corresponding operations completed. In your example, the contiguous datatype will exist in the MPI library until the `MPI_Wait` is called on the non-blocking reduction request.

OMPI implements this by a completion callback, [ompi_coll_base_retain_datatypes / release_vecs_callback](https://github.com/open-mpi/ompi/blob/0a180c1fb09698269421f8d80e8200c3c88cc891/ompi/mca/coll/base/coll_base_util.c), triggered on request completion.

**Comment by jeffhammond** [comment]
1. I fixed the code above, which was written directly into GitHub, and isn't something I have been running.
2. It's a scalar in the sense that there is one of them.  I don't understand your problem here.
3. Is calling `fn` to do the `iallreduce` not part of communication?  Is the implementation retaining a valid datatype handle to provide to `fn` or not?

**Comment by jprotze** [comment]
A handle is a reference to an implementation object. As long as the implementation maintains the object (as required by 5.1.9), it can hand out a reference to the object. Freeing the data type invalidates the application reference received from the construction call.

Since the communication is not complete until the reduction is done, the implementation can pass a reference to the user-defined reduction function.

I don't see an issue here.

**Comment by jeffhammond** [comment]
What does `MPI_Datatype * dt` point to when `fn` is called?

It is critically important to notice here that this is a pointer to a handle, not a handle.  If it was just a handle, pass-by-value semantics would preserve the value from the `iallreduce` call site and presumably it would still work.  That is *not* the case with a pointer.

**Comment by devreal** [comment]
@jeffhammond IIRC, all arguments to reduction functions are passed as pointers because Fortran (to be able to use the same function in a Fortran and C context)

**Comment by jeffhammond** [comment]
Sure, but in C, what happens when I dereference `dt` in `fn`?  Is that the same `dt` as was passed to `iallreduce` or is it a duplicate?

**Comment by devreal** [comment]
It will be the same handle as you passed to `iallreduce`, referencing the same datatype object. Once you free the datatype after the call to `iallreduce` you lost that handle in the main code, but the object is alive and well and the handle passed to `fn` will reference it.

**Comment by bosilca** [comment]
As long as it has all the properties and capabilities of your original **datatype**, including the attributes, why does it matters if *\*dt* points to the original or to a duplicate ? That is a quality of implementation issue, from the user perspective it should be irrelevant.

**Comment by jeffhammond** [comment]
@bosilca so you are saying that the MPI standard requires option 2 already and that I am the only person on earth who doesn't find that obvious?

**Comment by bosilca** [comment]
My understanding is that MPI currently requires the option 2, and seeing the discussion here it is shared by others. But it is good to raise issues and signal parts of the standard that could be misunderstood.

**Comment by jprotze** [comment]
Similarly, you could ask whether MPI_Type_get_content returns the same handles as used to create the type or duplicates. 

This function has interesting text:
> The datatypes returned in array_of_datatypes are handles to datatype objects that
are equivalent to the datatypes used in the original construction call. If these were derived
datatypes, then the returned datatypes are new datatype objects, and the user is responsible
for freeing these datatypes with MPI_TYPE_FREE. If these were predefined datatypes, then
the returned datatype is equal to that (constant) predefined datatype and cannot be freed.

Similar text might be added to clarify the argument passed to the reduction function.

**Comment by jeffhammond** [comment]
I will close this issue because I have better things to do than text edits to address my own confusion.

I verified empirically that both MPICH and Open-MPI understand the need to create a new datatype handle to pass to the user function.

```
~/HPCInfo/mpi/userdef-ireduce$ export IMPL=openmpi ; mpicc.${IMPL} -DBEFORE userdef_ireduce.c -o userdef_ireduce.x && mpirun.${IMPL} -n 4 ./userdef_ireduce.x
main: &dt=0x7ffe09da0be8
main: &dt=0x7ffe71e09998
main: &dt=0x7ffea4afc678
main: &dt=0x7ffc1e4f7808
fn: dt=0x7ffe09da08b8
fn: dt=0x7ffea4afc348
fn: dt=0x7ffea4afc348
```

```
~/HPCInfo/mpi/userdef-ireduce$ export IMPL=mpich ; mpicc.${IMPL} -DBEFORE userdef_ireduce.c -o userdef_ireduce.x && mpirun.${IMPL} -n 4 ./userdef_ireduce.x
main: &dt=0x7ffc9fac95e0
main: &dt=0x7ffe90cfa270
main: &dt=0x7ffdda07ffe0
main: &dt=0x7fff7891ad40
fn: dt=0x7ffc9fac92d0
fn: dt=0x7ffe90cf9f60
fn: dt=0x7ffdda07fcd0
fn: dt=0x7fff7891aa30
fn: dt=0x7ffc9fac92d0
fn: dt=0x7ffe90cf9f60
fn: dt=0x7ffdda07fcd0
fn: dt=0x7fff7891aa30
```

**Comment by jprotze** [comment]
You seem to print the memory location of the handle rather than the handle. In MPICH the handles are int rather than pointers as in OpenMPI.
Since you pass the handle by value to mpi_ireduce, how should the implementation know the memory location of your handle?
I would actually be surprised if you really get a different handle from either implementation, ie., printing dt in main and *dt in fn.

**Comment by jeffhammond** [comment]
Well, I was wondering if the `*dt` in `fn` was a pointer to the original handle, but it clearly isn't, but I ran it again with an [updated version](https://github.com/jeffhammond/HPCInfo/blob/master/mpi/userdef-ireduce/userdef_ireduce.c) to confirm that you are correct that the value of the handle is the same.
```
$ export IMPL=mpich ; mpicc.${IMPL} -DBEFORE userdef_ireduce.c -o userdef_ireduce.x && mpirun.${IMPL} -n 4 ./userdef_ireduce.x | sort
0: fn: dt=0x7fff488353d0
0: fn: dt=0x7fff488353d0
0: fn: *dt=0x8c000005
0: fn: *dt=0x8c000005
0: main: &dt=0x7fff488356d8
0: main: dt=0x8c000005
1: fn: dt=0x7ffd422d7a00
1: fn: dt=0x7ffd422d7a00
1: fn: *dt=0x8c000005
1: fn: *dt=0x8c000005
1: main: &dt=0x7ffd422d7d08
1: main: dt=0x8c000005
2: fn: dt=0x7ffe48f99fb0
2: fn: dt=0x7ffe48f99fb0
2: fn: *dt=0x8c000005
2: fn: *dt=0x8c000005
2: main: &dt=0x7ffe48f9a2b8
2: main: dt=0x8c000005
3: fn: dt=0x7ffff2f3a730
3: fn: dt=0x7ffff2f3a730
3: fn: *dt=0x8c000005
3: fn: *dt=0x8c000005
3: main: &dt=0x7ffff2f3aa38
3: main: dt=0x8c000005
```

```
$ export IMPL=openmpi ; mpicc.${IMPL} -DBEFORE userdef_ireduce.c -o userdef_ireduce.x && mpirun.${IMPL} -n 4 ./userdef_ireduce.x | sort
0: fn: *dt=0x562049d8f290
0: fn: *dt=0x562049d8f290
0: fn: dt=0x7ffc27281828
0: fn: dt=0x7ffc27281828
0: main: dt=0x562049d8f290
0: main: &dt=0x7ffc27281b58
1: main: dt=0x55fa635584f0
1: main: &dt=0x7ffcc92ff2b8
2: fn: *dt=0x564670d8d500
2: fn: dt=0x7ffe956d2f98
2: main: dt=0x564670d8d500
2: main: &dt=0x7ffe956d32c8
3: main: dt=0x55c5a2eaa270
3: main: &dt=0x7ffe97a0ccd8
```
