### ISSUE TITLE
Errata: Noncollective (for procedure) and nonpersistent are not defined

### ISSUE THREAD

**Issue by jaegerj** [mpi-forum/mpi-issues#679]
# Problem

Noncollective procedure is hinted at in the Semantic terms section but never defined. The text says "Additionally, all MPI operation-related procedures can be collective or noncollective." 
Noncollective is used multiple times in the standard for procedures (see Chapter 14 I/O).

Nonpersistent is used only twice in the Standard (v4.0) but never defined.
1- in MPI_Cancel: "MPI_CANCEL can be used to cancel a communication that uses a persistent communication request (see Section 3.9), in the same way it is used for nonpersistent requests"
2- in the general index, for Matching "persistent with nonpersistent". Here, the word "nonpersistent" seems to relate to operations.
We should fix this.

# Proposal
define or remove these terms

# Changes to the Text
Noncollective for procedure: add a similar text for MPI procedures than for MPI operations in Semantic terms.
"Noncollective operations are defined as operations that are not collective" -> "Noncollective procedures are defined as procedures that are not collective"

Nonpersistent for operations: "Nonpersistent operations are defined as operations that are not persistent" (to keep the entry in the general index)
or 
Remove the term in the general index

Remove the part of the sentence ",in the same way it is used for nonpersistent requests" in MPI_Cancel description, as the behavior of MPI_Cancel for persistent requests is detailed in the following sentences.

# Impact on Implementations

None

# Impact on Users

better understanding of the Standard

# References and Pull Requests

Pull request [PR 820](https://github.com/mpi-forum/mpi-standard/pull/820)

**Comment by jaegerj** [comment]
Some usage of noncollective for procedures may be wrong in the I/O chapter.

From MPI Standard v4.0, Chap 14.4, p.661:
"Coordination

Every noncollective data access routine MPI_FILE_XXX has a collective counterpart. For most routines, this counterpart is MPI_FILE_XXX_ALL or a pair of MPI_FILE_XXX_BEGIN and MPI_FILE_XXX_END. The counterparts to the MPI_FILE_XXX_SHARED routines are MPI_FILE_XXX_ORDERED.
The completion of a noncollective call only depends on the activity of the calling process. However, the completion of a collective call (which must be called by all members of the process group) may depend on the activity of the other processes participating in the collective call. See Section 14.6.4 for rules on semantics of collective calls. Collective operations may perform much better than their noncollective counterparts, as global data accesses have significant potential for automatic optimization."

1) I am uncertain that the first part relates to procedures, and not the related operations.
2) "The completion of a noncollective call ..." a procedure doesn't complete, an operation completes. The second part clearly relates to operations, and not procedures.

**Comment by RolfRabenseifner** [comment]
The changes are marked with PR820 and also in yellow color on pages 5, 91, 98, 263 and 1046 in
[mpi41-report_Issue679_PR820.pdf](https://github.com/mpi-forum/mpi-standard/files/11372960/mpi41-report_Issue679_PR820.pdf)

**Comment by RolfRabenseifner** [comment]
The changes are marked with PR820 and also in yellow color on pages 5, 91, 98, 263, 2x1046, and 1047 in
[mpi41-report_Issue679_PR820.pdf](https://github.com/mpi-forum/mpi-standard/files/11432286/mpi41-report_Issue679_PR820.pdf)

**Comment by wesbland** [comment]
This passed a [errata vote](https://mpi-forum.org/meetings/2023/07/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 32
    <td> 0
    <td> 2
</table>
