### ISSUE TITLE
Description of MPI_TESTANY is inconsistent and wrong

### ISSUE THREAD

**Issue by jprotze** [mpi-forum/mpi-issues#681]
# Problem

The last paragraph of `MPI_TESTANY` description reads:

> If the array of requests contains active handles then the execution of `MPI_TESTANY`
has the same effect as the execution of `MPI_TEST` with each of the array elements in some
arbitrary order, until one call returns `flag = true`, or all fail. In the former case, index is
set to indicate which array element returned `flag = true` and in the latter case, it is set to
`MPI_UNDEFINED`. `MPI_TESTANY` with an array containing one active entry is equivalent
to `MPI_TEST`.

This contradicts the description above. Let's assume, we have at least one null handle and 
one active handle in the array. Picking the elements in arbitrary order, we pick the null handle
first. According to the algorithm, we pass this handle to `MPI_TEST`. The call returns with 
`flag = true`, so we terminate. The index is set to the index of the null handle. 

This behavior is clearly different from what is written in the first two paragraphs.

# Proposal

Make the last paragraph consistent with the intended behavior of the call and what is written 
in the first two paragraphs.

# Changes to the Text

Start the paragraph with
> If the array of requests contains **only** active handles

OR

Change the algorithm to only pass active handles to `MPI_TEST`

OR

Delete the paragraph

# Impact on Implementations

I hope, no implementation actually implemented `MPI_TESTANY` as described in the last paragraph. Nevertheless should the change give better guideance regarding the expected behavior.

# Impact on Users

Have clarity that `MPI_TESTANY` is not broken by design.

# References and Pull Requests

We came across this inconsistency working on #519

PR https://github.com/mpi-forum/mpi-standard/pull/818

**Comment by bosilca** [comment]
Why would an `MPI_Test` on `MPI_REQUEST_NULL` returns the flag set ? There is no active operation associated with `MPI_REQUEST_NULL`, so `flag`should be false. This makes the text above accurate.

**Comment by jeffhammond** [comment]
@bosilca Because that's what the standard says on page 72 (MPI 4.0):
> One is allowed to call MPI_TEST with a null or inactive request argument. In such a case the procedure returns with flag = true and empty status.

**Comment by bosilca** [comment]
Right, we need to be able to test `MPI_REQUEST_NULL`, so it makes sense to get out of the test with success. Back to the original question, the paragraph talks about active requests, and `MPI_REQUEST_NULL`is not active. We can replace `each of the array elements in some arbitrary order` by `each of the active requests in the array elements in some arbitrary order`.

**Comment by jprotze** [comment]
That's basically text change solution 2. I was not too confident about the concrete wording change for this solution.

**Comment by RolfRabenseifner** [comment]
I agree and recommend a very simple correction (in bold only to show the change):

> If the array of requests contains active handles then the execution of `MPI_TESTANY`
has the same effect as the execution of `MPI_TEST` with each of the **active handles in the** array **[removed: elements]** in some
arbitrary order, until one call returns `flag = true`, or all fail. In the former case, index is
set to indicate which array element returned `flag = true` and in the latter case, it is set to
`MPI_UNDEFINED`. `MPI_TESTANY` with an array containing one active entry is equivalent
to `MPI_TEST`.

**Comment by Wee-Free-Scot** [comment]
I'm going to announce this as an errata for MPI-4.1

**Comment by wesbland** [comment]
Had errata reading on 2023-05-02.

**Comment by wesbland** [comment]
This passed a [errata vote](https://mpi-forum.org/meetings/2023/05/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 30
    <td> 0
    <td> 2
</table>
