### ISSUE TITLE
Definition and Explanation of External32

### ISSUE THREAD

**Issue by ahori** [mpi-forum/mpi-issues#69]
# Problem

Basically external32 is (was) based on IEEE 754-1985. In the newer version (IEEE 754-2008), there are no definitions on "Single," "Double," and "Extended Double." These are replaced by "binary32," "binary64," and "binary128" in the newer standard. So, these terms in the MPI standard at page 540 (13.5.2) must be replaced with the new ones.

# Proposal

Update the external32 explanation by replacing the old names with the newly defined names.

# Changes to the Text

The current text;
"All floating point values are in big-endian IEEE format [37] of the appropriate size. Floating point values are represented by one of three IEEE formats. These are the IEEE “**Single**,” “**Double**,” and “**Double Extended**” formats, requiring 4, 8, and 16 bytes of storage, respectively. "

must replaced by;
"All floating point values are in big-endian IEEE format [37] of the appropriate size. Floating point values are represented by one of three IEEE formats. These are the IEEE “**binary32**,” “**binary64**,” and “**binary128**” formats, requiring 4, 8, and 16 bytes of storage, respectively. "

The citation [37] must also be replaced with IEEE-754-2008.

# Impact on Implementations

Nothing.

# Impact on Users

For users who are familiar with the old names, the old names can be left, for example, in a parentheses.

# References

IEEE 754-1985
IEEE 754-2008
https://en.wikipedia.org/wiki/IEEE_754

Pull Request: https://github.com/mpi-forum/mpi-standard/pull/113

**Comment by ahori** [comment]
External32 in the current MPI standard refers the old IEEE standard (see below). So the text MUST not be changed and leave it as it is. However, this will not prevent to propose new one, say "External32-1018," in the future.

`[37] Institute of Electrical and Electronics Engineers, New York. IEEE Standard for Binary Floating-Point Arithmetic, ANSI/IEEE Standard 754-1985, 1985. 13.5.2`

**Comment by ahori** [comment]
Update for the Chicago reading:
[mpi32-report-EXT32.pdf](https://github.com/mpi-forum/mpi-issues/files/3170834/mpi32-report-EXT32.pdf)

**Comment by ahori** [comment]
PR: https://github.com/mpi-forum/mpi-standard/pull/113

[mpi32-report-ticket113.pdf](https://github.com/mpi-forum/mpi-issues/files/3580623/mpi32-report-ticket113.pdf)

**Comment by wesbland** [comment]
This passed the first and only vote on in Zurich, Switzerland on 2019-09-07.

**Comment by ahori** [comment]
I am very pleased because I could have contributed to the forum eventually.  I thank Dan and Wesley for helping me to get this.

BTW, who is going to close this ticket? Is there anything I should do?

**Comment by wesbland** [comment]
It will close itself when Bill merges the pull request.
