### ISSUE TITLE
MPI_C_FLOAT_COMPLEX should be "as a synonym" in Appendix A.1

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#698]
# Problem

Table 3.2 says that `MPI_C_FLOAT_COMPLEX` is a synonym of `MPI_C_COMPLEX`.  Appendix A.1 does not.  This leads to confusion if one refers to the Appendix when writing an implementation.

# Proposal

Make Appendix A.1 match Table 3.2.

# Changes to the Text

# Impact on Implementations

Both MPICH and Open-MPI already implement `MPI_C_COMPLEX` as a synonym for `MPI_C_FLOAT_COMPLEX` so nothing will change.

# Impact on Users

Standard is consistent.

# References and Pull Requests

**Comment by jeffhammond** [comment]
We made this change in Chapter 3 and Chapter 6 but not in Appendix A.  This is therefore an editorial change.  Do you agree @wesbland @wgropp ?

Sorry for not noticing this before.  I only look at Appendix A for lists of datatypes.  I didn't realize we have 2 copies of the table.

**Comment by wgropp** [comment]
Yes, I agree this is an editorial change.

**Comment by jeffhammond** [comment]
@wesbland Why did you change it back to a chapter committee change?

**Comment by wesbland** [comment]
I'm really not sure. I'll change it back.

**Comment by wgropp** [comment]
Fixed by PR https://github.com/mpi-forum/mpi-standard/pull/828

**Comment by wgropp** [comment]
Fixed by PR https://github.com/mpi-forum/mpi-standard/pull/828
