### ISSUE TITLE
Cleanup Advice and Definition of MPI_COMM_FREE

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#7]
The advice to users around `MPI_COMM_FREE` is confusing when discussing using a reference-count internally when calling `MPI_COMM_DUP` and friends on a communicator. Implementations can't actually implement things in this way without doing a lot of extra work that no implementations actually use. We propose to remove the confusing advice.

It is also unclear what it is valid to do with a communicator after it has been freed. This is because there is a period of time between calling `MPI_COMM_FREE` and when the communicator is actually destroyed. As long as there are outstanding operations on the communicator, it could be valid to keep starting new operations because the handle is still good. We add a sentence to say that after a communicator has been freed, it is no longer valid to start new operations on the communicator. Adding this text also makes a paragraph in Chapter 2 unnecessary because it was supposed to deal with a situation where operations would have no way of reporting errors. This is never the case because at the very least, the communicator object can always be used.

**Update:**

Decided not to add the new normative text and only remove the advice. So now the issue removes the following text from the advice to implementors:

> A reference-count mechanism may be used: the reference count is incremented by each call to MPI_COMM_DUP or MPI_COMM_IDUP, and decremented by each call to MPI_COMM_FREE.  The object is ultimately deallocated when the count reaches zero.

**Comment by wesbland** [comment]
How does this impact the attribute deletion callbacks? Does this prevent calling MPI calls in that function? Is that already prevented?

**Comment by wesbland** [comment]
This may also prevent error handlers from posting operations after the communicator has been freed.

**Comment by abouteiller** [comment]
The part about "comm_dup" is not very helpful, since its the posting of communication operations that increase the refcount rather than being "duped". The advice reframed in that scope could be useful. 

The issue of preventing operations posting on an already freed handle is separate enough to have it's own resolution maybe.

**Comment by wesbland** [comment]
Perhaps rather than bringing these as separate ideas, we can just combine this with mpi-forum/mpi-issues#4 and do a rewrite of the advice and add the bit about not posting new operations on freed handles. The advice (or maybe a rationale) would be able to explain why that is the case.

**Comment by wesbland** [comment]
After more discussion, we decided that the semantic changes here related to new MPI operations after calling `MPI_COMM_FREE` are probably not a good idea. The standard actually does a reasonable job of defining what happens after a communicator is freed by the user when it still has outstanding operations. Our main concern was that error handlers and other similar callback functions would have a hard time using the communicator object that they were passed, but the implementation should be able to keep track of the communicator object until it has actually been refcounted to 0. This means that the callbacks will get a valid object and will be able to use it for communication.

We do still plan to remove the advice as it is confusing and generally not used by implementation in practice.

**Comment by wesbland** [comment]
This issue was passed and is ready to be merged by @wgropp.
