### ISSUE TITLE
Errata: Fortran has only compile-time constants

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#705]
# Problem

MPI-4.0 Section "2.5.4 Named Constants" writes

All named constants, [...], can be used in
initialization expressions or assignments, but not necessarily in array declarations or as
labels in C switch or Fortran select/case statements. This implies named constants
to be link-time but not necessarily compile-time constants.

Fortran has only compile-time constants. 

# Proposal

Restrict the details about link-time constants on C only. 

# Changes to the Text

See pull request [PR 819](https://github.com/mpi-forum/mpi-standard/pull/819)

# Impact on Implementations

None, as long as they are correct, i.e., they allow MPI constants in Fortran in initialization expressions.

# Impact on Users

None, as long as they use correct MPI implemetations

# References and Pull Requests

Pull request [PR 821](https://github.com/mpi-forum/mpi-standard/pull/821) solves both issues https://github.com/mpi-forum/mpi-issues/issues/705 and https://github.com/mpi-forum/mpi-issues/issues/657.
Pull request [PR 819](https://github.com/mpi-forum/mpi-standard/pull/819) solves only issue https://github.com/mpi-forum/mpi-issues/issues/705 and **is obsolete if we decide to solve both issues through [PR 821](https://github.com/mpi-forum/mpi-standard/pull/821)**.

**Comment by jeffhammond** [comment]
Indeed, @eschnett raised this during ABI discussions.

You should also add that link-time constants are not portable in C.  Windows does not support them.

**Comment by eschnett** [comment]
Regarding link-time constants in C:

A link-time constant can be something like `y` in
```C
extern int x;
int *const y = &x;
```
The value of `y` is the address of `x`. This is known at link time but not at compile time. I assume the MPI standard wants to allow e.g. `MPI_COMM_WORLD` to be the address of an object. This is allowed in Windows as well.

Yes, the MPI standard wording for Fortran does not make sense.

**Comment by jeffhammond** [comment]
We won't invalidate the Open-MPI design but it doesn't work on Windows according to others so we cannot use in the ABI. That's not relevant to this ticket though.

**Comment by RolfRabenseifner** [comment]
I tried to keep the changelog short. 
@eschnett Thank you for your example. It helped me to write a rationale that shows the background of the differences between Fortran and C. I packed it in a rationale.
@eschnett and @jeffhammond Do I understand it correctly: the provided link-time constant example is correct in Linux and Windows?

**Comment by jeffhammond** [comment]
If Erik tested it then I believe it, but I've been told that OMPI cannot work on Windows using the link time constant method it uses, so I would not imply it works in general. It's possible it only works in Erik's case because the target is visible in the same compilation unit.

**Comment by RolfRabenseifner** [comment]
The changes are marked with PR819 and also in yellow color on pages 18, 1015 and 1044 in 
[mpi41-report_Issue705_PR819.pdf](https://github.com/mpi-forum/mpi-standard/files/11358444/mpi41-report_Issue705_PR819.pdf)

**Comment by RolfRabenseifner** [comment]
The changes of [PR822](https://github.com/mpi-forum/mpi-standard/pull/822) are marked with PR822 and also in yellow color on pages 18, 764-769, 825-839, 1021, 1023, 1050 in
[mpi41-report_Issue705+657_PR822.pdf](https://github.com/mpi-forum/mpi-standard/files/11450065/mpi41-report_Issue705%2B657_PR822.pdf)

**Comment by RolfRabenseifner** [comment]
The changes of [PR822](https://github.com/mpi-forum/mpi-standard/pull/822) are marked with PR822 and also in yellow color on pages 18, 764-769, 825-839, 1021, 1023, 1050 in
[mpi41-report_Issue705+657_PR822_v2.pdf](https://github.com/mpi-forum/mpi-standard/files/11800606/mpi41-report_Issue705%2B657_PR822_v2.pdf)

**Comment by wesbland** [comment]
This passed a [errata vote](https://mpi-forum.org/meetings/2023/07/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 31
    <td> 0
    <td> 3
</table>
