### ISSUE TITLE
Minor typos in Chapter 1

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#71]
# Problem

These problems were identified (long ago) by Swann Perarnau. These are extracted from his mail and included below.  Pages are from the 3.0 version, but these errors are still present in 3.1 and 3.2

1.8, page 5, title: What Platforms Are Targets For Implementation ?, 'For' should not be capitalized.

1.9 same page, title: What Is Included In The Standard ?, 'in the' should not be capitalized.
In addition, some of the capitalization of the items in the list does not match the capitalization used for the chapters, and should be made consistent.

1.10, page 6 title: 'in the' should not be capitalized.

1.11 same page, missing capital on 'this' in the title.

# Proposal

Apply the fixes identified above.

# Changes to the Text

As above.

# Impact on Implementations
None

# Impact on Users
None, although proper grammar will be appreciated by some :) 

# References
Chicago Manual of Style

**Comment by wesbland** [comment]
These all seem like things that fall under the editor's latitude to fix I believe. You can just make a PR to do this yourself (and get a review if you want it). Right?

**Comment by wgropp** [comment]
Yep, that's my plan.
Bill

On Jan 1, 2018 3:01 PM, Wesley Bland <notifications@github.com> wrote:

These all seem like things that fall under the editor's latitude to fix I believe. You can just make a PR to do this yourself (and get a review if you want it). Right?

**Comment by schulzm** [comment]
wgropp merged 1 commit into mpi-forum:mpi-3.x from schulzm:issue_71
