### ISSUE TITLE
Longest Fortran specific procedure name in MPI-4.0 wrong?

### ISSUE THREAD

**Issue by raffenet** [mpi-forum/mpi-issues#716]
# Problem

MPI-4.0 Section 19.1.5 states in advice to implementers:

```
 [...] With this, the three longest subroutine declaration statements are
 SUBROUTINE PMPI_DIST_GRAPH_CREATE_ADJACENT(a,b,c,d,e,f,g,h,i,j,k)
 SUBROUTINE PMPI_NEIGHBOR_ALLTOALLW_INIT(a,b,c,d,e,f,g,h,i,j,k,l)
 SUBROUTINE PMPI_NEIGHBOR_ALLTOALLV_INIT(a,b,c,d,e,f,g,h,i,j,k,l)
 with 71 and 70 characters each. With buffers implemented with TS 29113, the specific
 procedure names have an additional postfix. Some of the longest of such interface
 definitions are
 INTERFACE PMPI_NEIGHBOR_ALLTOALLW_INIT
 SUBROUTINE PMPI_NEIGHBOR_ALLTOALLW_INIT_F(a,b,c,d,e,f,g,h,i,j,j,k)
 INTERFACE PMPI_NEIGHBOR_ALLGATHERV_INIT
 SUBROUTINE PMPI_NEIGHBOR_ALLGATHERV_INIT_F(a,b,c,d,e,f,g,h,i,j,k)
 INTERFACE PMPI_RGET_ACCUMULATE
 SUBROUTINE PMPI_RGET_ACCUMULATE_FTS(a,b,c,d,e,f,g,h,i,j,k,l,m,n)
 [...]
 The longest specific procedure name is PMPI_Reduce_scatter_block_init_c_f08ts with
 38 characters in the mpi_f08 module.
```

But the same section also says:
```
Within the mpi_f08 and mpi modules and mpif.h, for all MPI procedures, a second
procedure with the same calling conventions shall be supplied, except that the name is
modified by prefixing with the letter “P”, e.g., PMPI_Isend. The specific procedure names
for these PMPI_Xxxx procedures must be different from the specific procedure names for
the MPI_Xxxx procedures and are not specified by this standard.
```

It seems that specific procedure names for PMPI_ interfaces are not standard, making the specific procedure names for PMPI interfaces above suspect.

# Proposal

Option 1: Change examples and longest specific procedure name to something mandated by the standard.
Option 2: Change the standard to specify the specific procedure names for `PMPI_Xxxx` procedures in Fortran.
Option 3: Tell Ken he is wrong and close the issue.

# Changes to the Text

TBD

# Impact on Implementations

Option 1: None
Option 2: Change specific procedure names, if needed.

# Impact on Users

None.

# References and Pull Requests

none

**Comment by jprotze** [comment]
I think the confusion comes from the word "specified" in the standard. The paragraph above already specifies the procedure names. What the sentence should say is that the specific procedure names are not spelled out explicitly for the individual instances.

For C, the pmpi interface is defined in the same way.

**Comment by raffenet** [comment]
But in C there is no interface polymorphism to handle different argument types like there is in Fortran. You need an explicit `PMPI_Send_c` for C tools.

In Fortran, we tell users who intercept either `MPI_Send_f08ts` or `MPI_Send_c_f08ts` to call `PMPI_Send` from their tool. From my reading, the specific procedure names associated with `PMPI_Send` are unspecified and the user should not access them directly. This is the example used in the chapter:
```f90
SUBROUTINE MPI_Isend_f08ts(buf,count,datatype,dest,tag,comm,request,ierror)
USE :: mpi_f08, my_noname => MPI_Isend_f08ts
TYPE(*), DIMENSION(..), ASYNCHRONOUS :: buf
INTEGER, INTENT(IN) :: count, dest, tag
TYPE(MPI_Datatype), INTENT(IN) :: datatype
TYPE(MPI_Comm), INTENT(IN) :: comm
TYPE(MPI_Request), INTENT(OUT) :: request
INTEGER, OPTIONAL, INTENT(OUT) :: ierror
! ... some code for the begin of profiling
call PMPI_Isend (buf, count, datatype, dest, tag, comm, request, ierror)
! ... some code for the end of profiling
END SUBROUTINE MPI_Isend_f08ts
```

**Comment by RolfRabenseifner** [comment]
The idea behind the existing wording is, that tools must intersept the MPI interface. To be more exact, they must intersept the specific procedures. the PMIP interface need not to be intersepted. Therefore, we need not to have standardized specific routine names for the Fortran PMPI interface. Therefore, there is also no problem with the length of the names and with the line length of mpif.h used in fixed source form. 

> It seems that specific procedure names for PMPI_ interfaces are not standard, making the specific procedure names for PMPI interfaces above suspect.

The "suspect" in this sentence is therefore wrong and option 3 may be the best.

**Comment by RolfRabenseifner** [comment]
> But in C there is no interface polymorphism to handle different argument types like there is in Fortran. You need an explicit `PMPI_Send_c` for C tools.
> 
> In Fortran, we tell users who intercept either `MPI_Send_f08ts` or `MPI_Send_c_f08ts` to call `PMPI_Send` from their tool. From my reading, the specific procedure names associated with `PMPI_Send` are unspecified and the user should not access them directly. This is the example used in the chapter:
> 
> ```fortran-modern
> SUBROUTINE MPI_Isend_f08ts(buf,count,datatype,dest,tag,comm,request,ierror)
> USE :: mpi_f08, my_noname => MPI_Isend_f08ts
> TYPE(*), DIMENSION(..), ASYNCHRONOUS :: buf
> INTEGER, INTENT(IN) :: count, dest, tag
> TYPE(MPI_Datatype), INTENT(IN) :: datatype
> TYPE(MPI_Comm), INTENT(IN) :: comm
> TYPE(MPI_Request), INTENT(OUT) :: request
> INTEGER, OPTIONAL, INTENT(OUT) :: ierror
> ! ... some code for the begin of profiling
> call PMPI_Isend (buf, count, datatype, dest, tag, comm, request, ierror)
> ! ... some code for the end of profiling
> END SUBROUTINE MPI_Isend_f08ts
> ```

Perfect example and answer. It shows that the specific procedure name of PMPI_Isend is not relevant for the tools developers

**Comment by raffenet** [comment]
> The idea behind the existing wording is, that tools must intersept the MPI interface. To be more exact, they must intersept the specific procedures. the PMIP interface need not to be intersepted. Therefore, we need not to have standardized specific routine names for the Fortran PMPI interface. Therefore, there is also no problem with the length of the names and with the line length of mpif.h used in fixed source form.
> 
> > It seems that specific procedure names for PMPI_ interfaces are not standard, making the specific procedure names for PMPI interfaces above suspect.
> 
> The "suspect" in this sentence is therefore wrong and option 3 may be the best.

Let me try to be explicit, because I am still confused.

In MPICH, if we provide specific procedure name `MPI_Reduce_scatter_block_init_c_f08ts`, do we also need to provide `PMPI_Reduce_scatter_block_init_c_f08ts`? If not, why is the standard telling me that it is the longest specific procedure name?

**Comment by RolfRabenseifner** [comment]
@raffenet Yes Ken, you are right. The MPI-4.0 sentence 
> The longest specific procedure name is PMPI_Reduce_scatter_block_init_c_f08ts with 38 characters in the mpi_f08 module.

should better read
> If an implementation applies the rules of Table 19.1 also for the PMPI interface, then the longest specific procedure name is PMPI_Reduce_scatter_block_init_c_f08ts with 38 characters in the mpi_f08 module.

I recommend to do this small addition as a chapter committee change before the July meeting. 
Please, can you provide this one-sentence pull request?

Thank you for catching this still in time before I finally retire :-)

Best regards
Rolf
