### ISSUE TITLE
Behavior of MPI_Dims_create when ndims is zero

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#72]
# Problem

The standard does not explicitly define what MPI_DIMS_CREATE does when ndims is zero. Note that ndim is an integer, so zero is a valid value.

# Proposal

To be consistent with MPI_Cart_create, which does define the behavior when ndims is zero (see page 292, line 39), MPI_Dims_create should permit ndims == 0 (as long as nnodes is 1), but produce no output (no values in the dims array) but return MPI_SUCCESS.

# Changes to the Text

Add after line 30:

    If ndims is zero and nnodes is one, MPI_DIMS_CREATE returns MPI_SUCCESS.

Note that since only dims[0] ... dims[ndims-1] is updated, it is not necessary for the standard to mention that dims is not updated in this case.

# Impact on Implementations

At most implementations would need to permit ndims == 0, check nnodes==1, and return MPI_SUCCESS.

# Impact on Users

None, other than providing a cleaner interface and permit 

MPI_Dims_create(...)
MPI_Cart_create(...)

instead of 

if (ndim > 0) MPI_Dims_create(...)
MPI_Cart_create(...)

No correct program will need to be changed.

# References

There was email discussion of this on MPI-comments between Nov 8-10, 2016.
Insert any internal (other issues) or external (websites, papers, etc.) references here.

It was argued there that this is a clarification, not a change or an errata.

**Comment by schulzm** [comment]
Created the matching text and turned it into
https://github.com/mpi-forum/mpi-standard/pull/41
I will present this at the Forum in Austin - I do think, though, this is more than an editorial change

**Comment by schulzm** [comment]
The forum decided to treat this as an errata - will have its vote at the Austin meeting

**Comment by schulzm** [comment]
Passed errata vote at Austin 2018 meeting

**Comment by wgropp** [comment]
This still requires a errata entry for the errata document.  The errata document contains errata and clarifications that can affect user programs, which this does as noted in the (limited) impact on user programs.

**Comment by wesbland** [comment]
@schulzm - I assume you'll take care of the errata entry since this is your ticket?

**Comment by schulzm** [comment]
This is complete and merged
