### ISSUE TITLE
Nonexistant LaTeX label used in semantic changes and warnings chapter.

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#725]
# Problem

Reference to a nonexistent label in the semantic changes and warnings chapter.

# Proposal

Delete the bad reference to `\ref{macros}`

# Changes to the Text

Change
`Implementations are no longer allowed to implement \mpifunc{MPI\_WTICK}, \mpifunc{PMPI\_WTICK}, \mpifunc{MPI\_WTIME}, and \mpifunc{PMPI\_WTIME}
as well as handle conversion functions as macros (Sections~\ref{sec:timers}, \ref{sec:misc-handleconvert}, and~\ref{macros}).`
to
`Implementations are no longer allowed to implement \mpifunc{MPI\_WTICK}, \mpifunc{PMPI\_WTICK}, \mpifunc{MPI\_WTIME}, and \mpifunc{PMPI\_WTIME}
as well as handle conversion functions as macros (Sections~\ref{sec:timers} and~\ref{sec:misc-handleconvert}).`

An alternative would be to add a reference to `\ref{sec:macros}`, which talks (in the MPI 4.1 text) only about the MPI routines that can be implemented as macros (aint add and diff). But this doesn't fit in the sentence about the routines that can no longer be implemented as macros, as they are not mentioned in that section. 

# Impact on Implementations

None

# Impact on Users

None

# References and Pull Requests

**Comment by RolfRabenseifner** [comment]
@wgropp Good catch. Can you proceed?

**Comment by wgropp** [comment]
I will include this in a number of other LaTeX warnings and errors.
