### ISSUE TITLE
Removing unnecessary text

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#728]
# Problem

As part of the PMPI interface, text provides unnecessary meta language about how unpleasant the situation is for library implementors. It does not provide any additional information. The text would be clearer and more concise without it.

# Proposal

Remove the sentence.

# Changes to the Text

[PR#851](https://github.com/mpi-forum/mpi-standard/pull/851)

# Impact on Implementations

Improved readability.

# Impact on Users

Improved readability.

# References and Pull Requests

**Comment by jeffhammond** [comment]
I find this text useful, and it would likely help me if I had to write an MPI implementation from scratch using only the standard.

**Comment by wrwilliams** [comment]
> I find this text useful, and it would likely help me if I had to write an MPI implementation from scratch using only the standard.

The second half of the sentence could I guess be AtoI ("you may need to do XYZ to implement this on some systems") but unlike the surrounding sentences is clearly not normative, the first half is neither useful nor normative. Do you strongly prefer that it be AtoI rather than deleted? There are lots of sentences that are helpful to implementers, true, and not present in the standard.

**Comment by jeffhammond** [comment]
I think removing this is a waste of the Forum's time.  It does zero harm to leave it there.  It is potentially helpful.  That it is not normative is irrelevant.  Lots of text that isn't AtoI is not normative.  For example, we have a sentence "In C, the use of void* formal arguments avoids these problems [with Fortran type checking]," that informs the reader of the differences between C and Fortran.  Should we remove that too?

**Comment by mahermanns** [comment]
> I find this text useful, and it would likely help me if I had to write an MPI implementation from scratch using only the standard.

The remaining text still states what is needed and why it's needed, doesn't it?

Is the advice discussed in the second part of the sentence the still current practice? If yes, I agree to @wrwilliams in bringing the second part back as an AtoI, if not we should replace it with the current state of the practice, shouldn't we?

I am not against useful advice to users or implementors. What struck me as odd here is the colloquial and complaining tone of the sentence.

**Comment by mahermanns** [comment]
> I think removing this is a waste of the Forum's time. It does zero harm to leave it there. It is potentially helpful. That it is not normative is irrelevant. Lots of text that isn't AtoI is not normative. For example, we have a sentence "In C, the use of void* formal arguments avoids these problems [with Fortran type checking]," that informs the reader of the differences between C and Fortran. Should we remove that too?

No, I wouldn't remove that. However if the sentence read

> Getting Fortran type checking work with C is an unpleasant task. as we need to use `void *` in C to avoid these problems.

I would propose to remove the first part of the sentence as well. (I hope I didn't obscure the reasoning of the initial statement here, but you should  get the gist)

**Comment by mahermanns** [comment]
@jeffhammond I brought back some of the text, leaving the only changes to be
1. Removing unnecessary meta language
2. Being more precise on on the implications (it's the 'compilation unit' that is meant here and not the 'file'.

Would you agree now that this is a chapter committee change without loosing important information?

**Comment by jeffhammond** [comment]
sure, the proposed change is fine with me
