### ISSUE TITLE
Update testing header file for MPI 4.1

### ISSUE THREAD

**Issue by bkmgit** [mpi-forum/mpi-issues#736]
# Problem

MPI 4.1 introduces some new functions, but these have not all been added to the tests used to check the standard.

# Proposal

Add new MPI function declarations for MPI 4.1 to the testing header file 

# Changes to the Text

No text changes needed.

# Impact on Implementations

Better check of conformant implementations.

# Impact on Users

Should enable better consistency in the standard.

# References and Pull Requests

Arose from https://github.com/mpi-forum/mpi-standard/pull/860

**Comment by wgropp** [comment]
I've added the ones needed for the examples in the 4.1 document. I am closing this issue.
