### ISSUE TITLE
Errata entry of PR #754 in wrong section

### ISSUE THREAD

**Issue by th-hlrs** [mpi-forum/mpi-issues#747]
# Problem

Errata entry of PR[#754](https://github.com/mpi-forum/mpi-standard/pull/754) to Issue https://github.com/mpi-forum/mpi-issues/issues/443 was voted in in February 2023. But its change-log entry is placed in section Changes from Version 3.1 to Version 4.0

# Proposal

Move the paragraph to section Changes from Version 4.0 to Version 4.1

# Changes to the Text

Move the paragraph to section Changes from Version 4.0 to Version 4.1

# Impact on Implementations

None.

# Impact on Users

They find the errata where they expect it to be.

**Comment by wesbland** [comment]
I think there's a similar problem here: https://github.com/mpi-forum/mpi-issues/issues/741

**Comment by th-hlrs** [comment]
In which sense do you think they are similar? If I am not mistaken, then both entries mentioned in #741 should be in the correct place, but one is redundant. I will write a PR for discussions suggesting to remove the shorter one.
