### ISSUE TITLE
RMA: Contradicting rules about use  of MPI_REQUEST_FREE

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#760]
# Problem

While rewriting parts of the text about request-based RMA operations a restriction forbidding the use of `MPI_REQUEST_FREE` on RMA requests was missed:

Restriction:

> It is erroneous to call MPI_REQUEST_FREE or MPI_CANCEL for a request associated with an RMA operation.
RMA requests are not persistent.

> However, users must still free the request by testing, waiting, or calling MPI_REQUEST_FREE on the
request handle to allow the MPI implementation to release any resources associated with these requests.

The original text read:

> However, users must still wait or test on the request handle to allow the MPI implementation to
clean up any resources associated with these requests; in such cases the wait operation will
complete locally.

See:
https://github.com/mpi-forum/mpi-standard/pull/611/files#diff-abcde0810b89c0faf160df24683574bc0f017a2e677e3b8dd0d2d73116877a9eR1998

# Proposal

Reintroduce the original text, minus the last subclause.

# Changes to the Text

> However, users must still wait or test on the request handle to allow the MPI implementation to
clean up any resources associated with these requests.

# Impact on Implementations

None

# Impact on Users

None

# References and Pull Requests

RMA semantic terms changes: https://github.com/mpi-forum/mpi-standard/pull/611

PR: tbd

**Comment by wesbland** [comment]
This passed an [errata vote](https://mpi-forum.org/meetings/2024/09/votes) on 2024-09-23.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 24
	<td> 0
	<td> 6
</table>
