### ISSUE TITLE
mpiexec and PMPI_ falsely appearing in the function index

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#785]
# Problem

`mpiexec`, `mpirun` and `PMPI_` are not functions and should not be in the function index
several other `PMPI_XXX` functions are in the function index, yet their `MPI_XXX` counterparts are already listed in the function listed.

# Proposal

Remove them from the function index.

# Changes to the Text

tbd.

# Impact on Implementations

None

# Impact on Users

Less confusion; cleaner index

# References and Pull Requests

**Comment by abouteiller** [comment]
I can help look at the mpiexec/mpirun term index, I think I wrote the problem text.

**Comment by mahermanns** [comment]
@abouteiller I took the liberty to create a branch  with changes needed to remove all offending entries from the function index.

However, while it does not make sense to have specific PMPI functions referenced, yet I wonder whether we should enter some special terms index entries there instead, such as `\mpitermindex{profiling interface!Intercepting Fortran 2008 procedures}`.

What do you think?

**Comment by mahermanns** [comment]
Sorry for the label confusion. I will separate the issues of `mpiexec` and `PMPI_` function index mentionings and deal with the `PMPI_Isend` mention as part of a standard issue that needs to be discussed by the forum.
