### ISSUE TITLE
Callback-driven event interface for MPI_T

### ISSUE THREAD

**Issue by mahermanns** [mpi-forum/mpi-issues#79]
# Problem

Currently there is no interface portable across MPI implementations to inquire and get notified about events within the implementation (e.g., a message gets matched, a lock gets acquired, etc.).

# Proposal

Create a set of function calls in symmetry with the existing MPI_T cvar and pvar interface to query available events and register callback functions to be called by the implementation when they occur.

# Changes to the Text

The necessary text will be integrated into the MPI_T section of the Tools Interface chapter.

# Impact on Implementations

* Implementation will be required to implement the query interface to allow portable tools to query available events.
* Implementations will not be required make specific events available to the user via this interface.

# Impact on Users

Users (primarily tools) will be able to obtain more fine grained information from within the MPI implementation to give better advice on performance and correctness.

# References

* [Tools WG Discussion Page](https://github.com/mpiwg-tools/tools-issues/wiki/MPI_T-Events)
* [Tools WG issue #11](https://github.com/mpiwg-tools/tools-issues/issues/11)
* Pull Request: https://github.com/mpi-forum/mpi-standard/pull/33

**Comment by mahermanns** [comment]
PDF version for March Reading: [mpi32-report-20190218.pdf](https://github.com/mpi-forum/mpi-issues/files/2876870/mpi32-report-20190218.pdf)

**Comment by jsquyres** [comment]
Is there an updated PDF for the Chicago May 2019 meeting?

**Comment by mahermanns** [comment]
Full PDF: [mpi32-report.pdf](https://github.com/mpi-forum/mpi-issues/files/3229216/mpi32-report.pdf)

**Comment by mahermanns** [comment]
Updated PDF after discussion on May 29, 2019: [mpi32-report.pdf](https://github.com/mpi-forum/mpi-issues/files/3232894/mpi32-report.pdf)

**Comment by mahermanns** [comment]
Full PDF: [mpi32-report.pdf](https://github.com/mpi-forum/mpi-issues/files/3586358/mpi32-report.pdf)

**Comment by wesbland** [comment]
This passed the first vote on in Zurich, Switzerland on 2019-09-07.

**Comment by wesbland** [comment]
> This passed the first vote (and no-no vote) in Zurich, Switzerland on 2019-09-07.

This comment is wrong I think. I don't have us as having done a first vote at the September 2019 meeting, just a first vote. Is that what you have too @mahermanns ?

https://www.mpi-forum.org/meetings/2019/09/votes

**Comment by mahermanns** [comment]
> This comment is wrong I think. I don't have us as having done a first vote at the September 2019 meeting, just a first vote. Is that what you have too @mahermanns ?

As far as I understood, the no no-vote in Zürich was to incorporate some minor fixes so we could have a proper **reading** at Zürich. Therefore, I announced this for a **1st vote in ABQ**.

**Comment by wesbland** [comment]
Ok. Then we agree I think. Thanks.

**Comment by wesbland** [comment]
This passed the first vote in Albuquerque, New Mexico on 2019-12-12.

**Comment by wesbland** [comment]
This proposal passed a no-no vote (removing extent) at the February 2020 meeting:

Yes - 23
No - 0
Abstain - 1

This proposal passed another no-no vote (timestamp as count) at the February 2020 meeting:

Yes - 23
No - 0
Abstain - 1

**Comment by wesbland** [comment]
This proposal passed a second and final vote at the November 2020 meeting:

Yes - 24
No - 0
Abstain - 0
