### ISSUE TITLE
subsubsection numbering is not showing

### ISSUE THREAD

**Issue by jaegerj** [mpi-forum/mpi-issues#796]
# Problem

In the document, we use \subsubsection{}, but the numbering of subsubsection is not showing on the generated pdf.
This usually creates a weird orphan small sentence of word.
See review from Guillaume for RC41, l.98 in the speadsheet.
Another example is the single word "Accumulate" with no numbering nor special font, p573 (document numbering) l.10 (rc41 document).

# Proposal

Show subsubsection numbering, or use a special font to indicate it's the start of a new subsection.

# Changes to the Text

See above

# Impact on Implementations

none

# Impact on Users

Better readability

# References and Pull Requests

**Comment by wgropp** [comment]
Another option is to reword the text to not depend on subsubsection. I can make the font bold or italics.

**Comment by jaegerj** [comment]
Subsubsection are used throughout the whole document. Thus, rewording may require involvement of all chapter committees. We may think of this for 4.2, but 4.1 seems out of scope.

for 4.1, having a bold font may do the trick.

**Comment by jprotze** [comment]
If the main concern is the TOC, latex provides separate settings for the depth of TOC from depth of numbering: 
```
\setcounter{secnumdepth}{3}
\setcounter{tocdepth}{2}
```

**Comment by jaegerj** [comment]
Oh yes, we can do that.

**Comment by wgropp** [comment]
I will take care of this in my editors fixes
