### ISSUE TITLE
Memory Allocation Kinds side document

### ISSUE THREAD

**Issue by rzambre** [mpi-forum/mpi-issues#809]
# Problem

The differences in memory types on modern systems influence feature availability and performance behavior of an application running on such systems. For a given type of memory, MPI libraries need to know the associated memory allocator and the limitations on memory access. The different memory kinds capture the differentiating information needed by MPI libraries for different memory types.

# Proposal

An MPI side document titled "Memory Allocation Kinds" that defines the memory allocation kinds and their associated restrictors that users can use to query the support for different memory kinds provided by the MPI library. These definitions supplement those that will be defined in section 11.4.3 of the MPI 4.1 standard, which also explains their usage model.

[mpi-report-5.pdf](https://github.com/user-attachments/files/17081420/mpi-report-5.pdf)
[mpi-report-4.pdf](https://github.com/mpi-forum/mpi-issues/files/14452843/mpi-report-4.pdf)
[mpi-report-3.pdf](https://github.com/mpi-forum/mpi-issues/files/13620603/mpi-report-3.pdf)
[mpi-report-2.pdf](https://github.com/mpi-forum/mpi-issues/files/13549559/mpi-report-2.pdf)
[mpi-report-1.pdf](https://github.com/mpi-forum/mpi-issues/files/13227813/mpi-report-1.pdf)

# Changes to the Text

New side document.
No changes to the MPI standard. 

# Impact on Implementations

MPI implementations would need to map their heterogeneous memory support to the strings defined in the proposal.

# Impact on Users

MPI users would need to use the strings defined in this proposal to achieve portability in their requests and queries of heterogenous memory support across MPI implementations.

# References and Pull Requests

https://github.com/mpi-forum/mem-alloc/pulls?q=

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2024/09/votes) on 2024-09-24.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 26
	<td> 0
	<td> 4
</table>

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2024/12/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 28
    <td> 0
    <td> 1
</table>

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2024/12/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 26
    <td> 0
    <td> 3
</table>

**Comment by wesbland** [comment]
@rzambre to send me a date stamped PDF to publish on the website.

**Comment by jeffhammond** [comment]
I still don't see any memory allocation kinds allocation side document on https://www.mpi-forum.org/docs/.  @rzambre is this available somewhere?

**Comment by rzambre** [comment]
Thanks for checking @jeffhammond. The doc is up on the website now https://www.mpi-forum.org/docs/#:~:text=MPI%20Memory%20Allocation%20Kinds
