### ISSUE TITLE
groups: relax restriction on pset name provenance

### ISSUE THREAD

**Issue by hppritcha** [mpi-forum/mpi-issues#811]
# Problem

It is anticipated that process set names will be used in more dynamic ways as the use cases for sessions broadens.
The wording around sessions and process set names in the process management chapter was intentionally made general enough that the methods defined in the chapter would not be overly restrictive on how process set names are generated and made usable by an MPI implementation.

In the Groups, communciators, etc. chapter there was wording about the ```pset_name``` argument to ```MPI_GROUP_FROM_SESSION_PSET``` that was restrictive in these regards.   The Sessions WG wants to change the wording to relax this restriction.

# Changes to the Text

# Impact on Implementations

Would allow implementations to permit use of ```pset_names``` that the application acquired by means other than querying ```MPI_SESSION_GET_NTH_PSET```.

# Impact on Users

Allows users to obtain ```pset_names``` from, for example, the runtime using non-MPI methods.

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/938

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2024/03/votes) on 2024-03-19.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 28
	<td> 0
	<td> 4
</table>

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2024/03/votes) on 2024-03-20.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 29
	<td> 0
	<td> 3
</table>

**Comment by wesbland** [comment]
This passed a [1st vote](https://mpi-forum.org/meetings/2023/12/votes) on 2023-12-05.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 24
	<td> 0
	<td> 6
</table>
