### ISSUE TITLE
Make examples in `MPI_COMM_SPLIT_TYPE` consistent with `MPI_GET_HW_RESOURCE_INFO`

### ISSUE THREAD

**Issue by GuillaumeMercier** [mpi-forum/mpi-issues#823]
# Problem

The examples (7.3 and 7.4 pp 335-338)  in `MPI_COMM_SPLIT_TYPE` (when using the `GUIDED` mode) does not use the URI format described in `MPI_GET_HW_IRESOURCE_NFO`.

# Proposal

Change the text to have better consistency.

# Changes to the Text

`NUMANode` -> `hwloc://NUMANode`

# Impact on Implementations

None.

# Impact on Users

None

# References and Pull Requests

mpi-forum/mpi-standard/pull/955

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2024/09/votes) on 2024-09-23.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 24
	<td> 0
	<td> 6
</table>

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2024/09/votes) on 2024-09-24.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 26
	<td> 0
	<td> 4
</table>

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2024/12/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 26
    <td> 0
    <td> 3
</table>
