### ISSUE TITLE
`MPI_GET_HW_RESOURCE_INFO` needs an example

### ISSUE THREAD

**Issue by GuillaumeMercier** [mpi-forum/mpi-issues#824]
# Problem

To better understand how `MPI_GET_HW_RESOURCE_INFO` complements the guided splitting mode of `MPI_COMM_SPLIT_TYPE`, put an actual code example.

# Proposal

Provide an example.

# Changes to the Text

# Impact on Implementations

None.

# Impact on Users

Improved understandability.

# References and Pull Requests
Fixed by  mpi-forum/mpi-standard/pull/957

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2024/09/votes) on 2024-09-23.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 24
	<td> 0
	<td> 6
</table>

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2024/09/votes) on 2024-09-24.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 26
	<td> 0
	<td> 4
</table>

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2024/12/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 26
    <td> 0
    <td> 3
</table>
