### ISSUE TITLE
MPI_T ABI

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#835]
# Problem

The constants in the MPI tools interface need to be defined in the ABI.

# Proposal

Somebody from the Tools WG needs to provide values to e.g. https://github.com/mpiwg-abi/header_and_stub_library/blob/main/mpi.h#L493.

# Changes to the Text

TODO

# Impact on Implementations

Necessary for ABI.

# Impact on Users

Necessary for ABI.

# References and Pull Requests

**Comment by mahermanns** [comment]
As per discussion in the Tools WG call on Mar 04, 2024:

-  `MPI_T_ERR_XXX` need to adhere to the restrictions of error codes (i.e., ranges of values, etc.)
- It might be of benefit to have different constant groups "own" different bitmasks (i.e., make any `MPI_T_BIND_xxx` distinguishable from `MPI_T_PVAR_CLASS_xxx` ... but this would be an interesting benefit, not strictly required
- The `MPI_T_CB_xxx` constants form a hierarchy, so in principle one could make them some form of bitfield, but it is also not strictly required, as they are not used in the bitfield-ish way of ORing multiple of those constants anyway. Again, this may add comfort, but as long as they are strictly distinct, I think, this should be OK.

We didn't get to checking for all MPI_T constants in the call and more discussion seems to be in order.

**Comment by mahermanns** [comment]
As @jeffhammond read the C ABI at the September 2024 meeting with all feedback of our group included, and not further changes anticipated, we close this ticket.
