### ISSUE TITLE
Text for `MPI_GET_HW_RESOURCE_INFO` needs clarification 

### ISSUE THREAD

**Issue by GuillaumeMercier** [mpi-forum/mpi-issues#838]
# Problem

# Proposal

After some discussions with @jsquyres, an agreement was found about improving the current text. 

# Changes to the Text

Two advices to users (AtoU) are added/expanded.

# Impact on Implementations

None, since AtoU text is non-normative.

# Impact on Users

Better understanding of what this function does.

# References and Pull Requests

Fixed by https://github.com/mpi-forum/mpi-standard/pull/964

**Comment by wesbland** [comment]
This passed a [no-no vote](https://mpi-forum.org/meetings/2024/09/votes) on 2024-09-23.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 24
	<td> 0
	<td> 6
</table>

**Comment by wesbland** [comment]
This passed a [first vote](https://mpi-forum.org/meetings/2024/09/votes) on 2024-09-24.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 26
	<td> 0
	<td> 4
</table>

**Comment by wesbland** [comment]
This passed a [2nd vote](https://mpi-forum.org/meetings/2024/12/votes).
<table>
<tr>
    <td> Yes
    <td> No
    <td> Abstain
<tr>
    <td> 25
    <td> 0
    <td> 4
</table>
