### ISSUE TITLE
RMA requests and MPI_REQUEST_FREE

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#855]
# Problem

The text in 12.3.5 regarding `MPI_REQUEST_FREE` seems contradictory.  It is erroneous to call `MPI_REQUEST_FREE` on RMA requests, but also, one must still free the requests by doing one of three things, of which `MPI_REQUEST_FREE` is one.

> It is erroneous to call MPI_REQUEST_FREE or MPI_CANCEL for a request associated with an RMA operation.
>
> However, users must still free the request by testing, waiting, or calling MPI_REQUEST_FREE on the request handle to allow the MPI implementation to release any resources associated with these requests.

Did we fix this already (after 4.1) and I missed it?  Or am I not thinking clearly?

# Proposal

# Changes to the Text

# Impact on Implementations

# Impact on Users

# References and Pull Requests

**Comment by raffenet** [comment]
Is this the same as #760 and mpi-forum/mpi-standard#904?

**Comment by jeffhammond** [comment]
Yes, it's a duplicate. Thanks.
