### ISSUE TITLE
Website: Add MPI 4.1 implementation status table

### ISSUE THREAD

**Issue by EwoutH** [mpi-forum/mpi-issues#856]
Currently, MPI 3.1 and 4.0 have tables for the [implementation status](https://www.mpi-forum.org/implementation-status/) on the website. It would be really useful if a table for MPI 4.1 was added.

![image](https://github.com/user-attachments/assets/65395251-d792-4d89-b5d9-d25478f80ab6)

**Comment by jeffhammond** [comment]
There's a link in "Create a pull request [here](https://github.com/mpi-forum/mpi-forum.github.io/edit/master/Implementation_Status.md) to make that change" at the bottom of the page.  It would be great if you can make the changes for what 4.1 features should be marked by the implementations.

**Comment by jeffhammond** [comment]
Here's a list of changes I can imagine wanting to see:

- [ ] MPI_WTIME, PMPI_WTIME, MPI_WTICK, and PMPI_WTICK are symbols, not macros (already true everywhere AFAIK)
- [ ] MPI handle conversion functions is not a macro (MPICH derivatives might need a change here)
- [ ] MPI_REQUEST_GET_STATUS makes progress
- [ ] MPI_STATUS_{GET,SET}_{SOURCE,TAG,ERROR} are implemented
- [ ] MPI_BUFFER_AUTOMATIC, MPI_BUFFER_(I)FLUSH and related are implemented
- [ ] MPI_REQUEST_GET_STATUS_ANY, MPI_REQUEST_GET_STATUS_SOME, and MPI_REQUEST_GET_STATUS_ALL are implemented
- [ ] MPI_TYPE_GET_VALUE_INDEX is implemented
- [ ] MPI_COMM_TYPE_RESOURCE_GUIDED and mpi_pset_name are supported
- [ ] mpi_assert_strict_persistent_collective_ordering is supported
- [ ] mpi_memory_alloc_kinds and mpi_assert_memory_alloc_kinds are supported
- [ ] MPI_{COMM,TYPE,WIN}_GET_NAME support the appropriate null handles
- [ ] MPI_GET_HW_RESOURCE_INFO is implemented
- [ ] MPI_ERR_ERRHANDLER is supported
- [ ] MPI_REMOVE_ERROR_CLASS, MPI_REMOVE_ERROR_CODE, MPI_REMOVE_ERROR_STRING are implemented
- [ ] MPI_WIN_SHARED_QUERY allowed for CREATE and ALLOCATE windows
- [ ] mpi_accumulate_granularity is supported

This is perhaps too detailed.

**Comment by jeffhammond** [comment]
I am working on a pull request now...

**Comment by jeffhammond** [comment]
See https://github.com/mpi-forum/mpi-forum.github.io/pull/19

**Comment by wesbland** [comment]
Above PR was merged.
