### ISSUE TITLE
Typos in MPI 3.1

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#9]
- Page 176 / line 46: no comma after "MPI_DOUBLE_PRECISION".
- Page 176 / line 47: no comma after "MPI_LONG_DOUBLE".
- Page 177 / line 4: no space before "MPI_C_BOOL".

WBR,
   Mikhail Kurnosov mkurnosov@gmail.com

**Comment by schulzm** [comment]
Ticket 0, created PR

https://github.com/mpi-forum/mpi-standard/pull/38

**Comment by schulzm** [comment]
wgropp merged commit af8994b into mpi-forum:mpi-3.x
