### ISSUE TITLE
MPI_STATUS_SET_CANCELED F08 binding: flag param intent

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#91]
# Problem

The language neutral binding for MPI_STATUS_SET_CANCELLED (MPI-3.1 p483:38) says that the `flag` parameter should be `in`.  The C binding declares `int flag` (MPI-3.1 p483:43).  But the F08 binding (MPI-3.1 p483:47) declares `LOGICAL, INTENT(OUT) ::  flag`.

# Proposal

The F08 binding should change the `flag` declaration to `LOGICAL, INTENT(IN) ::  flag`.

# Changes to the Text

`LOGICAL, INTENT(OUT) ::  flag` changes to `LOGICAL, INTENT(IN) ::  flag`

# Impact on Implementations

Fix their binding.

# Impact on Users

This could potentially introduce a backwards compatibility issue (in terms of compiling or linking) if users have coded their app to `use mpi_f08` and they are calling `MPI_STATUS_SET_CANCELLED`.

(but let's be brutally honest here -- no one is using `MPI_STATUS_SET_CANCELLED` in Fortran)

# References

Open MPI v3.0.1: has `flag` set to `INTENT(OUT)`.
MPICH 3.2.1: has `flag` set to `INTENT(OUT)`.

**Comment by schulzm** [comment]
Passed errata vote at Austin 2018 meeting

**Comment by wgropp** [comment]
This has been merged. It probably should have an errata item, because the standard was wrong, and (in the unlikely event anyone used Status_set_cancelled in Fortran), this is a correction.
