### ISSUE TITLE
The terms chapter is missing many terms we would like to see added for MPI-4

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#96]
# Problem

When reviewing the terms chapter to clarify issues for persistent/persistence (which was not defined there) and adding focused new changes to support persistence, we discovered that there are evidently many missing terms.   In preparing for the MPI-4 release, a complete glossary with definitions (some which may just be later in the standard) is missing.  What is more, the use of some terms are used interchangeably in the standard, and it might be necessary to review the entire proposal text once the glossary is updated, to uniformize certain terminology for clarity.  

No such changes will make functional changes in MPI-4, but we want the standard to be understandable to non-experts.

# Proposal

Add a full glossary of terms, clarify existing terms, add missing terms (e.g., buffer).   Clarify the differences between operations, procedure calls (aka procedures, aka calls), etc.  A thorough study of all useful glossary terms and standardized definitions should be here.  

# Changes to the Text

The terms chapter will be revised and extended.  Once that's done, it may be useful for chapter authors to review the terms, and make sure each chapter complies with the terminology as clarified.   No non-editorial changes are expected from such a review.

# Impact on Implementations

None.

# Impact on Users

Users will be able to understand the standard better.

# References

Ticket #90 addresses limited editions to the same chapter.

PR https://github.com/mpi-forum/mpi-standard/pull/116 provides the official changes for this ticket.

Presentation that provides the motivation for this issue: 
[SemanticTerms-Motivation-06020202.pdf](https://github.com/mpi-forum/mpi-issues/files/4842765/SemanticTerms-Motivation-06020202.pdf)

PDF file used for successful reading (including the changes from no-no-votes): [mpi40-report-ticket96-98f6380-01july2020.pdf](https://github.com/mpi-forum/mpi-standard/files/4858311/mpi40-report-ticket96-98f6380-01july2020.pdf)

Latest PDF file: [mpi40-report-ticket96-5ccf3e4-18Aug2020.pdf](https://github.com/mpi-forum/mpi-standard/files/5093050/mpi40-report-ticket96-5ccf3e4-18Aug2020.pdf)

Presentation on additional topics for MPI 4.1 and related discussion can be found here:
[SemanticTerms-4.1-Discussion.pdf](https://github.com/mpi-forum/mpi-issues/files/4842764/SemanticTerms-4.1-Discussion.pdf)

**Comment by puribangalore** [comment]
Attached is the PDF file that incorporates the changes to Semantic Terms section and corresponding updates to other chapters.
[mpi32-report.pdf](https://github.com/mpi-forum/mpi-issues/files/2874029/mpi32-report.pdf)

**Comment by RolfRabenseifner** [comment]
Annotated version of the mpi32-report.pdf from Puri:
[mpi32-report-semantic-terms-2019-02-18-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/2876862/mpi32-report-semantic-terms-2019-02-18-annotated.pdf)

A pdf with all changes together, including the proposal for the Annex A.2:
[MPI-semantics_2018-11-06_proposal.pdf](https://github.com/mpi-forum/mpi-issues/files/2876863/MPI-semantics_2018-11-06_proposal.pdf)

Proposale for new additional Annex A.2:
[MPI-semantics-appendix.pdf](https://github.com/mpi-forum/mpi-issues/files/2876866/MPI-semantics-appendix.pdf)

**Comment by RolfRabenseifner** [comment]
Annotated version, now also including new Annex A.2 and the change-log entry
[mpi32-report-semantic-terms-2019-02-18a-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/2879836/mpi32-report-semantic-terms-2019-02-18a-annotated.pdf)

**Comment by RolfRabenseifner** [comment]
This annotated version was used in the virtual meeting, March 27, 2019

**Comment by RolfRabenseifner** [comment]
[mpi32-report-semantic-terms-2019-03-27-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/3051577/mpi32-report-semantic-terms-2019-03-27-annotated.pdf)
This annotated version was used in the virtual meeting, March 27, 2019

**Comment by RolfRabenseifner** [comment]
The following pdf is the result of the discussion at the virtual meeting on March 27, 2019:
[mpi32-report-semantic-terms-2019-04-12-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/3075001/mpi32-report-semantic-terms-2019-04-12-annotated.pdf)

**Comment by RolfRabenseifner** [comment]
The following pdf includes the proposals for changes in the pull request 97 plus some additional enhancments plus a new text for MPI_REQUEST_FREE that fits better to the new terms and is more exact in the case of freeing inactive requests.
[mpi32-report-semantic-terms-2019-04-14-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/3077828/mpi32-report-semantic-terms-2019-04-14-annotated.pdf)

**Comment by RolfRabenseifner** [comment]
The following pdf includes all changes from and since the telcon on April 14 until now, May 07, 2019.
Additionally, I updated the Annex column about complete/incomplete for all Wait/Test/free routines according to the rule that before freeing, the routines are still incomplete, because freeing stage is still missing.
[mpi32-report-semantic-terms-2019-05-07-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/3153947/mpi32-report-semantic-terms-2019-05-07-annotated.pdf)

**Comment by RolfRabenseifner** [comment]
The following pdf should be the draft used for the formal reading at the Chicago meeting May 28-31, 2019.
The working-group internal many-color-bars are now substituted by one color for the reading.
Latest changes were the more accurate wording on page 13, lines 18-24. And we added page 835 lines 36-38 to the change-log.
[mpi32-report-semantic-terms-2019-05-08-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/3158423/mpi32-report-semantic-terms-2019-05-08-annotated.pdf)

**Comment by RolfRabenseifner** [comment]
Update for the Chicago reading:
[mpi32-report-semantic-terms-2019-05-12-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/3170594/mpi32-report-semantic-terms-2019-05-12-annotated.pdf)

**Comment by puribangalore** [comment]
Updated and annotated PDF file. 
[mpi32-report-issue96-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/3174990/mpi32-report-issue96-annotated.pdf)

**Comment by RolfRabenseifner** [comment]
Updated with change-bars instead of yellow marker. Added "#96" as marker at all changes
[mpi32-report-semantic-terms-2019-05-13-annotated-bars.pdf](https://github.com/mpi-forum/mpi-issues/files/3216273/mpi32-report-semantic-terms-2019-05-13-annotated-bars.pdf)

**Comment by puribangalore** [comment]
Updated PDF file with changes from Chicago MPI Forum meeting: [mpi32-report.pdf](https://github.com/mpi-forum/mpi-standard/files/3322144/mpi32-report.pdf)

**Comment by puribangalore** [comment]
Here is the latest PDF file for Zurich MPI Forum meeting: 
[mpi32-report.pdf](https://github.com/mpi-forum/mpi-standard/files/3527193/mpi32-report.pdf)

**Comment by puribangalore** [comment]
Here is the annotated PDF: 
[mpi32-report.pdf](https://github.com/mpi-forum/mpi-issues/files/3586323/mpi32-report.pdf)

**Comment by schulzm** [comment]
I don't see a link to the PR - I assume it is 97? Could you please add this?

**Comment by puribangalore** [comment]
The PR link is in the reference section, it is 116:

PR mpi-forum/mpi-standard#116
<https://github.com/mpi-forum/mpi-standard/pull/116> provides the official
changes for this ticket.

**Comment by puribangalore** [comment]
Here is the latest version of the annotated PDF with comments from the Zurich meeting: 
[mpi-report.pdf](https://github.com/mpi-forum/mpi-issues/files/3589297/mpi-report.pdf)

**Comment by puribangalore** [comment]
The updated version with comments and notes after the Zurich working group meeting on Sep 9, 2019:
[mpi32-report-zurich-2019-09-09.pdf](https://github.com/mpi-forum/mpi-issues/files/3590934/mpi32-report-zurich-2019-09-09.pdf)

**Comment by schulzm** [comment]
I just did another pass after Rolf's round of last comments (individual comments are on the PR), but - as a general direction - the direction of the ticket is worrying me (especially after discussions in Zürich and the latest updates): the original scope of this was, as stated by Tony up top:

No such changes will make functional changes in MPI-4, but we want the standard to be understandable to non-experts.

I think the current ticket goes way beyond that: it is changing semantics (e.g., for Mprobe) which restricts implementations and it also not making it clearer for the user (e.g., calling "I" functions blocking and completing). 

IMHO we should really limit this ticket to adding needed definitions and not touching any existing semantics. This should also stay fully backwards compatible - it should not impact how implementations (and tools) are written, it should not define MPI internals and internal steps, and it should not affect how users use MPI.

**Comment by puribangalore** [comment]
Updated version based on changes from Zurich meeting: 
[mpi-report-issue96-25nov2019.pdf](https://github.com/mpi-forum/mpi-issues/files/3889258/mpi-report-issue96-25nov2019.pdf)

**Comment by RolfRabenseifner** [comment]
Annotated version with identical content to the pdf above:
[mpi-report-issue96-25nov2019-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/3933551/mpi-report-issue96-25nov2019-annotated.pdf)
Will be used during the reading in Albuquerque.

**Comment by RolfRabenseifner** [comment]
Annotated version for the reading on Dec. 12, 2019 in Albuquerque
[mpi-report-issue96-12dec2019-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/3956381/mpi-report-issue96-12dec2019-annotated.pdf)
(It includes additional no-no-vote updates based on requests at the Zurich meeting plus from the discussion about weak and strong local at Albuquerque.)

**Comment by RolfRabenseifner** [comment]
New annotated version for the virtual meeting, Jan 22, 2020;
[mpi-report-issue96-2020-01-21-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/4093195/mpi-report-issue96-2020-01-21-annotated.pdf)
It includes all changes that were decided during the reading at Albuquerque (blue change bar).
Additionally, it includes proposals to solve the following problems:

- To define blocking / nonblocking only for the routines that are associated with an operation, and not also for all service and query routines.
  See page 14, lines 10-24.
- The forum decided that *local* was ever "de facto" defined as a *weak local*.
  It was obvious during the meeting that there is a big problem of understanding.
  Therefore I propose some clarifications that we'll not repeat such discussions every year.
  See page 14, lines 26-27, and page 15, lines 5-6.
- Footnotes 13), 17-20) on pages 722-724
- Extension of the change-log about the changed definition of *local*, see page 839, lines 36-39.

**Comment by RolfRabenseifner** [comment]
New version for the re-reading in Portland, Feb. 2020:
[mpi-report-issue96-2020-02-02-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/4145580/mpi-report-issue96-2020-02-02-annotated.pdf)

With this, we have now touched/solved all the topics from the reading in Albuquerque,

 - the weak/strong local definition problem;
 - the service/inquiry routines' problem -> now outside of the blocking/nonblocking precedure set,
 - together with clarifying/defining "operation-related",
 - and having correct wording for PROBE and IPROBE -> being non-local and local;
 - the MPROBE+MRECV problem -> a stage may be implemented with more than one procedure;
 - the one-sided problem;

except 

 - including the partitioned communication.

But this can be done as a fix in the "make the standard 4.0 consistent"
stage within the Portland (Feb) and Munich (Jun/Jul) meetings. 

"perfect is the enemy of good enough": 
With this version, the proposal should be really good enough for MPI-4.0 (and significantly better than MPI-3.1) and **solving the major inconsistencies** of current terms with 

- **nonblocking collectives** (voted into MPI-3.0)
- **persistent collectives** (already voted into MPI-4.0)

**Comment by RolfRabenseifner** [comment]
Intermediate pdf version after the discussion at Portland
 - WG meeting on Feb. 18, 2020
 - Plenary on Feb. 19, 2020

[mpi-report-issue96-2020-02-02-annotated+2020-02-18+19.pdf](https://github.com/mpi-forum/mpi-issues/files/4228517/mpi-report-issue96-2020-02-02-annotated%2B2020-02-18%2B19.pdf)

**Comment by puribangalore** [comment]
Here is the updated PDF file based on changes from plenary meeting discussions on Feb 19, 2020: 
[mpi40-report-02-20-2020-d25ab79.pdf](https://github.com/mpi-forum/mpi-issues/files/4231944/mpi40-report-02-20-2020-d25ab79.pdf)

**Comment by puribangalore** [comment]
Another version with minor edits: 
[mpi40-report-02-20-2020-a0163c7.pdf](https://github.com/mpi-forum/mpi-issues/files/4233405/mpi40-report-02-20-2020-a0163c7.pdf)

**Comment by wesbland** [comment]
The no-no vote in the February 2020 meeting was withdrawn. This will require a no-no vote before the first vote at the June 2020 meeting.

**Comment by RolfRabenseifner** [comment]
At the end of the Portland meeting (Feb 18-21, 2020), I forgot to upload the final version of the pdf that included the comments from the reading:

[mpi-report-issue96-2020-02-20c-a0163c7-reading-notes-printable.pdf](https://github.com/mpi-forum/mpi-issues/files/4442536/mpi-report-issue96-2020-02-20c-a0163c7-reading-notes-printable.pdf)

**Comment by RolfRabenseifner** [comment]
The latest Version (May 20, 2020) includes:
- includes the version from Feb, 2, two weeks before Portland meeting,
- plus small corrections from the meeting and since then.

[mpi32-report-semantic-terms-2020-05-20-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/4657558/mpi32-report-semantic-terms-2020-05-20-annotated.pdf)

**Comment by RolfRabenseifner** [comment]
Introduction slides for the MPI Forum (virtual Meeting May 20, 2020):
[EuroMPI2019-SematicTerms-fromPuri-2020-04-28_rab-2020-05-20.pdf](https://github.com/mpi-forum/mpi-issues/files/4657580/EuroMPI2019-SematicTerms-fromPuri-2020-04-28_rab-2020-05-20.pdf)

**Comment by RolfRabenseifner** [comment]
Since Portland meeting, four parts of small changes were added.
The version May 20, 2020: 
 - pdf:  [mpi32-report-semantic-terms-2020-05-20-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/4708009/mpi32-report-semantic-terms-2020-05-20-annotated.pdf)
 - It includes the version from Feb, 2, two weeks before Portland meeting,
 - **plus Part I** of small corrections from the meeting and since then.

The version May 31, 2020: 
 - pdf:  [mpi32-report-semantic-terms-2020-05-31-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/4708015/mpi32-report-semantic-terms-2020-05-31-annotated.pdf)
 - It includes the version from Feb, 2, two weeks before Portland meeting,
 - **plus Part I-IV** of small corrections from the meeting and since then.

These **Parts I-IV** of small changes are documented in the following slides:
 - [EuroMPI2019-SematicTerms-fromPuri-2020-04-28+RMA-rab-2020-05-31.pdf](https://github.com/mpi-forum/mpi-issues/files/4708036/EuroMPI2019-SematicTerms-fromPuri-2020-04-28%2BRMA-rab-2020-05-31.pdf)

**Comment by RolfRabenseifner** [comment]
Latest annotated versions for the reading at the exceptional virtual meeting in June 2020:

Version-1:
[mpi40-report-520db9c-june2020-reading-v1-annoteted.pdf](https://github.com/mpi-forum/mpi-issues/files/4780761/mpi40-report-520db9c-june2020-reading-v1-annoteted.pdf)

Version-2:
[mpi40-report-f51be45-june2020-reading-v2-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/4780771/mpi40-report-f51be45-june2020-reading-v2-annotated.pdf)

**Comment by RolfRabenseifner** [comment]
Latest annotated Version 3 for the reading at the exceptional virtual meeting in June 2020:

[mpi40-report-june2020-reading-v3-annotated.pdf](https://github.com/mpi-forum/mpi-issues/files/4841073/mpi40-report-june2020-reading-v3-annotated.pdf)

**Comment by wesbland** [comment]
This passed a "no no" vote on 2020-06-30.

**Comment by wesbland** [comment]
This passed a "no no" vote on 2020-07-01.

https://www.mpi-forum.org/meetings/2020/06/votes

**Comment by wesbland** [comment]
This passed a "no no" and first vote on 2020-08-19.

https://www.mpi-forum.org/meetings/2020/08/votes

**Comment by wesbland** [comment]
@puribangalore - This is scheduled for a second vote at the September meeting, but I can't remember now, does this also need a no-no vote, or did we take care of the last of that at the August meeting? I think we took care of it all, but I want to be sure.

**Comment by puribangalore** [comment]
The no-no-vote was already taken at the August meeting and there are no more changes, at least as of today.

**Comment by wesbland** [comment]
This passed a second vote on 2020-09-28.

https://www.mpi-forum.org/meetings/2020/09/votes
