### ISSUE TITLE
Big MPI--MPI I/O functionality

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#98]
# Problem

For 64-bit clean functionality, convenience, and symmetry, the Big MPI principles being applied in Ticket #80 to collective operations should be applied to MPI I/O functionality.

# Proposal

The I/O chapter will get new APIs for 64-bit clean support.

# Changes to the Text

Appropriate new API and descriptions will be added with the _X suffix.

# Impact on Implementations

Implementations will have to comply with 64-bit clean inside, add these new APIs, and make sure their drivers for parallel file systems support larger transfers and buffers.

# Impact on Users

Users who opt in to the new API will be able to do bigger I/O transfers.

# References

Tickets #80 and #97.

PR https://github.com/mpi-forum/mpi-standard/pull/58

**Comment by tonyskjellum** [comment]
Initial text of the PR:

[mpi32-report-ticket98-io-20sep18-1515.pdf](https://github.com/mpi-forum/mpi-issues/files/2401410/mpi32-report-ticket98-io-20sep18-1515.pdf)

**Comment by wesbland** [comment]
@tonyskjellum / @puribangalore - Is this issue replaced by #137? Can we close this?

**Comment by puribangalore** [comment]
Yes.
