### ISSUE TITLE
Big MPI--RMA functionality

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#99]
# Problem

For 64-bit clean functionality, convenience, and symmetry, the Big MPI principles being applied in Ticket #80 to collective operations should be applied to MPI RMA functionality.

# Proposal

64-bit clean versions of RMA operations will be provided.

# Changes to the Text

New APIs and descriptions with suffix _X will be added to support 64-bit clean operations for RMA chapter.

# Impact on Implementations

Implementations will have to support the new API plus any internal changes to support larger transfers.

# Impact on Users

Users who opt in to the new API will be able to do larger RMA transfers.

# References

Tickets #80, #97, #98 are closely related.

PR https://github.com/mpi-forum/mpi-standard/pull/62

RMA WG Issue to cross-correlate:  https://github.com/mpiwg-rma/rma-issues/issues/7

**Comment by tonyskjellum** [comment]
Here is the initial version of the text:

[mpi32-report-ticket99-29sep18-1139.pdf](https://github.com/mpi-forum/mpi-issues/files/2430785/mpi32-report-ticket99-29sep18-1139.pdf)

**Comment by tonyskjellum** [comment]
Latest text:

[mpi32-report-ticket99-03oct18-2038.pdf](https://github.com/mpi-forum/mpi-issues/files/2444508/mpi32-report-ticket99-03oct18-2038.pdf)

**Comment by wesbland** [comment]
@tonyskjellum / @puribangalore - Is this issue replaced by #137? Can we close this?

**Comment by puribangalore** [comment]
Yes.
